var h;h||(h=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},h),ba=[],ca="./this.program",da=(a,b)=>{throw b;},k="";"undefined"!=typeof document&&document.currentScript&&(k=document.currentScript.src);k=0!==k.indexOf("blob:")?k.substr(0,k.replace(/[?#].*/,"").lastIndexOf("/")+1):"";var ea=h.print||console.log.bind(console),l=h.printErr||console.error.bind(console);Object.assign(h,aa);aa=null;h.arguments&&(ba=h.arguments);h.thisProgram&&(ca=h.thisProgram);
h.quit&&(da=h.quit);var fa;h.wasmBinary&&(fa=h.wasmBinary);var noExitRuntime=h.noExitRuntime||!0;"object"!=typeof WebAssembly&&p("no native wasm support detected");var ha,q=!1,ia,t,v,ja,ka,w,x,y,A,la=[],ma=[],na=[],oa=[],pa=[];function qa(){var a=h.preRun.shift();la.unshift(a)}var B=0,ra=null,sa=null;function p(a){if(h.onAbort)h.onAbort(a);a="Aborted("+a+")";l(a);q=!0;ia=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}
function ta(a){return a.startsWith("data:application/octet-stream;base64,")}var C;C="game.wasm";if(!ta(C)){var ua=C;C=h.locateFile?h.locateFile(ua,k):k+ua}function va(a){if(a==C&&fa)return new Uint8Array(fa);throw"both async and sync fetching of the wasm failed";}function wa(a){return fa||"function"!=typeof fetch?Promise.resolve().then(()=>va(a)):fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>va(a))}
function xa(a,b,c){return wa(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{l(`failed to asynchronously prepare wasm: ${d}`);p(d)})}function ya(a,b){var c=C;fa||"function"!=typeof WebAssembly.instantiateStreaming||ta(c)||"function"!=typeof fetch?xa(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){l(`wasm streaming compile failed: ${e}`);l("falling back to ArrayBuffer instantiation");return xa(c,a,b)}))}
var Ca={44521248:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,44521395:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,44521629:a=>{"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.ae||("undefined"!==typeof AudioContext?b.ae=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.ae=new webkitAudioContext),
b.ae&&za(b.ae));return void 0===b.ae?-1:0},44522122:()=>h.SDL2.ae.sampleRate,44522190:(a,b,c,d)=>{function e(){}function g(m){void 0!==f.capture.me&&(clearTimeout(f.capture.me),f.capture.me=void 0);f.capture.te=f.ae.createMediaStreamSource(m);f.capture.ce=f.ae.createScriptProcessor(b,a,1);f.capture.ce.onaudioprocess=function(n){void 0!==f&&void 0!==f.capture&&(n.outputBuffer.getChannelData(0).fill(0),f.capture.we=n.inputBuffer,Aa(c,[d]))};f.capture.te.connect(f.capture.ce);f.capture.ce.connect(f.ae.destination);
f.capture.stream=m}var f=h.SDL2;f.capture.ue=f.ae.createBuffer(a,b,f.ae.sampleRate);f.capture.ue.getChannelData(0).fill(0);f.capture.me=setTimeout(function(){f.capture.we=f.capture.ue;Aa(c,[d])},b/f.ae.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(g).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},g,e)},44523842:(a,b,c,d)=>{var e=h.SDL2;e.audio.ce=
e.ae.createScriptProcessor(b,0,a);e.audio.ce.onaudioprocess=function(g){void 0!==e&&void 0!==e.audio&&(e.audio.Ce=g.outputBuffer,Aa(c,[d]))};e.audio.ce.connect(e.ae.destination)},44524252:(a,b)=>{for(var c=h.SDL2,d=c.capture.we.numberOfChannels,e=0;e<d;++e){var g=c.capture.we.getChannelData(e);if(g.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+g.length+" samples vs expected "+b+" samples!";if(1==d)for(var f=0;f<b;++f)Ba(a+4*f,g[f]);else for(f=0;f<b;++f)Ba(a+4*(f*d+
e),g[f])}},44524857:(a,b)=>{for(var c=h.SDL2,d=c.audio.Ce.numberOfChannels,e=0;e<d;++e){var g=c.audio.Ce.getChannelData(e);if(g.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+g.length+" samples vs expected "+b+" samples!";for(var f=0;f<b;++f)g[f]=y[a+(f*d+e<<2)>>2]}},44525337:a=>{var b=h.SDL2;if(a){void 0!==b.capture.me&&clearTimeout(b.capture.me);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);
b.capture.stream=void 0}void 0!==b.capture.ce&&(b.capture.ce.onaudioprocess=function(){},b.capture.ce.disconnect(),b.capture.ce=void 0);void 0!==b.capture.te&&(b.capture.te.disconnect(),b.capture.te=void 0);void 0!==b.capture.ue&&(b.capture.ue=void 0);b.capture=void 0}else void 0!=b.audio.ce&&(b.audio.ce.disconnect(),b.audio.ce=void 0),b.audio=void 0;void 0!==b.ae&&void 0===b.audio&&void 0===b.capture&&(b.ae.close(),b.ae=void 0)},44526509:(a,b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;d.Le!==h.canvas&&
(d.ge=h.createContext(h.canvas,!1,!0),d.Le=h.canvas);if(d.w!==a||d.h!==b||d.Ve!==d.ge)d.image=d.ge.createImageData(a,b),d.w=a,d.h=b,d.Ve=d.ge;a=d.image.data;b=c>>2;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var g=w[b];a[e]=g&255;a[e+1]=g>>8&255;a[e+2]=g>>16&255;a[e+3]=255;b++;e+=4}else if(d.Oe!==a&&(d.Ne=new Int32Array(a.buffer),d.Pe=new Uint8Array(a.buffer),d.Oe=a),a=d.Ne,c=a.length,a.set(w.subarray(b,b+c)),a=d.Pe,b=3,e=b+4*c,0==c%8)for(;b<
e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.ge.putImageData(d.image,0,0)},44527978:(a,b,c,d,e)=>{var g=document.createElement("canvas");g.width=a;g.height=b;var f=g.getContext("2d");a=f.createImageData(a,b);b=a.data;e>>=2;var m=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(n=b.length;m<n;){var r=w[e];b[m]=r&255;b[m+1]=r>>8&255;b[m+2]=r>>
16&255;b[m+3]=r>>24&255;e++;m+=4}else b=new Int32Array(b.buffer),n=b.length,b.set(w.subarray(e,e+n));f.putImageData(a,0,0);c=0===c&&0===d?"url("+g.toDataURL()+"), auto":"url("+g.toDataURL()+") "+c+" "+d+", auto";d=D(c.length+1);E(c,d,c.length+1);return d},44528967:a=>{h.canvas&&(h.canvas.style.cursor=a?F(v,a):"")},44529050:()=>{h.canvas&&(h.canvas.style.cursor="none")},44529119:()=>window.innerWidth,44529149:()=>window.innerHeight};
function Da(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Ea=(a,b,c)=>{a.addEventListener(b,c,{once:!0})},za=a=>{var b;b||(b=[document,document.getElementById("canvas")]);["keydown","mousedown","touchstart"].forEach(c=>{b.forEach(d=>{d&&Ea(d,c,()=>{"suspended"===a.state&&a.resume()})})})},Fa=a=>{for(;0<a.length;)a.shift()(h)},Ga=[],Ha,G=a=>{var b=Ga[a];b||(a>=Ga.length&&(Ga.length=a+1),Ga[a]=b=Ha.get(a));return b},Aa=(a,b)=>{if("vi".includes("j")){var c=h.dynCall_vi;b&&b.length?c.apply(null,[a].concat(b)):c.call(null,a)}else G(a).apply(null,b)};
function Ba(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":t[a>>0]=b;break;case "i8":t[a>>0]=b;break;case "i16":ja[a>>1]=b;break;case "i32":w[a>>2]=b;break;case "i64":p("to do setValue(i64) use WASM_BIGINT");case "float":y[a>>2]=b;break;case "double":A[a>>3]=b;break;case "*":x[a>>2]=b;break;default:p(`invalid type for setValue: ${c}`)}}
var Ia="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,F=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ia)return Ia.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|f:(e&7)<<18|g<<12|f<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
Ta=(a,b)=>{Ja=a;Ka=b;if(La)if(Ma||(Ma=!0),0==a)H=function(){var d=Math.max(0,Na+b-Oa())|0;setTimeout(Ra,d)};else if(1==a)H=function(){Sa(Ra)};else if(2==a){if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);postMessage("setimmediate","*")}}H=function(){setImmediate(Ra)}}},Oa;Oa=()=>performance.now();
var ab=(a,b,c,d,e)=>{!La||p("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");La=a;Ua=d;var g=I;Ma=!1;Ra=function(){if(!q)if(0<Va.length){var f=Va.shift();f.ef(f.af);if(Wa){var m=Wa,n=0==m%1?m-1:Math.floor(m);Wa=f.cf?n:(8*m+(n+.5))/9}h.setStatus&&(f=h.statusMessage||"Please wait...",m=Wa,n=Xa.df,m?m<n?h.setStatus(f+" ("+(n-m)+"/"+n+")"):h.setStatus(f):h.setStatus(""));
g<I||setTimeout(Ra,0)}else if(!(g<I))if(Ya=Ya+1|0,1==Ja&&1<Ka&&0!=Ya%Ka)H();else{0==Ja&&(Na=Oa());if(!(q||h.preMainLoop&&!1===h.preMainLoop())){if(!q)try{if(a(),!noExitRuntime)try{ia=f=ia,Za(f)}catch(r){$a(r)}}catch(r){$a(r)}h.postMainLoop&&h.postMainLoop()}g<I||("object"==typeof SDL&&SDL.audio&&SDL.audio.Xe&&SDL.audio.Xe(),H())}};e||(b&&0<b?Ta(0,1E3/b):Ta(1,1),H());if(c)throw"unwind";},$a=a=>{a instanceof Da||"unwind"==a||da(1,a)},Za=a=>{ia=a;if(!noExitRuntime){if(h.onExit)h.onExit(a);q=!0}da(a,
new Da(a))},bb=a=>{ia=a;Za(a)},Ma=!1,H=null,I=0,La=null,Ua=0,Ja=0,Ka=0,Ya=0,Va=[],Xa={},Na,Ra,Wa,cb=!1,db=!1,eb=[];
function fb(){function a(){db=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}if(!gb){gb=!0;var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),
b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",c=>{!db&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function hb(a,b,c,d){if(b&&h.ge&&a==h.canvas)return h.ge;var e;if(b){var g={antialias:!1,alpha:!1,Ee:1};if(d)for(var f in d)g[f]=d[f];if("undefined"!=typeof ib&&(e=jb(a,g)))var m=J[e].ie}else m=a.getContext("2d");if(!m)return null;c&&(b||"undefined"==typeof K||p("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),h.ge=m,b&&kb(e),h.Ze=b,eb.forEach(n=>n()),fb());return m}var lb=!1,mb=void 0,nb=void 0;
function ob(a,b){function c(){cb=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=pb,mb&&d.requestPointerLock(),cb=!0,nb?("undefined"!=typeof SDL&&(w[SDL.screen>>2]=x[SDL.screen>>2]|8388608),qb(h.canvas),rb()):qb(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),nb?("undefined"!=typeof SDL&&(w[SDL.screen>>2]=x[SDL.screen>>2]&
-8388609),qb(h.canvas),rb()):qb(d));if(h.onFullScreen)h.onFullScreen(cb);if(h.onFullscreen)h.onFullscreen(cb)}mb=a;nb=b;"undefined"==typeof mb&&(mb=!0);"undefined"==typeof nb&&(nb=!1);var d=h.canvas;lb||(lb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}
function pb(){if(!cb)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var sb=0;function Sa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===sb)sb=b+1E3/60;else for(;b+2>=sb;)sb+=1E3/60;setTimeout(a,Math.max(sb-b,0))}}var tb=[];function rb(){var a=h.canvas;tb.forEach(b=>b(a.width,a.height))}
function qb(a,b,c){b&&c?(a.$e=b,a.Ue=c):(b=a.$e,c=a.Ue);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/e);d=Math.round(d*g);e=Math.round(e*
g)}nb?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var gb,L=12288,ub=!1,vb=0,wb=0,xb=0,M={alpha:!1,depth:!1,stencil:!1,antialias:!1},yb={},zb,Ab=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,g)=>b.drawArraysInstancedANGLE(c,d,e,g),a.drawElementsInstanced=(c,d,e,g,f)=>b.drawElementsInstancedANGLE(c,d,e,g,f))},Bb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Cb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Db=1,Eb=[],N=[],Fb=[],Gb=[],Hb=[],O=[],Ib=[],J=[],P=[],Jb={},Kb=4;function Q(a){Lb||(Lb=a)}
var Mb=a=>{for(var b=Db++,c=a.length;c<b;c++)a[c]=null;return b},jb=(a,b)=>{a.oe||(a.oe=a.getContext,a.getContext=function(d,e){e=a.oe(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Nb(c,b):0},Nb=(a,b)=>{var c=Mb(J),d={handle:c,attributes:b,version:b.Ee,ie:a};a.canvas&&(a.canvas.ke=d);J[c]=d;("undefined"==typeof b.Re||b.Re)&&Ob(d);return c},kb=a=>{Pb=J[a];h.ge=K=Pb&&Pb.ie},Ob=a=>{a||(a=Pb);if(!a.We){a.We=!0;var b=a.ie;Ab(b);Bb(b);Cb(b);b.he=
b.getExtension("EXT_disjoint_timer_query");b.hf=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},ib={},Lb,Pb,Qb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},E=(a,b,c)=>{var d=v;if(!(0<c))return 0;var e=b;c=b+c-1;for(var g=0;g<a.length;++g){var f=a.charCodeAt(g);if(55296<=f&&57343>=f){var m=a.charCodeAt(++g);f=65536+
((f&1023)<<10)|m&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=0;return b-e},R=a=>{var b=Qb(a)+1,c=D(b);c&&E(a,c,b);return c},Rb=[],Sb=(a,b)=>{Rb.length=0;for(var c;c=v[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;Rb.push(112==c?x[b>>2]:105==c?w[b>>2]:A[b>>3]);b+=d?8:4}return Rb},Vb=a=>{var b=Tb();a=a();Ub(b);
return a},Wb=0;function Xb(){for(var a=S.length-1;0<=a;--a)Yb(a);S=[];T=[]}var T=[];function Zb(a,b,c){function d(f,m){if(f.length!=m.length)return!1;for(var n in f)if(f[n]!=m[n])return!1;return!0}for(var e in T){var g=T[e];if(g.ye==a&&d(g.Ae,c))return}T.push({ye:a,Ge:b,Ae:c});T.sort((f,m)=>f.Ge<m.Ge)}function $b(a){for(var b=0;b<T.length;++b)T[b].ye==a&&(T.splice(b,1),--b)}function ac(){return navigator.userActivation?navigator.userActivation.isActive:Wb&&bc.le}
function cc(){if(ac())for(var a=0;a<T.length;++a){var b=T[a];T.splice(a,1);--a;b.ye.apply(null,b.Ae)}}var S=[];function Yb(a){var b=S[a];b.target.removeEventListener(b.be,b.Se,b.de);S.splice(a,1)}function U(a){function b(d){++Wb;bc=a;cc();a.fe(d);cc();--Wb}if(!a.target)return-4;if(a.ee)a.Se=b,a.target.addEventListener(a.be,b,a.de),S.push(a),dc||(oa.push(Xb),dc=!0);else for(var c=0;c<S.length;++c)S[c].target==a.target&&S[c].be==a.be&&Yb(c--);return 0}
function ec(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}function fc(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}
var gc={},dc,bc,hc,ic,jc,kc,lc,mc,nc,oc,pc,qc,rc,sc,tc={},uc=[0,document,window],V=a=>{a=2<a?a?F(v,a):"":a;return uc[a]||document.querySelector(a)},wc=a=>{var b=Qb(a)+1,c=vc(b);E(a,c,b);return c},xc=a=>Vb(()=>{var b=vc(8),c=b+4,d=wc(a.id);if(d=V(d))w[b>>2]=d.width,w[c>>2]=d.height;return[w[b>>2],w[c>>2]]}),yc=(a,b,c)=>{a=V(a);if(!a)return-4;a.width=b;a.height=c;return 0},zc=(a,b,c)=>{a.bf?Vb(()=>{var d=wc(a.id);yc(d,b,c)}):(a.width=b,a.height=c)},Ac=a=>{function b(){document.fullscreenElement||document.webkitFullscreenElement||
(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),zc(a,d,e),a.style.width=g,a.style.height=f,a.style.backgroundColor=m,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=r,a.style.paddingRight=u,a.style.paddingTop=z,a.style.paddingBottom=Pa,a.style.marginLeft=Qa,a.style.marginRight=Hd,a.style.marginTop=Id,a.style.marginBottom=Jd,document.body.style.margin=Kd,document.documentElement.style.overflow=
Ld,document.body.scroll=Md,a.style.je=Nd,a.ke&&a.ke.ie.viewport(0,0,d,e),tc.pe&&G(tc.pe)(37,0,tc.Be))}var c=xc(a),d=c[0],e=c[1],g=a.style.width,f=a.style.height,m=a.style.backgroundColor,n=document.body.style.backgroundColor,r=a.style.paddingLeft,u=a.style.paddingRight,z=a.style.paddingTop,Pa=a.style.paddingBottom,Qa=a.style.marginLeft,Hd=a.style.marginRight,Id=a.style.marginTop,Jd=a.style.marginBottom,Kd=document.body.style.margin,Ld=document.documentElement.style.overflow,Md=document.body.scroll,
Nd=a.style.je;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)},Bc=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},Cc=a=>0>uc.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},Dc=(a,b)=>{if(0!=b.xe||0!=b.ve){Ac(a);var c=b.Ye?innerWidth:screen.width,d=b.Ye?innerHeight:screen.height,e=Cc(a),g=e.width;e=e.height;var f=xc(a),m=f[0];f=f[1];3==b.xe?(Bc(a,(d-e)/2,(c-g)/2),c=g,d=e):2==b.xe&&(c*
f<m*d?(g=f*c/m,Bc(a,(d-g)/2,0),d=g):(g=m*d/f,Bc(a,0,(c-g)/2),c=g));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.Te&&(a.style.je="optimizeSpeed",a.style.je="-moz-crisp-edges",a.style.je="-o-crisp-edges",a.style.je="-webkit-optimize-contrast",a.style.je="optimize-contrast",a.style.je="crisp-edges",a.style.je="pixelated");g=2==b.ve?devicePixelRatio:1;0!=b.ve&&
(c=c*g|0,d=d*g|0,zc(a,c,d),a.ke&&a.ke.ie.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return fc()?-3:-1;tc=b;b.pe&&G(b.pe)(37,0,b.Be);return 0},Ec=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0},Fc=(a,b)=>{A[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)A[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)A[a+8*c+528>>
3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)w[a+4*c+1040>>2]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];w[a+1296>>2]=b.connected;w[a+1300>>2]=b.index;w[a+8>>2]=b.axes.length;w[a+12>>2]=b.buttons.length;E(b.id,a+1304,64);E(b.mapping,a+1368,64)},Gc=(a,b)=>{K.attachShader(N[a],O[b])},Hc=(a,b)=>{K.bindBuffer(a,Eb[b])};function Ic(a,b){K.blendFunc(a,b)}var Jc=(a,b,c,d)=>{K.bufferData(a,c?v.subarray(c,c+b):b,d)};
function Kc(a){K.clear(a)}function Lc(a,b,c,d){K.clearColor(a,b,c,d)}var Mc=a=>{K.compileShader(O[a])},Nc=()=>{var a=Mb(N),b=K.createProgram();b.name=a;b.se=b.qe=b.re=0;b.ze=1;N[a]=b;return a},Oc=a=>{var b=Mb(O);O[b]=K.createShader(a);return b},Pc=a=>{if(a){var b=N[a];b?(K.deleteProgram(b),b.name=0,N[a]=null):Q(1281)}};function Qc(a){K.disable(a)}var Rc=[],Sc=(a,b,c,d)=>{K.drawElements(a,b,c,d)};function Tc(a){K.enable(a)}
var Uc=a=>{K.enableVertexAttribArray(a)},Vc=(a,b,c,d)=>{for(var e=0;e<a;e++){var g=K[c](),f=g&&Mb(d);g?(g.name=f,d[f]=g):Q(1282);w[b+4*e>>2]=f}},Wc=(a,b)=>{Vc(a,b,"createBuffer",Eb)},Xc=(a,b,c,d,e,g,f,m)=>{b=N[b];if(a=K[a](b,c))d=m&&E(a.name,m,d),e&&(w[e>>2]=d),g&&(w[g>>2]=a.size),f&&(w[f>>2]=a.type)},Yc=(a,b)=>K.getAttribLocation(N[a],b?F(v,b):""),Zc=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&Q(1280);return;case 36345:d=0;break;case 34466:var e=K.getParameter(34467);
d=e?e.length:0}if(void 0===d)switch(e=K.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":Q(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:Q(1280);return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:w[b+4*a>>2]=e[a];break;case 2:y[b+4*a>>2]=e[a];break;
case 4:t[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(g){Q(1280);l("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+g+")");return}}break;default:Q(1280);l("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:c=d;x[b>>2]=c;x[b+4>>2]=(c-x[b>>2])/4294967296;break;case 0:w[b>>2]=d;break;case 2:y[b>>2]=d;break;case 4:t[b>>0]=d?1:0}}else Q(1281)},$c=(a,b,c,d)=>{a=K.getProgramInfoLog(N[a]);
null===a&&(a="(unknown error)");b=0<b&&d?E(a,d,b):0;c&&(w[c>>2]=b)},ad=(a,b,c)=>{if(c)if(a>=Db)Q(1281);else if(a=N[a],35716==b)a=K.getProgramInfoLog(a),null===a&&(a="(unknown error)"),w[c>>2]=a.length+1;else if(35719==b){if(!a.se)for(b=0;b<K.getProgramParameter(a,35718);++b)a.se=Math.max(a.se,K.getActiveUniform(a,b).name.length+1);w[c>>2]=a.se}else if(35722==b){if(!a.qe)for(b=0;b<K.getProgramParameter(a,35721);++b)a.qe=Math.max(a.qe,K.getActiveAttrib(a,b).name.length+1);w[c>>2]=a.qe}else if(35381==
b){if(!a.re)for(b=0;b<K.getProgramParameter(a,35382);++b)a.re=Math.max(a.re,K.getActiveUniformBlockName(a,b).length+1);w[c>>2]=a.re}else w[c>>2]=K.getProgramParameter(a,b);else Q(1281)},bd=(a,b,c)=>{if(c){a=K.he.getQueryObjectEXT(P[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;x[c>>2]=d;x[c+4>>2]=(d-x[c>>2])/4294967296}else Q(1281)},cd=(a,b,c)=>{if(c){a=K.he.getQueryObjectEXT(P[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;w[c>>2]=d}else Q(1281)},dd=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),ed=a=>{var b=
a.ne,c=a.Ie,d;if(!b)for(a.ne=b={},a.He={},d=0;d<K.getProgramParameter(a,35718);++d){var e=K.getActiveUniform(a,d);var g=e.name;e=e.size;var f=dd(g);f=0<f?g.slice(0,f):g;var m=a.ze;a.ze+=e;c[f]=[e,m];for(g=0;g<e;++g)b[m]=g,a.He[m++]=f}},fd=(a,b)=>{b=b?F(v,b):"";if(a=N[a]){ed(a);var c=a.ne,d=0,e=b,g=dd(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.Ie[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||K.getUniformLocation(a,b)))return d}else Q(1281);return-1},W=a=>{var b=K.Me;if(b){var c=b.ne[a];"number"==
typeof c&&(b.ne[a]=c=K.getUniformLocation(b,b.He[a]+(0<c?"["+c+"]":"")));return c}Q(1282)},gd=(a,b,c,d)=>{if(c)if(a=N[a],ed(a),a=K.getUniform(a,W(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:w[c>>2]=a;break;case 2:y[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:w[c+4*b>>2]=a[b];break;case 2:y[c+4*b>>2]=a[b]}else Q(1281)},hd=(a,b,c,d)=>{if(c)if(a=K.getVertexAttrib(a,b),34975==b)w[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:w[c>>2]=a;break;
case 2:y[c>>2]=a;break;case 5:w[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:w[c+4*b>>2]=a[b];break;case 2:y[c+4*b>>2]=a[b];break;case 5:w[c+4*b>>2]=Math.fround(a[b])}else Q(1281)},jd=a=>{a=N[a];K.linkProgram(a);a.ne=0;a.Ie={}},kd=(a,b,c,d,e)=>{a-=5120;a=1==a?v:4==a?w:6==a?y:5==a||28922==a?x:ka;var g=31-Math.clz32(a.BYTES_PER_ELEMENT),f=Kb;return a.subarray(e>>g,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<g)+f-1&-f)>>g)},ld=(a,b,c,d)=>{for(var e="",g=0;g<b;++g){var f=
d?w[d+4*g>>2]:-1,m=w[c+4*g>>2];f=m?F(v,m,0>f?void 0:f):"";e+=f}K.shaderSource(O[a],e)},md=(a,b)=>{K.uniform1f(W(a),b)},X=[],nd=[],od=(a,b,c,d)=>{K.uniform3f(W(a),b,c,d)},pd=(a,b,c,d)=>{if(18>=b){var e=X[16*b-1],g=y;d>>=2;for(var f=0;f<16*b;f+=16){var m=d+f;e[f]=g[m];e[f+1]=g[m+1];e[f+2]=g[m+2];e[f+3]=g[m+3];e[f+4]=g[m+4];e[f+5]=g[m+5];e[f+6]=g[m+6];e[f+7]=g[m+7];e[f+8]=g[m+8];e[f+9]=g[m+9];e[f+10]=g[m+10];e[f+11]=g[m+11];e[f+12]=g[m+12];e[f+13]=g[m+13];e[f+14]=g[m+14];e[f+15]=g[m+15]}}else e=y.subarray(d>>
2,d+64*b>>2);K.uniformMatrix4fv(W(a),!!c,e)},qd=a=>{a=N[a];K.useProgram(a);K.Me=a},rd=(a,b,c,d,e,g)=>{K.vertexAttribPointer(a,b,c,!!d,e,g)};function sd(a,b,c,d){K.viewport(a,b,c,d)}
var td=(a,b)=>{if(!fc())return-1;a=V(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?ac()?Dc(a,b):b.Qe?(Zb(Dc,1,[a,b]),1):-2:-3:-4},ud=(a,b)=>{var c={target:V(2),be:"beforeunload",ee:b,fe:(d=event)=>{var e=G(b)(28,0,a);e&&(e=e?F(v,e):"");if(e)return d.preventDefault(),d.returnValue=e},de:!0};return U(c)},vd=(a,b,c,d,e,g)=>{ic||(ic=D(256));a={target:V(a),be:g,ee:d,fe:(f=event)=>{var m=f.target.id?f.target.id:"",n=ic;E(ec(f.target),n+0,128);E(m,n+128,128);G(d)(e,n,b)&&f.preventDefault()},
de:c};return U(a)},wd=(a,b,c,d,e)=>{kc||(kc=D(280));return U({target:a,be:e,ee:d,fe:(g=event)=>{var f=kc,m=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,n=!!m;w[f>>2]=n;w[f+4>>2]=fc();var r=n?m:jc,u=r&&r.id?r.id:"";E(ec(r),f+8,128);E(u,f+136,128);w[f+264>>2]=r?r.clientWidth:0;w[f+268>>2]=r?r.clientHeight:0;w[f+272>>2]=screen.width;w[f+276>>2]=screen.height;n&&(jc=m);G(d)(19,f,b)&&g.preventDefault()},de:c})},xd=(a,b,c,d,e)=>
{lc||(lc=D(1432));b={target:V(2),le:!0,be:e,ee:c,fe:(g=event)=>{var f=lc;Fc(f,g.gamepad);G(c)(d,f,a)&&g.preventDefault()},de:b};return U(b)},yd=(a,b,c,d,e,g)=>{mc||(mc=D(176));a={target:V(a),le:!0,be:g,ee:d,fe:f=>{var m=mc;A[m>>3]=f.timeStamp;var n=m>>2;w[n+2]=f.location;w[n+3]=f.ctrlKey;w[n+4]=f.shiftKey;w[n+5]=f.altKey;w[n+6]=f.metaKey;w[n+7]=f.repeat;w[n+8]=f.charCode;w[n+9]=f.keyCode;w[n+10]=f.which;E(f.key||"",m+44,32);E(f.code||"",m+76,32);E(f.char||"",m+108,32);E(f.locale||"",m+140,32);G(d)(e,
m,b)&&f.preventDefault()},de:c};return U(a)},zd=(a,b,c)=>{A[a>>3]=b.timeStamp;a>>=2;w[a+2]=b.screenX;w[a+3]=b.screenY;w[a+4]=b.clientX;w[a+5]=b.clientY;w[a+6]=b.ctrlKey;w[a+7]=b.shiftKey;w[a+8]=b.altKey;w[a+9]=b.metaKey;ja[2*a+20]=b.button;ja[2*a+21]=b.buttons;w[a+11]=b.movementX;w[a+12]=b.movementY;c=Cc(c);w[a+13]=b.clientX-c.left;w[a+14]=b.clientY-c.top},Ad=(a,b,c,d,e,g)=>{nc||(nc=D(72));a=V(a);return U({target:a,le:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,be:g,ee:d,fe:(f=event)=>{zd(nc,
f,a);G(d)(e,nc,b)&&f.preventDefault()},de:c})},Bd=(a,b,c,d,e)=>{oc||(oc=D(260));return U({target:a,be:e,ee:d,fe:(g=event)=>{var f=oc,m=document.pointerLockElement||document.oe||document.Ke||document.Je;w[f>>2]=!!m;var n=m&&m.id?m.id:"";E(ec(m),f+4,128);E(n,f+132,128);G(d)(20,f,b)&&g.preventDefault()},de:c})},Cd=(a,b,c,d)=>{pc||(pc=D(36));a=V(a);return U({target:a,be:"resize",ee:d,fe:(e=event)=>{if(e.target==a){var g=document.body;if(g){var f=pc;w[f>>2]=e.detail;w[f+4>>2]=g.clientWidth;w[f+8>>2]=g.clientHeight;
w[f+12>>2]=innerWidth;w[f+16>>2]=innerHeight;w[f+20>>2]=outerWidth;w[f+24>>2]=outerHeight;w[f+28>>2]=pageXOffset;w[f+32>>2]=pageYOffset;G(d)(10,f,b)&&e.preventDefault()}}},de:c})},Dd=(a,b,c,d,e,g)=>{qc||(qc=D(1696));a=V(a);return U({target:a,le:"touchstart"==g||"touchend"==g,be:g,ee:d,fe:f=>{for(var m,n={},r=f.touches,u=0;u<r.length;++u)m=r[u],m.De=m.Fe=0,n[m.identifier]=m;for(u=0;u<f.changedTouches.length;++u)m=f.changedTouches[u],m.De=1,n[m.identifier]=m;for(u=0;u<f.targetTouches.length;++u)n[f.targetTouches[u].identifier].Fe=
1;r=qc;A[r>>3]=f.timeStamp;var z=r>>2;w[z+3]=f.ctrlKey;w[z+4]=f.shiftKey;w[z+5]=f.altKey;w[z+6]=f.metaKey;z+=7;var Pa=Cc(a),Qa=0;for(u in n)if(m=n[u],w[z]=m.identifier,w[z+1]=m.screenX,w[z+2]=m.screenY,w[z+3]=m.clientX,w[z+4]=m.clientY,w[z+5]=m.pageX,w[z+6]=m.pageY,w[z+7]=m.De,w[z+8]=m.Fe,w[z+9]=m.clientX-Pa.left,w[z+10]=m.clientY-Pa.top,z+=13,31<++Qa)break;w[r+8>>2]=Qa;G(d)(e,r,b)&&f.preventDefault()},de:c})},Ed=(a,b,c)=>{var d=uc[1];rc||(rc=D(8));return U({target:d,be:"visibilitychange",ee:c,fe:(e=
event)=>{var g=rc,f=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);w[g>>2]=document.hidden;w[g+4>>2]=f;G(c)(21,g,a)&&e.preventDefault()},de:b})},Fd=(a,b,c,d)=>{sc||(sc=D(104));return U({target:a,le:!0,be:"wheel",ee:d,fe:(e=event)=>{var g=sc;zd(g,e,a);A[g+72>>3]=e.deltaX;A[g+80>>3]=e.deltaY;A[g+88>>3]=e.deltaZ;w[g+96>>2]=e.deltaMode;G(d)(9,g,b)&&e.preventDefault()},de:c})},Gd={},Pd=()=>{if(!Od){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",
LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in Gd)void 0===Gd[b]?delete a[b]:a[b]=Gd[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Od=c}return Od},Od,Qd=[null,[],[]];h.requestFullscreen=(a,b)=>ob(a,b);h.requestAnimationFrame=a=>Sa(a);h.setCanvasSize=(a,b,c)=>{qb(h.canvas,a,b);c||rb()};h.pauseMainLoop=()=>{H=null;I++};h.resumeMainLoop=()=>{I++;var a=Ja,b=Ka,c=La;La=null;ab(c,0,!1,Ua,!0);Ta(a,b);H()};
h.getUserMedia=()=>{window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};h.createContext=(a,b,c,d)=>hb(a,b,c,d);for(var K,Y=0;32>Y;++Y)Rc.push(Array(Y));var Rd=new Float32Array(288);for(Y=0;288>Y;++Y)X[Y]=Rd.subarray(0,Y+1);var Sd=new Int32Array(288);for(Y=0;288>Y;++Y)nd[Y]=Sd.subarray(0,Y+1);
var Td={$:function(){return 0},$a:function(){return 0},ab:function(){},bb:()=>!0,Ma:a=>{if(12448==a)return L=12288,1;L=12300;return 0},Pa:(a,b,c,d,e)=>{if(62E3!=a)L=12296,c=0;else{if(b)for(;;){a=w[b>>2];if(12321==a)M.alpha=0<w[b+4>>2];else if(12325==a)M.depth=0<w[b+4>>2];else if(12326==a)M.stencil=0<w[b+4>>2];else if(12337==a)a=w[b+4>>2],M.antialias=0<a;else if(12338==a)a=w[b+4>>2],M.antialias=1==a;else if(12544==a)M.ff=12547!=w[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(w[e>>2]=1),c&&0<d&&
(w[c>>2]=62002),L=12288,c=1):(L=12300,c=0)}return c},Da:(a,b,c,d)=>{if(62E3!=a)return L=12296,0;for(a=1;;){b=w[d>>2];if(12440==b)a=w[d+4>>2];else if(12344==b)break;else return L=12292,0;d+=8}if(2!=a)return L=12293,0;M.Ee=a-1;M.gf=0;zb=jb(h.canvas,M);if(0!=zb)return L=12288,kb(zb),h.Ze=!0,eb.forEach(function(e){e()}),kb(null),62004;L=12297;return 0},Fa:(a,b)=>{if(62E3!=a)return L=12296,0;if(62002!=b)return L=12293,0;L=12288;return 62006},Ea:(a,b)=>{if(62E3!=a)return L=12296,0;if(62004!=b)return L=
12294,0;a=zb;Pb===J[a]&&(Pb=null);if("object"==typeof gc)for(var c=J[a].ie.canvas,d=0;d<S.length;++d)S[d].target!=c||Yb(d--);J[a]&&J[a].ie.canvas&&(J[a].ie.canvas.ke=void 0);J[a]=null;L=12288;vb==b&&(vb=0);return 1},Ga:(a,b)=>{if(62E3!=a)return L=12296,0;if(62006!=b)return L=12301,1;wb==b&&(wb=0);xb==b&&(xb=0);L=12288;return 1},Qa:(a,b,c,d)=>{if(62E3!=a)return L=12296,0;if(62002!=b)return L=12293,0;if(!d)return L=12300,0;L=12288;switch(c){case 12320:return w[d>>2]=M.alpha?32:24,1;case 12321:return w[d>>
2]=M.alpha?8:0,1;case 12322:return w[d>>2]=8,1;case 12323:return w[d>>2]=8,1;case 12324:return w[d>>2]=8,1;case 12325:return w[d>>2]=M.depth?24:0,1;case 12326:return w[d>>2]=M.stencil?8:0,1;case 12327:return w[d>>2]=12344,1;case 12328:return w[d>>2]=62002,1;case 12329:return w[d>>2]=0,1;case 12330:return w[d>>2]=4096,1;case 12331:return w[d>>2]=16777216,1;case 12332:return w[d>>2]=4096,1;case 12333:return w[d>>2]=0,1;case 12334:return w[d>>2]=0,1;case 12335:return w[d>>2]=12344,1;case 12337:return w[d>>
2]=M.antialias?4:0,1;case 12338:return w[d>>2]=M.antialias?1:0,1;case 12339:return w[d>>2]=4,1;case 12340:return w[d>>2]=12344,1;case 12341:case 12342:case 12343:return w[d>>2]=-1,1;case 12345:case 12346:return w[d>>2]=0,1;case 12347:return w[d>>2]=0,1;case 12348:return w[d>>2]=1;case 12349:case 12350:return w[d>>2]=0,1;case 12351:return w[d>>2]=12430,1;case 12352:return w[d>>2]=4,1;case 12354:return w[d>>2]=0,1;default:return L=12292,0}},U:()=>{L=12288;return 62E3},Ca:()=>L,Na:(a,b,c)=>{if(62E3!=
a)return L=12296,0;b&&(w[b>>2]=1);c&&(w[c>>2]=4);ub=!0;L=12288;return 1},Ha:(a,b,c,d)=>{if(62E3!=a)return L=12296,0;if(0!=d&&62004!=d)return L=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return L=12301,0;kb(d?zb:null);vb=d;xb=b;wb=c;L=12288;return 1},Ba:(a,b)=>{if(62E3!=a)return L=12296,0;L=12288;if(yb[b])return yb[b];switch(b){case 12371:a=R("Emscripten");break;case 12372:a=R("1.4 Emscripten EGL");break;case 12373:a=R("");break;case 12429:a=R("OpenGL_ES");break;default:return L=12300,0}return yb[b]=
a},Ia:()=>{if(ub)if(h.ge)if(h.ge.isContextLost())L=12302;else return L=12288,1;else L=12290;else L=12289;return 0},Ja:(a,b)=>{if(62E3!=a)return L=12296,0;0==b?Ta(0,0):Ta(1,b);L=12288;return 1},Oa:a=>{if(62E3!=a)return L=12296,0;xb=wb=vb=0;ub=!1;L=12288;return 1},La:()=>{L=12288;return 1},Ka:()=>{L=12288;return 1},Sa:(a,b,c)=>{b=Sb(b,c);return Ca[a].apply(null,b)},i:(a,b,c)=>{b=Sb(b,c);return Ca[a].apply(null,b)},ba:()=>Date.now(),ua:()=>{if(!fc())return-1;$b(Dc);var a=uc[1];if(a.exitFullscreen)a.fullscreenElement&&
a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},za:()=>{$b(Ec);if(document.exitPointerLock)document.exitPointerLock();else return-1;return 0},n:()=>devicePixelRatio,l:(a,b,c)=>{a=V(a);if(!a)return-4;a=Cc(a);A[b>>3]=a.width;A[c>>3]=a.height;return 0},X:(a,b)=>{if(0>a||a>=hc.length)return-5;if(!hc[a])return-7;Fc(b,hc[a]);return 0},B:Oa,Ra:()=>hc.length,Aa:(a,b)=>{w[a>>2]=screen.width;w[b>>2]=screen.height},Nd:function(a){K.activeTexture(a)},
Md:Gc,qa:(a,b)=>{K.he.beginQueryEXT(a,P[b])},Ld:(a,b,c)=>{K.bindAttribLocation(N[a],b,c?F(v,c):"")},Kd:Hc,Jd:(a,b)=>{K.bindFramebuffer(a,Fb[b])},Id:(a,b)=>{K.bindRenderbuffer(a,Gb[b])},Hd:(a,b)=>{K.bindTexture(a,Hb[b])},ia:a=>{K.bindVertexArray(Ib[a])},Gd:function(a,b,c,d){K.blendColor(a,b,c,d)},Fd:function(a){K.blendEquation(a)},Ed:function(a,b){K.blendEquationSeparate(a,b)},Dd:Ic,Cd:function(a,b,c,d){K.blendFuncSeparate(a,b,c,d)},Bd:Jc,Ad:(a,b,c,d)=>{K.bufferSubData(a,b,v.subarray(d,d+c))},zd:function(a){return K.checkFramebufferStatus(a)},
yd:Kc,xd:Lc,wd:function(a){K.clearDepth(a)},vd:function(a){K.clearStencil(a)},ud:(a,b,c,d)=>{K.colorMask(!!a,!!b,!!c,!!d)},td:Mc,sd:(a,b,c,d,e,g,f,m)=>{K.compressedTexImage2D(a,b,c,d,e,g,m?v.subarray(m,m+f):null)},rd:(a,b,c,d,e,g,f,m,n)=>{K.compressedTexSubImage2D(a,b,c,d,e,g,f,n?v.subarray(n,n+m):null)},qd:function(a,b,c,d,e,g,f,m){K.copyTexImage2D(a,b,c,d,e,g,f,m)},pd:function(a,b,c,d,e,g,f,m){K.copyTexSubImage2D(a,b,c,d,e,g,f,m)},od:Nc,nd:Oc,md:function(a){K.cullFace(a)},ld:(a,b)=>{for(var c=0;c<
a;c++){var d=w[b+4*c>>2],e=Eb[d];e&&(K.deleteBuffer(e),e.name=0,Eb[d]=null)}},kd:(a,b)=>{for(var c=0;c<a;++c){var d=w[b+4*c>>2],e=Fb[d];e&&(K.deleteFramebuffer(e),e.name=0,Fb[d]=null)}},jd:Pc,sa:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=P[d];e&&(K.he.deleteQueryEXT(e),P[d]=null)}},id:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=Gb[d];e&&(K.deleteRenderbuffer(e),e.name=0,Gb[d]=null)}},hd:a=>{if(a){var b=O[a];b?(K.deleteShader(b),O[a]=null):Q(1281)}},gd:(a,b)=>{for(var c=0;c<a;c++){var d=
w[b+4*c>>2],e=Hb[d];e&&(K.deleteTexture(e),e.name=0,Hb[d]=null)}},ha:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2];K.deleteVertexArray(Ib[d]);Ib[d]=null}},fd:function(a){K.depthFunc(a)},ed:a=>{K.depthMask(!!a)},dd:function(a,b){K.depthRange(a,b)},cd:(a,b)=>{K.detachShader(N[a],O[b])},bd:Qc,ad:a=>{K.disableVertexAttribArray(a)},$c:(a,b,c)=>{K.drawArrays(a,b,c)},Qd:(a,b,c,d)=>{K.drawArraysInstanced(a,b,c,d)},Rd:(a,b)=>{for(var c=Rc[a],d=0;d<a;d++)c[d]=w[b+4*d>>2];K.drawBuffers(c)},_c:Sc,Pd:(a,b,c,
d,e)=>{K.drawElementsInstanced(a,b,c,d,e)},Zc:Tc,Yc:Uc,pa:a=>{K.he.endQueryEXT(a)},Xc:function(){K.finish()},Wc:function(){K.flush()},Vc:(a,b,c,d)=>{K.framebufferRenderbuffer(a,b,c,Gb[d])},Uc:(a,b,c,d,e)=>{K.framebufferTexture2D(a,b,c,Hb[d],e)},Tc:function(a){K.frontFace(a)},Sc:Wc,Qc:(a,b)=>{Vc(a,b,"createFramebuffer",Fb)},ta:(a,b)=>{for(var c=0;c<a;c++){var d=K.he.createQueryEXT();if(!d){for(Q(1282);c<a;)w[b+4*c++>>2]=0;break}var e=Mb(P);d.name=e;P[e]=d;w[b+4*c>>2]=e}},Pc:(a,b)=>{Vc(a,b,"createRenderbuffer",
Gb)},Oc:(a,b)=>{Vc(a,b,"createTexture",Hb)},ga:function(a,b){Vc(a,b,"createVertexArray",Ib)},Rc:function(a){K.generateMipmap(a)},Nc:(a,b,c,d,e,g,f)=>{Xc("getActiveAttrib",a,b,c,d,e,g,f)},Mc:(a,b,c,d,e,g,f)=>{Xc("getActiveUniform",a,b,c,d,e,g,f)},Lc:(a,b,c,d)=>{a=K.getAttachedShaders(N[a]);var e=a.length;e>b&&(e=b);w[c>>2]=e;for(b=0;b<e;++b)w[d+4*b>>2]=O.indexOf(a[b])},Kc:Yc,Jc:(a,b)=>{Zc(a,b,4)},Ic:(a,b,c)=>{c?w[c>>2]=K.getBufferParameter(a,b):Q(1281)},Hc:()=>{var a=K.getError()||Lb;Lb=0;return a},
Gc:(a,b)=>{Zc(a,b,2)},Fc:(a,b,c,d)=>{a=K.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;w[d>>2]=a},Ec:(a,b)=>{Zc(a,b,0)},Cc:$c,Dc:ad,ka:bd,ma:cd,ja:bd,la:cd,na:(a,b,c)=>{c?w[c>>2]=K.he.getQueryEXT(a,b):Q(1281)},Bc:(a,b,c)=>{c?w[c>>2]=K.getRenderbufferParameter(a,b):Q(1281)},zc:(a,b,c,d)=>{a=K.getShaderInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,d,b):0;c&&(w[c>>2]=b)},yc:(a,b,c,d)=>{a=K.getShaderPrecisionFormat(a,b);w[c>>
2]=a.rangeMin;w[c+4>>2]=a.rangeMax;w[d>>2]=a.precision},xc:(a,b,c,d)=>{if(a=K.getShaderSource(O[a]))b=0<b&&d?E(a,d,b):0,c&&(w[c>>2]=b)},Ac:(a,b,c)=>{c?35716==b?(a=K.getShaderInfoLog(O[a]),null===a&&(a="(unknown error)"),w[c>>2]=a?a.length+1:0):35720==b?(a=K.getShaderSource(O[a]),w[c>>2]=a?a.length+1:0):w[c>>2]=K.getShaderParameter(O[a],b):Q(1281)},wc:a=>{var b=Jb[a];if(!b){switch(a){case 7939:b=K.getSupportedExtensions()||[];b=b.concat(b.map(d=>"GL_"+d));b=R(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=
K.getParameter(a))||Q(1280);b=b&&R(b);break;case 7938:b=R("OpenGL ES 2.0 ("+K.getParameter(7938)+")");break;case 35724:b=K.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=R(b);break;default:Q(1280)}Jb[a]=b}return b},vc:(a,b,c)=>{c?y[c>>2]=K.getTexParameter(a,b):Q(1281)},uc:(a,b,c)=>{c?w[c>>2]=K.getTexParameter(a,b):Q(1281)},rc:fd,tc:(a,b,c)=>{gd(a,b,c,2)},sc:(a,b,c)=>{gd(a,b,c,0)},oc:(a,
b,c)=>{c?w[c>>2]=K.getVertexAttribOffset(a,b):Q(1281)},qc:(a,b,c)=>{hd(a,b,c,2)},pc:(a,b,c)=>{hd(a,b,c,5)},nc:function(a,b){K.hint(a,b)},mc:a=>(a=Eb[a])?K.isBuffer(a):0,lc:function(a){return K.isEnabled(a)},kc:a=>(a=Fb[a])?K.isFramebuffer(a):0,jc:a=>(a=N[a])?K.isProgram(a):0,ra:a=>(a=P[a])?K.he.isQueryEXT(a):0,ic:a=>(a=Gb[a])?K.isRenderbuffer(a):0,gc:a=>(a=O[a])?K.isShader(a):0,fc:a=>(a=Hb[a])?K.isTexture(a):0,fa:a=>(a=Ib[a])?K.isVertexArray(a):0,ec:function(a){K.lineWidth(a)},dc:jd,cc:(a,b)=>{3317==
a&&(Kb=b);K.pixelStorei(a,b)},bc:function(a,b){K.polygonOffset(a,b)},oa:(a,b)=>{K.he.queryCounterEXT(P[a],b)},ac:(a,b,c,d,e,g,f)=>{(f=kd(g,e,c,d,f))?K.readPixels(a,b,c,d,e,g,f):Q(1280)},$b:()=>{},_b:function(a,b,c,d){K.renderbufferStorage(a,b,c,d)},Zb:(a,b)=>{K.sampleCoverage(a,!!b)},Xb:function(a,b,c,d){K.scissor(a,b,c,d)},Wb:()=>{Q(1280)},Vb:ld,Ub:function(a,b,c){K.stencilFunc(a,b,c)},Tb:function(a,b,c,d){K.stencilFuncSeparate(a,b,c,d)},Sb:function(a){K.stencilMask(a)},Rb:function(a,b){K.stencilMaskSeparate(a,
b)},Qb:function(a,b,c){K.stencilOp(a,b,c)},Pb:function(a,b,c,d){K.stencilOpSeparate(a,b,c,d)},Ob:(a,b,c,d,e,g,f,m,n)=>{K.texImage2D(a,b,c,d,e,g,f,m,n?kd(m,f,d,e,n):null)},Mb:function(a,b,c){K.texParameterf(a,b,c)},Lb:(a,b,c)=>{K.texParameterf(a,b,y[c>>2])},Kb:function(a,b,c){K.texParameteri(a,b,c)},Jb:(a,b,c)=>{K.texParameteri(a,b,w[c>>2])},Ib:(a,b,c,d,e,g,f,m,n)=>{var r=null;n&&(r=kd(m,f,e,g,n));K.texSubImage2D(a,b,c,d,e,g,f,m,r)},Hb:md,Gb:(a,b,c)=>{if(288>=b)for(var d=X[b-1],e=0;e<b;++e)d[e]=y[c+
4*e>>2];else d=y.subarray(c>>2,c+4*b>>2);K.uniform1fv(W(a),d)},Fb:(a,b)=>{K.uniform1i(W(a),b)},Eb:(a,b,c)=>{if(288>=b)for(var d=nd[b-1],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+4*b>>2);K.uniform1iv(W(a),d)},Db:(a,b,c)=>{K.uniform2f(W(a),b,c)},Cb:(a,b,c)=>{if(144>=b)for(var d=X[2*b-1],e=0;e<2*b;e+=2)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2];else d=y.subarray(c>>2,c+8*b>>2);K.uniform2fv(W(a),d)},Bb:(a,b,c)=>{K.uniform2i(W(a),b,c)},Ab:(a,b,c)=>{if(144>=b)for(var d=nd[2*b-1],e=0;e<2*b;e+=2)d[e]=
w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2];else d=w.subarray(c>>2,c+8*b>>2);K.uniform2iv(W(a),d)},zb:od,yb:(a,b,c)=>{if(96>=b)for(var d=X[3*b-1],e=0;e<3*b;e+=3)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2],d[e+2]=y[c+(4*e+8)>>2];else d=y.subarray(c>>2,c+12*b>>2);K.uniform3fv(W(a),d)},xb:(a,b,c,d)=>{K.uniform3i(W(a),b,c,d)},wb:(a,b,c)=>{if(96>=b)for(var d=nd[3*b-1],e=0;e<3*b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2];else d=w.subarray(c>>2,c+12*b>>2);K.uniform3iv(W(a),d)},vb:(a,b,c,d,e)=>
{K.uniform4f(W(a),b,c,d,e)},ub:(a,b,c)=>{if(72>=b){var d=X[4*b-1],e=y;c>>=2;for(var g=0;g<4*b;g+=4){var f=c+g;d[g]=e[f];d[g+1]=e[f+1];d[g+2]=e[f+2];d[g+3]=e[f+3]}}else d=y.subarray(c>>2,c+16*b>>2);K.uniform4fv(W(a),d)},tb:(a,b,c,d,e)=>{K.uniform4i(W(a),b,c,d,e)},sb:(a,b,c)=>{if(72>=b)for(var d=nd[4*b-1],e=0;e<4*b;e+=4)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2],d[e+3]=w[c+(4*e+12)>>2];else d=w.subarray(c>>2,c+16*b>>2);K.uniform4iv(W(a),d)},rb:(a,b,c,d)=>{if(72>=b)for(var e=X[4*
b-1],g=0;g<4*b;g+=4)e[g]=y[d+4*g>>2],e[g+1]=y[d+(4*g+4)>>2],e[g+2]=y[d+(4*g+8)>>2],e[g+3]=y[d+(4*g+12)>>2];else e=y.subarray(d>>2,d+16*b>>2);K.uniformMatrix2fv(W(a),!!c,e)},qb:(a,b,c,d)=>{if(32>=b)for(var e=X[9*b-1],g=0;g<9*b;g+=9)e[g]=y[d+4*g>>2],e[g+1]=y[d+(4*g+4)>>2],e[g+2]=y[d+(4*g+8)>>2],e[g+3]=y[d+(4*g+12)>>2],e[g+4]=y[d+(4*g+16)>>2],e[g+5]=y[d+(4*g+20)>>2],e[g+6]=y[d+(4*g+24)>>2],e[g+7]=y[d+(4*g+28)>>2],e[g+8]=y[d+(4*g+32)>>2];else e=y.subarray(d>>2,d+36*b>>2);K.uniformMatrix3fv(W(a),!!c,e)},
pb:pd,ob:qd,nb:a=>{K.validateProgram(N[a])},mb:function(a,b){K.vertexAttrib1f(a,b)},lb:(a,b)=>{K.vertexAttrib1f(a,y[b>>2])},kb:function(a,b,c){K.vertexAttrib2f(a,b,c)},jb:(a,b)=>{K.vertexAttrib2f(a,y[b>>2],y[b+4>>2])},ib:function(a,b,c,d){K.vertexAttrib3f(a,b,c,d)},hb:(a,b)=>{K.vertexAttrib3f(a,y[b>>2],y[b+4>>2],y[b+8>>2])},gb:function(a,b,c,d,e){K.vertexAttrib4f(a,b,c,d,e)},fb:(a,b)=>{K.vertexAttrib4f(a,y[b>>2],y[b+4>>2],y[b+8>>2],y[b+12>>2])},Od:(a,b)=>{K.vertexAttribDivisor(a,b)},eb:rd,db:sd,w:()=>
0,cb:(a,b,c)=>v.copyWithin(a,b,b+c),va:(a,b,c)=>td(a,{xe:w[c>>2],ve:w[c+4>>2],Te:w[c+8>>2],Qe:b,pe:w[c+12>>2],Be:w[c+16>>2]}),S:(a,b)=>{a=V(a);return a?a.requestPointerLock?ac()?Ec(a):b?(Zb(Ec,2,[a]),1):-2:-1:-4},Xa:()=>{p("OOM")},Yb:a=>{eval(a?F(v,a):"")},Y:()=>(hc=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads():null)?0:-1,C:(a,b,c)=>"undefined"==typeof onbeforeunload?-1:1!==c?-5:ud(a,b),L:(a,b,c,d)=>vd(a,b,c,d,12,"blur"),m:yc,u:(a,b,c)=>{a=
V(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},M:(a,b,c,d)=>vd(a,b,c,d,13,"focus"),E:(a,b,c,d)=>{if(!fc())return-1;a=V(a);if(!a)return-4;wd(a,b,c,d,"webkitfullscreenchange");return wd(a,b,c,d,"fullscreenchange")},W:(a,b,c)=>navigator.getGamepads||navigator.webkitGetGamepads?xd(a,b,c,26,"gamepadconnected"):-1,V:(a,b,c)=>navigator.getGamepads||navigator.webkitGetGamepads?xd(a,b,c,27,"gamepaddisconnected"):-1,H:(a,b,c,d)=>yd(a,b,c,d,2,"keydown"),F:(a,b,c,d)=>yd(a,b,c,d,1,"keypress"),
G:(a,b,c,d)=>yd(a,b,c,d,3,"keyup"),Ta:(a,b,c)=>{a=G(a);ab(a,b,c)},R:(a,b,c,d)=>Ad(a,b,c,d,5,"mousedown"),P:(a,b,c,d)=>Ad(a,b,c,d,33,"mouseenter"),O:(a,b,c,d)=>Ad(a,b,c,d,34,"mouseleave"),z:(a,b,c,d)=>Ad(a,b,c,d,8,"mousemove"),Q:(a,b,c,d)=>Ad(a,b,c,d,6,"mouseup"),I:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.oe||document.body.Ke||document.body.Je))return-1;a=V(a);if(!a)return-4;Bd(a,b,c,d,"mozpointerlockchange");Bd(a,b,c,d,"webkitpointerlockchange");
Bd(a,b,c,d,"mspointerlockchange");return Bd(a,b,c,d,"pointerlockchange")},A:(a,b,c,d)=>Cd(a,b,c,d),J:(a,b,c,d)=>Dd(a,b,c,d,25,"touchcancel"),x:(a,b,c,d)=>Dd(a,b,c,d,23,"touchend"),y:(a,b,c,d)=>Dd(a,b,c,d,24,"touchmove"),K:(a,b,c,d)=>Dd(a,b,c,d,22,"touchstart"),D:(a,b,c)=>Ed(a,b,c),N:(a,b,c,d)=>(a=V(a))?"undefined"!=typeof a.onwheel?Fd(a,b,c,d):-1:-4,wa:a=>document.title=a?F(v,a):"",v:()=>{throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";
},Ya:(a,b)=>{var c=0;Pd().forEach((d,e)=>{var g=b+c;e=x[a+4*e>>2]=g;for(g=0;g<d.length;++g)t[e++>>0]=d.charCodeAt(g);t[e>>0]=0;c+=d.length+1});return 0},Za:(a,b)=>{var c=Pd();x[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);x[b>>2]=d;return 0},Z:()=>52,_a:()=>52,Wa:function(){return 70},_:(a,b,c,d)=>{for(var e=0,g=0;g<c;g++){var f=x[b>>2],m=x[b+4>>2];b+=8;for(var n=0;n<m;n++){var r=v[f+n],u=Qd[a];0===r||10===r?((1===a?ea:l)(F(u,0)),u.length=0):u.push(r)}e+=m}x[d>>2]=e;return 0},r:Gc,a:Hc,Va:Ic,
b:Jc,Nb:Kc,Ua:Lc,s:Mc,ea:Nc,o:Oc,xa:Pc,aa:Qc,f:Sc,p:Tc,d:Uc,c:Wc,q:Yc,ya:$c,T:ad,k:fd,da:jd,t:ld,g:md,j:od,h:pd,ca:qd,e:rd,hc:sd},Z=function(){function a(c){Z=c.exports;ha=Z.Sd;c=ha.buffer;h.HEAP8=t=new Int8Array(c);h.HEAP16=ja=new Int16Array(c);h.HEAPU8=v=new Uint8Array(c);h.HEAPU16=ka=new Uint16Array(c);h.HEAP32=w=new Int32Array(c);h.HEAPU32=x=new Uint32Array(c);h.HEAPF32=y=new Float32Array(c);h.HEAPF64=A=new Float64Array(c);Ha=Z.Wd;ma.unshift(Z.Td);B--;h.monitorRunDependencies&&h.monitorRunDependencies(B);
0==B&&(null!==ra&&(clearInterval(ra),ra=null),sa&&(c=sa,sa=null,c()));return Z}var b={a:Td};B++;h.monitorRunDependencies&&h.monitorRunDependencies(B);if(h.instantiateWasm)try{return h.instantiateWasm(b,a)}catch(c){return l(`Module.instantiateWasm callback failed with error: ${c}`),!1}ya(b,function(c){a(c.instance)});return{}}(),D=a=>(D=Z.Ud)(a),Ud=h._main=(a,b)=>(Ud=h._main=Z.Vd)(a,b),Tb=()=>(Tb=Z.Xd)(),Ub=a=>(Ub=Z.Yd)(a),vc=a=>(vc=Z.Zd)(a);
h.dynCall_jiji=(a,b,c,d,e)=>(h.dynCall_jiji=Z._d)(a,b,c,d,e);h.dynCall_ji=(a,b)=>(h.dynCall_ji=Z.$d)(a,b);var Vd;sa=function Wd(){Vd||Xd();Vd||(sa=Wd)};function Yd(a=[]){var b=Ud;a.unshift(ca);var c=a.length,d=vc(4*(c+1)),e=d;a.forEach(f=>{x[e>>2]=wc(f);e+=4});x[e>>2]=0;try{var g=b(c,d);bb(g)}catch(f){$a(f)}}
function Xd(){var a=ba;function b(){if(!Vd&&(Vd=!0,h.calledRun=!0,!q)){Fa(ma);Fa(na);if(h.onRuntimeInitialized)h.onRuntimeInitialized();Zd&&Yd(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();pa.unshift(c)}Fa(pa)}}if(!(0<B)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)qa();Fa(la);0<B||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);b()},
1)):b())}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var Zd=!0;h.noInitialRun&&(Zd=!1);Xd();
