var g;g||(g=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},g),ba=[],ca="./this.program",da=(a,b)=>{throw b;},h="";"undefined"!=typeof document&&document.currentScript&&(h=document.currentScript.src);h=0!==h.indexOf("blob:")?h.substr(0,h.replace(/[?#].*/,"").lastIndexOf("/")+1):"";var ea=g.print||console.log.bind(console),m=g.printErr||console.warn.bind(console);Object.assign(g,aa);aa=null;g.arguments&&(ba=g.arguments);g.thisProgram&&(ca=g.thisProgram);
g.quit&&(da=g.quit);var fa;g.wasmBinary&&(fa=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!=typeof WebAssembly&&n("no native wasm support detected");var ha,q=!1,ia="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ja(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&ia)return ia.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|k:(e&7)<<18|f<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function t(a,b){return a?ja(y,a,b):""}
function z(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var k=a.charCodeAt(f);if(55296<=k&&57343>=k){var p=a.charCodeAt(++f);k=65536+((k&1023)<<10)|p&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e}
function ka(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}var A,y,la,B,C,D,ma,na,oa=[],pa=[],qa=[],ra=[],sa=[];function ta(){var a=g.preRun.shift();oa.unshift(a)}var E=0,ua=null,va=null;function n(a){if(g.onAbort)g.onAbort(a);a="Aborted("+a+")";m(a);q=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function wa(){return F.startsWith("data:application/octet-stream;base64,")}var F;F="index.wasm";
if(!wa()){var xa=F;F=g.locateFile?g.locateFile(xa,h):h+xa}function ya(){var a=F;try{if(a==F&&fa)return new Uint8Array(fa);throw"both async and sync fetching of the wasm failed";}catch(b){n(b)}}function za(){return fa||"function"!=typeof fetch?Promise.resolve().then(function(){return ya()}):fetch(F,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+F+"'";return a.arrayBuffer()}).catch(function(){return ya()})}
function Aa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}function Ba(a){for(;0<a.length;)a.shift()(g)}function Ca(a){return 0===a%4&&(0!==a%100||0===a%400)}var Da=[0,31,60,91,121,152,182,213,244,274,305,335],Ea=[0,31,59,90,120,151,181,212,243,273,304,334];function Fa(a){var b=ka(a)+1,c=G(b);c&&z(a,A,c,b);return c}var Ga=0;function Ha(){for(var a=H.length-1;0<=a;--a)Ia(a);H=[];Ja=[]}var Ja=[];
function Ka(){if(Ga&&La.Id)for(var a=0;a<Ja.length;++a){var b=Ja[a];Ja.splice(a,1);--a;b.Vd.apply(null,b.Kd)}}var H=[];function Ia(a){var b=H[a];b.target.removeEventListener(b.Qc,b.wd,b.rd);H.splice(a,1)}function Ma(a){function b(d){++Ga;La=a;Ka();a.xd(d);Ka();--Ga}if(a.td)a.wd=b,a.target.addEventListener(a.Qc,b,a.rd),H.push(a),Na||(ra.push(Ha),Na=!0);else for(var c=0;c<H.length;++c)H[c].target==a.target&&H[c].Qc==a.Qc&&Ia(c--)}var Na,La,Oa,Pa=[0,document,window];
function Qa(a){a=2<a?t(a):a;return Pa[a]||document.querySelector(a)}function Ra(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,k){b.drawElementsInstancedANGLE(c,d,e,f,k)})}
function Sa(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Ta(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}var Ua=1,Va=[],J=[],Wa=[],K=[],Xa=[],L=[],Ya=[],Za=[],M=[],$a={},ab=4;
function N(a){bb||(bb=a)}function cb(a){for(var b=Ua++,c=a.length;c<b;c++)a[c]=null;return b}function db(a,b){a.dd||(a.dd=a.getContext,a.getContext=function(d,e){e=a.dd(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?eb(c,b):0}function eb(a,b){var c=cb(Za),d={Qd:c,attributes:b,version:b.Ad,Zc:a};a.canvas&&(a.canvas.Hd=d);Za[c]=d;("undefined"==typeof b.vd||b.vd)&&fb(d);return c}
function fb(a){a||(a=gb);if(!a.zd){a.zd=!0;var b=a.Zc;Ra(b);Sa(b);Ta(b);b.Jc=b.getExtension("EXT_disjoint_timer_query");b.Td=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var hb={},bb,gb,ib=[];function jb(a,b,c,d){for(var e=0;e<a;e++){var f=O[c](),k=f&&cb(d);f?(f.name=k,d[k]=f):N(1282);B[b+4*e>>2]=k}}
function kb(a,b,c,d,e,f,k,p){b=J[b];if(a=O[a](b,c))d=p&&z(a.name,y,p,d),e&&(B[e>>2]=d),f&&(B[f>>2]=a.size),k&&(B[k>>2]=a.type)}function lb(a,b){C[a>>2]=b;C[a+4>>2]=(b-C[a>>2])/4294967296}
function mb(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&N(1280);return;case 36345:d=0;break;case 34466:var e=O.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=O.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":N(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:N(1280);return}else{if(e instanceof Float32Array||
e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:B[b+4*a>>2]=e[a];break;case 2:D[b+4*a>>2]=e[a];break;case 4:A[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){N(1280);m("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:N(1280);m("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:lb(b,
d);break;case 0:B[b>>2]=d;break;case 2:D[b>>2]=d;break;case 4:A[b>>0]=d?1:0}}else N(1281)}function nb(a){var b=ka(a)+1,c=G(b);z(a,y,c,b);return c}function ob(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function pb(a){var b=a.Oc,c=a.qd,d;if(!b)for(a.Oc=b={},a.pd={},d=0;d<O.getProgramParameter(a,35718);++d){var e=O.getActiveUniform(a,d);var f=e.name;e=e.size;var k=ob(f);k=0<k?f.slice(0,k):f;var p=a.cd;a.cd+=e;c[k]=[e,p];for(f=0;f<e;++f)b[p]=f,a.pd[p++]=k}}
function Q(a){var b=O.ud;if(b){var c=b.Oc[a];"number"==typeof c&&(b.Oc[a]=c=O.getUniformLocation(b,b.pd[a]+(0<c?"["+c+"]":"")));return c}N(1282)}function qb(a,b,c,d){if(c)if(a=J[a],pb(a),a=O.getUniform(a,Q(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:B[c>>2]=a;break;case 2:D[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:B[c+4*b>>2]=a[b];break;case 2:D[c+4*b>>2]=a[b]}else N(1281)}
function rb(a,b,c,d){if(c)if(a=O.getVertexAttrib(a,b),34975==b)B[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:B[c>>2]=a;break;case 2:D[c>>2]=a;break;case 5:B[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:B[c+4*b>>2]=a[b];break;case 2:D[c+4*b>>2]=a[b];break;case 5:B[c+4*b>>2]=Math.fround(a[b])}else N(1281)}
function sb(a,b,c,d,e){a-=5120;a=1==a?y:4==a?B:6==a?D:5==a||28922==a?C:la;var f=31-Math.clz32(a.BYTES_PER_ELEMENT),k=ab;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<f)+k-1&-k)>>f)}var R=[],tb=[];function ub(a){a instanceof Aa||"unwind"==a||da(1,a)}function vb(a){if(!q)try{a()}catch(b){ub(b)}}function wb(a){setTimeout(function(){vb(a)},1E4)}function xb(a){yb||(yb={});yb[a]||(yb[a]=1,m(a))}
var yb,zb=!1,S=null,Ab=0,Bb=null,Cb=0,Db=0,Eb=0,Fb=0,Gb=[],Hb={},Ib,Jb,Kb,Lb=!1,Mb=!1,Nb=[];
function Ob(){function a(){Mb=document.pointerLockElement===g.canvas||document.mozPointerLockElement===g.canvas||document.webkitPointerLockElement===g.canvas||document.msPointerLockElement===g.canvas}g.preloadPlugins||(g.preloadPlugins=[]);if(!Pb){Pb=!0;try{Qb=!0}catch(c){Qb=!1,m("warning: no blob constructor, cannot create blobs with mimetypes")}Rb="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:Qb?null:m("warning: no BlobBuilder");Sb="undefined"!=
typeof window?window.URL?window.URL:window.webkitURL:void 0;g.jd||"undefined"!=typeof Sb||(m("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),g.jd=!0);g.preloadPlugins.push({canHandle:function(c){return!g.jd&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var k=null;if(Qb)try{k=new Blob([c],{type:Tb(d)}),k.size!==c.length&&(k=new Blob([(new Uint8Array(c)).buffer],{type:Tb(d)}))}catch(u){xb("Blob constructor present but fails: "+
u+"; falling back to blob builder")}k||(k=new Rb,k.append((new Uint8Array(c)).buffer),k=k.getBlob());var p=Sb.createObjectURL(k),r=new Image;r.onload=()=>{r.complete||n("Image "+d+" could not be decoded");var u=document.createElement("canvas");u.width=r.width;u.height=r.height;u.getContext("2d").drawImage(r,0,0);Sb.revokeObjectURL(p);e&&e(c)};r.onerror=()=>{ea("Image "+p+" could not be decoded");f&&f()};r.src=p}});g.preloadPlugins.push({canHandle:function(c){return!g.Ud&&c.substr(-4)in{".ogg":1,".wav":1,
".mp3":1}},handle:function(c,d,e,f){function k(){r||(r=!0,e&&e(c))}function p(){r||(r=!0,new Audio,f&&f())}var r=!1;if(Qb){try{var u=new Blob([c],{type:Tb(d)})}catch(I){return p()}u=Sb.createObjectURL(u);var w=new Audio;w.addEventListener("canplaythrough",()=>k(w),!1);w.onerror=function(){if(!r){m("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var I="",P=0,l=0,v=0;v<c.length;v++)for(P=P<<8|c[v],l+=8;6<=l;){var x=P>>l-6&63;l-=6;I+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[x]}2==
l?(I+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(P&3)<<4],I+="=="):4==l&&(I+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(P&15)<<2],I+="=");w.src="data:audio/x-"+d.substr(-3)+";base64,"+I;k(w)}};w.src=u;wb(function(){k(w)})}else return p()}});var b=g.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||
document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),g.elementPointerLock&&b.addEventListener("click",c=>{!Mb&&g.canvas.requestPointerLock&&(g.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Ub(a,b,c,d){if(b&&g.Nc&&a==g.canvas)return g.Nc;var e;if(b){var f={antialias:!1,alpha:!1,Ad:1};if(d)for(var k in d)f[k]=d[k];if("undefined"!=typeof hb&&(e=db(a,f)))var p=Za[e].Zc}else p=a.getContext("2d");if(!p)return null;c&&(b||"undefined"==typeof O||n("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),g.Nc=p,b&&(gb=Za[e],g.Nc=O=gb&&gb.Zc),g.Xd=b,Nb.forEach(function(r){r()}),Ob());return p}var Vb=!1,Wb=void 0,Xb=void 0;
function Yb(a,b){function c(){Lb=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=Zb,Wb&&d.requestPointerLock(),Lb=!0,Xb?("undefined"!=typeof SDL&&(B[SDL.screen>>2]=C[SDL.screen>>2]|8388608),$b(g.canvas),ac()):$b(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),Xb?("undefined"!=typeof SDL&&(B[SDL.screen>>2]=C[SDL.screen>>2]&
-8388609),$b(g.canvas),ac()):$b(d));if(g.onFullScreen)g.onFullScreen(Lb);if(g.onFullscreen)g.onFullscreen(Lb)}Wb=a;Xb=b;"undefined"==typeof Wb&&(Wb=!0);"undefined"==typeof Xb&&(Xb=!1);var d=g.canvas;Vb||(Vb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}
function Zb(){if(!Lb)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var bc=0;function cc(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===bc)bc=b+1E3/60;else for(;b+2>=bc;)bc+=1E3/60;setTimeout(a,Math.max(bc-b,0))}}
function Tb(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var dc=0,ec=0,fc=0,gc=0;
function hc(a){if(Mb)"mousemove"!=a.type&&"mozMovementX"in a?fc=gc=0:(fc=a.movementX||a.mozMovementX||a.webkitMovementX||0,gc=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(dc=SDL.Rd+fc,ec=SDL.Sd+gc):(dc+=fc,ec+=gc);else{var b=g.canvas.getBoundingClientRect(),c=g.canvas.width,d=g.canvas.height,e="undefined"!=typeof window.scrollX?window.scrollX:window.pageXOffset,f="undefined"!=typeof window.scrollY?window.scrollY:window.pageYOffset;"touchstart"!==a.type&&"touchend"!==
a.type&&"touchmove"!==a.type&&(e=a.pageX-(e+b.left),a=a.pageY-(f+b.top),e*=c/b.width,a*=d/b.height,fc=e-dc,gc=a-ec,dc=e,ec=a)}}var ic=[];function ac(){var a=g.canvas;ic.forEach(function(b){b(a.width,a.height)})}function jc(a,b,c){$b(g.canvas,a,b);c||ac()}
function $b(a,b,c){b&&c?(a.Gd=b,a.yd=c):(b=a.Gd,c=a.yd);var d=b,e=c;g.forcedAspectRatio&&0<g.forcedAspectRatio&&(d/e<g.forcedAspectRatio?d=Math.round(e*g.forcedAspectRatio):e=Math.round(d/g.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}Xb?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var Pb,Qb,Rb,Sb;
function kc(a,b){Db=a;Eb=b;if(Bb)if(zb||(zb=!0),0==a)S=function(){var d=Math.max(0,Jb+b-lc())|0;setTimeout(Kb,d)};else if(1==a)S=function(){cc(Kb)};else if(2==a){if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);postMessage("setimmediate","*")}}S=function(){setImmediate(Kb)}}}var lc;lc=()=>performance.now();
function mc(a,b,c,d,e){!Bb||n("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");Bb=a;Cb=d;var f=Ab;zb=!1;Kb=function(){if(!q)if(0<Gb.length){var k=Date.now(),p=Gb.shift();p.Pd(p.Jd);if(Ib){var r=Ib,u=0==r%1?r-1:Math.floor(r);Ib=p.Nd?u:(8*r+(u+.5))/9}ea('main loop blocker "'+p.name+'" took '+(Date.now()-k)+" ms");g.setStatus&&(k=g.statusMessage||"Please wait...",
p=Ib,r=Hb.Od,p?p<r?g.setStatus(k+" ("+(r-p)+"/"+r+")"):g.setStatus(k):g.setStatus(""));f<Ab||setTimeout(Kb,0)}else f<Ab||(Fb=Fb+1|0,1==Db&&1<Eb&&0!=Fb%Eb?S():(0==Db&&(Jb=lc()),q||g.preMainLoop&&!1===g.preMainLoop()||(vb(a),g.postMainLoop&&g.postMainLoop()),f<Ab||("object"==typeof SDL&&SDL.audio&&SDL.audio.Bd&&SDL.audio.Bd(),S())))};e||(b&&0<b?kc(0,1E3/b):kc(1,1),S());if(c)throw"unwind";}var nc=[];function T(a){var b=nc[a];b||(a>=nc.length&&(nc.length=a+1),nc[a]=b=na.get(a));return b}
function oc(a,b,c,d){Oa||(Oa=G(36));a=Qa(a);Ma({target:a,Qc:"resize",td:d,xd:function(e=event){if(e.target==a){var f=document.body;if(f){var k=Oa;B[k>>2]=e.detail;B[k+4>>2]=f.clientWidth;B[k+8>>2]=f.clientHeight;B[k+12>>2]=innerWidth;B[k+16>>2]=innerHeight;B[k+20>>2]=outerWidth;B[k+24>>2]=outerHeight;B[k+28>>2]=pageXOffset;B[k+32>>2]=pageYOffset;T(d)(10,k,b)&&e.preventDefault()}}},rd:c})}function pc(a){if(!noExitRuntime){if(g.onExit)g.onExit(a);q=!0}da(a,new Aa(a))}var qc=[null,[],[]];
function rc(a,b,c,d){this.id=a;this.y=this.x=0;this.ad=!1;this.od=this.nd=0;this.width=b;this.height=c;this.md=b;this.ld=c;this.title=d;this.attributes=U;this.buttons=0;this.keys=[];this.$c=[];this.ed=this.Rc=this.gd=this.kd=this.Pc=this.fd=this.Vc=this.hd=this.sd=this.Yc=this.title=null}function sc(a){return 0>=a||!V?null:V[a-1]}
var X=null,V=null,tc=null,U=null,uc={131073:0,131074:0,131075:1,131076:1,131077:1,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0};
function vc(a){switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;
case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 96;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;
case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;
case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;
case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 93:return 348;default:return-1}}function xc(){var a=X,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);a.keys[343]&&(b|=8);return b}function yc(a){X&&X.ed&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||T(X.ed)(X.id,a))}function zc(a,b){if(X){var c=vc(a);if(-1!=c){var d=b&&X.keys[c];X.keys[c]=b;X.$c[a]=b;X.Rc&&(d&&(b=2),T(X.Rc)(X.id,c,a,b,xc()))}}}
function Ac(){Bc()}function Cc(){Bc()}function Dc(a){zc(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()}function Ec(a){zc(a.keyCode,0)}function Fc(){if(X)for(var a=0;a<X.$c.length;++a)X.$c[a]&&zc(a,0)}function Gc(a){X&&(hc(a),a.target==g.canvas&&X.fd&&T(X.fd)(X.id,dc,ec))}function Hc(a){X&&a.target==g.canvas&&X.Pc&&T(X.Pc)(X.id,1)}function Ic(a){X&&a.target==g.canvas&&X.Pc&&T(X.Pc)(X.id,0)}
function Jc(a,b){if(X&&(hc(a),a.target==g.canvas)){var c=a.button;0<c&&(c=1==c?2:1);if(1==b){X.buttons|=1<<c;try{a.target.setCapture()}catch(d){}}else X.buttons&=~(1<<c);X.Vc&&T(X.Vc)(X.id,c,b,xc())}}function Kc(a){X&&Jc(a,1)}function Lc(a){X&&Jc(a,0)}
function Mc(a){switch(a.type){case "DOMMouseScroll":var b=a.detail/3;break;case "mousewheel":b=a.wheelDelta/120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=100;break;case 1:b/=3;break;case 2:b*=80;break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}b=-b;b=0==b?0:0<b?Math.max(b,1):Math.min(b,-1);if(X&&X.kd&&a.target==g.canvas){var c=b;b="mousewheel"==a.type?a.wheelDeltaX:a.deltaX;T(X.kd)(X.id,b,c);a.preventDefault()}}
var Y={},Nc=[],Oc=null;
function Bc(){if(Fb!==Oc||!Fb){Nc=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads:[];Oc=Fb;for(var a=0;a<Nc.length;++a){var b=Nc[a];if(b){Y[a]||(ea("glfw joystick connected:",a),Y[a]={id:Fa(b.id),Md:b.buttons.length,Ld:b.axes.length,buttons:G(b.buttons.length),axes:G(4*b.axes.length)});for(var c=Y[a],d=0;d<b.buttons.length;++d)A[c.buttons+d>>0]=b.buttons[d].pressed;for(d=0;d<b.axes.length;++d)D[c.axes+4*d>>2]=b.axes[d]}else Y[a]&&(ea("glfw joystick disconnected",
a),Pc(Y[a].id),Pc(Y[a].buttons),Pc(Y[a].axes),delete Y[a])}}}function Qc(a){if(X&&X.gd&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length)return a.preventDefault(),!1}function Rc(a){if(X&&X.gd)return a.preventDefault(),!1}var Sc=[31,29,31,30,31,30,31,31,30,31,30,31],Tc=[31,28,31,30,31,30,31,31,30,31,30,31];function Uc(a){var b=Array(ka(a)+1);z(a,b,0,b.length);return b}for(var O,Z=0;32>Z;++Z)ib.push(Array(Z));var Vc=new Float32Array(288);for(Z=0;288>Z;++Z)R[Z]=Vc.subarray(0,Z+1);
var Wc=new Int32Array(288);for(Z=0;288>Z;++Z)tb[Z]=Wc.subarray(0,Z+1);g.requestFullscreen=function(a,b){Yb(a,b)};g.requestAnimationFrame=function(a){cc(a)};g.setCanvasSize=function(a,b,c){jc(a,b,c)};g.pauseMainLoop=function(){S=null;Ab++};g.resumeMainLoop=function(){Ab++;var a=Db,b=Eb,c=Bb;Bb=null;mc(c,0,!1,Cb,!0);kc(a,b);S()};g.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};
g.createContext=function(a,b,c,d){return Ub(a,b,c,d)};
var Xc={Oa:function(a,b){a=new Date(1E3*(C[a>>2]+4294967296*B[a+4>>2]));B[b>>2]=a.getSeconds();B[b+4>>2]=a.getMinutes();B[b+8>>2]=a.getHours();B[b+12>>2]=a.getDate();B[b+16>>2]=a.getMonth();B[b+20>>2]=a.getFullYear()-1900;B[b+24>>2]=a.getDay();B[b+28>>2]=(Ca(a.getFullYear())?Da:Ea)[a.getMonth()]+a.getDate()-1|0;B[b+36>>2]=-(60*a.getTimezoneOffset());var c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset(),d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();B[b+32>>2]=(c!=d&&a.getTimezoneOffset()==
Math.min(d,c))|0},Pa:function(a,b,c){function d(r){return(r=r.toTimeString().match(/\(([A-Za-z ]+)\)$/))?r[1]:"GMT"}var e=(new Date).getFullYear(),f=new Date(e,0,1),k=new Date(e,6,1);e=f.getTimezoneOffset();var p=k.getTimezoneOffset();C[a>>2]=60*Math.max(e,p);B[b>>2]=Number(e!=p);a=d(f);b=d(k);a=Fa(a);b=Fa(b);p<e?(C[c>>2]=a,C[c+4>>2]=b):(C[c>>2]=b,C[c+4>>2]=a)},Na:function(){return Date.now()},M:function(a,b,c){a=Qa(a);if(!a)return-4;a=0>Pa.indexOf(a)?a.getBoundingClientRect():{left:0,top:0};ma[b>>
3]=a.width;ma[c>>3]=a.height;return 0},oa:function(a){O.activeTexture(a)},na:function(a,b){O.attachShader(J[a],L[b])},Ga:function(a,b){O.Jc.beginQueryEXT(a,M[b])},ma:function(a,b,c){O.bindAttribLocation(J[a],b,t(c))},la:function(a,b){O.bindBuffer(a,Va[b])},ka:function(a,b){O.bindFramebuffer(a,Wa[b])},ja:function(a,b){O.bindRenderbuffer(a,K[b])},ia:function(a,b){O.bindTexture(a,Xa[b])},xa:function(a){O.bindVertexArray(Ya[a])},ha:function(a,b,c,d){O.blendColor(a,b,c,d)},fa:function(a){O.blendEquation(a)},
ea:function(a,b){O.blendEquationSeparate(a,b)},da:function(a,b){O.blendFunc(a,b)},ca:function(a,b,c,d){O.blendFuncSeparate(a,b,c,d)},ba:function(a,b,c,d){O.bufferData(a,c?y.subarray(c,c+b):b,d)},aa:function(a,b,c,d){O.bufferSubData(a,b,y.subarray(d,d+c))},$:function(a){return O.checkFramebufferStatus(a)},_:function(a){O.clear(a)},Z:function(a,b,c,d){O.clearColor(a,b,c,d)},Y:function(a){O.clearDepth(a)},W:function(a){O.clearStencil(a)},V:function(a,b,c,d){O.colorMask(!!a,!!b,!!c,!!d)},U:function(a){O.compileShader(L[a])},
T:function(a,b,c,d,e,f,k,p){O.compressedTexImage2D(a,b,c,d,e,f,p?y.subarray(p,p+k):null)},S:function(a,b,c,d,e,f,k,p,r){O.compressedTexSubImage2D(a,b,c,d,e,f,k,r?y.subarray(r,r+p):null)},R:function(a,b,c,d,e,f,k,p){O.copyTexImage2D(a,b,c,d,e,f,k,p)},Q:function(a,b,c,d,e,f,k,p){O.copyTexSubImage2D(a,b,c,d,e,f,k,p)},P:function(){var a=cb(J),b=O.createProgram();b.name=a;b.Uc=b.Sc=b.Tc=0;b.cd=1;J[a]=b;return a},O:function(a){var b=cb(L);L[b]=O.createShader(a);return b},N:function(a){O.cullFace(a)},L:function(a,
b){for(var c=0;c<a;c++){var d=B[b+4*c>>2],e=Va[d];e&&(O.deleteBuffer(e),e.name=0,Va[d]=null)}},K:function(a,b){for(var c=0;c<a;++c){var d=B[b+4*c>>2],e=Wa[d];e&&(O.deleteFramebuffer(e),e.name=0,Wa[d]=null)}},J:function(a){if(a){var b=J[a];b?(O.deleteProgram(b),b.name=0,J[a]=null):N(1281)}},Ia:function(a,b){for(var c=0;c<a;c++){var d=B[b+4*c>>2],e=M[d];e&&(O.Jc.deleteQueryEXT(e),M[d]=null)}},I:function(a,b){for(var c=0;c<a;c++){var d=B[b+4*c>>2],e=K[d];e&&(O.deleteRenderbuffer(e),e.name=0,K[d]=null)}},
H:function(a){if(a){var b=L[a];b?(O.deleteShader(b),L[a]=null):N(1281)}},G:function(a,b){for(var c=0;c<a;c++){var d=B[b+4*c>>2],e=Xa[d];e&&(O.deleteTexture(e),e.name=0,Xa[d]=null)}},wa:function(a,b){for(var c=0;c<a;c++){var d=B[b+4*c>>2];O.deleteVertexArray(Ya[d]);Ya[d]=null}},F:function(a){O.depthFunc(a)},E:function(a){O.depthMask(!!a)},D:function(a,b){O.depthRange(a,b)},C:function(a,b){O.detachShader(J[a],L[b])},B:function(a){O.disable(a)},A:function(a){O.disableVertexAttribArray(a)},z:function(a,
b,c){O.drawArrays(a,b,c)},sa:function(a,b,c,d){O.drawArraysInstanced(a,b,c,d)},ta:function(a,b){for(var c=ib[a],d=0;d<a;d++)c[d]=B[b+4*d>>2];O.drawBuffers(c)},y:function(a,b,c,d){O.drawElements(a,b,c,d)},qa:function(a,b,c,d,e){O.drawElementsInstanced(a,b,c,d,e)},x:function(a){O.enable(a)},w:function(a){O.enableVertexAttribArray(a)},Fa:function(a){O.Jc.endQueryEXT(a)},v:function(){O.finish()},u:function(){O.flush()},t:function(a,b,c,d){O.framebufferRenderbuffer(a,b,c,K[d])},s:function(a,b,c,d,e){O.framebufferTexture2D(a,
b,c,Xa[d],e)},q:function(a){O.frontFace(a)},p:function(a,b){jb(a,b,"createBuffer",Va)},n:function(a,b){jb(a,b,"createFramebuffer",Wa)},Ja:function(a,b){for(var c=0;c<a;c++){var d=O.Jc.createQueryEXT();if(!d){for(N(1282);c<a;)B[b+4*c++>>2]=0;break}var e=cb(M);d.name=e;M[e]=d;B[b+4*c>>2]=e}},m:function(a,b){jb(a,b,"createRenderbuffer",K)},l:function(a,b){jb(a,b,"createTexture",Xa)},va:function(a,b){jb(a,b,"createVertexArray",Ya)},o:function(a){O.generateMipmap(a)},k:function(a,b,c,d,e,f,k){kb("getActiveAttrib",
a,b,c,d,e,f,k)},j:function(a,b,c,d,e,f,k){kb("getActiveUniform",a,b,c,d,e,f,k)},i:function(a,b,c,d){a=O.getAttachedShaders(J[a]);var e=a.length;e>b&&(e=b);B[c>>2]=e;for(b=0;b<e;++b)B[d+4*b>>2]=L.indexOf(a[b])},h:function(a,b){return O.getAttribLocation(J[a],t(b))},Ac:function(a,b){mb(a,b,4)},zc:function(a,b,c){c?B[c>>2]=O.getBufferParameter(a,b):N(1281)},yc:function(){var a=O.getError()||bb;bb=0;return a},xc:function(a,b){mb(a,b,2)},wc:function(a,b,c,d){a=O.getFramebufferAttachmentParameter(a,b,c);
if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;B[d>>2]=a},vc:function(a,b){mb(a,b,0)},tc:function(a,b,c,d){a=O.getProgramInfoLog(J[a]);null===a&&(a="(unknown error)");b=0<b&&d?z(a,y,d,b):0;c&&(B[c>>2]=b)},uc:function(a,b,c){if(c)if(a>=Ua)N(1281);else if(a=J[a],35716==b)a=O.getProgramInfoLog(a),null===a&&(a="(unknown error)"),B[c>>2]=a.length+1;else if(35719==b){if(!a.Uc)for(b=0;b<O.getProgramParameter(a,35718);++b)a.Uc=Math.max(a.Uc,O.getActiveUniform(a,b).name.length+1);
B[c>>2]=a.Uc}else if(35722==b){if(!a.Sc)for(b=0;b<O.getProgramParameter(a,35721);++b)a.Sc=Math.max(a.Sc,O.getActiveAttrib(a,b).name.length+1);B[c>>2]=a.Sc}else if(35381==b){if(!a.Tc)for(b=0;b<O.getProgramParameter(a,35382);++b)a.Tc=Math.max(a.Tc,O.getActiveUniformBlockName(a,b).length+1);B[c>>2]=a.Tc}else B[c>>2]=O.getProgramParameter(a,b);else N(1281)},za:function(a,b,c){if(c){a=O.Jc.getQueryObjectEXT(M[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;lb(c,d)}else N(1281)},Ba:function(a,b,c){if(c){a=
O.Jc.getQueryObjectEXT(M[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;B[c>>2]=d}else N(1281)},ya:function(a,b,c){if(c){a=O.Jc.getQueryObjectEXT(M[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;lb(c,d)}else N(1281)},Aa:function(a,b,c){if(c){a=O.Jc.getQueryObjectEXT(M[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;B[c>>2]=d}else N(1281)},Da:function(a,b,c){c?B[c>>2]=O.Jc.getQueryEXT(a,b):N(1281)},sc:function(a,b,c){c?B[c>>2]=O.getRenderbufferParameter(a,b):N(1281)},pc:function(a,b,c,d){a=O.getShaderInfoLog(L[a]);
null===a&&(a="(unknown error)");b=0<b&&d?z(a,y,d,b):0;c&&(B[c>>2]=b)},oc:function(a,b,c,d){a=O.getShaderPrecisionFormat(a,b);B[c>>2]=a.rangeMin;B[c+4>>2]=a.rangeMax;B[d>>2]=a.precision},nc:function(a,b,c,d){if(a=O.getShaderSource(L[a]))b=0<b&&d?z(a,y,d,b):0,c&&(B[c>>2]=b)},rc:function(a,b,c){c?35716==b?(a=O.getShaderInfoLog(L[a]),null===a&&(a="(unknown error)"),B[c>>2]=a?a.length+1:0):35720==b?(a=O.getShaderSource(L[a]),B[c>>2]=a?a.length+1:0):B[c>>2]=O.getShaderParameter(L[a],b):N(1281)},mc:function(a){var b=
$a[a];if(!b){switch(a){case 7939:b=O.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=nb(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=O.getParameter(a))||N(1280);b=b&&nb(b);break;case 7938:b=nb("OpenGL ES 2.0 ("+O.getParameter(7938)+")");break;case 35724:b=O.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=nb(b);break;default:N(1280)}$a[a]=
b}return b},lc:function(a,b,c){c?D[c>>2]=O.getTexParameter(a,b):N(1281)},kc:function(a,b,c){c?B[c>>2]=O.getTexParameter(a,b):N(1281)},hc:function(a,b){b=t(b);if(a=J[a]){pb(a);var c=a.Oc,d=0,e=b,f=ob(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.qd[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||O.getUniformLocation(a,b)))return d}else N(1281);return-1},jc:function(a,b,c){qb(a,b,c,2)},ic:function(a,b,c){qb(a,b,c,0)},dc:function(a,b,c){c?B[c>>2]=O.getVertexAttribOffset(a,b):N(1281)},gc:function(a,
b,c){rb(a,b,c,2)},ec:function(a,b,c){rb(a,b,c,5)},cc:function(a,b){O.hint(a,b)},bc:function(a){return(a=Va[a])?O.isBuffer(a):0},ac:function(a){return O.isEnabled(a)},$b:function(a){return(a=Wa[a])?O.isFramebuffer(a):0},_b:function(a){return(a=J[a])?O.isProgram(a):0},Ha:function(a){return(a=M[a])?O.Jc.isQueryEXT(a):0},Zb:function(a){return(a=K[a])?O.isRenderbuffer(a):0},Yb:function(a){return(a=L[a])?O.isShader(a):0},Xb:function(a){return(a=Xa[a])?O.isTexture(a):0},ua:function(a){return(a=Ya[a])?O.isVertexArray(a):
0},Vb:function(a){O.lineWidth(a)},Ub:function(a){a=J[a];O.linkProgram(a);a.Oc=0;a.qd={}},Tb:function(a,b){3317==a&&(ab=b);O.pixelStorei(a,b)},Sb:function(a,b){O.polygonOffset(a,b)},Ea:function(a,b){O.Jc.queryCounterEXT(M[a],b)},Rb:function(a,b,c,d,e,f,k){(k=sb(f,e,c,d,k))?O.readPixels(a,b,c,d,e,f,k):N(1280)},Qb:function(){},Pb:function(a,b,c,d){O.renderbufferStorage(a,b,c,d)},Ob:function(a,b){O.sampleCoverage(a,!!b)},Nb:function(a,b,c,d){O.scissor(a,b,c,d)},Mb:function(){N(1280)},Kb:function(a,b,
c,d){for(var e="",f=0;f<b;++f){var k=d?B[d+4*f>>2]:-1;e+=t(B[c+4*f>>2],0>k?void 0:k)}O.shaderSource(L[a],e)},Jb:function(a,b,c){O.stencilFunc(a,b,c)},Ib:function(a,b,c,d){O.stencilFuncSeparate(a,b,c,d)},Hb:function(a){O.stencilMask(a)},Gb:function(a,b){O.stencilMaskSeparate(a,b)},Fb:function(a,b,c){O.stencilOp(a,b,c)},Eb:function(a,b,c,d){O.stencilOpSeparate(a,b,c,d)},Db:function(a,b,c,d,e,f,k,p,r){O.texImage2D(a,b,c,d,e,f,k,p,r?sb(p,k,d,e,r):null)},Cb:function(a,b,c){O.texParameterf(a,b,c)},Bb:function(a,
b,c){O.texParameterf(a,b,D[c>>2])},zb:function(a,b,c){O.texParameteri(a,b,c)},yb:function(a,b,c){O.texParameteri(a,b,B[c>>2])},xb:function(a,b,c,d,e,f,k,p,r){var u=null;r&&(u=sb(p,k,e,f,r));O.texSubImage2D(a,b,c,d,e,f,k,p,u)},wb:function(a,b){O.uniform1f(Q(a),b)},vb:function(a,b,c){if(288>=b)for(var d=R[b-1],e=0;e<b;++e)d[e]=D[c+4*e>>2];else d=D.subarray(c>>2,c+4*b>>2);O.uniform1fv(Q(a),d)},ub:function(a,b){O.uniform1i(Q(a),b)},tb:function(a,b,c){if(288>=b)for(var d=tb[b-1],e=0;e<b;++e)d[e]=B[c+4*
e>>2];else d=B.subarray(c>>2,c+4*b>>2);O.uniform1iv(Q(a),d)},sb:function(a,b,c){O.uniform2f(Q(a),b,c)},rb:function(a,b,c){if(144>=b)for(var d=R[2*b-1],e=0;e<2*b;e+=2)d[e]=D[c+4*e>>2],d[e+1]=D[c+(4*e+4)>>2];else d=D.subarray(c>>2,c+8*b>>2);O.uniform2fv(Q(a),d)},qb:function(a,b,c){O.uniform2i(Q(a),b,c)},ob:function(a,b,c){if(144>=b)for(var d=tb[2*b-1],e=0;e<2*b;e+=2)d[e]=B[c+4*e>>2],d[e+1]=B[c+(4*e+4)>>2];else d=B.subarray(c>>2,c+8*b>>2);O.uniform2iv(Q(a),d)},nb:function(a,b,c,d){O.uniform3f(Q(a),b,
c,d)},mb:function(a,b,c){if(96>=b)for(var d=R[3*b-1],e=0;e<3*b;e+=3)d[e]=D[c+4*e>>2],d[e+1]=D[c+(4*e+4)>>2],d[e+2]=D[c+(4*e+8)>>2];else d=D.subarray(c>>2,c+12*b>>2);O.uniform3fv(Q(a),d)},lb:function(a,b,c,d){O.uniform3i(Q(a),b,c,d)},kb:function(a,b,c){if(96>=b)for(var d=tb[3*b-1],e=0;e<3*b;e+=3)d[e]=B[c+4*e>>2],d[e+1]=B[c+(4*e+4)>>2],d[e+2]=B[c+(4*e+8)>>2];else d=B.subarray(c>>2,c+12*b>>2);O.uniform3iv(Q(a),d)},jb:function(a,b,c,d,e){O.uniform4f(Q(a),b,c,d,e)},ib:function(a,b,c){if(72>=b){var d=R[4*
b-1],e=D;c>>=2;for(var f=0;f<4*b;f+=4){var k=c+f;d[f]=e[k];d[f+1]=e[k+1];d[f+2]=e[k+2];d[f+3]=e[k+3]}}else d=D.subarray(c>>2,c+16*b>>2);O.uniform4fv(Q(a),d)},hb:function(a,b,c,d,e){O.uniform4i(Q(a),b,c,d,e)},gb:function(a,b,c){if(72>=b)for(var d=tb[4*b-1],e=0;e<4*b;e+=4)d[e]=B[c+4*e>>2],d[e+1]=B[c+(4*e+4)>>2],d[e+2]=B[c+(4*e+8)>>2],d[e+3]=B[c+(4*e+12)>>2];else d=B.subarray(c>>2,c+16*b>>2);O.uniform4iv(Q(a),d)},fb:function(a,b,c,d){if(72>=b)for(var e=R[4*b-1],f=0;f<4*b;f+=4)e[f]=D[d+4*f>>2],e[f+1]=
D[d+(4*f+4)>>2],e[f+2]=D[d+(4*f+8)>>2],e[f+3]=D[d+(4*f+12)>>2];else e=D.subarray(d>>2,d+16*b>>2);O.uniformMatrix2fv(Q(a),!!c,e)},db:function(a,b,c,d){if(32>=b)for(var e=R[9*b-1],f=0;f<9*b;f+=9)e[f]=D[d+4*f>>2],e[f+1]=D[d+(4*f+4)>>2],e[f+2]=D[d+(4*f+8)>>2],e[f+3]=D[d+(4*f+12)>>2],e[f+4]=D[d+(4*f+16)>>2],e[f+5]=D[d+(4*f+20)>>2],e[f+6]=D[d+(4*f+24)>>2],e[f+7]=D[d+(4*f+28)>>2],e[f+8]=D[d+(4*f+32)>>2];else e=D.subarray(d>>2,d+36*b>>2);O.uniformMatrix3fv(Q(a),!!c,e)},cb:function(a,b,c,d){if(18>=b){var e=
R[16*b-1],f=D;d>>=2;for(var k=0;k<16*b;k+=16){var p=d+k;e[k]=f[p];e[k+1]=f[p+1];e[k+2]=f[p+2];e[k+3]=f[p+3];e[k+4]=f[p+4];e[k+5]=f[p+5];e[k+6]=f[p+6];e[k+7]=f[p+7];e[k+8]=f[p+8];e[k+9]=f[p+9];e[k+10]=f[p+10];e[k+11]=f[p+11];e[k+12]=f[p+12];e[k+13]=f[p+13];e[k+14]=f[p+14];e[k+15]=f[p+15]}}else e=D.subarray(d>>2,d+64*b>>2);O.uniformMatrix4fv(Q(a),!!c,e)},bb:function(a){a=J[a];O.useProgram(a);O.ud=a},ab:function(a){O.validateProgram(J[a])},$a:function(a,b){O.vertexAttrib1f(a,b)},_a:function(a,b){O.vertexAttrib1f(a,
D[b>>2])},Za:function(a,b,c){O.vertexAttrib2f(a,b,c)},Ya:function(a,b){O.vertexAttrib2f(a,D[b>>2],D[b+4>>2])},Xa:function(a,b,c,d){O.vertexAttrib3f(a,b,c,d)},Wa:function(a,b){O.vertexAttrib3f(a,D[b>>2],D[b+4>>2],D[b+8>>2])},Ua:function(a,b,c,d,e){O.vertexAttrib4f(a,b,c,d,e)},Ta:function(a,b){O.vertexAttrib4f(a,D[b>>2],D[b+4>>2],D[b+8>>2],D[b+12>>2])},pa:function(a,b){O.vertexAttribDivisor(a,b)},Sa:function(a,b,c,d,e,f){O.vertexAttribPointer(a,b,c,!!d,e,f)},Ra:function(a,b,c,d){O.viewport(a,b,c,d)},
Qa:function(a,b,c){y.copyWithin(a,b,b+c)},Ma:function(){n("OOM")},ga:function(a,b,c){a=Qa(a);if(!a)return-4;a.width=b;a.height=c;return 0},La:function(a,b,c){a=T(a);mc(a,b,c)},Va:function(a,b,c,d){oc(a,b,c,d);return 0},d:pc,g:function(a,b,c,d){for(var e=0,f=0;f<c;f++){var k=C[b>>2],p=C[b+4>>2];b+=8;for(var r=0;r<p;r++){var u=y[k+r],w=qc[a];0===u||10===u?((1===a?ea:m)(ja(w,0)),w.length=0):w.push(u)}e+=p}C[d>>2]=e;return 0},r:function(a,b,c,d){var e;for(e=0;e<V.length&&null!==V[e];e++);if(0<e)throw"glfwCreateWindow only supports one window at time currently";
var f=e+1;if(0>=a||0>=b)f=0;else{d?Yb():jc(a,b);for(e=0;e<V.length&&null==V[e];e++);d=0<U[139265];e==V.length&&(d?g.Nc=Ub(g.canvas,!0,!0,{antialias:1<U[135181],depth:0<U[135173],stencil:0<U[135174],alpha:0<U[135172]}):Ob());!g.Nc&&d?f=0:(a=new rc(f,a,b,c),f-1==V.length?V.push(a):V[f-1]=a,X=a,f=a.id)}return f},Ka:function(a){a:{if(a=sc(a)){a.sd&&T(a.sd)(a.id);V[a.id-1]=null;X.id==a.id&&(X=null);for(a=0;a<V.length;a++)if(null!==V[a]){a=void 0;break a}g.Nc=void 0}a=void 0}return a},Ca:function(a,b,c){ma[b>>
3]=dc;ma[c>>3]=ec},Bc:function(){return 1},f:function(){return lc()/1E3-tc},qc:function(){return 0},X:function(){if(V)return 1;tc=lc()/1E3;U=uc;V=[];X=null;window.addEventListener("gamepadconnected",Ac,!0);window.addEventListener("gamepaddisconnected",Cc,!0);window.addEventListener("keydown",Dc,!0);window.addEventListener("keypress",yc,!0);window.addEventListener("keyup",Ec,!0);window.addEventListener("blur",Fc,!0);g.canvas.addEventListener("touchmove",Gc,!0);g.canvas.addEventListener("touchstart",
Kc,!0);g.canvas.addEventListener("touchcancel",Lc,!0);g.canvas.addEventListener("touchend",Lc,!0);g.canvas.addEventListener("mousemove",Gc,!0);g.canvas.addEventListener("mousedown",Kc,!0);g.canvas.addEventListener("mouseup",Lc,!0);g.canvas.addEventListener("wheel",Mc,!0);g.canvas.addEventListener("mousewheel",Mc,!0);g.canvas.addEventListener("mouseenter",Hc,!0);g.canvas.addEventListener("mouseleave",Ic,!0);g.canvas.addEventListener("drop",Qc,!0);g.canvas.addEventListener("dragover",Rc,!0);ic.push((a,
b)=>{if(X){var c=!0;document.fullscreen||document.fullScreen||document.mozFullScreen||document.webkitIsFullScreen?(X.nd=X.x,X.od=X.y,X.md=X.width,X.ld=X.height,X.x=X.y=0,X.width=screen.width,X.height=screen.height,X.ad=!0):1==X.ad?(X.x=X.nd,X.y=X.od,X.width=X.md,X.height=X.ld,X.ad=!1):X.width!=a||X.height!=b?(X.width=a,X.height=b):c=!1;c&&(jc(X.width,X.height,!0),X&&X.Yc&&T(X.Yc)(X.id,X.width,X.height),X&&X.hd&&T(X.hd)(X.id,X.width,X.height))}});return 1},pb:function(){},Lb:function(a,b){if(a=sc(a)){var c=
a.Rc;a.Rc=b;b=c}else b=null;return b},Ab:function(a,b){if(a=sc(a)){var c=a.Vc;a.Vc=b;b=c}else b=null;return b},fc:function(a,b,c){if(a=sc(a))a.x=b,a.y=c},Wb:function(a,b){if(a=sc(a)){var c=a.Yc;a.Yc=b;b=c}else b=null;return b},b:function(a,b){if(a=sc(a))a.title=t(b),X.id==a.id&&(document.title=a.title)},ra:function(){},eb:function(a){a=Math.abs(a);0==a?kc(0,0):kc(1,a)},e:function(){window.removeEventListener("gamepadconnected",Ac,!0);window.removeEventListener("gamepaddisconnected",Cc,!0);window.removeEventListener("keydown",
Dc,!0);window.removeEventListener("keypress",yc,!0);window.removeEventListener("keyup",Ec,!0);window.removeEventListener("blur",Fc,!0);g.canvas.removeEventListener("touchmove",Gc,!0);g.canvas.removeEventListener("touchstart",Kc,!0);g.canvas.removeEventListener("touchcancel",Lc,!0);g.canvas.removeEventListener("touchend",Lc,!0);g.canvas.removeEventListener("mousemove",Gc,!0);g.canvas.removeEventListener("mousedown",Kc,!0);g.canvas.removeEventListener("mouseup",Lc,!0);g.canvas.removeEventListener("wheel",
Mc,!0);g.canvas.removeEventListener("mousewheel",Mc,!0);g.canvas.removeEventListener("mouseenter",Hc,!0);g.canvas.removeEventListener("mouseleave",Ic,!0);g.canvas.removeEventListener("drop",Qc,!0);g.canvas.removeEventListener("dragover",Rc,!0);g.canvas.width=g.canvas.height=1;X=V=null},c:function(a,b){U[a]=b},a:function(a,b,c,d){function e(l,v,x){for(l="number"==typeof l?l.toString():l||"";l.length<v;)l=x[0]+l;return l}function f(l,v){return e(l,v,"0")}function k(l,v){function x(wc){return 0>wc?-1:
0<wc?1:0}var W;0===(W=x(l.getFullYear()-v.getFullYear()))&&0===(W=x(l.getMonth()-v.getMonth()))&&(W=x(l.getDate()-v.getDate()));return W}function p(l){switch(l.getDay()){case 0:return new Date(l.getFullYear()-1,11,29);case 1:return l;case 2:return new Date(l.getFullYear(),0,3);case 3:return new Date(l.getFullYear(),0,2);case 4:return new Date(l.getFullYear(),0,1);case 5:return new Date(l.getFullYear()-1,11,31);case 6:return new Date(l.getFullYear()-1,11,30)}}function r(l){var v=l.Lc;for(l=new Date((new Date(l.Mc+
1900,0,1)).getTime());0<v;){var x=l.getMonth(),W=(Ca(l.getFullYear())?Sc:Tc)[x];if(v>W-l.getDate())v-=W-l.getDate()+1,l.setDate(1),11>x?l.setMonth(x+1):(l.setMonth(0),l.setFullYear(l.getFullYear()+1));else{l.setDate(l.getDate()+v);break}}x=new Date(l.getFullYear()+1,0,4);v=p(new Date(l.getFullYear(),0,4));x=p(x);return 0>=k(v,l)?0>=k(x,l)?l.getFullYear()+1:l.getFullYear():l.getFullYear()-1}var u=B[d+40>>2];d={Ed:B[d>>2],Dd:B[d+4>>2],Wc:B[d+8>>2],bd:B[d+12>>2],Xc:B[d+16>>2],Mc:B[d+20>>2],Kc:B[d+24>>
2],Lc:B[d+28>>2],Wd:B[d+32>>2],Cd:B[d+36>>2],Fd:u?t(u):""};c=t(c);u={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var w in u)c=c.replace(new RegExp(w,"g"),u[w]);var I="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
P="January February March April May June July August September October November December".split(" ");u={"%a":function(l){return I[l.Kc].substring(0,3)},"%A":function(l){return I[l.Kc]},"%b":function(l){return P[l.Xc].substring(0,3)},"%B":function(l){return P[l.Xc]},"%C":function(l){return f((l.Mc+1900)/100|0,2)},"%d":function(l){return f(l.bd,2)},"%e":function(l){return e(l.bd,2," ")},"%g":function(l){return r(l).toString().substring(2)},"%G":function(l){return r(l)},"%H":function(l){return f(l.Wc,
2)},"%I":function(l){l=l.Wc;0==l?l=12:12<l&&(l-=12);return f(l,2)},"%j":function(l){for(var v=0,x=0;x<=l.Xc-1;v+=(Ca(l.Mc+1900)?Sc:Tc)[x++]);return f(l.bd+v,3)},"%m":function(l){return f(l.Xc+1,2)},"%M":function(l){return f(l.Dd,2)},"%n":function(){return"\n"},"%p":function(l){return 0<=l.Wc&&12>l.Wc?"AM":"PM"},"%S":function(l){return f(l.Ed,2)},"%t":function(){return"\t"},"%u":function(l){return l.Kc||7},"%U":function(l){return f(Math.floor((l.Lc+7-l.Kc)/7),2)},"%V":function(l){var v=Math.floor((l.Lc+
7-(l.Kc+6)%7)/7);2>=(l.Kc+371-l.Lc-2)%7&&v++;if(v)53==v&&(x=(l.Kc+371-l.Lc)%7,4==x||3==x&&Ca(l.Mc)||(v=1));else{v=52;var x=(l.Kc+7-l.Lc-1)%7;(4==x||5==x&&Ca(l.Mc%400-1))&&v++}return f(v,2)},"%w":function(l){return l.Kc},"%W":function(l){return f(Math.floor((l.Lc+7-(l.Kc+6)%7)/7),2)},"%y":function(l){return(l.Mc+1900).toString().substring(2)},"%Y":function(l){return l.Mc+1900},"%z":function(l){l=l.Cd;var v=0<=l;l=Math.abs(l)/60;return(v?"+":"-")+String("0000"+(l/60*100+l%60)).slice(-4)},"%Z":function(l){return l.Fd},
"%%":function(){return"%"}};c=c.replace(/%%/g,"\x00\x00");for(w in u)c.includes(w)&&(c=c.replace(new RegExp(w,"g"),u[w](d)));c=c.replace(/\0\0/g,"%");w=Uc(c);if(w.length>b)return 0;A.set(w,a);return w.length-1}};
(function(){function a(e){g.asm=e.exports;ha=g.asm.Cc;e=ha.buffer;g.HEAP8=A=new Int8Array(e);g.HEAP16=new Int16Array(e);g.HEAP32=B=new Int32Array(e);g.HEAPU8=y=new Uint8Array(e);g.HEAPU16=la=new Uint16Array(e);g.HEAPU32=C=new Uint32Array(e);g.HEAPF32=D=new Float32Array(e);g.HEAPF64=ma=new Float64Array(e);na=g.asm.Hc;pa.unshift(g.asm.Dc);E--;g.monitorRunDependencies&&g.monitorRunDependencies(E);0==E&&(null!==ua&&(clearInterval(ua),ua=null),va&&(e=va,va=null,e()))}function b(e){a(e.instance)}function c(e){return za().then(function(f){return WebAssembly.instantiate(f,
d)}).then(function(f){return f}).then(e,function(f){m("failed to asynchronously prepare wasm: "+f);n(f)})}var d={a:Xc};E++;g.monitorRunDependencies&&g.monitorRunDependencies(E);if(g.instantiateWasm)try{return g.instantiateWasm(d,a)}catch(e){return m("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return fa||"function"!=typeof WebAssembly.instantiateStreaming||wa()||"function"!=typeof fetch?c(b):fetch(F,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,
d).then(b,function(f){m("wasm streaming compile failed: "+f);m("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();function G(){return(G=g.asm.Ec).apply(null,arguments)}function Pc(){return(Pc=g.asm.Fc).apply(null,arguments)}var Yc=g._main=function(){return(Yc=g._main=g.asm.Gc).apply(null,arguments)};function Zc(){return(Zc=g.asm.Ic).apply(null,arguments)}var $c;va=function ad(){$c||bd();$c||(va=ad)};
function cd(a=[]){var b=Yc;a.unshift(ca);var c=a.length,d=Zc(4*(c+1)),e=d>>2;a.forEach(k=>{var p=B,r=e++,u=ka(k)+1,w=Zc(u);z(k,A,w,u);p[r]=w});B[e]=0;try{var f=b(c,d);pc(f,!0)}catch(k){ub(k)}}
function bd(){var a=ba;function b(){if(!$c&&($c=!0,g.calledRun=!0,!q)){Ba(pa);Ba(qa);if(g.onRuntimeInitialized)g.onRuntimeInitialized();dd&&cd(a);if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();sa.unshift(c)}Ba(sa)}}if(!(0<E)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)ta();Ba(oa);0<E||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},
1)):b())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var dd=!0;g.noInitialRun&&(dd=!1);bd();
