
var g;g||(g=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},g),ba=[],ca="./this.program",da=(a,b)=>{throw b;},h="";"undefined"!=typeof document&&document.currentScript&&(h=document.currentScript.src);h=0!==h.indexOf("blob:")?h.substr(0,h.replace(/[?#].*/,"").lastIndexOf("/")+1):"";var m=g.print||console.log.bind(console),n=g.printErr||console.warn.bind(console);Object.assign(g,aa);aa=null;g.arguments&&(ba=g.arguments);g.thisProgram&&(ca=g.thisProgram);
g.quit&&(da=g.quit);var ea;g.wasmBinary&&(ea=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!=typeof WebAssembly&&q("no native wasm support detected");var fa,t=!1,ha="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ia(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&ha)return ha.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|k:(e&7)<<18|f<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function y(a,b){return a?ia(z,a,b):""}
function A(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var k=a.charCodeAt(f);if(55296<=k&&57343>=k){var p=a.charCodeAt(++f);k=65536+((k&1023)<<10)|p&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e}
function ja(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}var B,z,ka,C,D,E,la,ma,na=[],oa=[],pa=[],qa=[],ra=[];function sa(){var a=g.preRun.shift();na.unshift(a)}var F=0,ta=null,ua=null;function q(a){if(g.onAbort)g.onAbort(a);a="Aborted("+a+")";n(a);t=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function va(){return G.startsWith("data:application/octet-stream;base64,")}var G;G="index.wasm";
if(!va()){var wa=G;G=g.locateFile?g.locateFile(wa,h):h+wa}function xa(){var a=G;try{if(a==G&&ea)return new Uint8Array(ea);throw"both async and sync fetching of the wasm failed";}catch(b){q(b)}}function ya(){return ea||"function"!=typeof fetch?Promise.resolve().then(function(){return xa()}):fetch(G,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+G+"'";return a.arrayBuffer()}).catch(function(){return xa()})}
function za(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}function Aa(a){for(;0<a.length;)a.shift()(g)}function Ba(a){return 0===a%4&&(0!==a%100||0===a%400)}var Ca=[0,31,60,91,121,152,182,213,244,274,305,335],Da=[0,31,59,90,120,151,181,212,243,273,304,334];function Ea(a){var b=ja(a)+1,c=Fa(b);c&&A(a,B,c,b);return c}var Ga=0;function Ha(){for(var a=H.length-1;0<=a;--a)Ia(a);H=[];Ja=[]}var Ja=[];
function Ka(){if(Ga&&La.Nd)for(var a=0;a<Ja.length;++a){var b=Ja[a];Ja.splice(a,1);--a;b.$d.apply(null,b.Pd)}}var H=[];function Ia(a){var b=H[a];b.target.removeEventListener(b.Uc,b.Bd,b.wd);H.splice(a,1)}function Ma(a){function b(d){++Ga;La=a;Ka();a.Cd(d);Ka();--Ga}if(a.yd)a.Bd=b,a.target.addEventListener(a.Uc,b,a.wd),H.push(a),Na||(qa.push(Ha),Na=!0);else for(var c=0;c<H.length;++c)H[c].target==a.target&&H[c].Uc==a.Uc&&Ia(c--)}var Na,La,Oa,Pa=[0,document,window];
function Qa(a){a=2<a?y(a):a;return Pa[a]||document.querySelector(a)}function Ra(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,k){b.drawElementsInstancedANGLE(c,d,e,f,k)})}
function Sa(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Ta(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}var Ua=1,Va=[],I=[],Wa=[],Xa=[],Ya=[],K=[],Za=[],$a=[],L=[],ab={},bb=4;
function M(a){cb||(cb=a)}function db(a){for(var b=Ua++,c=a.length;c<b;c++)a[c]=null;return b}function eb(a,b){a.hd||(a.hd=a.getContext,a.getContext=function(d,e){e=a.hd(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?fb(c,b):0}function fb(a,b){var c=db($a),d={Vd:c,attributes:b,version:b.Fd,cd:a};a.canvas&&(a.canvas.Md=d);$a[c]=d;("undefined"==typeof b.Ad||b.Ad)&&gb(d);return c}
function gb(a){a||(a=hb);if(!a.Ed){a.Ed=!0;var b=a.cd;Ra(b);Sa(b);Ta(b);b.Nc=b.getExtension("EXT_disjoint_timer_query");b.Yd=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var ib={},cb,hb,jb=[];function kb(a,b,c,d){for(var e=0;e<a;e++){var f=N[c](),k=f&&db(d);f?(f.name=k,d[k]=f):M(1282);C[b+4*e>>2]=k}}
function lb(a,b,c,d,e,f,k,p){b=I[b];if(a=N[a](b,c))d=p&&A(a.name,z,p,d),e&&(C[e>>2]=d),f&&(C[f>>2]=a.size),k&&(C[k>>2]=a.type)}function mb(a,b){D[a>>2]=b;D[a+4>>2]=(b-D[a>>2])/4294967296}
function nb(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&M(1280);return;case 36345:d=0;break;case 34466:var e=N.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=N.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":M(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:M(1280);return}else{if(e instanceof Float32Array||
e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:C[b+4*a>>2]=e[a];break;case 2:E[b+4*a>>2]=e[a];break;case 4:B[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){M(1280);n("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:M(1280);n("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:mb(b,
d);break;case 0:C[b>>2]=d;break;case 2:E[b>>2]=d;break;case 4:B[b>>0]=d?1:0}}else M(1281)}function ob(a){var b=ja(a)+1,c=Fa(b);A(a,z,c,b);return c}function pb(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function qb(a){var b=a.Sc,c=a.vd,d;if(!b)for(a.Sc=b={},a.ud={},d=0;d<N.getProgramParameter(a,35718);++d){var e=N.getActiveUniform(a,d);var f=e.name;e=e.size;var k=pb(f);k=0<k?f.slice(0,k):f;var p=a.gd;a.gd+=e;c[k]=[e,p];for(f=0;f<e;++f)b[p]=f,a.ud[p++]=k}}
function O(a){var b=N.zd;if(b){var c=b.Sc[a];"number"==typeof c&&(b.Sc[a]=c=N.getUniformLocation(b,b.ud[a]+(0<c?"["+c+"]":"")));return c}M(1282)}function rb(a,b,c,d){if(c)if(a=I[a],qb(a),a=N.getUniform(a,O(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:C[c>>2]=a;break;case 2:E[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:C[c+4*b>>2]=a[b];break;case 2:E[c+4*b>>2]=a[b]}else M(1281)}
function sb(a,b,c,d){if(c)if(a=N.getVertexAttrib(a,b),34975==b)C[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:C[c>>2]=a;break;case 2:E[c>>2]=a;break;case 5:C[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:C[c+4*b>>2]=a[b];break;case 2:E[c+4*b>>2]=a[b];break;case 5:C[c+4*b>>2]=Math.fround(a[b])}else M(1281)}
function tb(a,b,c,d,e){a-=5120;a=1==a?z:4==a?C:6==a?E:5==a||28922==a?D:ka;var f=31-Math.clz32(a.BYTES_PER_ELEMENT),k=bb;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<f)+k-1&-k)>>f)}var P=[],ub=[];function vb(a){a instanceof za||"unwind"==a||da(1,a)}function wb(a){if(!t)try{a()}catch(b){vb(b)}}function xb(a){setTimeout(function(){wb(a)},1E4)}function yb(a){zb||(zb={});zb[a]||(zb[a]=1,n(a))}
var zb,Ab=!1,R=null,Bb=0,Cb=null,Db=0,Eb=0,Fb=0,Gb=0,Hb=[],Ib={},Jb,Kb,Lb,Mb=!1,Nb=!1,Ob=[];
function Pb(){function a(){Nb=document.pointerLockElement===g.canvas||document.mozPointerLockElement===g.canvas||document.webkitPointerLockElement===g.canvas||document.msPointerLockElement===g.canvas}g.preloadPlugins||(g.preloadPlugins=[]);if(!Qb){Qb=!0;try{Rb=!0}catch(c){Rb=!1,n("warning: no blob constructor, cannot create blobs with mimetypes")}Sb="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:Rb?null:n("warning: no BlobBuilder");Tb="undefined"!=
typeof window?window.URL?window.URL:window.webkitURL:void 0;g.od||"undefined"!=typeof Tb||(n("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),g.od=!0);g.preloadPlugins.push({canHandle:function(c){return!g.od&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var k=null;if(Rb)try{k=new Blob([c],{type:Ub(d)}),k.size!==c.length&&(k=new Blob([(new Uint8Array(c)).buffer],{type:Ub(d)}))}catch(u){yb("Blob constructor present but fails: "+
u+"; falling back to blob builder")}k||(k=new Sb,k.append((new Uint8Array(c)).buffer),k=k.getBlob());var p=Tb.createObjectURL(k),r=new Image;r.onload=()=>{r.complete||q("Image "+d+" could not be decoded");var u=document.createElement("canvas");u.width=r.width;u.height=r.height;u.getContext("2d").drawImage(r,0,0);Tb.revokeObjectURL(p);e&&e(c)};r.onerror=()=>{m("Image "+p+" could not be decoded");f&&f()};r.src=p}});g.preloadPlugins.push({canHandle:function(c){return!g.Zd&&c.substr(-4)in{".ogg":1,".wav":1,
".mp3":1}},handle:function(c,d,e,f){function k(){r||(r=!0,e&&e(c))}function p(){r||(r=!0,new Audio,f&&f())}var r=!1;if(Rb){try{var u=new Blob([c],{type:Ub(d)})}catch(J){return p()}u=Tb.createObjectURL(u);var w=new Audio;w.addEventListener("canplaythrough",()=>k(w),!1);w.onerror=function(){if(!r){n("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var J="",Q=0,l=0,v=0;v<c.length;v++)for(Q=Q<<8|c[v],l+=8;6<=l;){var x=Q>>l-6&63;l-=6;J+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[x]}2==
l?(J+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(Q&3)<<4],J+="=="):4==l&&(J+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(Q&15)<<2],J+="=");w.src="data:audio/x-"+d.substr(-3)+";base64,"+J;k(w)}};w.src=u;xb(function(){k(w)})}else return p()}});var b=g.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||
document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),g.elementPointerLock&&b.addEventListener("click",c=>{!Nb&&g.canvas.requestPointerLock&&(g.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Vb(a,b,c,d){if(b&&g.Rc&&a==g.canvas)return g.Rc;var e;if(b){var f={antialias:!1,alpha:!1,Fd:1};if(d)for(var k in d)f[k]=d[k];if("undefined"!=typeof ib&&(e=eb(a,f)))var p=$a[e].cd}else p=a.getContext("2d");if(!p)return null;c&&(b||"undefined"==typeof N||q("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),g.Rc=p,b&&(hb=$a[e],g.Rc=N=hb&&hb.cd),g.be=b,Ob.forEach(function(r){r()}),Pb());return p}var Wb=!1,Xb=void 0,Yb=void 0;
function Zb(a,b){function c(){Mb=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=$b,Xb&&d.requestPointerLock(),Mb=!0,Yb?("undefined"!=typeof SDL&&(C[SDL.screen>>2]=D[SDL.screen>>2]|8388608),ac(g.canvas),bc()):ac(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),Yb?("undefined"!=typeof SDL&&(C[SDL.screen>>2]=D[SDL.screen>>2]&
-8388609),ac(g.canvas),bc()):ac(d));if(g.onFullScreen)g.onFullScreen(Mb);if(g.onFullscreen)g.onFullscreen(Mb)}Xb=a;Yb=b;"undefined"==typeof Xb&&(Xb=!0);"undefined"==typeof Yb&&(Yb=!1);var d=g.canvas;Wb||(Wb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}
function $b(){if(!Mb)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var cc=0;function dc(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===cc)cc=b+1E3/60;else for(;b+2>=cc;)cc+=1E3/60;setTimeout(a,Math.max(cc-b,0))}}
function Ub(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var ec=0,fc=0,gc=0,hc=0;
function ic(a){if(Nb)"mousemove"!=a.type&&"mozMovementX"in a?gc=hc=0:(gc=a.movementX||a.mozMovementX||a.webkitMovementX||0,hc=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(ec=SDL.Wd+gc,fc=SDL.Xd+hc):(ec+=gc,fc+=hc);else{var b=g.canvas.getBoundingClientRect(),c=g.canvas.width,d=g.canvas.height,e="undefined"!=typeof window.scrollX?window.scrollX:window.pageXOffset,f="undefined"!=typeof window.scrollY?window.scrollY:window.pageYOffset;"touchstart"!==a.type&&"touchend"!==
a.type&&"touchmove"!==a.type&&(e=a.pageX-(e+b.left),a=a.pageY-(f+b.top),e*=c/b.width,a*=d/b.height,gc=e-ec,hc=a-fc,ec=e,fc=a)}}var jc=[];function bc(){var a=g.canvas;jc.forEach(function(b){b(a.width,a.height)})}function kc(a,b,c){ac(g.canvas,a,b);c||bc()}
function ac(a,b,c){b&&c?(a.Ld=b,a.Dd=c):(b=a.Ld,c=a.Dd);var d=b,e=c;g.forcedAspectRatio&&0<g.forcedAspectRatio&&(d/e<g.forcedAspectRatio?d=Math.round(e*g.forcedAspectRatio):e=Math.round(d/g.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}Yb?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var Qb,Rb,Sb,Tb;
function lc(a,b){Eb=a;Fb=b;if(Cb)if(Ab||(Ab=!0),0==a)R=function(){var d=Math.max(0,Kb+b-mc())|0;setTimeout(Lb,d)};else if(1==a)R=function(){dc(Lb)};else if(2==a){if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);postMessage("setimmediate","*")}}R=function(){setImmediate(Lb)}}}var mc;mc=()=>performance.now();
function nc(a){if(!noExitRuntime){if(g.onExit)g.onExit(a);t=!0}da(a,new za(a))}
function oc(a,b,c,d,e){!Cb||q("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");Cb=a;Db=d;var f=Bb;Ab=!1;Lb=function(){if(!t)if(0<Hb.length){var k=Date.now(),p=Hb.shift();p.Ud(p.Od);if(Jb){var r=Jb,u=0==r%1?r-1:Math.floor(r);Jb=p.Sd?u:(8*r+(u+.5))/9}m('main loop blocker "'+p.name+'" took '+(Date.now()-k)+" ms");g.setStatus&&(k=g.statusMessage||"Please wait...",
p=Jb,r=Ib.Td,p?p<r?g.setStatus(k+" ("+(r-p)+"/"+r+")"):g.setStatus(k):g.setStatus(""));f<Bb||setTimeout(Lb,0)}else f<Bb||(Gb=Gb+1|0,1==Eb&&1<Fb&&0!=Gb%Fb?R():(0==Eb&&(Kb=mc()),t||g.preMainLoop&&!1===g.preMainLoop()||(wb(a),g.postMainLoop&&g.postMainLoop()),f<Bb||("object"==typeof SDL&&SDL.audio&&SDL.audio.Gd&&SDL.audio.Gd(),R())))};e||(b&&0<b?lc(0,1E3/b):lc(1,1),R());if(c)throw"unwind";}var pc=[];function S(a){var b=pc[a];b||(a>=pc.length&&(pc.length=a+1),pc[a]=b=ma.get(a));return b}
function qc(a,b,c,d){Oa||(Oa=Fa(36));a=Qa(a);Ma({target:a,Uc:"resize",yd:d,Cd:function(e){e=e||event;if(e.target==a){var f=document.body;if(f){var k=Oa;C[k>>2]=e.detail;C[k+4>>2]=f.clientWidth;C[k+8>>2]=f.clientHeight;C[k+12>>2]=innerWidth;C[k+16>>2]=innerHeight;C[k+20>>2]=outerWidth;C[k+24>>2]=outerHeight;C[k+28>>2]=pageXOffset;C[k+32>>2]=pageYOffset;S(d)(10,k,b)&&e.preventDefault()}}},wd:c})}var rc=[null,[],[]];
function sc(a,b,c,d){this.id=a;this.y=this.x=0;this.ed=!1;this.td=this.sd=0;this.width=b;this.height=c;this.rd=b;this.qd=c;this.title=d;this.attributes=T;this.nd={208897:212993,208898:0,208899:0};this.buttons=0;this.keys=[];this.dd=[];this.jd=this.Vc=this.ld=this.pd=this.Tc=this.kd=this.Zc=this.md=this.xd=this.bd=this.title=null}function U(a){return 0>=a||!V?null:V[a-1]}
var W=null,V=null,tc=null,uc=null,T=null,vc={131073:0,131074:0,131075:1,131076:1,131077:1,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0};
function wc(a){switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;
case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 96;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;
case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;
case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;
case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 93:return 348;default:return-1}}function xc(){var a=W,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);a.keys[343]&&(b|=8);return b}function zc(a){W&&W.jd&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||S(W.jd)(W.id,a))}function Ac(a,b){if(W){var c=wc(a);if(-1!=c){var d=b&&W.keys[c];W.keys[c]=b;W.dd[a]=b;W.Vc&&(d&&(b=2),S(W.Vc)(W.id,c,a,b,xc()))}}}
function Bc(){Cc()}function Dc(){Cc()}function Ec(a){Ac(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()}function Fc(a){Ac(a.keyCode,0)}function Gc(){if(W)for(var a=0;a<W.dd.length;++a)W.dd[a]&&Ac(a,0)}function Hc(a){W&&(ic(a),a.target==g.canvas&&W.kd&&S(W.kd)(W.id,ec,fc))}function Ic(a){W&&a.target==g.canvas&&W.Tc&&S(W.Tc)(W.id,1)}function Jc(a){W&&a.target==g.canvas&&W.Tc&&S(W.Tc)(W.id,0)}
function Kc(a,b){if(W&&(ic(a),a.target==g.canvas)){var c=a.button;0<c&&(c=1==c?2:1);if(1==b){W.buttons|=1<<c;try{a.target.setCapture()}catch(d){}}else W.buttons&=~(1<<c);W.Zc&&S(W.Zc)(W.id,c,b,xc())}}function Lc(a){W&&Kc(a,1)}function Mc(a){W&&Kc(a,0)}
function Nc(a){switch(a.type){case "DOMMouseScroll":var b=a.detail/3;break;case "mousewheel":b=a.wheelDelta/120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=100;break;case 1:b/=3;break;case 2:b*=80;break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}b=-b;b=0==b?0:0<b?Math.max(b,1):Math.min(b,-1);if(W&&W.pd&&a.target==g.canvas){var c=b;b="mousewheel"==a.type?a.wheelDeltaX:a.deltaX;S(W.pd)(W.id,b,c);a.preventDefault()}}
var X={},Oc=[],Pc=null;
function Cc(){if(Gb!==Pc||!Gb){Oc=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads:[];Pc=Gb;for(var a=0;a<Oc.length;++a){var b=Oc[a];if(b){X[a]||(m("glfw joystick connected:",a),X[a]={id:Ea(b.id),Rd:b.buttons.length,Qd:b.axes.length,buttons:Fa(b.buttons.length),axes:Fa(4*b.axes.length)});for(var c=X[a],d=0;d<b.buttons.length;++d)B[c.buttons+d>>0]=b.buttons[d].pressed;for(d=0;d<b.axes.length;++d)E[c.axes+4*d>>2]=b.axes[d]}else X[a]&&(m("glfw joystick disconnected",
a),Qc(X[a].id),Qc(X[a].buttons),Qc(X[a].axes),delete X[a])}}}function Rc(a){if(W&&W.ld&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length)return a.preventDefault(),!1}function Sc(a){if(W&&W.ld)return a.preventDefault(),!1}function Tc(a){!Nb&&g.canvas.requestPointerLock&&(g.canvas.requestPointerLock(),a.preventDefault())}var Uc=[31,29,31,30,31,30,31,31,30,31,30,31],Vc=[31,28,31,30,31,30,31,31,30,31,30,31];function Wc(a){var b=Array(ja(a)+1);A(a,b,0,b.length);return b}
for(var N,Z=0;32>Z;++Z)jb.push(Array(Z));var Xc=new Float32Array(288);for(Z=0;288>Z;++Z)P[Z]=Xc.subarray(0,Z+1);var Yc=new Int32Array(288);for(Z=0;288>Z;++Z)ub[Z]=Yc.subarray(0,Z+1);g.requestFullscreen=function(a,b){Zb(a,b)};g.requestAnimationFrame=function(a){dc(a)};g.setCanvasSize=function(a,b,c){kc(a,b,c)};g.pauseMainLoop=function(){R=null;Bb++};g.resumeMainLoop=function(){Bb++;var a=Eb,b=Fb,c=Cb;Cb=null;oc(c,0,!1,Db,!0);lc(a,b);R()};
g.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};g.createContext=function(a,b,c,d){return Vb(a,b,c,d)};
var Zc={Na:function(a,b){a=new Date(1E3*(D[a>>2]+4294967296*C[a+4>>2]));C[b>>2]=a.getSeconds();C[b+4>>2]=a.getMinutes();C[b+8>>2]=a.getHours();C[b+12>>2]=a.getDate();C[b+16>>2]=a.getMonth();C[b+20>>2]=a.getFullYear()-1900;C[b+24>>2]=a.getDay();C[b+28>>2]=(Ba(a.getFullYear())?Ca:Da)[a.getMonth()]+a.getDate()-1|0;C[b+36>>2]=-(60*a.getTimezoneOffset());var c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset(),d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();C[b+32>>2]=(c!=d&&a.getTimezoneOffset()==
Math.min(d,c))|0},Pa:function(a,b,c){function d(r){return(r=r.toTimeString().match(/\(([A-Za-z ]+)\)$/))?r[1]:"GMT"}var e=(new Date).getFullYear(),f=new Date(e,0,1),k=new Date(e,6,1);e=f.getTimezoneOffset();var p=k.getTimezoneOffset();D[a>>2]=60*Math.max(e,p);C[b>>2]=Number(e!=p);a=d(f);b=d(k);a=Ea(a);b=Ea(b);p<e?(D[c>>2]=a,D[c+4>>2]=b):(D[c>>2]=b,D[c+4>>2]=a)},Ma:function(){return Date.now()},r:function(a,b,c){a=Qa(a);if(!a)return-4;a=0>Pa.indexOf(a)?a.getBoundingClientRect():{left:0,top:0};la[b>>
3]=a.width;la[c>>3]=a.height;return 0},ka:function(a){N.activeTexture(a)},ja:function(a,b){N.attachShader(I[a],K[b])},Aa:function(a,b){N.Nc.beginQueryEXT(a,L[b])},ia:function(a,b,c){N.bindAttribLocation(I[a],b,y(c))},ha:function(a,b){N.bindBuffer(a,Va[b])},ga:function(a,b){N.bindFramebuffer(a,Wa[b])},fa:function(a,b){N.bindRenderbuffer(a,Xa[b])},ea:function(a,b){N.bindTexture(a,Ya[b])},sa:function(a){N.bindVertexArray(Za[a])},da:function(a,b,c,d){N.blendColor(a,b,c,d)},ca:function(a){N.blendEquation(a)},
ba:function(a,b){N.blendEquationSeparate(a,b)},aa:function(a,b){N.blendFunc(a,b)},$:function(a,b,c,d){N.blendFuncSeparate(a,b,c,d)},_:function(a,b,c,d){N.bufferData(a,c?z.subarray(c,c+b):b,d)},Z:function(a,b,c,d){N.bufferSubData(a,b,z.subarray(d,d+c))},X:function(a){return N.checkFramebufferStatus(a)},W:function(a){N.clear(a)},V:function(a,b,c,d){N.clearColor(a,b,c,d)},U:function(a){N.clearDepth(a)},T:function(a){N.clearStencil(a)},S:function(a,b,c,d){N.colorMask(!!a,!!b,!!c,!!d)},R:function(a){N.compileShader(K[a])},
Q:function(a,b,c,d,e,f,k,p){N.compressedTexImage2D(a,b,c,d,e,f,p?z.subarray(p,p+k):null)},P:function(a,b,c,d,e,f,k,p,r){N.compressedTexSubImage2D(a,b,c,d,e,f,k,r?z.subarray(r,r+p):null)},O:function(a,b,c,d,e,f,k,p){N.copyTexImage2D(a,b,c,d,e,f,k,p)},M:function(a,b,c,d,e,f,k,p){N.copyTexSubImage2D(a,b,c,d,e,f,k,p)},L:function(){var a=db(I),b=N.createProgram();b.name=a;b.Yc=b.Wc=b.Xc=0;b.gd=1;I[a]=b;return a},K:function(a){var b=db(K);K[b]=N.createShader(a);return b},J:function(a){N.cullFace(a)},I:function(a,
b){for(var c=0;c<a;c++){var d=C[b+4*c>>2],e=Va[d];e&&(N.deleteBuffer(e),e.name=0,Va[d]=null)}},H:function(a,b){for(var c=0;c<a;++c){var d=C[b+4*c>>2],e=Wa[d];e&&(N.deleteFramebuffer(e),e.name=0,Wa[d]=null)}},G:function(a){if(a){var b=I[a];b?(N.deleteProgram(b),b.name=0,I[a]=null):M(1281)}},Da:function(a,b){for(var c=0;c<a;c++){var d=C[b+4*c>>2],e=L[d];e&&(N.Nc.deleteQueryEXT(e),L[d]=null)}},F:function(a,b){for(var c=0;c<a;c++){var d=C[b+4*c>>2],e=Xa[d];e&&(N.deleteRenderbuffer(e),e.name=0,Xa[d]=null)}},
E:function(a){if(a){var b=K[a];b?(N.deleteShader(b),K[a]=null):M(1281)}},D:function(a,b){for(var c=0;c<a;c++){var d=C[b+4*c>>2],e=Ya[d];e&&(N.deleteTexture(e),e.name=0,Ya[d]=null)}},ra:function(a,b){for(var c=0;c<a;c++){var d=C[b+4*c>>2];N.deleteVertexArray(Za[d]);Za[d]=null}},B:function(a){N.depthFunc(a)},A:function(a){N.depthMask(!!a)},z:function(a,b){N.depthRange(a,b)},y:function(a,b){N.detachShader(I[a],K[b])},x:function(a){N.disable(a)},w:function(a){N.disableVertexAttribArray(a)},v:function(a,
b,c){N.drawArrays(a,b,c)},na:function(a,b,c,d){N.drawArraysInstanced(a,b,c,d)},oa:function(a,b){for(var c=jb[a],d=0;d<a;d++)c[d]=C[b+4*d>>2];N.drawBuffers(c)},u:function(a,b,c,d){N.drawElements(a,b,c,d)},ma:function(a,b,c,d,e){N.drawElementsInstanced(a,b,c,d,e)},t:function(a){N.enable(a)},s:function(a){N.enableVertexAttribArray(a)},za:function(a){N.Nc.endQueryEXT(a)},q:function(){N.finish()},p:function(){N.flush()},o:function(a,b,c,d){N.framebufferRenderbuffer(a,b,c,Xa[d])},n:function(a,b,c,d,e){N.framebufferTexture2D(a,
b,c,Ya[d],e)},m:function(a){N.frontFace(a)},l:function(a,b){kb(a,b,"createBuffer",Va)},j:function(a,b){kb(a,b,"createFramebuffer",Wa)},Ea:function(a,b){for(var c=0;c<a;c++){var d=N.Nc.createQueryEXT();if(!d){for(M(1282);c<a;)C[b+4*c++>>2]=0;break}var e=db(L);d.name=e;L[e]=d;C[b+4*c>>2]=e}},i:function(a,b){kb(a,b,"createRenderbuffer",Xa)},h:function(a,b){kb(a,b,"createTexture",Ya)},qa:function(a,b){kb(a,b,"createVertexArray",Za)},k:function(a){N.generateMipmap(a)},Ec:function(a,b,c,d,e,f,k){lb("getActiveAttrib",
a,b,c,d,e,f,k)},Dc:function(a,b,c,d,e,f,k){lb("getActiveUniform",a,b,c,d,e,f,k)},Cc:function(a,b,c,d){a=N.getAttachedShaders(I[a]);var e=a.length;e>b&&(e=b);C[c>>2]=e;for(b=0;b<e;++b)C[d+4*b>>2]=K.indexOf(a[b])},Bc:function(a,b){return N.getAttribLocation(I[a],y(b))},Ac:function(a,b){nb(a,b,4)},zc:function(a,b,c){c?C[c>>2]=N.getBufferParameter(a,b):M(1281)},yc:function(){var a=N.getError()||cb;cb=0;return a},xc:function(a,b){nb(a,b,2)},wc:function(a,b,c,d){a=N.getFramebufferAttachmentParameter(a,
b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;C[d>>2]=a},vc:function(a,b){nb(a,b,0)},sc:function(a,b,c,d){a=N.getProgramInfoLog(I[a]);null===a&&(a="(unknown error)");b=0<b&&d?A(a,z,d,b):0;c&&(C[c>>2]=b)},tc:function(a,b,c){if(c)if(a>=Ua)M(1281);else if(a=I[a],35716==b)a=N.getProgramInfoLog(a),null===a&&(a="(unknown error)"),C[c>>2]=a.length+1;else if(35719==b){if(!a.Yc)for(b=0;b<N.getProgramParameter(a,35718);++b)a.Yc=Math.max(a.Yc,N.getActiveUniform(a,b).name.length+
1);C[c>>2]=a.Yc}else if(35722==b){if(!a.Wc)for(b=0;b<N.getProgramParameter(a,35721);++b)a.Wc=Math.max(a.Wc,N.getActiveAttrib(a,b).name.length+1);C[c>>2]=a.Wc}else if(35381==b){if(!a.Xc)for(b=0;b<N.getProgramParameter(a,35382);++b)a.Xc=Math.max(a.Xc,N.getActiveUniformBlockName(a,b).length+1);C[c>>2]=a.Xc}else C[c>>2]=N.getProgramParameter(a,b);else M(1281)},ua:function(a,b,c){if(c){a=N.Nc.getQueryObjectEXT(L[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;mb(c,d)}else M(1281)},wa:function(a,b,c){if(c){a=
N.Nc.getQueryObjectEXT(L[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;C[c>>2]=d}else M(1281)},ta:function(a,b,c){if(c){a=N.Nc.getQueryObjectEXT(L[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;mb(c,d)}else M(1281)},va:function(a,b,c){if(c){a=N.Nc.getQueryObjectEXT(L[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;C[c>>2]=d}else M(1281)},xa:function(a,b,c){c?C[c>>2]=N.Nc.getQueryEXT(a,b):M(1281)},rc:function(a,b,c){c?C[c>>2]=N.getRenderbufferParameter(a,b):M(1281)},pc:function(a,b,c,d){a=N.getShaderInfoLog(K[a]);
null===a&&(a="(unknown error)");b=0<b&&d?A(a,z,d,b):0;c&&(C[c>>2]=b)},oc:function(a,b,c,d){a=N.getShaderPrecisionFormat(a,b);C[c>>2]=a.rangeMin;C[c+4>>2]=a.rangeMax;C[d>>2]=a.precision},nc:function(a,b,c,d){if(a=N.getShaderSource(K[a]))b=0<b&&d?A(a,z,d,b):0,c&&(C[c>>2]=b)},qc:function(a,b,c){c?35716==b?(a=N.getShaderInfoLog(K[a]),null===a&&(a="(unknown error)"),C[c>>2]=a?a.length+1:0):35720==b?(a=N.getShaderSource(K[a]),C[c>>2]=a?a.length+1:0):C[c>>2]=N.getShaderParameter(K[a],b):M(1281)},mc:function(a){var b=
ab[a];if(!b){switch(a){case 7939:b=N.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=ob(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=N.getParameter(a))||M(1280);b=b&&ob(b);break;case 7938:b=ob("OpenGL ES 2.0 ("+N.getParameter(7938)+")");break;case 35724:b=N.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=ob(b);break;default:M(1280)}ab[a]=
b}return b},lc:function(a,b,c){c?E[c>>2]=N.getTexParameter(a,b):M(1281)},kc:function(a,b,c){c?C[c>>2]=N.getTexParameter(a,b):M(1281)},gc:function(a,b){b=y(b);if(a=I[a]){qb(a);var c=a.Sc,d=0,e=b,f=pb(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.vd[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||N.getUniformLocation(a,b)))return d}else M(1281);return-1},ic:function(a,b,c){rb(a,b,c,2)},hc:function(a,b,c){rb(a,b,c,0)},dc:function(a,b,c){c?C[c>>2]=N.getVertexAttribOffset(a,b):M(1281)},fc:function(a,
b,c){sb(a,b,c,2)},ec:function(a,b,c){sb(a,b,c,5)},cc:function(a,b){N.hint(a,b)},bc:function(a){return(a=Va[a])?N.isBuffer(a):0},ac:function(a){return N.isEnabled(a)},$b:function(a){return(a=Wa[a])?N.isFramebuffer(a):0},Zb:function(a){return(a=I[a])?N.isProgram(a):0},Ca:function(a){return(a=L[a])?N.Nc.isQueryEXT(a):0},Yb:function(a){return(a=Xa[a])?N.isRenderbuffer(a):0},Xb:function(a){return(a=K[a])?N.isShader(a):0},Wb:function(a){return(a=Ya[a])?N.isTexture(a):0},pa:function(a){return(a=Za[a])?N.isVertexArray(a):
0},Vb:function(a){N.lineWidth(a)},Ub:function(a){a=I[a];N.linkProgram(a);a.Sc=0;a.vd={}},Tb:function(a,b){3317==a&&(bb=b);N.pixelStorei(a,b)},Sb:function(a,b){N.polygonOffset(a,b)},ya:function(a,b){N.Nc.queryCounterEXT(L[a],b)},Rb:function(a,b,c,d,e,f,k){(k=tb(f,e,c,d,k))?N.readPixels(a,b,c,d,e,f,k):M(1280)},Qb:function(){},Ob:function(a,b,c,d){N.renderbufferStorage(a,b,c,d)},Nb:function(a,b){N.sampleCoverage(a,!!b)},Mb:function(a,b,c,d){N.scissor(a,b,c,d)},Lb:function(){M(1280)},Kb:function(a,b,
c,d){for(var e="",f=0;f<b;++f){var k=d?C[d+4*f>>2]:-1;e+=y(C[c+4*f>>2],0>k?void 0:k)}N.shaderSource(K[a],e)},Jb:function(a,b,c){N.stencilFunc(a,b,c)},Ib:function(a,b,c,d){N.stencilFuncSeparate(a,b,c,d)},Hb:function(a){N.stencilMask(a)},Gb:function(a,b){N.stencilMaskSeparate(a,b)},Fb:function(a,b,c){N.stencilOp(a,b,c)},Db:function(a,b,c,d){N.stencilOpSeparate(a,b,c,d)},Cb:function(a,b,c,d,e,f,k,p,r){N.texImage2D(a,b,c,d,e,f,k,p,r?tb(p,k,d,e,r):null)},Bb:function(a,b,c){N.texParameterf(a,b,c)},Ab:function(a,
b,c){N.texParameterf(a,b,E[c>>2])},zb:function(a,b,c){N.texParameteri(a,b,c)},yb:function(a,b,c){N.texParameteri(a,b,C[c>>2])},xb:function(a,b,c,d,e,f,k,p,r){var u=null;r&&(u=tb(p,k,e,f,r));N.texSubImage2D(a,b,c,d,e,f,k,p,u)},wb:function(a,b){N.uniform1f(O(a),b)},vb:function(a,b,c){if(288>=b)for(var d=P[b-1],e=0;e<b;++e)d[e]=E[c+4*e>>2];else d=E.subarray(c>>2,c+4*b>>2);N.uniform1fv(O(a),d)},ub:function(a,b){N.uniform1i(O(a),b)},sb:function(a,b,c){if(288>=b)for(var d=ub[b-1],e=0;e<b;++e)d[e]=C[c+4*
e>>2];else d=C.subarray(c>>2,c+4*b>>2);N.uniform1iv(O(a),d)},rb:function(a,b,c){N.uniform2f(O(a),b,c)},qb:function(a,b,c){if(144>=b)for(var d=P[2*b-1],e=0;e<2*b;e+=2)d[e]=E[c+4*e>>2],d[e+1]=E[c+(4*e+4)>>2];else d=E.subarray(c>>2,c+8*b>>2);N.uniform2fv(O(a),d)},pb:function(a,b,c){N.uniform2i(O(a),b,c)},ob:function(a,b,c){if(144>=b)for(var d=ub[2*b-1],e=0;e<2*b;e+=2)d[e]=C[c+4*e>>2],d[e+1]=C[c+(4*e+4)>>2];else d=C.subarray(c>>2,c+8*b>>2);N.uniform2iv(O(a),d)},nb:function(a,b,c,d){N.uniform3f(O(a),b,
c,d)},mb:function(a,b,c){if(96>=b)for(var d=P[3*b-1],e=0;e<3*b;e+=3)d[e]=E[c+4*e>>2],d[e+1]=E[c+(4*e+4)>>2],d[e+2]=E[c+(4*e+8)>>2];else d=E.subarray(c>>2,c+12*b>>2);N.uniform3fv(O(a),d)},lb:function(a,b,c,d){N.uniform3i(O(a),b,c,d)},kb:function(a,b,c){if(96>=b)for(var d=ub[3*b-1],e=0;e<3*b;e+=3)d[e]=C[c+4*e>>2],d[e+1]=C[c+(4*e+4)>>2],d[e+2]=C[c+(4*e+8)>>2];else d=C.subarray(c>>2,c+12*b>>2);N.uniform3iv(O(a),d)},jb:function(a,b,c,d,e){N.uniform4f(O(a),b,c,d,e)},hb:function(a,b,c){if(72>=b){var d=P[4*
b-1],e=E;c>>=2;for(var f=0;f<4*b;f+=4){var k=c+f;d[f]=e[k];d[f+1]=e[k+1];d[f+2]=e[k+2];d[f+3]=e[k+3]}}else d=E.subarray(c>>2,c+16*b>>2);N.uniform4fv(O(a),d)},gb:function(a,b,c,d,e){N.uniform4i(O(a),b,c,d,e)},fb:function(a,b,c){if(72>=b)for(var d=ub[4*b-1],e=0;e<4*b;e+=4)d[e]=C[c+4*e>>2],d[e+1]=C[c+(4*e+4)>>2],d[e+2]=C[c+(4*e+8)>>2],d[e+3]=C[c+(4*e+12)>>2];else d=C.subarray(c>>2,c+16*b>>2);N.uniform4iv(O(a),d)},eb:function(a,b,c,d){if(72>=b)for(var e=P[4*b-1],f=0;f<4*b;f+=4)e[f]=E[d+4*f>>2],e[f+1]=
E[d+(4*f+4)>>2],e[f+2]=E[d+(4*f+8)>>2],e[f+3]=E[d+(4*f+12)>>2];else e=E.subarray(d>>2,d+16*b>>2);N.uniformMatrix2fv(O(a),!!c,e)},db:function(a,b,c,d){if(32>=b)for(var e=P[9*b-1],f=0;f<9*b;f+=9)e[f]=E[d+4*f>>2],e[f+1]=E[d+(4*f+4)>>2],e[f+2]=E[d+(4*f+8)>>2],e[f+3]=E[d+(4*f+12)>>2],e[f+4]=E[d+(4*f+16)>>2],e[f+5]=E[d+(4*f+20)>>2],e[f+6]=E[d+(4*f+24)>>2],e[f+7]=E[d+(4*f+28)>>2],e[f+8]=E[d+(4*f+32)>>2];else e=E.subarray(d>>2,d+36*b>>2);N.uniformMatrix3fv(O(a),!!c,e)},cb:function(a,b,c,d){if(18>=b){var e=
P[16*b-1],f=E;d>>=2;for(var k=0;k<16*b;k+=16){var p=d+k;e[k]=f[p];e[k+1]=f[p+1];e[k+2]=f[p+2];e[k+3]=f[p+3];e[k+4]=f[p+4];e[k+5]=f[p+5];e[k+6]=f[p+6];e[k+7]=f[p+7];e[k+8]=f[p+8];e[k+9]=f[p+9];e[k+10]=f[p+10];e[k+11]=f[p+11];e[k+12]=f[p+12];e[k+13]=f[p+13];e[k+14]=f[p+14];e[k+15]=f[p+15]}}else e=E.subarray(d>>2,d+64*b>>2);N.uniformMatrix4fv(O(a),!!c,e)},bb:function(a){a=I[a];N.useProgram(a);N.zd=a},ab:function(a){N.validateProgram(I[a])},$a:function(a,b){N.vertexAttrib1f(a,b)},_a:function(a,b){N.vertexAttrib1f(a,
E[b>>2])},Ya:function(a,b,c){N.vertexAttrib2f(a,b,c)},Xa:function(a,b){N.vertexAttrib2f(a,E[b>>2],E[b+4>>2])},Wa:function(a,b,c,d){N.vertexAttrib3f(a,b,c,d)},Va:function(a,b){N.vertexAttrib3f(a,E[b>>2],E[b+4>>2],E[b+8>>2])},Ua:function(a,b,c,d,e){N.vertexAttrib4f(a,b,c,d,e)},Ta:function(a,b){N.vertexAttrib4f(a,E[b>>2],E[b+4>>2],E[b+8>>2],E[b+12>>2])},la:function(a,b){N.vertexAttribDivisor(a,b)},Sa:function(a,b,c,d,e,f){N.vertexAttribPointer(a,b,c,!!d,e,f)},Ra:function(a,b,c,d){N.viewport(a,b,c,d)},
Qa:function(a,b,c){z.copyWithin(a,b,b+c)},La:function(){q("OOM")},Fa:function(a){eval(y(a))},Y:function(a,b,c){a=Qa(a);if(!a)return-4;a.width=b;a.height=c;return 0},Ha:function(a,b,c){a=S(a);oc(a,b,c)},Ia:function(a,b,c,d){qc(a,b,c,d);return 0},b:nc,g:function(a,b,c,d){for(var e=0,f=0;f<c;f++){var k=D[b>>2],p=D[b+4>>2];b+=8;for(var r=0;r<p;r++){var u=z[k+r],w=rc[a];0===u||10===u?((1===a?m:n)(ia(w,0)),w.length=0):w.push(u)}e+=p}D[d>>2]=e;return 0},uc:function(a,b,c,d){var e;for(e=0;e<V.length&&null!==
V[e];e++);if(0<e)throw"glfwCreateWindow only supports one window at time currently";var f=e+1;if(0>=a||0>=b)f=0;else{d?Zb():kc(a,b);for(e=0;e<V.length&&null==V[e];e++);d=0<T[139265];e==V.length&&(d?g.Rc=Vb(g.canvas,!0,!0,{antialias:1<T[135181],depth:0<T[135173],stencil:0<T[135174],alpha:0<T[135172]}):Pb());!g.Rc&&d?f=0:(a=new sc(f,a,b,c),f-1==V.length?V.push(a):V[f-1]=a,W=a,f=a.id)}return f},Ga:function(a){a:{if(a=U(a)){a.xd&&S(a.xd)(a.id);V[a.id-1]=null;W.id==a.id&&(W=null);for(a=0;a<V.length;a++)if(null!==
V[a]){a=void 0;break a}g.Rc=void 0}a=void 0}return a},Ka:function(a,b,c){la[b>>3]=ec;la[c>>3]=fc},jc:function(){return 1},a:function(){return mc()/1E3-uc},N:function(){tc||(tc=Ea("3.2.1 JS WebGL Emscripten"));return tc},_b:function(){return 0},C:function(){if(V)return 1;uc=mc()/1E3;T=vc;V=[];W=null;window.addEventListener("gamepadconnected",Bc,!0);window.addEventListener("gamepaddisconnected",Dc,!0);window.addEventListener("keydown",Ec,!0);window.addEventListener("keypress",zc,!0);window.addEventListener("keyup",
Fc,!0);window.addEventListener("blur",Gc,!0);g.canvas.addEventListener("touchmove",Hc,!0);g.canvas.addEventListener("touchstart",Lc,!0);g.canvas.addEventListener("touchcancel",Mc,!0);g.canvas.addEventListener("touchend",Mc,!0);g.canvas.addEventListener("mousemove",Hc,!0);g.canvas.addEventListener("mousedown",Lc,!0);g.canvas.addEventListener("mouseup",Mc,!0);g.canvas.addEventListener("wheel",Nc,!0);g.canvas.addEventListener("mousewheel",Nc,!0);g.canvas.addEventListener("mouseenter",Ic,!0);g.canvas.addEventListener("mouseleave",
Jc,!0);g.canvas.addEventListener("drop",Rc,!0);g.canvas.addEventListener("dragover",Sc,!0);jc.push((a,b)=>{if(W){var c=!0;document.fullscreen||document.fullScreen||document.mozFullScreen||document.webkitIsFullScreen?(W.sd=W.x,W.td=W.y,W.rd=W.width,W.qd=W.height,W.x=W.y=0,W.width=screen.width,W.height=screen.height,W.ed=!0):1==W.ed?(W.x=W.sd,W.y=W.td,W.width=W.rd,W.height=W.qd,W.ed=!1):W.width!=a||W.height!=b?(W.width=a,W.height=b):c=!1;c&&(kc(W.width,W.height,!0),W&&W.bd&&S(W.bd)(W.id,W.width,W.height),
W&&W.md&&S(W.md)(W.id,W.width,W.height))}});return 1},Za:function(){},d:function(a,b,c){if(a=U(a))switch(b){case 208897:switch(c){case 212993:a.nd[b]=c;g.canvas.removeEventListener("click",Tc,!0);g.canvas.exitPointerLock();break;case 212994:m("glfwSetInputMode called with GLFW_CURSOR_HIDDEN value not implemented.");break;case 212995:a.nd[b]=c;g.canvas.addEventListener("click",Tc,!0);g.canvas.requestPointerLock();break;default:m("glfwSetInputMode called with unknown value parameter value: "+c+".")}break;
case 208898:m("glfwSetInputMode called with GLFW_STICKY_KEYS mode not implemented.");break;case 208899:m("glfwSetInputMode called with GLFW_STICKY_MOUSE_BUTTONS mode not implemented.");break;default:m("glfwSetInputMode called with unknown mode parameter value: "+b+".")}},tb:function(a,b){if(a=U(a)){var c=a.Vc;a.Vc=b;b=c}else b=null;return b},ib:function(a,b){if(a=U(a)){var c=a.Zc;a.Zc=b;b=c}else b=null;return b},Ja:function(){},Pb:function(a,b,c){if(a=U(a))a.x=b,a.y=c},Eb:function(a,b){if(a=U(a)){var c=
a.bd;a.bd=b;b=c}else b=null;return b},e:function(a,b){if(a=U(a))a.title=y(b),W.id==a.id&&(document.title=a.title)},Ba:function(){},Oa:function(a){a=Math.abs(a);0==a?lc(0,0):lc(1,a)},f:function(){window.removeEventListener("gamepadconnected",Bc,!0);window.removeEventListener("gamepaddisconnected",Dc,!0);window.removeEventListener("keydown",Ec,!0);window.removeEventListener("keypress",zc,!0);window.removeEventListener("keyup",Fc,!0);window.removeEventListener("blur",Gc,!0);g.canvas.removeEventListener("touchmove",
Hc,!0);g.canvas.removeEventListener("touchstart",Lc,!0);g.canvas.removeEventListener("touchcancel",Mc,!0);g.canvas.removeEventListener("touchend",Mc,!0);g.canvas.removeEventListener("mousemove",Hc,!0);g.canvas.removeEventListener("mousedown",Lc,!0);g.canvas.removeEventListener("mouseup",Mc,!0);g.canvas.removeEventListener("wheel",Nc,!0);g.canvas.removeEventListener("mousewheel",Nc,!0);g.canvas.removeEventListener("mouseenter",Ic,!0);g.canvas.removeEventListener("mouseleave",Jc,!0);g.canvas.removeEventListener("drop",
Rc,!0);g.canvas.removeEventListener("dragover",Sc,!0);g.canvas.width=g.canvas.height=1;W=V=null},c:function(a,b){T[a]=b},Fc:function(a,b,c,d){function e(l,v,x){for(l="number"==typeof l?l.toString():l||"";l.length<v;)l=x[0]+l;return l}function f(l,v){return e(l,v,"0")}function k(l,v){function x(yc){return 0>yc?-1:0<yc?1:0}var Y;0===(Y=x(l.getFullYear()-v.getFullYear()))&&0===(Y=x(l.getMonth()-v.getMonth()))&&(Y=x(l.getDate()-v.getDate()));return Y}function p(l){switch(l.getDay()){case 0:return new Date(l.getFullYear()-
1,11,29);case 1:return l;case 2:return new Date(l.getFullYear(),0,3);case 3:return new Date(l.getFullYear(),0,2);case 4:return new Date(l.getFullYear(),0,1);case 5:return new Date(l.getFullYear()-1,11,31);case 6:return new Date(l.getFullYear()-1,11,30)}}function r(l){var v=l.Pc;for(l=new Date((new Date(l.Qc+1900,0,1)).getTime());0<v;){var x=l.getMonth(),Y=(Ba(l.getFullYear())?Uc:Vc)[x];if(v>Y-l.getDate())v-=Y-l.getDate()+1,l.setDate(1),11>x?l.setMonth(x+1):(l.setMonth(0),l.setFullYear(l.getFullYear()+
1));else{l.setDate(l.getDate()+v);break}}x=new Date(l.getFullYear()+1,0,4);v=p(new Date(l.getFullYear(),0,4));x=p(x);return 0>=k(v,l)?0>=k(x,l)?l.getFullYear()+1:l.getFullYear():l.getFullYear()-1}var u=C[d+40>>2];d={Jd:C[d>>2],Id:C[d+4>>2],$c:C[d+8>>2],fd:C[d+12>>2],ad:C[d+16>>2],Qc:C[d+20>>2],Oc:C[d+24>>2],Pc:C[d+28>>2],ae:C[d+32>>2],Hd:C[d+36>>2],Kd:u?y(u):""};c=y(c);u={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y",
"%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var w in u)c=c.replace(new RegExp(w,"g"),u[w]);var J="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),Q="January February March April May June July August September October November December".split(" ");u={"%a":function(l){return J[l.Oc].substring(0,
3)},"%A":function(l){return J[l.Oc]},"%b":function(l){return Q[l.ad].substring(0,3)},"%B":function(l){return Q[l.ad]},"%C":function(l){return f((l.Qc+1900)/100|0,2)},"%d":function(l){return f(l.fd,2)},"%e":function(l){return e(l.fd,2," ")},"%g":function(l){return r(l).toString().substring(2)},"%G":function(l){return r(l)},"%H":function(l){return f(l.$c,2)},"%I":function(l){l=l.$c;0==l?l=12:12<l&&(l-=12);return f(l,2)},"%j":function(l){for(var v=0,x=0;x<=l.ad-1;v+=(Ba(l.Qc+1900)?Uc:Vc)[x++]);return f(l.fd+
v,3)},"%m":function(l){return f(l.ad+1,2)},"%M":function(l){return f(l.Id,2)},"%n":function(){return"\n"},"%p":function(l){return 0<=l.$c&&12>l.$c?"AM":"PM"},"%S":function(l){return f(l.Jd,2)},"%t":function(){return"\t"},"%u":function(l){return l.Oc||7},"%U":function(l){return f(Math.floor((l.Pc+7-l.Oc)/7),2)},"%V":function(l){var v=Math.floor((l.Pc+7-(l.Oc+6)%7)/7);2>=(l.Oc+371-l.Pc-2)%7&&v++;if(v)53==v&&(x=(l.Oc+371-l.Pc)%7,4==x||3==x&&Ba(l.Qc)||(v=1));else{v=52;var x=(l.Oc+7-l.Pc-1)%7;(4==x||5==
x&&Ba(l.Qc%400-1))&&v++}return f(v,2)},"%w":function(l){return l.Oc},"%W":function(l){return f(Math.floor((l.Pc+7-(l.Oc+6)%7)/7),2)},"%y":function(l){return(l.Qc+1900).toString().substring(2)},"%Y":function(l){return l.Qc+1900},"%z":function(l){l=l.Hd;var v=0<=l;l=Math.abs(l)/60;return(v?"+":"-")+String("0000"+(l/60*100+l%60)).slice(-4)},"%Z":function(l){return l.Kd},"%%":function(){return"%"}};c=c.replace(/%%/g,"\x00\x00");for(w in u)c.includes(w)&&(c=c.replace(new RegExp(w,"g"),u[w](d)));c=c.replace(/\0\0/g,
"%");w=Wc(c);if(w.length>b)return 0;B.set(w,a);return w.length-1}};
(function(){function a(e){g.asm=e.exports;fa=g.asm.Gc;e=fa.buffer;g.HEAP8=B=new Int8Array(e);g.HEAP16=new Int16Array(e);g.HEAP32=C=new Int32Array(e);g.HEAPU8=z=new Uint8Array(e);g.HEAPU16=ka=new Uint16Array(e);g.HEAPU32=D=new Uint32Array(e);g.HEAPF32=E=new Float32Array(e);g.HEAPF64=la=new Float64Array(e);ma=g.asm.Lc;oa.unshift(g.asm.Hc);F--;g.monitorRunDependencies&&g.monitorRunDependencies(F);0==F&&(null!==ta&&(clearInterval(ta),ta=null),ua&&(e=ua,ua=null,e()))}function b(e){a(e.instance)}function c(e){return ya().then(function(f){return WebAssembly.instantiate(f,
d)}).then(function(f){return f}).then(e,function(f){n("failed to asynchronously prepare wasm: "+f);q(f)})}var d={a:Zc};F++;g.monitorRunDependencies&&g.monitorRunDependencies(F);if(g.instantiateWasm)try{return g.instantiateWasm(d,a)}catch(e){return n("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return ea||"function"!=typeof WebAssembly.instantiateStreaming||va()||"function"!=typeof fetch?c(b):fetch(G,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,
d).then(b,function(f){n("wasm streaming compile failed: "+f);n("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();g.___wasm_call_ctors=function(){return(g.___wasm_call_ctors=g.asm.Hc).apply(null,arguments)};var Fa=g._malloc=function(){return(Fa=g._malloc=g.asm.Ic).apply(null,arguments)},Qc=g._free=function(){return(Qc=g._free=g.asm.Jc).apply(null,arguments)};g._main=function(){return(g._main=g.asm.Kc).apply(null,arguments)};
var $c=g.stackAlloc=function(){return($c=g.stackAlloc=g.asm.Mc).apply(null,arguments)},ad;ua=function bd(){ad||cd();ad||(ua=bd)};function dd(a){var b=g._main;a=a||[];a.unshift(ca);var c=a.length,d=$c(4*(c+1)),e=d>>2;a.forEach(k=>{var p=C,r=e++,u=ja(k)+1,w=$c(u);A(k,B,w,u);p[r]=w});C[e]=0;try{var f=b(c,d);nc(f,!0)}catch(k){vb(k)}}
function cd(){function a(){if(!ad&&(ad=!0,g.calledRun=!0,!t)){Aa(oa);Aa(pa);if(g.onRuntimeInitialized)g.onRuntimeInitialized();ed&&dd(b);if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();ra.unshift(c)}Aa(ra)}}var b=b||ba;if(!(0<F)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)sa();Aa(na);0<F||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);
a()},1)):a())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var ed=!0;g.noInitialRun&&(ed=!1);cd();
