var h;h||(h=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},h),ba=[],ca="./this.program",da=(a,b)=>{throw b;},ea="",fa;"undefined"!=typeof document&&document.currentScript&&(ea=document.currentScript.src);ea=0!==ea.indexOf("blob:")?ea.substr(0,ea.replace(/[?#].*/,"").lastIndexOf("/")+1):"";fa=a=>{document.title=a};var ha=h.print||console.log.bind(console),k=h.printErr||console.warn.bind(console);Object.assign(h,aa);aa=null;h.arguments&&(ba=h.arguments);
h.thisProgram&&(ca=h.thisProgram);h.quit&&(da=h.quit);var ia;h.wasmBinary&&(ia=h.wasmBinary);var noExitRuntime=h.noExitRuntime||!0;"object"!=typeof WebAssembly&&m("no native wasm support detected");var ja,ka=!1,la="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ma(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&la)return la.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function r(a,b){return a?ma(t,a,b):""}
function na(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var l=a.charCodeAt(++f);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e}function v(a,b,c){return na(a,t,b,c)}
function oa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}var y,t,pa,qa,A,B,C,D,ra,sa=[],ta=[],ua=[],va=[],wa=[];function xa(){var a=h.preRun.shift();sa.unshift(a)}var ya=0,za=null,Aa=null;function m(a){if(h.onAbort)h.onAbort(a);a="Aborted("+a+")";k(a);ka=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function Ba(){return E.startsWith("data:application/octet-stream;base64,")}var E;
E="index.wasm";if(!Ba()){var Ca=E;E=h.locateFile?h.locateFile(Ca,ea):ea+Ca}function Da(){var a=E;try{if(a==E&&ia)return new Uint8Array(ia);throw"both async and sync fetching of the wasm failed";}catch(b){m(b)}}function Ea(){return ia||"function"!=typeof fetch?Promise.resolve().then(function(){return Da()}):fetch(E,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+E+"'";return a.arrayBuffer()}).catch(function(){return Da()})}
var Fa,Ga,Ka={5812832:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,5812979:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,5813213:a=>{"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.ie||("undefined"!==typeof AudioContext?b.ie=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.ie=new webkitAudioContext),
b.ie&&Ha(b.ie));return void 0===b.ie?-1:0},5813706:()=>h.SDL2.ie.sampleRate,5813774:(a,b,c,d)=>{function e(){}function f(l){void 0!==g.capture.Be&&(clearTimeout(g.capture.Be),g.capture.Be=void 0);g.capture.Ee=g.ie.createMediaStreamSource(l);g.capture.ke=g.ie.createScriptProcessor(b,a,1);g.capture.ke.onaudioprocess=function(p){void 0!==g&&void 0!==g.capture&&(p.outputBuffer.getChannelData(0).fill(0),g.capture.Le=p.inputBuffer,Ia(c,[d]))};g.capture.Ee.connect(g.capture.ke);g.capture.ke.connect(g.ie.destination);
g.capture.stream=l}var g=h.SDL2;g.capture.Fe=g.ie.createBuffer(a,b,g.ie.sampleRate);g.capture.Fe.getChannelData(0).fill(0);g.capture.Be=setTimeout(function(){g.capture.Le=g.capture.Fe;Ia(c,[d])},b/g.ie.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},5815426:(a,b,c,d)=>{var e=h.SDL2;e.audio.ke=
e.ie.createScriptProcessor(b,0,a);e.audio.ke.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(e.audio.Re=f.outputBuffer,Ia(c,[d]))};e.audio.ke.connect(e.ie.destination)},5815836:(a,b)=>{for(var c=h.SDL2,d=c.capture.Le.numberOfChannels,e=0;e<d;++e){var f=c.capture.Le.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var g=0;g<b;++g)Ja(a+4*g,f[g]);else for(g=0;g<b;++g)Ja(a+4*(g*d+e),
f[g])}},5816441:(a,b)=>{for(var c=h.SDL2,d=c.audio.Re.numberOfChannels,e=0;e<d;++e){var f=c.audio.Re.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=C[a+(g*d+e<<2)>>2]}},5816921:a=>{var b=h.SDL2;if(a){void 0!==b.capture.Be&&clearTimeout(b.capture.Be);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);
b.capture.stream=void 0}void 0!==b.capture.ke&&(b.capture.ke.onaudioprocess=function(){},b.capture.ke.disconnect(),b.capture.ke=void 0);void 0!==b.capture.Ee&&(b.capture.Ee.disconnect(),b.capture.Ee=void 0);void 0!==b.capture.Fe&&(b.capture.Fe=void 0);b.capture=void 0}else void 0!=b.audio.ke&&(b.audio.ke.disconnect(),b.audio.ke=void 0),b.audio=void 0;void 0!==b.ie&&void 0===b.audio&&void 0===b.capture&&(b.ie.close(),b.ie=void 0)},5818093:(a,b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;d.Ze!==h.canvas&&
(d.pe=h.createContext(h.canvas,!1,!0),d.Ze=h.canvas);if(d.w!==a||d.gf!==b||d.jf!==d.pe)d.image=d.pe.createImageData(a,b),d.w=a,d.gf=b,d.jf=d.pe;a=d.image.data;b=c>>2;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=A[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.af!==a&&(d.$e=new Int32Array(a.buffer),d.bf=new Uint8Array(a.buffer),d.af=a),a=d.$e,c=a.length,a.set(A.subarray(b,b+c)),a=d.bf,b=3,e=b+4*c,0==c%8)for(;b<
e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.pe.putImageData(d.image,0,0)},5819562:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e>>=2;var l=0,p;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(p=b.length;l<p;){var q=A[e];b[l]=q&255;b[l+1]=q>>8&255;b[l+2]=q>>
16&255;b[l+3]=q>>24&255;e++;l+=4}else b=new Int32Array(b.buffer),p=b.length,b.set(A.subarray(e,e+p));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=F(c.length+1);v(c,d,c.length+1);return d},5820551:a=>{h.canvas&&(h.canvas.style.cursor=r(a))},5820634:()=>{h.canvas&&(h.canvas.style.cursor="none")},5820703:()=>window.innerWidth,5820733:()=>window.innerHeight};
function La(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}function Ma(a,b,c){a.addEventListener(b,c,{once:!0})}function Ha(a){var b;b||(b=[document,document.getElementById("canvas")]);["keydown","mousedown","touchstart"].forEach(function(c){b.forEach(function(d){d&&Ma(d,c,()=>{"suspended"===a.state&&a.resume()})})})}function Na(a){for(;0<a.length;)a.shift()(h)}var Oa=[];
function G(a){var b=Oa[a];b||(a>=Oa.length&&(Oa.length=a+1),Oa[a]=b=ra.get(a));return b}function Ia(a,b){if("vi".includes("j")){var c=h.dynCall_vi;b&&b.length?c.apply(null,[a].concat(b)):c.call(null,a)}else G(a).apply(null,b)}
function Ja(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":y[a>>0]=b;break;case "i8":y[a>>0]=b;break;case "i16":pa[a>>1]=b;break;case "i32":A[a>>2]=b;break;case "i64":Ga=[b>>>0,(Fa=b,1<=+Math.abs(Fa)?0<Fa?(Math.min(+Math.floor(Fa/4294967296),4294967295)|0)>>>0:~~+Math.ceil((Fa-+(~~Fa>>>0))/4294967296)>>>0:0)];A[a>>2]=Ga[0];A[a+4>>2]=Ga[1];break;case "float":C[a>>2]=b;break;case "double":D[a>>3]=b;break;case "*":B[a>>2]=b;break;default:m("invalid type for setValue: "+c)}}
function Pa(a){return 0===a%4&&(0!==a%100||0===a%400)}var Qa=[0,31,60,91,121,152,182,213,244,274,305,335],Ra=[0,31,59,90,120,151,181,212,243,273,304,334];function Sa(a){var b=oa(a)+1,c=F(b);c&&na(a,y,c,b);return c}
function Ta(a,b){Ua=a;Va=b;if(Wa)if(Xa||(Xa=!0),0==a)H=function(){var d=Math.max(0,Ya+b-Za())|0;setTimeout($a,d)};else if(1==a)H=function(){bb($a)};else if(2==a){if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);postMessage("setimmediate","*")}}H=function(){setImmediate($a)}}}var Za;Za=()=>performance.now();
function cb(a,b,c,d,e){!Wa||m("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");Wa=a;db=d;var f=eb;Xa=!1;$a=function(){if(!ka)if(0<fb.length){var g=Date.now(),l=fb.shift();l.Af(l.wf);if(gb){var p=gb,q=0==p%1?p-1:Math.floor(p);gb=l.yf?q:(8*p+(q+.5))/9}ha('main loop blocker "'+l.name+'" took '+(Date.now()-g)+" ms");h.setStatus&&(g=h.statusMessage||"Please wait...",
l=gb,p=hb.zf,l?l<p?h.setStatus(g+" ("+(p-l)+"/"+p+")"):h.setStatus(g):h.setStatus(""));f<eb||setTimeout($a,0)}else f<eb||(ib=ib+1|0,1==Ua&&1<Va&&0!=ib%Va?H():(0==Ua&&(Ya=Za()),ka||h.preMainLoop&&!1===h.preMainLoop()||(jb(a),h.postMainLoop&&h.postMainLoop()),f<eb||("object"==typeof SDL&&SDL.audio&&SDL.audio.nf&&SDL.audio.nf(),H())))};e||(b&&0<b?Ta(0,1E3/b):Ta(1,1),H());if(c)throw"unwind";}function kb(a){a instanceof La||"unwind"==a||da(1,a)}function jb(a){if(!ka)try{a()}catch(b){kb(b)}}
function lb(a){setTimeout(function(){jb(a)},1E4)}function mb(a){nb||(nb={});nb[a]||(nb[a]=1,k(a))}var nb,Xa=!1,H=null,eb=0,Wa=null,db=0,Ua=0,Va=0,ib=0,fb=[],hb={},Ya,$a,gb,ob=!1,pb=!1,qb=[];
function rb(){function a(){pb=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}h.preloadPlugins||(h.preloadPlugins=[]);if(!sb){sb=!0;try{tb=!0}catch(c){tb=!1,k("warning: no blob constructor, cannot create blobs with mimetypes")}ub="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:tb?null:k("warning: no BlobBuilder");vb="undefined"!=
typeof window?window.URL?window.URL:window.webkitURL:void 0;h.Ve||"undefined"!=typeof vb||(k("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),h.Ve=!0);h.preloadPlugins.push({canHandle:function(c){return!h.Ve&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var g=null;if(tb)try{g=new Blob([c],{type:wb(d)}),g.size!==c.length&&(g=new Blob([(new Uint8Array(c)).buffer],{type:wb(d)}))}catch(q){mb("Blob constructor present but fails: "+
q+"; falling back to blob builder")}g||(g=new ub,g.append((new Uint8Array(c)).buffer),g=g.getBlob());var l=vb.createObjectURL(g),p=new Image;p.onload=()=>{p.complete||m("Image "+d+" could not be decoded");var q=document.createElement("canvas");q.width=p.width;q.height=p.height;q.getContext("2d").drawImage(p,0,0);vb.revokeObjectURL(l);e&&e(c)};p.onerror=()=>{ha("Image "+l+" could not be decoded");f&&f()};p.src=l}});h.preloadPlugins.push({canHandle:function(c){return!h.Ff&&c.substr(-4)in{".ogg":1,".wav":1,
".mp3":1}},handle:function(c,d,e,f){function g(){p||(p=!0,e&&e(c))}function l(){p||(p=!0,new Audio,f&&f())}var p=!1;if(tb){try{var q=new Blob([c],{type:wb(d)})}catch(x){return l()}q=vb.createObjectURL(q);var u=new Audio;u.addEventListener("canplaythrough",()=>g(u),!1);u.onerror=function(){if(!p){k("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var x="",L=0,n=0,w=0;w<c.length;w++)for(L=L<<8|c[w],n+=8;6<=n;){var z=L>>n-6&63;n-=6;x+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[z]}2==
n?(x+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(L&3)<<4],x+="=="):4==n&&(x+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(L&15)<<2],x+="=");u.src="data:audio/x-"+d.substr(-3)+";base64,"+x;g(u)}};u.src=q;lb(function(){g(u)})}else return l()}});var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||
document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",c=>{!pb&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function xb(a,b,c,d){if(b&&h.pe&&a==h.canvas)return h.pe;var e;if(b){var f={antialias:!1,alpha:!1,Ue:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!=typeof yb&&(e=zb(a,f)))var l=I[e].ue}else l=a.getContext("2d");if(!l)return null;c&&(b||"undefined"==typeof J||m("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),h.pe=l,b&&Ab(e),h.uf=b,qb.forEach(function(p){p()}),rb());return l}var Bb=!1,Cb=void 0,Db=void 0;
function Eb(a,b){function c(){ob=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=Fb,Cb&&d.requestPointerLock(),ob=!0,Db?("undefined"!=typeof SDL&&(A[SDL.screen>>2]=B[SDL.screen>>2]|8388608),Gb(h.canvas),Hb()):Gb(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),Db?("undefined"!=typeof SDL&&(A[SDL.screen>>2]=B[SDL.screen>>2]&
-8388609),Gb(h.canvas),Hb()):Gb(d));if(h.onFullScreen)h.onFullScreen(ob);if(h.onFullscreen)h.onFullscreen(ob)}Cb=a;Db=b;"undefined"==typeof Cb&&(Cb=!0);"undefined"==typeof Db&&(Db=!1);var d=h.canvas;Bb||(Bb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}
function Fb(){if(!ob)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var Ib=0;function bb(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Ib)Ib=b+1E3/60;else for(;b+2>=Ib;)Ib+=1E3/60;setTimeout(a,Math.max(Ib-b,0))}}
function wb(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Jb=[];function Hb(){var a=h.canvas;Jb.forEach(function(b){b(a.width,a.height)})}
function Gb(a,b,c){b&&c?(a.vf=b,a.hf=c):(b=a.vf,c=a.hf);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}Db?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var sb,tb,ub,vb,K=12288,Kb=!1,Lb=0,Mb=0,Nb=0,M={alpha:!1,depth:!1,stencil:!1,antialias:!1},Ob={},Pb;function Qb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,g){b.drawElementsInstancedANGLE(c,d,e,f,g)})}
function Rb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Sb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}var Tb=1,Ub=[],N=[],Vb=[],Wb=[],O=[],P=[],Xb=[],I=[],Q=[],Yb={},Zb=4;
function R(a){$b||($b=a)}function ac(a){for(var b=Tb++,c=a.length;c<b;c++)a[c]=null;return b}function bc(a,b,c){for(var d="",e=0;e<a;++e){var f=c?A[c+4*e>>2]:-1;d+=r(A[b+4*e>>2],0>f?void 0:f)}return d}function zb(a,b){a.De||(a.De=a.getContext,a.getContext=function(d,e){e=a.De(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?cc(c,b):0}
function cc(a,b){var c=ac(I),d={Bf:c,attributes:b,version:b.Ue,ue:a};a.canvas&&(a.canvas.Ae=d);I[c]=d;("undefined"==typeof b.df||b.df)&&dc(d);return c}function Ab(a){ec=I[a];h.pe=J=ec&&ec.ue}function dc(a){a||(a=ec);if(!a.kf){a.kf=!0;var b=a.ue;Qb(b);Rb(b);Sb(b);b.ne=b.getExtension("EXT_disjoint_timer_query");b.Ef=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var yb={},$b,ec,fc=[];
function gc(a,b){fc.length=0;var c;for(b>>=2;c=t[a++];)b+=105!=c&b,fc.push(105==c?A[b]:D[b++>>1]),++b;return fc}function hc(a){var b=ic();a=a();jc(b);return a}var kc=0;function lc(){for(var a=S.length-1;0<=a;--a)mc(a);S=[];T=[]}var T=[];function nc(a,b,c){function d(g,l){if(g.length!=l.length)return!1;for(var p in g)if(g[p]!=l[p])return!1;return!0}for(var e in T){var f=T[e];if(f.Ne==a&&d(f.Pe,c))return}T.push({Ne:a,Xe:b,Pe:c});T.sort(function(g,l){return g.Xe<l.Xe})}
function oc(a){for(var b=0;b<T.length;++b)T[b].Ne==a&&(T.splice(b,1),--b)}function pc(){if(kc&&qc.we)for(var a=0;a<T.length;++a){var b=T[a];T.splice(a,1);--a;b.Ne.apply(null,b.Pe)}}var S=[];function mc(a){var b=S[a];b.target.removeEventListener(b.je,b.ef,b.le);S.splice(a,1)}
function U(a){function b(d){++kc;qc=a;pc();a.oe(d);pc();--kc}if(a.me)a.ef=b,a.target.addEventListener(a.je,b,a.le),S.push(a),rc||(va.push(lc),rc=!0);else for(var c=0;c<S.length;++c)S[c].target==a.target&&S[c].je==a.je&&mc(c--)}function sc(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}function tc(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}var uc={},rc,qc,vc,wc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc={},Ic=[0,document,window];
function W(a){a=2<a?r(a):a;return Ic[a]||document.querySelector(a)}function Jc(a){return hc(function(){var b=Kc(8),c=b+4,d=Kc(a.id.length+1);v(a.id,d,a.id.length+1);if(d=W(d))A[b>>2]=d.width,A[c>>2]=d.height;return[A[b>>2],A[c>>2]]})}function Lc(a,b,c){a=W(a);if(!a)return-4;a.width=b;a.height=c;return 0}function Mc(a,b,c){a.xf?hc(function(){var d=Kc(a.id.length+1);v(a.id,d,a.id.length+1);Lc(d,b,c)}):(a.width=b,a.height=c)}
function Nc(a){function b(){document.fullscreenElement||document.webkitFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),Mc(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=l,p||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=p,a.style.paddingLeft=q,a.style.paddingRight=u,a.style.paddingTop=x,a.style.paddingBottom=L,a.style.marginLeft=n,a.style.marginRight=w,a.style.marginTop=
z,a.style.marginBottom=V,document.body.style.margin=ab,document.documentElement.style.overflow=wd,document.body.scroll=xd,a.style.ve=yd,a.Ae&&a.Ae.ue.viewport(0,0,d,e),Hc.Ce&&G(Hc.Ce)(37,0,Hc.Qe))}var c=Jc(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,l=a.style.backgroundColor,p=document.body.style.backgroundColor,q=a.style.paddingLeft,u=a.style.paddingRight,x=a.style.paddingTop,L=a.style.paddingBottom,n=a.style.marginLeft,w=a.style.marginRight,z=a.style.marginTop,V=a.style.marginBottom,ab=document.body.style.margin,
wd=document.documentElement.style.overflow,xd=document.body.scroll,yd=a.style.ve;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)}function Oc(a,b,c){a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"}function Pc(a){return 0>Ic.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function Qc(a,b){if(0!=b.Me||0!=b.Ke){Nc(a);var c=b.pf?innerWidth:screen.width,d=b.pf?innerHeight:screen.height,e=Pc(a),f=e.width;e=e.height;var g=Jc(a),l=g[0];g=g[1];3==b.Me?(Oc(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.Me&&(c*g<l*d?(f=g*c/l,Oc(a,(d-f)/2,0),d=f):(f=l*d/g,Oc(a,0,(c-f)/2),c=f));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.ff&&(a.style.ve="optimizeSpeed",
a.style.ve="-moz-crisp-edges",a.style.ve="-o-crisp-edges",a.style.ve="-webkit-optimize-contrast",a.style.ve="optimize-contrast",a.style.ve="crisp-edges",a.style.ve="pixelated");f=2==b.Ke?devicePixelRatio:1;0!=b.Ke&&(c=c*f|0,d=d*f|0,Mc(a,c,d),a.Ae&&a.Ae.ue.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return tc()?-3:-1;Hc=b;b.Ce&&G(b.Ce)(37,0,b.Qe);return 0}
function Rc(a){if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0}
function Sc(a,b){D[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)D[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)D[a+8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)A[a+4*c+1040>>2]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];A[a+1296>>2]=b.connected;A[a+1300>>2]=b.index;A[a+8>>2]=b.axes.length;A[a+12>>2]=b.buttons.length;v(b.id,a+1304,64);v(b.mapping,a+1368,64)}var Tc=[];
function Uc(a,b,c,d){for(var e=0;e<a;e++){var f=J[c](),g=f&&ac(d);f?(f.name=g,d[g]=f):R(1282);A[b+4*e>>2]=g}}function Vc(a,b,c,d,e,f,g,l){b=N[b];if(a=J[a](b,c))d=l&&v(a.name,l,d),e&&(A[e>>2]=d),f&&(A[f>>2]=a.size),g&&(A[g>>2]=a.type)}function Wc(a,b){B[a>>2]=b;B[a+4>>2]=(b-B[a>>2])/4294967296}
function Xc(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&R(1280);return;case 36345:d=0;break;case 34466:var e=J.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=J.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":R(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:R(1280);return}else{if(e instanceof Float32Array||
e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:A[b+4*a>>2]=e[a];break;case 2:C[b+4*a>>2]=e[a];break;case 4:y[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){R(1280);k("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:R(1280);k("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:Wc(b,
d);break;case 0:A[b>>2]=d;break;case 2:C[b>>2]=d;break;case 4:y[b>>0]=d?1:0}}else R(1281)}function Yc(a){var b=oa(a)+1,c=F(b);v(a,c,b);return c}function Zc(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function $c(a){var b=a.ze,c=a.Je,d;if(!b)for(a.ze=b={},a.Ye={},d=0;d<J.getProgramParameter(a,35718);++d){var e=J.getActiveUniform(a,d);var f=e.name;e=e.size;var g=Zc(f);g=0<g?f.slice(0,g):f;var l=a.Ie;a.Ie+=e;c[g]=[e,l];for(f=0;f<e;++f)b[l]=f,a.Ye[l++]=g}}
function X(a){var b=J.Se;if(b){var c=b.ze[a];"number"==typeof c&&(b.ze[a]=c=J.getUniformLocation(b,b.Ye[a]+(0<c?"["+c+"]":"")));return c}R(1282)}function ad(a,b,c,d){if(c)if(a=N[a],$c(a),a=J.getUniform(a,X(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:A[c>>2]=a;break;case 2:C[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:A[c+4*b>>2]=a[b];break;case 2:C[c+4*b>>2]=a[b]}else R(1281)}
function bd(a,b,c,d){if(c)if(a=J.getVertexAttrib(a,b),34975==b)A[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:A[c>>2]=a;break;case 2:C[c>>2]=a;break;case 5:A[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:A[c+4*b>>2]=a[b];break;case 2:C[c+4*b>>2]=a[b];break;case 5:A[c+4*b>>2]=Math.fround(a[b])}else R(1281)}
function cd(a,b,c,d,e){a-=5120;a=1==a?t:4==a?A:6==a?C:5==a||28922==a?B:qa;var f=31-Math.clz32(a.BYTES_PER_ELEMENT),g=Zb;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<f)+g-1&-g)>>f)}var Y=[],dd=[];function ed(a,b){if(!tc())return-1;a=W(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?kc&&qc.we?Qc(a,b):b.cf?(nc(Qc,1,[a,b]),1):-2:-3:-4}
function fd(a,b){var c={target:W(2),je:"beforeunload",me:b,oe:function(d=event){var e=G(b)(28,0,a);e&&(e=r(e));if(e)return d.preventDefault(),d.returnValue=e},le:!0};U(c)}function gd(a,b,c,d,e,f){wc||(wc=F(256));a={target:W(a),je:f,me:d,oe:function(g=event){var l=g.target.id?g.target.id:"",p=wc;v(sc(g.target),p+0,128);v(l,p+128,128);G(d)(e,p,b)&&g.preventDefault()},le:c};U(a)}
function hd(a,b,c,d,e){yc||(yc=F(280));U({target:a,je:e,me:d,oe:function(f=event){var g=yc,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,p=!!l;A[g>>2]=p;A[g+4>>2]=tc();var q=p?l:xc,u=q&&q.id?q.id:"";v(sc(q),g+8,128);v(u,g+136,128);A[g+264>>2]=q?q.clientWidth:0;A[g+268>>2]=q?q.clientHeight:0;A[g+272>>2]=screen.width;A[g+276>>2]=screen.height;p&&(xc=l);G(d)(19,g,b)&&f.preventDefault()},le:c})}
function jd(a,b,c,d,e){zc||(zc=F(1432));b={target:W(2),we:!0,je:e,me:c,oe:function(f=event){var g=zc;Sc(g,f.gamepad);G(c)(d,g,a)&&f.preventDefault()},le:b};U(b)}
function kd(a,b,c,d,e,f){Ac||(Ac=F(176));a={target:W(a),we:!0,je:f,me:d,oe:function(g){var l=Ac;D[l>>3]=g.timeStamp;var p=l>>2;A[p+2]=g.location;A[p+3]=g.ctrlKey;A[p+4]=g.shiftKey;A[p+5]=g.altKey;A[p+6]=g.metaKey;A[p+7]=g.repeat;A[p+8]=g.charCode;A[p+9]=g.keyCode;A[p+10]=g.which;v(g.key||"",l+44,32);v(g.code||"",l+76,32);v(g.char||"",l+108,32);v(g.locale||"",l+140,32);G(d)(e,l,b)&&g.preventDefault()},le:c};U(a)}
function ld(a,b,c){D[a>>3]=b.timeStamp;a>>=2;A[a+2]=b.screenX;A[a+3]=b.screenY;A[a+4]=b.clientX;A[a+5]=b.clientY;A[a+6]=b.ctrlKey;A[a+7]=b.shiftKey;A[a+8]=b.altKey;A[a+9]=b.metaKey;pa[2*a+20]=b.button;pa[2*a+21]=b.buttons;A[a+11]=b.movementX;A[a+12]=b.movementY;c=Pc(c);A[a+13]=b.clientX-c.left;A[a+14]=b.clientY-c.top}
function md(a,b,c,d,e,f){Bc||(Bc=F(72));a=W(a);U({target:a,we:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,je:f,me:d,oe:function(g=event){ld(Bc,g,a);G(d)(e,Bc,b)&&g.preventDefault()},le:c})}function nd(a,b,c,d,e){Cc||(Cc=F(260));U({target:a,je:e,me:d,oe:function(f=event){var g=Cc,l=document.pointerLockElement||document.De||document.mf||document.lf;A[g>>2]=!!l;var p=l&&l.id?l.id:"";v(sc(l),g+4,128);v(p,g+132,128);G(d)(20,g,b)&&f.preventDefault()},le:c})}
function od(a,b,c,d){Dc||(Dc=F(36));a=W(a);U({target:a,je:"resize",me:d,oe:function(e=event){if(e.target==a){var f=document.body;if(f){var g=Dc;A[g>>2]=e.detail;A[g+4>>2]=f.clientWidth;A[g+8>>2]=f.clientHeight;A[g+12>>2]=innerWidth;A[g+16>>2]=innerHeight;A[g+20>>2]=outerWidth;A[g+24>>2]=outerHeight;A[g+28>>2]=pageXOffset;A[g+32>>2]=pageYOffset;G(d)(10,g,b)&&e.preventDefault()}}},le:c})}
function pd(a,b,c,d,e,f){Ec||(Ec=F(1696));a=W(a);U({target:a,we:"touchstart"==f||"touchend"==f,je:f,me:d,oe:function(g){for(var l,p={},q=g.touches,u=0;u<q.length;++u)l=q[u],l.Te=l.We=0,p[l.identifier]=l;for(u=0;u<g.changedTouches.length;++u)l=g.changedTouches[u],l.Te=1,p[l.identifier]=l;for(u=0;u<g.targetTouches.length;++u)p[g.targetTouches[u].identifier].We=1;q=Ec;D[q>>3]=g.timeStamp;var x=q>>2;A[x+3]=g.ctrlKey;A[x+4]=g.shiftKey;A[x+5]=g.altKey;A[x+6]=g.metaKey;x+=7;var L=Pc(a),n=0;for(u in p)if(l=
p[u],A[x]=l.identifier,A[x+1]=l.screenX,A[x+2]=l.screenY,A[x+3]=l.clientX,A[x+4]=l.clientY,A[x+5]=l.pageX,A[x+6]=l.pageY,A[x+7]=l.Te,A[x+8]=l.We,A[x+9]=l.clientX-L.left,A[x+10]=l.clientY-L.top,x+=13,31<++n)break;A[q+8>>2]=n;G(d)(e,q,b)&&g.preventDefault()},le:c})}
function qd(a,b,c){var d=Ic[1];Fc||(Fc=F(8));U({target:d,je:"visibilitychange",me:c,oe:function(e=event){var f=Fc,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);A[f>>2]=document.hidden;A[f+4>>2]=g;G(c)(21,f,a)&&e.preventDefault()},le:b})}
function rd(a,b,c,d){Gc||(Gc=F(104));U({target:a,we:!0,je:"wheel",me:d,oe:function(e=event){var f=Gc;ld(f,e,a);D[f+72>>3]=e.deltaX;D[f+80>>3]=e.deltaY;D[f+88>>3]=e.deltaZ;A[f+96>>2]=e.deltaMode;G(d)(9,f,b)&&e.preventDefault()},le:c})}var sd={};
function td(){if(!ud){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in sd)void 0===sd[b]?delete a[b]:a[b]=sd[b];var c=[];for(b in a)c.push(b+"="+a[b]);ud=c}return ud}var ud,vd=[null,[],[]],zd=[31,29,31,30,31,30,31,31,30,31,30,31],Ad=[31,28,31,30,31,30,31,31,30,31,30,31];
function Bd(a){var b=Array(oa(a)+1);na(a,b,0,b.length);return b}function Cd(a){if(!noExitRuntime){if(h.onExit)h.onExit(a);ka=!0}da(a,new La(a))}h.requestFullscreen=function(a,b){Eb(a,b)};h.requestAnimationFrame=function(a){bb(a)};h.setCanvasSize=function(a,b,c){Gb(h.canvas,a,b);c||Hb()};h.pauseMainLoop=function(){H=null;eb++};h.resumeMainLoop=function(){eb++;var a=Ua,b=Va,c=Wa;Wa=null;cb(c,0,!1,db,!0);Ta(a,b);H()};
h.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};h.createContext=function(a,b,c,d){return xb(a,b,c,d)};for(var J,Z=0;32>Z;++Z)Tc.push(Array(Z));var Dd=new Float32Array(288);for(Z=0;288>Z;++Z)Y[Z]=Dd.subarray(0,Z+1);var Ed=new Int32Array(288);for(Z=0;288>Z;++Z)dd[Z]=Ed.subarray(0,Z+1);
var Fd={fa:function(){return 0},$a:function(){return 0},ab:function(){},bb:function(){return!0},cb:function(a,b){a=new Date(1E3*(B[a>>2]+4294967296*A[a+4>>2]));A[b>>2]=a.getSeconds();A[b+4>>2]=a.getMinutes();A[b+8>>2]=a.getHours();A[b+12>>2]=a.getDate();A[b+16>>2]=a.getMonth();A[b+20>>2]=a.getFullYear()-1900;A[b+24>>2]=a.getDay();A[b+28>>2]=(Pa(a.getFullYear())?Qa:Ra)[a.getMonth()]+a.getDate()-1|0;A[b+36>>2]=-(60*a.getTimezoneOffset());var c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset(),d=(new Date(a.getFullYear(),
0,1)).getTimezoneOffset();A[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},db:function(a,b,c){function d(p){return(p=p.toTimeString().match(/\(([A-Za-z ]+)\)$/))?p[1]:"GMT"}var e=(new Date).getFullYear(),f=new Date(e,0,1),g=new Date(e,6,1);e=f.getTimezoneOffset();var l=g.getTimezoneOffset();B[a>>2]=60*Math.max(e,l);A[b>>2]=Number(e!=l);a=d(f);b=d(g);a=Sa(a);b=Sa(b);l<e?(B[c>>2]=a,B[c+4>>2]=b):(B[c>>2]=b,B[c+4>>2]=a)},Ia:function(a){if(12448==a)return K=12288,1;K=12300;return 0},La:function(a,
b,c,d,e){if(62E3!=a)K=12296,c=0;else{if(b)for(;;){a=A[b>>2];if(12321==a)M.alpha=0<A[b+4>>2];else if(12325==a)M.depth=0<A[b+4>>2];else if(12326==a)M.stencil=0<A[b+4>>2];else if(12337==a)a=A[b+4>>2],M.antialias=0<a;else if(12338==a)a=A[b+4>>2],M.antialias=1==a;else if(12544==a)M.Cf=12547!=A[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(A[e>>2]=1),c&&0<d&&(A[c>>2]=62002),K=12288,c=1):(K=12300,c=0)}return c},ya:function(a,b,c,d){if(62E3!=a)return K=12296,0;for(a=1;;){b=A[d>>2];if(12440==b)a=A[d+4>>
2];else if(12344==b)break;else return K=12292,0;d+=8}if(2!=a)return K=12293,0;M.Ue=a-1;M.Df=0;Pb=zb(h.canvas,M);if(0!=Pb)return K=12288,Ab(Pb),h.uf=!0,qb.forEach(function(e){e()}),Ab(null),62004;K=12297;return 0},Ba:function(a,b){if(62E3!=a)return K=12296,0;if(62002!=b)return K=12293,0;K=12288;return 62006},za:function(a,b){if(62E3!=a)return K=12296,0;if(62004!=b)return K=12294,0;a=Pb;ec===I[a]&&(ec=null);if("object"==typeof uc)for(var c=I[a].ue.canvas,d=0;d<S.length;++d)S[d].target!=c||mc(d--);I[a]&&
I[a].ue.canvas&&(I[a].ue.canvas.Ae=void 0);I[a]=null;K=12288;Lb==b&&(Lb=0);return 1},Ca:function(a,b){if(62E3!=a)return K=12296,0;if(62006!=b)return K=12301,1;Mb==b&&(Mb=0);Nb==b&&(Nb=0);K=12288;return 1},Ma:function(a,b,c,d){if(62E3!=a)return K=12296,0;if(62002!=b)return K=12293,0;if(!d)return K=12300,0;K=12288;switch(c){case 12320:return A[d>>2]=M.alpha?32:24,1;case 12321:return A[d>>2]=M.alpha?8:0,1;case 12322:return A[d>>2]=8,1;case 12323:return A[d>>2]=8,1;case 12324:return A[d>>2]=8,1;case 12325:return A[d>>
2]=M.depth?24:0,1;case 12326:return A[d>>2]=M.stencil?8:0,1;case 12327:return A[d>>2]=12344,1;case 12328:return A[d>>2]=62002,1;case 12329:return A[d>>2]=0,1;case 12330:return A[d>>2]=4096,1;case 12331:return A[d>>2]=16777216,1;case 12332:return A[d>>2]=4096,1;case 12333:return A[d>>2]=0,1;case 12334:return A[d>>2]=0,1;case 12335:return A[d>>2]=12344,1;case 12337:return A[d>>2]=M.antialias?4:0,1;case 12338:return A[d>>2]=M.antialias?1:0,1;case 12339:return A[d>>2]=4,1;case 12340:return A[d>>2]=12344,
1;case 12341:case 12342:case 12343:return A[d>>2]=-1,1;case 12345:case 12346:return A[d>>2]=0,1;case 12347:return A[d>>2]=0,1;case 12348:return A[d>>2]=1;case 12349:case 12350:return A[d>>2]=0,1;case 12351:return A[d>>2]=12430,1;case 12352:return A[d>>2]=4,1;case 12354:return A[d>>2]=0,1;default:return K=12292,0}},X:function(){K=12288;return 62E3},xa:function(){return K},Ja:function(a,b,c){if(62E3!=a)return K=12296,0;b&&(A[b>>2]=1);c&&(A[c>>2]=4);Kb=!0;K=12288;return 1},Da:function(a,b,c,d){if(62E3!=
a)return K=12296,0;if(0!=d&&62004!=d)return K=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return K=12301,0;Ab(d?Pb:null);Lb=d;Nb=b;Mb=c;K=12288;return 1},wa:function(a,b){if(62E3!=a)return K=12296,0;K=12288;if(Ob[b])return Ob[b];switch(b){case 12371:a=Sa("Emscripten");break;case 12372:a=Sa("1.4 Emscripten EGL");break;case 12373:a=Sa("");break;case 12429:a=Sa("OpenGL_ES");break;default:return K=12300,0}return Ob[b]=a},Ea:function(){if(Kb)if(h.pe)if(h.pe.isContextLost())K=12302;else return K=12288,1;
else K=12290;else K=12289;return 0},Fa:function(a,b){if(62E3!=a)return K=12296,0;0==b?Ta(0,0):Ta(1,b);K=12288;return 1},Ka:function(a){if(62E3!=a)return K=12296,0;Nb=Mb=Lb=0;Kb=!1;K=12288;return 1},Ha:function(){K=12288;return 1},Ga:function(){K=12288;return 1},Pa:function(a,b,c){b=gc(b,c);return Ka[a].apply(null,b)},b:function(a,b,c){b=gc(b,c);return Ka[a].apply(null,b)},ga:function(){return Date.now()},qa:function(){if(!tc())return-1;oc(Qc);var a=Ic[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();
else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},ua:function(){oc(Rc);if(document.exitPointerLock)document.exitPointerLock();else return-1;return 0},q:function(){return devicePixelRatio},h:function(a,b,c){a=W(a);if(!a)return-4;a=Pc(a);D[b>>3]=a.width;D[c>>3]=a.height;return 0},$:function(a,b){if(0>a||a>=vc.length)return-5;if(!vc[a])return-7;Sc(b,vc[a]);return 0},y:Za,Na:function(){return vc.length},va:function(a,b){A[a>>2]=screen.width;A[b>>
2]=screen.height},Od:function(a){J.activeTexture(a)},Nd:function(a,b){J.attachShader(N[a],P[b])},ma:function(a,b){J.ne.beginQueryEXT(a,Q[b])},Md:function(a,b,c){J.bindAttribLocation(N[a],b,r(c))},Ld:function(a,b){J.bindBuffer(a,Ub[b])},Kd:function(a,b){J.bindFramebuffer(a,Vb[b])},Jd:function(a,b){J.bindRenderbuffer(a,Wb[b])},Id:function(a,b){J.bindTexture(a,O[b])},Wd:function(a){J.bindVertexArray(Xb[a])},Hd:function(a,b,c,d){J.blendColor(a,b,c,d)},Gd:function(a){J.blendEquation(a)},Fd:function(a,
b){J.blendEquationSeparate(a,b)},Ed:function(a,b){J.blendFunc(a,b)},Dd:function(a,b,c,d){J.blendFuncSeparate(a,b,c,d)},Cd:function(a,b,c,d){J.bufferData(a,c?t.subarray(c,c+b):b,d)},Bd:function(a,b,c,d){J.bufferSubData(a,b,t.subarray(d,d+c))},Ad:function(a){return J.checkFramebufferStatus(a)},zd:function(a){J.clear(a)},yd:function(a,b,c,d){J.clearColor(a,b,c,d)},xd:function(a){J.clearDepth(a)},wd:function(a){J.clearStencil(a)},vd:function(a,b,c,d){J.colorMask(!!a,!!b,!!c,!!d)},ud:function(a){J.compileShader(P[a])},
td:function(a,b,c,d,e,f,g,l){J.compressedTexImage2D(a,b,c,d,e,f,l?t.subarray(l,l+g):null)},sd:function(a,b,c,d,e,f,g,l,p){J.compressedTexSubImage2D(a,b,c,d,e,f,g,p?t.subarray(p,p+l):null)},rd:function(a,b,c,d,e,f,g,l){J.copyTexImage2D(a,b,c,d,e,f,g,l)},qd:function(a,b,c,d,e,f,g,l){J.copyTexSubImage2D(a,b,c,d,e,f,g,l)},pd:function(){var a=ac(N),b=J.createProgram();b.name=a;b.te=b.re=b.se=0;b.Ie=1;N[a]=b;return a},od:function(a){var b=ac(P);P[b]=J.createShader(a);return b},nd:function(a){J.cullFace(a)},
md:function(a,b){for(var c=0;c<a;c++){var d=A[b+4*c>>2],e=Ub[d];e&&(J.deleteBuffer(e),e.name=0,Ub[d]=null)}},ld:function(a,b){for(var c=0;c<a;++c){var d=A[b+4*c>>2],e=Vb[d];e&&(J.deleteFramebuffer(e),e.name=0,Vb[d]=null)}},kd:function(a){if(a){var b=N[a];b?(J.deleteProgram(b),b.name=0,N[a]=null):R(1281)}},oa:function(a,b){for(var c=0;c<a;c++){var d=A[b+4*c>>2],e=Q[d];e&&(J.ne.deleteQueryEXT(e),Q[d]=null)}},jd:function(a,b){for(var c=0;c<a;c++){var d=A[b+4*c>>2],e=Wb[d];e&&(J.deleteRenderbuffer(e),
e.name=0,Wb[d]=null)}},id:function(a){if(a){var b=P[a];b?(J.deleteShader(b),P[a]=null):R(1281)}},hd:function(a,b){for(var c=0;c<a;c++){var d=A[b+4*c>>2],e=O[d];e&&(J.deleteTexture(e),e.name=0,O[d]=null)}},Vd:function(a,b){for(var c=0;c<a;c++){var d=A[b+4*c>>2];J.deleteVertexArray(Xb[d]);Xb[d]=null}},gd:function(a){J.depthFunc(a)},fd:function(a){J.depthMask(!!a)},ed:function(a,b){J.depthRange(a,b)},dd:function(a,b){J.detachShader(N[a],P[b])},cd:function(a){J.disable(a)},bd:function(a){J.disableVertexAttribArray(a)},
ad:function(a,b,c){J.drawArrays(a,b,c)},Rd:function(a,b,c,d){J.drawArraysInstanced(a,b,c,d)},Sd:function(a,b){for(var c=Tc[a],d=0;d<a;d++)c[d]=A[b+4*d>>2];J.drawBuffers(c)},$c:function(a,b,c,d){J.drawElements(a,b,c,d)},Qd:function(a,b,c,d,e){J.drawElementsInstanced(a,b,c,d,e)},_c:function(a){J.enable(a)},Zc:function(a){J.enableVertexAttribArray(a)},la:function(a){J.ne.endQueryEXT(a)},Yc:function(){J.finish()},Xc:function(){J.flush()},Wc:function(a,b,c,d){J.framebufferRenderbuffer(a,b,c,Wb[d])},Vc:function(a,
b,c,d,e){J.framebufferTexture2D(a,b,c,O[d],e)},Uc:function(a){J.frontFace(a)},Tc:function(a,b){Uc(a,b,"createBuffer",Ub)},Rc:function(a,b){Uc(a,b,"createFramebuffer",Vb)},pa:function(a,b){for(var c=0;c<a;c++){var d=J.ne.createQueryEXT();if(!d){for(R(1282);c<a;)A[b+4*c++>>2]=0;break}var e=ac(Q);d.name=e;Q[e]=d;A[b+4*c>>2]=e}},Qc:function(a,b){Uc(a,b,"createRenderbuffer",Wb)},Pc:function(a,b){Uc(a,b,"createTexture",O)},Ud:function(a,b){Uc(a,b,"createVertexArray",Xb)},Sc:function(a){J.generateMipmap(a)},
Oc:function(a,b,c,d,e,f,g){Vc("getActiveAttrib",a,b,c,d,e,f,g)},Nc:function(a,b,c,d,e,f,g){Vc("getActiveUniform",a,b,c,d,e,f,g)},Mc:function(a,b,c,d){a=J.getAttachedShaders(N[a]);var e=a.length;e>b&&(e=b);A[c>>2]=e;for(b=0;b<e;++b)A[d+4*b>>2]=P.indexOf(a[b])},Lc:function(a,b){return J.getAttribLocation(N[a],r(b))},Kc:function(a,b){Xc(a,b,4)},Jc:function(a,b,c){c?A[c>>2]=J.getBufferParameter(a,b):R(1281)},Ic:function(){var a=J.getError()||$b;$b=0;return a},Hc:function(a,b){Xc(a,b,2)},Gc:function(a,
b,c,d){a=J.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;A[d>>2]=a},Fc:function(a,b){Xc(a,b,0)},Dc:function(a,b,c,d){a=J.getProgramInfoLog(N[a]);null===a&&(a="(unknown error)");b=0<b&&d?v(a,d,b):0;c&&(A[c>>2]=b)},Ec:function(a,b,c){if(c)if(a>=Tb)R(1281);else if(a=N[a],35716==b)a=J.getProgramInfoLog(a),null===a&&(a="(unknown error)"),A[c>>2]=a.length+1;else if(35719==b){if(!a.te)for(b=0;b<J.getProgramParameter(a,35718);++b)a.te=Math.max(a.te,
J.getActiveUniform(a,b).name.length+1);A[c>>2]=a.te}else if(35722==b){if(!a.re)for(b=0;b<J.getProgramParameter(a,35721);++b)a.re=Math.max(a.re,J.getActiveAttrib(a,b).name.length+1);A[c>>2]=a.re}else if(35381==b){if(!a.se)for(b=0;b<J.getProgramParameter(a,35382);++b)a.se=Math.max(a.se,J.getActiveUniformBlockName(a,b).length+1);A[c>>2]=a.se}else A[c>>2]=J.getProgramParameter(a,b);else R(1281)},Yd:function(a,b,c){if(c){a=J.ne.getQueryObjectEXT(Q[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;Wc(c,d)}else R(1281)},
ia:function(a,b,c){if(c){a=J.ne.getQueryObjectEXT(Q[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;A[c>>2]=d}else R(1281)},Xd:function(a,b,c){if(c){a=J.ne.getQueryObjectEXT(Q[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;Wc(c,d)}else R(1281)},ha:function(a,b,c){if(c){a=J.ne.getQueryObjectEXT(Q[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;A[c>>2]=d}else R(1281)},ja:function(a,b,c){c?A[c>>2]=J.ne.getQueryEXT(a,b):R(1281)},Cc:function(a,b,c){c?A[c>>2]=J.getRenderbufferParameter(a,b):R(1281)},Ac:function(a,
b,c,d){a=J.getShaderInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?v(a,d,b):0;c&&(A[c>>2]=b)},zc:function(a,b,c,d){a=J.getShaderPrecisionFormat(a,b);A[c>>2]=a.rangeMin;A[c+4>>2]=a.rangeMax;A[d>>2]=a.precision},yc:function(a,b,c,d){if(a=J.getShaderSource(P[a]))b=0<b&&d?v(a,d,b):0,c&&(A[c>>2]=b)},Bc:function(a,b,c){c?35716==b?(a=J.getShaderInfoLog(P[a]),null===a&&(a="(unknown error)"),A[c>>2]=a?a.length+1:0):35720==b?(a=J.getShaderSource(P[a]),A[c>>2]=a?a.length+1:0):A[c>>2]=J.getShaderParameter(P[a],
b):R(1281)},xc:function(a){var b=Yb[a];if(!b){switch(a){case 7939:b=J.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Yc(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=J.getParameter(a))||R(1280);b=b&&Yc(b);break;case 7938:b=Yc("OpenGL ES 2.0 ("+J.getParameter(7938)+")");break;case 35724:b=J.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=
Yc(b);break;default:R(1280)}Yb[a]=b}return b},wc:function(a,b,c){c?C[c>>2]=J.getTexParameter(a,b):R(1281)},vc:function(a,b,c){c?A[c>>2]=J.getTexParameter(a,b):R(1281)},sc:function(a,b){b=r(b);if(a=N[a]){$c(a);var c=a.ze,d=0,e=b,f=Zc(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.Je[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||J.getUniformLocation(a,b)))return d}else R(1281);return-1},uc:function(a,b,c){ad(a,b,c,2)},tc:function(a,b,c){ad(a,b,c,0)},pc:function(a,b,c){c?A[c>>2]=J.getVertexAttribOffset(a,
b):R(1281)},rc:function(a,b,c){bd(a,b,c,2)},qc:function(a,b,c){bd(a,b,c,5)},oc:function(a,b){J.hint(a,b)},nc:function(a){return(a=Ub[a])?J.isBuffer(a):0},mc:function(a){return J.isEnabled(a)},lc:function(a){return(a=Vb[a])?J.isFramebuffer(a):0},kc:function(a){return(a=N[a])?J.isProgram(a):0},na:function(a){return(a=Q[a])?J.ne.isQueryEXT(a):0},jc:function(a){return(a=Wb[a])?J.isRenderbuffer(a):0},ic:function(a){return(a=P[a])?J.isShader(a):0},hc:function(a){return(a=O[a])?J.isTexture(a):0},Td:function(a){return(a=
Xb[a])?J.isVertexArray(a):0},gc:function(a){J.lineWidth(a)},fc:function(a){a=N[a];J.linkProgram(a);a.ze=0;a.Je={}},ec:function(a,b){3317==a&&(Zb=b);J.pixelStorei(a,b)},dc:function(a,b){J.polygonOffset(a,b)},ka:function(a,b){J.ne.queryCounterEXT(Q[a],b)},cc:function(a,b,c,d,e,f,g){(g=cd(f,e,c,d,g))?J.readPixels(a,b,c,d,e,f,g):R(1280)},bc:function(){},ac:function(a,b,c,d){J.renderbufferStorage(a,b,c,d)},$b:function(a,b){J.sampleCoverage(a,!!b)},_b:function(a,b,c,d){J.scissor(a,b,c,d)},Zb:function(){R(1280)},
Yb:function(a,b,c,d){b=bc(b,c,d);J.shaderSource(P[a],b)},Xb:function(a,b,c){J.stencilFunc(a,b,c)},Wb:function(a,b,c,d){J.stencilFuncSeparate(a,b,c,d)},Vb:function(a){J.stencilMask(a)},Ub:function(a,b){J.stencilMaskSeparate(a,b)},Tb:function(a,b,c){J.stencilOp(a,b,c)},Sb:function(a,b,c,d){J.stencilOpSeparate(a,b,c,d)},Rb:function(a,b,c,d,e,f,g,l,p){J.texImage2D(a,b,c,d,e,f,g,l,p?cd(l,g,d,e,p):null)},Qb:function(a,b,c){J.texParameterf(a,b,c)},Pb:function(a,b,c){J.texParameterf(a,b,C[c>>2])},Ob:function(a,
b,c){J.texParameteri(a,b,c)},Nb:function(a,b,c){J.texParameteri(a,b,A[c>>2])},Mb:function(a,b,c,d,e,f,g,l,p){var q=null;p&&(q=cd(l,g,e,f,p));J.texSubImage2D(a,b,c,d,e,f,g,l,q)},Lb:function(a,b){J.uniform1f(X(a),b)},Kb:function(a,b,c){if(288>=b)for(var d=Y[b-1],e=0;e<b;++e)d[e]=C[c+4*e>>2];else d=C.subarray(c>>2,c+4*b>>2);J.uniform1fv(X(a),d)},Jb:function(a,b){J.uniform1i(X(a),b)},Ib:function(a,b,c){if(288>=b)for(var d=dd[b-1],e=0;e<b;++e)d[e]=A[c+4*e>>2];else d=A.subarray(c>>2,c+4*b>>2);J.uniform1iv(X(a),
d)},Hb:function(a,b,c){J.uniform2f(X(a),b,c)},Gb:function(a,b,c){if(144>=b)for(var d=Y[2*b-1],e=0;e<2*b;e+=2)d[e]=C[c+4*e>>2],d[e+1]=C[c+(4*e+4)>>2];else d=C.subarray(c>>2,c+8*b>>2);J.uniform2fv(X(a),d)},Fb:function(a,b,c){J.uniform2i(X(a),b,c)},Eb:function(a,b,c){if(144>=b)for(var d=dd[2*b-1],e=0;e<2*b;e+=2)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2];else d=A.subarray(c>>2,c+8*b>>2);J.uniform2iv(X(a),d)},Db:function(a,b,c,d){J.uniform3f(X(a),b,c,d)},Cb:function(a,b,c){if(96>=b)for(var d=Y[3*b-1],e=0;e<
3*b;e+=3)d[e]=C[c+4*e>>2],d[e+1]=C[c+(4*e+4)>>2],d[e+2]=C[c+(4*e+8)>>2];else d=C.subarray(c>>2,c+12*b>>2);J.uniform3fv(X(a),d)},Bb:function(a,b,c,d){J.uniform3i(X(a),b,c,d)},Ab:function(a,b,c){if(96>=b)for(var d=dd[3*b-1],e=0;e<3*b;e+=3)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2],d[e+2]=A[c+(4*e+8)>>2];else d=A.subarray(c>>2,c+12*b>>2);J.uniform3iv(X(a),d)},zb:function(a,b,c,d,e){J.uniform4f(X(a),b,c,d,e)},yb:function(a,b,c){if(72>=b){var d=Y[4*b-1],e=C;c>>=2;for(var f=0;f<4*b;f+=4){var g=c+f;d[f]=e[g];
d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=C.subarray(c>>2,c+16*b>>2);J.uniform4fv(X(a),d)},xb:function(a,b,c,d,e){J.uniform4i(X(a),b,c,d,e)},wb:function(a,b,c){if(72>=b)for(var d=dd[4*b-1],e=0;e<4*b;e+=4)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2],d[e+2]=A[c+(4*e+8)>>2],d[e+3]=A[c+(4*e+12)>>2];else d=A.subarray(c>>2,c+16*b>>2);J.uniform4iv(X(a),d)},vb:function(a,b,c,d){if(72>=b)for(var e=Y[4*b-1],f=0;f<4*b;f+=4)e[f]=C[d+4*f>>2],e[f+1]=C[d+(4*f+4)>>2],e[f+2]=C[d+(4*f+8)>>2],e[f+3]=C[d+(4*f+12)>>
2];else e=C.subarray(d>>2,d+16*b>>2);J.uniformMatrix2fv(X(a),!!c,e)},ub:function(a,b,c,d){if(32>=b)for(var e=Y[9*b-1],f=0;f<9*b;f+=9)e[f]=C[d+4*f>>2],e[f+1]=C[d+(4*f+4)>>2],e[f+2]=C[d+(4*f+8)>>2],e[f+3]=C[d+(4*f+12)>>2],e[f+4]=C[d+(4*f+16)>>2],e[f+5]=C[d+(4*f+20)>>2],e[f+6]=C[d+(4*f+24)>>2],e[f+7]=C[d+(4*f+28)>>2],e[f+8]=C[d+(4*f+32)>>2];else e=C.subarray(d>>2,d+36*b>>2);J.uniformMatrix3fv(X(a),!!c,e)},tb:function(a,b,c,d){if(18>=b){var e=Y[16*b-1],f=C;d>>=2;for(var g=0;g<16*b;g+=16){var l=d+g;e[g]=
f[l];e[g+1]=f[l+1];e[g+2]=f[l+2];e[g+3]=f[l+3];e[g+4]=f[l+4];e[g+5]=f[l+5];e[g+6]=f[l+6];e[g+7]=f[l+7];e[g+8]=f[l+8];e[g+9]=f[l+9];e[g+10]=f[l+10];e[g+11]=f[l+11];e[g+12]=f[l+12];e[g+13]=f[l+13];e[g+14]=f[l+14];e[g+15]=f[l+15]}}else e=C.subarray(d>>2,d+64*b>>2);J.uniformMatrix4fv(X(a),!!c,e)},rb:function(a){a=N[a];J.useProgram(a);J.Se=a},qb:function(a){J.validateProgram(N[a])},pb:function(a,b){J.vertexAttrib1f(a,b)},ob:function(a,b){J.vertexAttrib1f(a,C[b>>2])},nb:function(a,b,c){J.vertexAttrib2f(a,
b,c)},mb:function(a,b){J.vertexAttrib2f(a,C[b>>2],C[b+4>>2])},lb:function(a,b,c,d){J.vertexAttrib3f(a,b,c,d)},kb:function(a,b){J.vertexAttrib3f(a,C[b>>2],C[b+4>>2],C[b+8>>2])},jb:function(a,b,c,d,e){J.vertexAttrib4f(a,b,c,d,e)},ib:function(a,b){J.vertexAttrib4f(a,C[b>>2],C[b+4>>2],C[b+8>>2],C[b+12>>2])},Pd:function(a,b){J.vertexAttribDivisor(a,b)},gb:function(a,b,c,d,e,f){J.vertexAttribPointer(a,b,c,!!d,e,f)},fb:function(a,b,c,d){J.viewport(a,b,c,d)},w:function(){return 0},eb:function(a,b,c){t.copyWithin(a,
b,b+c)},sa:function(a,b,c){return ed(a,{Me:A[c>>2],Ke:A[c+4>>2],ff:A[c+8>>2],cf:b,Ce:A[c+12>>2],Qe:A[c+16>>2]})},W:function(a,b){a=W(a);return a?a.requestPointerLock?kc&&qc.we?Rc(a):b?(nc(Rc,2,[a]),1):-2:-1:-4},Xa:function(){m("OOM")},Ta:function(a){eval(r(a))},aa:function(){return(vc=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads():null)?0:-1},C:function(a,b,c){if("undefined"==typeof onbeforeunload)return-1;if(1!==c)return-5;fd(a,b);return 0},
O:function(a,b,c,d){gd(a,b,c,d,12,"blur");return 0},k:Lc,u:function(a,b,c){a=W(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},P:function(a,b,c,d){gd(a,b,c,d,13,"focus");return 0},E:function(a,b,c,d){if(!tc())return-1;a=W(a);if(!a)return-4;hd(a,b,c,d,"fullscreenchange");hd(a,b,c,d,"webkitfullscreenchange");return 0},_:function(a,b,c){if(!navigator.getGamepads&&!navigator.webkitGetGamepads)return-1;jd(a,b,c,26,"gamepadconnected");return 0},Z:function(a,b,c){if(!navigator.getGamepads&&
!navigator.webkitGetGamepads)return-1;jd(a,b,c,27,"gamepaddisconnected");return 0},H:function(a,b,c,d){kd(a,b,c,d,2,"keydown");return 0},F:function(a,b,c,d){kd(a,b,c,d,1,"keypress");return 0},G:function(a,b,c,d){kd(a,b,c,d,3,"keyup");return 0},Qa:function(a,b,c){a=G(a);cb(a,b,c)},U:function(a,b,c,d){md(a,b,c,d,5,"mousedown");return 0},S:function(a,b,c,d){md(a,b,c,d,33,"mouseenter");return 0},R:function(a,b,c,d){md(a,b,c,d,34,"mouseleave");return 0},V:function(a,b,c,d){md(a,b,c,d,8,"mousemove");return 0},
T:function(a,b,c,d){md(a,b,c,d,6,"mouseup");return 0},I:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.De||document.body.mf||document.body.lf))return-1;a=W(a);if(!a)return-4;nd(a,b,c,d,"pointerlockchange");nd(a,b,c,d,"mozpointerlockchange");nd(a,b,c,d,"webkitpointerlockchange");nd(a,b,c,d,"mspointerlockchange");return 0},x:function(a,b,c,d){od(a,b,c,d);return 0},J:function(a,b,c,d){pd(a,b,c,d,25,"touchcancel");return 0},M:function(a,b,c,d){pd(a,b,
c,d,23,"touchend");return 0},L:function(a,b,c,d){pd(a,b,c,d,24,"touchmove");return 0},N:function(a,b,c,d){pd(a,b,c,d,22,"touchstart");return 0},D:function(a,b,c){qd(a,b,c);return 0},Q:function(a,b,c,d){a=W(a);return"undefined"!=typeof a.onwheel?(rd(a,b,c,d),0):-1},ta:function(a){fa(r(a))},v:function(){throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},Ya:function(a,b){var c=0;td().forEach(function(d,e){var f=b+c;e=B[a+4*e>>2]=f;for(f=
0;f<d.length;++f)y[e++>>0]=d.charCodeAt(f);y[e>>0]=0;c+=d.length+1});return 0},Za:function(a,b){var c=td();B[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});B[b>>2]=d;return 0},da:function(){return 52},_a:function(){return 52},Wa:function(){return 70},ea:function(a,b,c,d){for(var e=0,f=0;f<c;f++){var g=B[b>>2],l=B[b+4>>2];b+=8;for(var p=0;p<l;p++){var q=t[g+p],u=vd[a];0===q||10===q?((1===a?ha:k)(ma(u,0)),u.length=0):u.push(q)}e+=l}B[d>>2]=e;return 0},sb:function(a){J.activeTexture(a)},
m:function(a,b){J.attachShader(N[a],P[b])},a:function(a,b){J.bindBuffer(a,Ub[b])},Y:function(a,b){J.bindTexture(a,O[b])},c:function(a,b,c,d){J.bufferData(a,c?t.subarray(c,c+b):b,d)},Sa:function(a){J.clear(a)},Ra:function(a,b,c,d){J.clearColor(a,b,c,d)},n:function(a){J.compileShader(P[a])},B:function(){var a=ac(N),b=J.createProgram();b.name=a;b.te=b.re=b.se=0;b.Ie=1;N[a]=b;return a},p:function(a){var b=ac(P);P[b]=J.createShader(a);return b},Zd:function(a){if(a){var b=N[a];b?(J.deleteProgram(b),b.name=
0,N[a]=null):R(1281)}},t:function(a,b,c,d){J.drawElements(a,b,c,d)},ba:function(a){J.enable(a)},f:function(a){J.enableVertexAttribArray(a)},d:function(a,b){Uc(a,b,"createBuffer",Ub)},Oa:function(a,b){Uc(a,b,"createTexture",O)},l:function(a,b){return J.getAttribLocation(N[a],r(b))},ra:function(a,b,c,d){a=J.getProgramInfoLog(N[a]);null===a&&(a="(unknown error)");b=0<b&&d?v(a,d,b):0;c&&(A[c>>2]=b)},K:function(a,b,c){if(c)if(a>=Tb)R(1281);else if(a=N[a],35716==b)a=J.getProgramInfoLog(a),null===a&&(a=
"(unknown error)"),A[c>>2]=a.length+1;else if(35719==b){if(!a.te)for(b=0;b<J.getProgramParameter(a,35718);++b)a.te=Math.max(a.te,J.getActiveUniform(a,b).name.length+1);A[c>>2]=a.te}else if(35722==b){if(!a.re)for(b=0;b<J.getProgramParameter(a,35721);++b)a.re=Math.max(a.re,J.getActiveAttrib(a,b).name.length+1);A[c>>2]=a.re}else if(35381==b){if(!a.se)for(b=0;b<J.getProgramParameter(a,35382);++b)a.se=Math.max(a.se,J.getActiveUniformBlockName(a,b).length+1);A[c>>2]=a.se}else A[c>>2]=J.getProgramParameter(a,
b);else R(1281)},e:function(a,b){b=r(b);if(a=N[a]){$c(a);var c=a.ze,d=0,e=b,f=Zc(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.Je[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||J.getUniformLocation(a,b)))return d}else R(1281);return-1},A:function(a){a=N[a];J.linkProgram(a);a.ze=0;a.Je={}},Ua:function(a,b){3317==a&&(Zb=b);J.pixelStorei(a,b)},o:function(a,b,c,d){b=bc(b,c,d);J.shaderSource(P[a],b)},Aa:function(a,b,c,d,e,f,g,l,p){J.texImage2D(a,b,c,d,e,f,g,l,p?cd(l,g,d,e,p):null)},r:function(a,b,c){J.texParameteri(a,
b,c)},ca:function(a,b){J.uniform1f(X(a),b)},hb:function(a,b){J.uniform1i(X(a),b)},s:function(a,b,c,d){J.uniform3f(X(a),b,c,d)},i:function(a,b,c,d){if(18>=b){var e=Y[16*b-1],f=C;d>>=2;for(var g=0;g<16*b;g+=16){var l=d+g;e[g]=f[l];e[g+1]=f[l+1];e[g+2]=f[l+2];e[g+3]=f[l+3];e[g+4]=f[l+4];e[g+5]=f[l+5];e[g+6]=f[l+6];e[g+7]=f[l+7];e[g+8]=f[l+8];e[g+9]=f[l+9];e[g+10]=f[l+10];e[g+11]=f[l+11];e[g+12]=f[l+12];e[g+13]=f[l+13];e[g+14]=f[l+14];e[g+15]=f[l+15]}}else e=C.subarray(d>>2,d+64*b>>2);J.uniformMatrix4fv(X(a),
!!c,e)},z:function(a){a=N[a];J.useProgram(a);J.Se=a},g:function(a,b,c,d,e,f){J.vertexAttribPointer(a,b,c,!!d,e,f)},Va:function(a,b,c,d){J.viewport(a,b,c,d)},j:function(a,b,c,d){function e(n,w,z){for(n="number"==typeof n?n.toString():n||"";n.length<w;)n=z[0]+n;return n}function f(n,w){return e(n,w,"0")}function g(n,w){function z(ab){return 0>ab?-1:0<ab?1:0}var V;0===(V=z(n.getFullYear()-w.getFullYear()))&&0===(V=z(n.getMonth()-w.getMonth()))&&(V=z(n.getDate()-w.getDate()));return V}function l(n){switch(n.getDay()){case 0:return new Date(n.getFullYear()-
1,11,29);case 1:return n;case 2:return new Date(n.getFullYear(),0,3);case 3:return new Date(n.getFullYear(),0,2);case 4:return new Date(n.getFullYear(),0,1);case 5:return new Date(n.getFullYear()-1,11,31);case 6:return new Date(n.getFullYear()-1,11,30)}}function p(n){var w=n.xe;for(n=new Date((new Date(n.ye+1900,0,1)).getTime());0<w;){var z=n.getMonth(),V=(Pa(n.getFullYear())?zd:Ad)[z];if(w>V-n.getDate())w-=V-n.getDate()+1,n.setDate(1),11>z?n.setMonth(z+1):(n.setMonth(0),n.setFullYear(n.getFullYear()+
1));else{n.setDate(n.getDate()+w);break}}z=new Date(n.getFullYear()+1,0,4);w=l(new Date(n.getFullYear(),0,4));z=l(z);return 0>=g(w,n)?0>=g(z,n)?n.getFullYear()+1:n.getFullYear():n.getFullYear()-1}var q=A[d+40>>2];d={sf:A[d>>2],rf:A[d+4>>2],Ge:A[d+8>>2],Oe:A[d+12>>2],He:A[d+16>>2],ye:A[d+20>>2],qe:A[d+24>>2],xe:A[d+28>>2],Gf:A[d+32>>2],qf:A[d+36>>2],tf:q?r(q):""};c=r(c);q={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y",
"%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var u in q)c=c.replace(new RegExp(u,"g"),q[u]);var x="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),L="January February March April May June July August September October November December".split(" ");q={"%a":function(n){return x[n.qe].substring(0,
3)},"%A":function(n){return x[n.qe]},"%b":function(n){return L[n.He].substring(0,3)},"%B":function(n){return L[n.He]},"%C":function(n){return f((n.ye+1900)/100|0,2)},"%d":function(n){return f(n.Oe,2)},"%e":function(n){return e(n.Oe,2," ")},"%g":function(n){return p(n).toString().substring(2)},"%G":function(n){return p(n)},"%H":function(n){return f(n.Ge,2)},"%I":function(n){n=n.Ge;0==n?n=12:12<n&&(n-=12);return f(n,2)},"%j":function(n){for(var w=0,z=0;z<=n.He-1;w+=(Pa(n.ye+1900)?zd:Ad)[z++]);return f(n.Oe+
w,3)},"%m":function(n){return f(n.He+1,2)},"%M":function(n){return f(n.rf,2)},"%n":function(){return"\n"},"%p":function(n){return 0<=n.Ge&&12>n.Ge?"AM":"PM"},"%S":function(n){return f(n.sf,2)},"%t":function(){return"\t"},"%u":function(n){return n.qe||7},"%U":function(n){return f(Math.floor((n.xe+7-n.qe)/7),2)},"%V":function(n){var w=Math.floor((n.xe+7-(n.qe+6)%7)/7);2>=(n.qe+371-n.xe-2)%7&&w++;if(w)53==w&&(z=(n.qe+371-n.xe)%7,4==z||3==z&&Pa(n.ye)||(w=1));else{w=52;var z=(n.qe+7-n.xe-1)%7;(4==z||5==
z&&Pa(n.ye%400-1))&&w++}return f(w,2)},"%w":function(n){return n.qe},"%W":function(n){return f(Math.floor((n.xe+7-(n.qe+6)%7)/7),2)},"%y":function(n){return(n.ye+1900).toString().substring(2)},"%Y":function(n){return n.ye+1900},"%z":function(n){n=n.qf;var w=0<=n;n=Math.abs(n)/60;return(w?"+":"-")+String("0000"+(n/60*100+n%60)).slice(-4)},"%Z":function(n){return n.tf},"%%":function(){return"%"}};c=c.replace(/%%/g,"\x00\x00");for(u in q)c.includes(u)&&(c=c.replace(new RegExp(u,"g"),q[u](d)));c=c.replace(/\0\0/g,
"%");u=Bd(c);if(u.length>b)return 0;y.set(u,a);return u.length-1}};
(function(){function a(e){h.asm=e.exports;ja=h.asm._d;e=ja.buffer;h.HEAP8=y=new Int8Array(e);h.HEAP16=pa=new Int16Array(e);h.HEAP32=A=new Int32Array(e);h.HEAPU8=t=new Uint8Array(e);h.HEAPU16=qa=new Uint16Array(e);h.HEAPU32=B=new Uint32Array(e);h.HEAPF32=C=new Float32Array(e);h.HEAPF64=D=new Float64Array(e);ra=h.asm.ce;ta.unshift(h.asm.$d);ya--;h.monitorRunDependencies&&h.monitorRunDependencies(ya);0==ya&&(null!==za&&(clearInterval(za),za=null),Aa&&(e=Aa,Aa=null,e()))}function b(e){a(e.instance)}function c(e){return Ea().then(function(f){return WebAssembly.instantiate(f,
d)}).then(function(f){return f}).then(e,function(f){k("failed to asynchronously prepare wasm: "+f);m(f)})}var d={a:Fd};ya++;h.monitorRunDependencies&&h.monitorRunDependencies(ya);if(h.instantiateWasm)try{return h.instantiateWasm(d,a)}catch(e){return k("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return ia||"function"!=typeof WebAssembly.instantiateStreaming||Ba()||"function"!=typeof fetch?c(b):fetch(E,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,
d).then(b,function(f){k("wasm streaming compile failed: "+f);k("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();function F(){return(F=h.asm.ae).apply(null,arguments)}var Gd=h._main=function(){return(Gd=h._main=h.asm.be).apply(null,arguments)};function ic(){return(ic=h.asm.de).apply(null,arguments)}function jc(){return(jc=h.asm.ee).apply(null,arguments)}function Kc(){return(Kc=h.asm.fe).apply(null,arguments)}
h.dynCall_jiji=function(){return(h.dynCall_jiji=h.asm.ge).apply(null,arguments)};h.dynCall_ji=function(){return(h.dynCall_ji=h.asm.he).apply(null,arguments)};var Hd;Aa=function Id(){Hd||Jd();Hd||(Aa=Id)};function Kd(a=[]){var b=Gd;a.unshift(ca);var c=a.length,d=Kc(4*(c+1)),e=d>>2;a.forEach(g=>{var l=A,p=e++,q=oa(g)+1,u=Kc(q);na(g,y,u,q);l[p]=u});A[e]=0;try{var f=b(c,d);Cd(f)}catch(g){kb(g)}}
function Jd(){var a=ba;function b(){if(!Hd&&(Hd=!0,h.calledRun=!0,!ka)){Na(ta);Na(ua);if(h.onRuntimeInitialized)h.onRuntimeInitialized();Ld&&Kd(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();wa.unshift(c)}Na(wa)}}if(!(0<ya)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)xa();Na(sa);0<ya||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);
b()},1)):b())}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var Ld=!0;h.noInitialRun&&(Ld=!1);Jd();
