var h;h||(h=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},h),ca=[],da="./this.program",ea=(a,b)=>{throw b;},k="";"undefined"!=typeof document&&document.currentScript&&(k=document.currentScript.src);k=0!==k.indexOf("blob:")?k.substr(0,k.replace(/[?#].*/,"").lastIndexOf("/")+1):"";var fa=h.print||console.log.bind(console),l=h.printErr||console.error.bind(console);Object.assign(h,aa);aa=null;h.arguments&&(ca=h.arguments);h.thisProgram&&(da=h.thisProgram);
h.quit&&(ea=h.quit);var ha;h.wasmBinary&&(ha=h.wasmBinary);var noExitRuntime=h.noExitRuntime||!0;"object"!=typeof WebAssembly&&q("no native wasm support detected");var ia,ja=!1,ka,r,u,la,ma,w,y,B,C,na=[],oa=[],pa=[],qa=[],ra=[];function sa(){var a=h.preRun.shift();na.unshift(a)}var ta=0,ua=null,va=null;function q(a){if(h.onAbort)h.onAbort(a);a="Aborted("+a+")";l(a);ja=!0;ka=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}
function wa(a){return a.startsWith("data:application/octet-stream;base64,")}var xa;xa="index.wasm";if(!wa(xa)){var ya=xa;xa=h.locateFile?h.locateFile(ya,k):k+ya}function za(a){if(a==xa&&ha)return new Uint8Array(ha);throw"both async and sync fetching of the wasm failed";}
function Aa(a){return ha||"function"!=typeof fetch?Promise.resolve().then(()=>za(a)):fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>za(a))}function Ba(a,b,c){return Aa(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{l(`failed to asynchronously prepare wasm: ${d}`);q(d)})}
function Ca(a,b){var c=xa;ha||"function"!=typeof WebAssembly.instantiateStreaming||wa(c)||"function"!=typeof fetch?Ba(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){l(`wasm streaming compile failed: ${e}`);l("falling back to ArrayBuffer instantiation");return Ba(c,a,b)}))}
var Ga={5812992:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,5813139:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,5813373:a=>{"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.je||("undefined"!==typeof AudioContext?b.je=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.je=new webkitAudioContext),b.je&&
Da(b.je));return void 0===b.je?-1:0},5813866:()=>h.SDL2.je.sampleRate,5813934:(a,b,c,d)=>{function e(){}function f(m){void 0!==g.capture.ye&&(clearTimeout(g.capture.ye),g.capture.ye=void 0);g.capture.Fe=g.je.createMediaStreamSource(m);g.capture.le=g.je.createScriptProcessor(b,a,1);g.capture.le.onaudioprocess=function(p){void 0!==g&&void 0!==g.capture&&(p.outputBuffer.getChannelData(0).fill(0),g.capture.Ke=p.inputBuffer,Ea(c,[d]))};g.capture.Fe.connect(g.capture.le);g.capture.le.connect(g.je.destination);
g.capture.stream=m}var g=h.SDL2;g.capture.Ge=g.je.createBuffer(a,b,g.je.sampleRate);g.capture.Ge.getChannelData(0).fill(0);g.capture.ye=setTimeout(function(){g.capture.Ke=g.capture.Ge;Ea(c,[d])},b/g.je.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},5815586:(a,b,c,d)=>{var e=h.SDL2;e.audio.le=
e.je.createScriptProcessor(b,0,a);e.audio.le.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(e.audio.Re=f.outputBuffer,Ea(c,[d]))};e.audio.le.connect(e.je.destination)},5815996:(a,b)=>{for(var c=h.SDL2,d=c.capture.Ke.numberOfChannels,e=0;e<d;++e){var f=c.capture.Ke.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var g=0;g<b;++g)Fa(a+4*g,f[g]);else for(g=0;g<b;++g)Fa(a+4*(g*d+e),
f[g])}},5816601:(a,b)=>{for(var c=h.SDL2,d=c.audio.Re.numberOfChannels,e=0;e<d;++e){var f=c.audio.Re.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=B[a+(g*d+e<<2)>>2]}},5817081:a=>{var b=h.SDL2;if(a){void 0!==b.capture.ye&&clearTimeout(b.capture.ye);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);
b.capture.stream=void 0}void 0!==b.capture.le&&(b.capture.le.onaudioprocess=function(){},b.capture.le.disconnect(),b.capture.le=void 0);void 0!==b.capture.Fe&&(b.capture.Fe.disconnect(),b.capture.Fe=void 0);void 0!==b.capture.Ge&&(b.capture.Ge=void 0);b.capture=void 0}else void 0!=b.audio.le&&(b.audio.le.disconnect(),b.audio.le=void 0),b.audio=void 0;void 0!==b.je&&void 0===b.audio&&void 0===b.capture&&(b.je.close(),b.je=void 0)},5818253:(a,b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;d.Ye!==h.canvas&&
(d.pe=h.createContext(h.canvas,!1,!0),d.Ye=h.canvas);if(d.w!==a||d.h!==b||d.hf!==d.pe)d.image=d.pe.createImageData(a,b),d.w=a,d.h=b,d.hf=d.pe;a=d.image.data;b=c>>2;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=w[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.af!==a&&(d.$e=new Int32Array(a.buffer),d.bf=new Uint8Array(a.buffer),d.af=a),a=d.$e,c=a.length,a.set(w.subarray(b,b+c)),a=d.bf,b=3,e=b+4*c,0==c%8)for(;b<
e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.pe.putImageData(d.image,0,0)},5819722:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e>>=2;var m=0,p;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(p=b.length;m<p;){var t=w[e];b[m]=t&255;b[m+1]=t>>8&255;b[m+2]=t>>
16&255;b[m+3]=t>>24&255;e++;m+=4}else b=new Int32Array(b.buffer),p=b.length,b.set(w.subarray(e,e+p));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=D(c.length+1);E(c,u,d,c.length+1);return d},5820711:a=>{h.canvas&&(h.canvas.style.cursor=a?F(u,a):"")},5820794:()=>{h.canvas&&(h.canvas.style.cursor="none")},5820863:()=>window.innerWidth,5820893:()=>window.innerHeight};
function Ha(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Ia=(a,b,c)=>{a.addEventListener(b,c,{once:!0})},Da=a=>{var b;b||(b=[document,document.getElementById("canvas")]);["keydown","mousedown","touchstart"].forEach(c=>{b.forEach(d=>{d&&Ia(d,c,()=>{"suspended"===a.state&&a.resume()})})})},Ja=a=>{for(;0<a.length;)a.shift()(h)},Ka=[],La,G=a=>{var b=Ka[a];b||(a>=Ka.length&&(Ka.length=a+1),Ka[a]=b=La.get(a));return b},Ea=(a,b)=>{if("vi".includes("j")){var c=h.dynCall_vi;b&&b.length?c.apply(null,[a].concat(b)):c.call(null,a)}else G(a).apply(null,b)};
function Fa(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":r[a>>0]=b;break;case "i8":r[a>>0]=b;break;case "i16":la[a>>1]=b;break;case "i32":w[a>>2]=b;break;case "i64":q("to do setValue(i64) use WASM_BIGINT");case "float":B[a>>2]=b;break;case "double":C[a>>3]=b;break;case "*":y[a>>2]=b;break;default:q(`invalid type for setValue: ${c}`)}}
var Ma="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,F=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ma)return Ma.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
Na=a=>0===a%4&&(0!==a%100||0===a%400),Oa=[0,31,60,91,121,152,182,213,244,274,305,335],Pa=[0,31,59,90,120,151,181,212,243,273,304,334],Qa=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},E=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var m=a.charCodeAt(++f);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;
b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e},H=a=>{var b=Qa(a)+1,c=D(b);c&&E(a,u,c,b);return c},$a=(a,b)=>{Ra=a;Sa=b;if(Ta)if(Ua||(Ua=!0),0==a)I=function(){var d=Math.max(0,Wa+b-Xa())|0;setTimeout(Ya,d)};else if(1==a)I=function(){Za(Ya)};else if(2==a){if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===
d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);postMessage("setimmediate","*")}}I=function(){setImmediate(Ya)}}},Xa;Xa=()=>performance.now();
var ib=(a,b,c,d,e)=>{!Ta||q("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");Ta=a;ab=d;var f=bb;Ua=!1;Ya=function(){if(!ja)if(0<cb.length){var g=cb.shift();g.zf(g.vf);if(db){var m=db,p=0==m%1?m-1:Math.floor(m);db=g.xf?p:(8*m+(p+.5))/9}h.setStatus&&(g=h.statusMessage||"Please wait...",m=db,p=eb.yf,m?m<p?h.setStatus(g+" ("+(p-m)+"/"+p+")"):h.setStatus(g):h.setStatus(""));
f<bb||setTimeout(Ya,0)}else if(!(f<bb))if(fb=fb+1|0,1==Ra&&1<Sa&&0!=fb%Sa)I();else{0==Ra&&(Wa=Xa());if(!(ja||h.preMainLoop&&!1===h.preMainLoop())){if(!ja)try{if(a(),!noExitRuntime)try{ka=g=ka,gb(g)}catch(t){hb(t)}}catch(t){hb(t)}h.postMainLoop&&h.postMainLoop()}f<bb||("object"==typeof SDL&&SDL.audio&&SDL.audio.mf&&SDL.audio.mf(),I())}};e||(b&&0<b?$a(0,1E3/b):$a(1,1),I());if(c)throw"unwind";},hb=a=>{a instanceof Ha||"unwind"==a||ea(1,a)},gb=a=>{ka=a;if(!noExitRuntime){if(h.onExit)h.onExit(a);ja=!0}ea(a,
new Ha(a))},jb=a=>{ka=a;gb(a)},Ua=!1,I=null,bb=0,Ta=null,ab=0,Ra=0,Sa=0,fb=0,cb=[],eb={},Wa,Ya,db,kb=!1,lb=!1,mb=[];
function nb(){function a(){lb=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}if(!ob){ob=!0;var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),
b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",c=>{!lb&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function pb(a,b,c,d){if(b&&h.pe&&a==h.canvas)return h.pe;var e;if(b){var f={antialias:!1,alpha:!1,Te:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!=typeof qb&&(e=rb(a,f)))var m=J[e].se}else m=a.getContext("2d");if(!m)return null;c&&(b||"undefined"==typeof K||q("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),h.pe=m,b&&sb(e),h.tf=b,mb.forEach(p=>p()),nb());return m}var tb=!1,ub=void 0,vb=void 0;
function wb(a,b){function c(){kb=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=xb,ub&&d.requestPointerLock(),kb=!0,vb?("undefined"!=typeof SDL&&(w[SDL.screen>>2]=y[SDL.screen>>2]|8388608),yb(h.canvas),zb()):yb(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),vb?("undefined"!=typeof SDL&&(w[SDL.screen>>2]=y[SDL.screen>>2]&
-8388609),yb(h.canvas),zb()):yb(d));if(h.onFullScreen)h.onFullScreen(kb);if(h.onFullscreen)h.onFullscreen(kb)}ub=a;vb=b;"undefined"==typeof ub&&(ub=!0);"undefined"==typeof vb&&(vb=!1);var d=h.canvas;tb||(tb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}
function xb(){if(!kb)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var Ab=0;function Za(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Ab)Ab=b+1E3/60;else for(;b+2>=Ab;)Ab+=1E3/60;setTimeout(a,Math.max(Ab-b,0))}}var Bb=[];function zb(){var a=h.canvas;Bb.forEach(b=>b(a.width,a.height))}
function yb(a,b,c){b&&c?(a.uf=b,a.gf=c):(b=a.uf,c=a.gf);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}vb?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var ob,L=12288,Cb=!1,Db=0,Eb=0,Fb=0,M={alpha:!1,depth:!1,stencil:!1,antialias:!1},Gb={},Hb,Ib=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},Jb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Kb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Lb=1,Mb=[],N=[],Nb=[],Ob=[],Pb=[],O=[],Qb=[],J=[],P=[],Rb={},Sb=4;function Q(a){Tb||(Tb=a)}
var Ub=a=>{for(var b=Lb++,c=a.length;c<b;c++)a[c]=null;return b},rb=(a,b)=>{a.Be||(a.Be=a.getContext,a.getContext=function(d,e){e=a.Be(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Vb(c,b):0},Vb=(a,b)=>{var c=Ub(J),d={handle:c,attributes:b,version:b.Te,se:a};a.canvas&&(a.canvas.we=d);J[c]=d;("undefined"==typeof b.df||b.df)&&Wb(d);return c},sb=a=>{Xb=J[a];h.pe=K=Xb&&Xb.se},Wb=a=>{a||(a=Xb);if(!a.jf){a.jf=!0;var b=a.se;Ib(b);Jb(b);Kb(b);b.re=
b.getExtension("EXT_disjoint_timer_query");b.Cf=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},qb={},Tb,Xb,Yb=[],Zb=(a,b)=>{Yb.length=0;for(var c;c=u[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;Yb.push(112==c?y[b>>2]:105==c?w[b>>2]:C[b>>3]);b+=d?8:4}return Yb},bc=a=>{var b=$b();a=a();ac(b);return a},cc=0;function dc(){for(var a=R.length-1;0<=a;--a)ec(a);R=[];S=[]}var S=[];
function fc(a,b,c){function d(g,m){if(g.length!=m.length)return!1;for(var p in g)if(g[p]!=m[p])return!1;return!0}for(var e in S){var f=S[e];if(f.Me==a&&d(f.Pe,c))return}S.push({Me:a,Ve:b,Pe:c});S.sort((g,m)=>g.Ve<m.Ve)}function gc(a){for(var b=0;b<S.length;++b)S[b].Me==a&&(S.splice(b,1),--b)}function hc(){return navigator.userActivation?navigator.userActivation.isActive:cc&&ic.xe}function jc(){if(hc())for(var a=0;a<S.length;++a){var b=S[a];S.splice(a,1);--a;b.Me.apply(null,b.Pe)}}var R=[];
function ec(a){var b=R[a];b.target.removeEventListener(b.ke,b.ef,b.me);R.splice(a,1)}function U(a){function b(d){++cc;ic=a;jc();a.oe(d);jc();--cc}if(!a.target)return-4;if(a.ne)a.ef=b,a.target.addEventListener(a.ke,b,a.me),R.push(a),kc||(qa.push(dc),kc=!0);else for(var c=0;c<R.length;++c)R[c].target==a.target&&R[c].ke==a.ke&&ec(c--);return 0}function lc(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}
function mc(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}
var nc={},kc,ic,oc,pc,qc,rc,sc,tc,uc,vc,wc,xc,yc,zc,Ac={},Bc=[0,document,window],V=a=>{a=2<a?a?F(u,a):"":a;return Bc[a]||document.querySelector(a)},Dc=a=>{var b=Qa(a)+1,c=Cc(b);E(a,u,c,b);return c},Ec=a=>bc(()=>{var b=Cc(8),c=b+4,d=Dc(a.id);if(d=V(d))w[b>>2]=d.width,w[c>>2]=d.height;return[w[b>>2],w[c>>2]]}),Fc=(a,b,c)=>{a=V(a);if(!a)return-4;a.width=b;a.height=c;return 0},Gc=(a,b,c)=>{a.wf?bc(()=>{var d=Dc(a.id);Fc(d,b,c)}):(a.width=b,a.height=c)},Hc=a=>{function b(){document.fullscreenElement||
document.webkitFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),Gc(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=m,p||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=p,a.style.paddingLeft=t,a.style.paddingRight=v,a.style.paddingTop=A,a.style.paddingBottom=ba,a.style.marginLeft=n,a.style.marginRight=x,a.style.marginTop=z,a.style.marginBottom=T,document.body.style.margin=
Va,document.documentElement.style.overflow=Wd,document.body.scroll=Xd,a.style.te=Yd,a.we&&a.we.se.viewport(0,0,d,e),Ac.Ae&&G(Ac.Ae)(37,0,Ac.Qe))}var c=Ec(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,m=a.style.backgroundColor,p=document.body.style.backgroundColor,t=a.style.paddingLeft,v=a.style.paddingRight,A=a.style.paddingTop,ba=a.style.paddingBottom,n=a.style.marginLeft,x=a.style.marginRight,z=a.style.marginTop,T=a.style.marginBottom,Va=document.body.style.margin,Wd=document.documentElement.style.overflow,
Xd=document.body.scroll,Yd=a.style.te;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)},Ic=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},Jc=a=>0>Bc.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},Kc=(a,b)=>{if(0!=b.Le||0!=b.Je){Hc(a);var c=b.nf?innerWidth:screen.width,d=b.nf?innerHeight:screen.height,e=Jc(a),f=e.width;e=e.height;var g=Ec(a),m=g[0];g=g[1];3==b.Le?(Ic(a,(d-e)/2,(c-f)/
2),c=f,d=e):2==b.Le&&(c*g<m*d?(f=g*c/m,Ic(a,(d-f)/2,0),d=f):(f=m*d/g,Ic(a,0,(c-f)/2),c=f));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.ff&&(a.style.te="optimizeSpeed",a.style.te="-moz-crisp-edges",a.style.te="-o-crisp-edges",a.style.te="-webkit-optimize-contrast",a.style.te="optimize-contrast",a.style.te="crisp-edges",a.style.te="pixelated");f=2==b.Je?devicePixelRatio:
1;0!=b.Je&&(c=c*f|0,d=d*f|0,Gc(a,c,d),a.we&&a.we.se.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return mc()?-3:-1;Ac=b;b.Ae&&G(b.Ae)(37,0,b.Qe);return 0},Lc=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0},Mc=(a,b)=>{C[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)C[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)C[a+
8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)w[a+4*c+1040>>2]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];w[a+1296>>2]=b.connected;w[a+1300>>2]=b.index;w[a+8>>2]=b.axes.length;w[a+12>>2]=b.buttons.length;E(b.id,u,a+1304,64);E(b.mapping,u,a+1368,64)};function Nc(a){K.activeTexture(a)}
var Oc=(a,b)=>{K.attachShader(N[a],O[b])},Pc=(a,b)=>{K.bindBuffer(a,Mb[b])},Qc=(a,b)=>{K.bindTexture(a,Pb[b])},Rc=(a,b,c,d)=>{K.bufferData(a,c?u.subarray(c,c+b):b,d)};function Sc(a){K.clear(a)}function Tc(a,b,c,d){K.clearColor(a,b,c,d)}
var Uc=a=>{K.compileShader(O[a])},Vc=()=>{var a=Ub(N),b=K.createProgram();b.name=a;b.Ee=b.Ce=b.De=0;b.Oe=1;N[a]=b;return a},Wc=a=>{var b=Ub(O);O[b]=K.createShader(a);return b},Xc=a=>{if(a){var b=N[a];b?(K.deleteProgram(b),b.name=0,N[a]=null):Q(1281)}},Yc=a=>{K.disableVertexAttribArray(a)},Zc=[],$c=(a,b,c,d)=>{K.drawElements(a,b,c,d)};function ad(a){K.enable(a)}
var bd=a=>{K.enableVertexAttribArray(a)},cd=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=K[c](),g=f&&Ub(d);f?(f.name=g,d[g]=f):Q(1282);w[b+4*e>>2]=g}},dd=(a,b)=>{cd(a,b,"createBuffer",Mb)},ed=(a,b)=>{cd(a,b,"createTexture",Pb)},fd=(a,b,c,d,e,f,g,m)=>{b=N[b];if(a=K[a](b,c))d=m&&E(a.name,u,m,d),e&&(w[e>>2]=d),f&&(w[f>>2]=a.size),g&&(w[g>>2]=a.type)},gd=(a,b)=>K.getAttribLocation(N[a],b?F(u,b):""),hd=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&Q(1280);return;case 36345:d=
0;break;case 34466:var e=K.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=K.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":Q(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:Q(1280);return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:w[b+
4*a>>2]=e[a];break;case 2:B[b+4*a>>2]=e[a];break;case 4:r[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){Q(1280);l("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:Q(1280);l("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:c=d;y[b>>2]=c;y[b+4>>2]=(c-y[b>>2])/4294967296;break;case 0:w[b>>2]=d;break;case 2:B[b>>2]=d;break;case 4:r[b>>
0]=d?1:0}}else Q(1281)},jd=(a,b,c,d)=>{a=K.getProgramInfoLog(N[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,u,d,b):0;c&&(w[c>>2]=b)},kd=(a,b,c)=>{if(c)if(a>=Lb)Q(1281);else if(a=N[a],35716==b)a=K.getProgramInfoLog(a),null===a&&(a="(unknown error)"),w[c>>2]=a.length+1;else if(35719==b){if(!a.Ee)for(b=0;b<K.getProgramParameter(a,35718);++b)a.Ee=Math.max(a.Ee,K.getActiveUniform(a,b).name.length+1);w[c>>2]=a.Ee}else if(35722==b){if(!a.Ce)for(b=0;b<K.getProgramParameter(a,35721);++b)a.Ce=Math.max(a.Ce,
K.getActiveAttrib(a,b).name.length+1);w[c>>2]=a.Ce}else if(35381==b){if(!a.De)for(b=0;b<K.getProgramParameter(a,35382);++b)a.De=Math.max(a.De,K.getActiveUniformBlockName(a,b).length+1);w[c>>2]=a.De}else w[c>>2]=K.getProgramParameter(a,b);else Q(1281)},ld=(a,b,c)=>{if(c){a=K.re.getQueryObjectEXT(P[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;y[c>>2]=d;y[c+4>>2]=(d-y[c>>2])/4294967296}else Q(1281)},md=(a,b,c)=>{if(c){a=K.re.getQueryObjectEXT(P[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;w[c>>2]=d}else Q(1281)},
nd=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),od=a=>{var b=a.ze,c=a.Xe,d;if(!b)for(a.ze=b={},a.We={},d=0;d<K.getProgramParameter(a,35718);++d){var e=K.getActiveUniform(a,d);var f=e.name;e=e.size;var g=nd(f);g=0<g?f.slice(0,g):f;var m=a.Oe;a.Oe+=e;c[g]=[e,m];for(f=0;f<e;++f)b[m]=f,a.We[m++]=g}},pd=(a,b)=>{b=b?F(u,b):"";if(a=N[a]){od(a);var c=a.ze,d=0,e=b,f=nd(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.Xe[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||K.getUniformLocation(a,b)))return d}else Q(1281);
return-1},W=a=>{var b=K.Ze;if(b){var c=b.ze[a];"number"==typeof c&&(b.ze[a]=c=K.getUniformLocation(b,b.We[a]+(0<c?"["+c+"]":"")));return c}Q(1282)},qd=(a,b,c,d)=>{if(c)if(a=N[a],od(a),a=K.getUniform(a,W(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:w[c>>2]=a;break;case 2:B[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:w[c+4*b>>2]=a[b];break;case 2:B[c+4*b>>2]=a[b]}else Q(1281)},rd=(a,b,c,d)=>{if(c)if(a=K.getVertexAttrib(a,b),34975==b)w[c>>2]=a&&a.name;else if("number"==typeof a||
"boolean"==typeof a)switch(d){case 0:w[c>>2]=a;break;case 2:B[c>>2]=a;break;case 5:w[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:w[c+4*b>>2]=a[b];break;case 2:B[c+4*b>>2]=a[b];break;case 5:w[c+4*b>>2]=Math.fround(a[b])}else Q(1281)},sd=a=>{a=N[a];K.linkProgram(a);a.ze=0;a.Xe={}},td=(a,b)=>{3317==a&&(Sb=b);K.pixelStorei(a,b)},ud=(a,b,c,d,e)=>{a-=5120;a=1==a?u:4==a?w:6==a?B:5==a||28922==a?y:ma;var f=31-Math.clz32(a.BYTES_PER_ELEMENT),g=Sb;return a.subarray(e>>f,e+d*(c*({5:3,6:4,
8:2,29502:3,29504:4}[b-6402]||1)*(1<<f)+g-1&-g)>>f)},vd=(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var g=d?w[d+4*f>>2]:-1,m=w[c+4*f>>2];g=m?F(u,m,0>g?void 0:g):"";e+=g}K.shaderSource(O[a],e)},wd=(a,b,c,d,e,f,g,m,p)=>{K.texImage2D(a,b,c,d,e,f,g,m,p?ud(m,g,d,e,p):null)};function xd(a,b,c){K.texParameteri(a,b,c)}
var yd=(a,b)=>{K.uniform1f(W(a),b)},X=[],zd=(a,b)=>{K.uniform1i(W(a),b)},Ad=[],Bd=(a,b,c,d)=>{K.uniform3f(W(a),b,c,d)},Cd=(a,b,c,d)=>{if(18>=b){var e=X[16*b-1],f=B;d>>=2;for(var g=0;g<16*b;g+=16){var m=d+g;e[g]=f[m];e[g+1]=f[m+1];e[g+2]=f[m+2];e[g+3]=f[m+3];e[g+4]=f[m+4];e[g+5]=f[m+5];e[g+6]=f[m+6];e[g+7]=f[m+7];e[g+8]=f[m+8];e[g+9]=f[m+9];e[g+10]=f[m+10];e[g+11]=f[m+11];e[g+12]=f[m+12];e[g+13]=f[m+13];e[g+14]=f[m+14];e[g+15]=f[m+15]}}else e=B.subarray(d>>2,d+64*b>>2);K.uniformMatrix4fv(W(a),!!c,
e)},Dd=a=>{a=N[a];K.useProgram(a);K.Ze=a},Ed=(a,b,c,d,e,f)=>{K.vertexAttribPointer(a,b,c,!!d,e,f)};function Fd(a,b,c,d){K.viewport(a,b,c,d)}
var Gd=(a,b)=>{if(!mc())return-1;a=V(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?hc()?Kc(a,b):b.cf?(fc(Kc,1,[a,b]),1):-2:-3:-4},Hd=(a,b)=>{var c={target:V(2),ke:"beforeunload",ne:b,oe:(d=event)=>{var e=G(b)(28,0,a);e&&(e=e?F(u,e):"");if(e)return d.preventDefault(),d.returnValue=e},me:!0};return U(c)},Id=(a,b,c,d,e,f)=>{pc||(pc=D(256));a={target:V(a),ke:f,ne:d,oe:(g=event)=>{var m=g.target.id?g.target.id:"",p=pc;E(lc(g.target),u,p+0,128);E(m,u,p+128,128);G(d)(e,p,b)&&g.preventDefault()},
me:c};return U(a)},Jd=(a,b,c,d,e)=>{rc||(rc=D(280));return U({target:a,ke:e,ne:d,oe:(f=event)=>{var g=rc,m=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,p=!!m;w[g>>2]=p;w[g+4>>2]=mc();var t=p?m:qc,v=t&&t.id?t.id:"";E(lc(t),u,g+8,128);E(v,u,g+136,128);w[g+264>>2]=t?t.clientWidth:0;w[g+268>>2]=t?t.clientHeight:0;w[g+272>>2]=screen.width;w[g+276>>2]=screen.height;p&&(qc=m);G(d)(19,g,b)&&f.preventDefault()},me:c})},Kd=(a,b,c,
d,e)=>{sc||(sc=D(1432));b={target:V(2),xe:!0,ke:e,ne:c,oe:(f=event)=>{var g=sc;Mc(g,f.gamepad);G(c)(d,g,a)&&f.preventDefault()},me:b};return U(b)},Ld=(a,b,c,d,e,f)=>{tc||(tc=D(176));a={target:V(a),xe:!0,ke:f,ne:d,oe:g=>{var m=tc;C[m>>3]=g.timeStamp;var p=m>>2;w[p+2]=g.location;w[p+3]=g.ctrlKey;w[p+4]=g.shiftKey;w[p+5]=g.altKey;w[p+6]=g.metaKey;w[p+7]=g.repeat;w[p+8]=g.charCode;w[p+9]=g.keyCode;w[p+10]=g.which;E(g.key||"",u,m+44,32);E(g.code||"",u,m+76,32);E(g.char||"",u,m+108,32);E(g.locale||"",u,
m+140,32);G(d)(e,m,b)&&g.preventDefault()},me:c};return U(a)},Md=(a,b,c)=>{C[a>>3]=b.timeStamp;a>>=2;w[a+2]=b.screenX;w[a+3]=b.screenY;w[a+4]=b.clientX;w[a+5]=b.clientY;w[a+6]=b.ctrlKey;w[a+7]=b.shiftKey;w[a+8]=b.altKey;w[a+9]=b.metaKey;la[2*a+20]=b.button;la[2*a+21]=b.buttons;w[a+11]=b.movementX;w[a+12]=b.movementY;c=Jc(c);w[a+13]=b.clientX-c.left;w[a+14]=b.clientY-c.top},Nd=(a,b,c,d,e,f)=>{uc||(uc=D(72));a=V(a);return U({target:a,xe:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,ke:f,ne:d,oe:(g=
event)=>{Md(uc,g,a);G(d)(e,uc,b)&&g.preventDefault()},me:c})},Od=(a,b,c,d,e)=>{vc||(vc=D(260));return U({target:a,ke:e,ne:d,oe:(f=event)=>{var g=vc,m=document.pointerLockElement||document.Be||document.lf||document.kf;w[g>>2]=!!m;var p=m&&m.id?m.id:"";E(lc(m),u,g+4,128);E(p,u,g+132,128);G(d)(20,g,b)&&f.preventDefault()},me:c})},Pd=(a,b,c,d)=>{wc||(wc=D(36));a=V(a);return U({target:a,ke:"resize",ne:d,oe:(e=event)=>{if(e.target==a){var f=document.body;if(f){var g=wc;w[g>>2]=e.detail;w[g+4>>2]=f.clientWidth;
w[g+8>>2]=f.clientHeight;w[g+12>>2]=innerWidth;w[g+16>>2]=innerHeight;w[g+20>>2]=outerWidth;w[g+24>>2]=outerHeight;w[g+28>>2]=pageXOffset;w[g+32>>2]=pageYOffset;G(d)(10,g,b)&&e.preventDefault()}}},me:c})},Qd=(a,b,c,d,e,f)=>{xc||(xc=D(1696));a=V(a);return U({target:a,xe:"touchstart"==f||"touchend"==f,ke:f,ne:d,oe:g=>{for(var m,p={},t=g.touches,v=0;v<t.length;++v)m=t[v],m.Se=m.Ue=0,p[m.identifier]=m;for(v=0;v<g.changedTouches.length;++v)m=g.changedTouches[v],m.Se=1,p[m.identifier]=m;for(v=0;v<g.targetTouches.length;++v)p[g.targetTouches[v].identifier].Ue=
1;t=xc;C[t>>3]=g.timeStamp;var A=t>>2;w[A+3]=g.ctrlKey;w[A+4]=g.shiftKey;w[A+5]=g.altKey;w[A+6]=g.metaKey;A+=7;var ba=Jc(a),n=0;for(v in p)if(m=p[v],w[A]=m.identifier,w[A+1]=m.screenX,w[A+2]=m.screenY,w[A+3]=m.clientX,w[A+4]=m.clientY,w[A+5]=m.pageX,w[A+6]=m.pageY,w[A+7]=m.Se,w[A+8]=m.Ue,w[A+9]=m.clientX-ba.left,w[A+10]=m.clientY-ba.top,A+=13,31<++n)break;w[t+8>>2]=n;G(d)(e,t,b)&&g.preventDefault()},me:c})},Rd=(a,b,c)=>{var d=Bc[1];yc||(yc=D(8));return U({target:d,ke:"visibilitychange",ne:c,oe:(e=
event)=>{var f=yc,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);w[f>>2]=document.hidden;w[f+4>>2]=g;G(c)(21,f,a)&&e.preventDefault()},me:b})},Sd=(a,b,c,d)=>{zc||(zc=D(104));return U({target:a,xe:!0,ke:"wheel",ne:d,oe:(e=event)=>{var f=zc;Md(f,e,a);C[f+72>>3]=e.deltaX;C[f+80>>3]=e.deltaY;C[f+88>>3]=e.deltaZ;w[f+96>>2]=e.deltaMode;G(d)(9,f,b)&&e.preventDefault()},me:c})},Td={},Vd=()=>{if(!Ud){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",
LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Td)void 0===Td[b]?delete a[b]:a[b]=Td[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Ud=c}return Ud},Ud,Zd=[null,[],[]],$d=[31,29,31,30,31,30,31,31,30,31,30,31],ae=[31,28,31,30,31,30,31,31,30,31,30,31];function be(a){var b=Array(Qa(a)+1);E(a,b,0,b.length);return b}h.requestFullscreen=(a,b)=>wb(a,b);h.requestAnimationFrame=a=>Za(a);
h.setCanvasSize=(a,b,c)=>{yb(h.canvas,a,b);c||zb()};h.pauseMainLoop=()=>{I=null;bb++};h.resumeMainLoop=()=>{bb++;var a=Ra,b=Sa,c=Ta;Ta=null;ib(c,0,!1,ab,!0);$a(a,b);I()};h.getUserMedia=()=>{window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};h.createContext=(a,b,c,d)=>pb(a,b,c,d);for(var K,Y=0;32>Y;++Y)Zc.push(Array(Y));var ce=new Float32Array(288);for(Y=0;288>Y;++Y)X[Y]=ce.subarray(0,Y+1);var de=new Int32Array(288);
for(Y=0;288>Y;++Y)Ad[Y]=de.subarray(0,Y+1);
var ee={fa:function(){return 0},cb:function(){return 0},db:function(){},eb:()=>!0,Wa:function(a,b,c){a=new Date(1E3*(b+2097152>>>0<4194305-!!a?(a>>>0)+4294967296*b:NaN));w[c>>2]=a.getSeconds();w[c+4>>2]=a.getMinutes();w[c+8>>2]=a.getHours();w[c+12>>2]=a.getDate();w[c+16>>2]=a.getMonth();w[c+20>>2]=a.getFullYear()-1900;w[c+24>>2]=a.getDay();w[c+28>>2]=(Na(a.getFullYear())?Oa:Pa)[a.getMonth()]+a.getDate()-1|0;w[c+36>>2]=-(60*a.getTimezoneOffset());b=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();
var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();w[c+32>>2]=(b!=d&&a.getTimezoneOffset()==Math.min(d,b))|0},Za:(a,b,c)=>{function d(p){return(p=p.toTimeString().match(/\(([A-Za-z ]+)\)$/))?p[1]:"GMT"}var e=(new Date).getFullYear(),f=new Date(e,0,1),g=new Date(e,6,1);e=f.getTimezoneOffset();var m=g.getTimezoneOffset();y[a>>2]=60*Math.max(e,m);w[b>>2]=Number(e!=m);a=d(f);b=d(g);a=H(a);b=H(b);m<e?(y[c>>2]=a,y[c+4>>2]=b):(y[c>>2]=b,y[c+4>>2]=a)},Ha:a=>{if(12448==a)return L=12288,1;L=12300;return 0},
Ka:(a,b,c,d,e)=>{if(62E3!=a)L=12296,c=0;else{if(b)for(;;){a=w[b>>2];if(12321==a)M.alpha=0<w[b+4>>2];else if(12325==a)M.depth=0<w[b+4>>2];else if(12326==a)M.stencil=0<w[b+4>>2];else if(12337==a)a=w[b+4>>2],M.antialias=0<a;else if(12338==a)a=w[b+4>>2],M.antialias=1==a;else if(12544==a)M.Af=12547!=w[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(w[e>>2]=1),c&&0<d&&(w[c>>2]=62002),L=12288,c=1):(L=12300,c=0)}return c},xa:(a,b,c,d)=>{if(62E3!=a)return L=12296,0;for(a=1;;){b=w[d>>2];if(12440==b)a=w[d+
4>>2];else if(12344==b)break;else return L=12292,0;d+=8}if(2!=a)return L=12293,0;M.Te=a-1;M.Bf=0;Hb=rb(h.canvas,M);if(0!=Hb)return L=12288,sb(Hb),h.tf=!0,mb.forEach(function(e){e()}),sb(null),62004;L=12297;return 0},za:(a,b)=>{if(62E3!=a)return L=12296,0;if(62002!=b)return L=12293,0;L=12288;return 62006},ya:(a,b)=>{if(62E3!=a)return L=12296,0;if(62004!=b)return L=12294,0;a=Hb;Xb===J[a]&&(Xb=null);if("object"==typeof nc)for(var c=J[a].se.canvas,d=0;d<R.length;++d)R[d].target!=c||ec(d--);J[a]&&J[a].se.canvas&&
(J[a].se.canvas.we=void 0);J[a]=null;L=12288;Db==b&&(Db=0);return 1},Ba:(a,b)=>{if(62E3!=a)return L=12296,0;if(62006!=b)return L=12301,1;Eb==b&&(Eb=0);Fb==b&&(Fb=0);L=12288;return 1},La:(a,b,c,d)=>{if(62E3!=a)return L=12296,0;if(62002!=b)return L=12293,0;if(!d)return L=12300,0;L=12288;switch(c){case 12320:return w[d>>2]=M.alpha?32:24,1;case 12321:return w[d>>2]=M.alpha?8:0,1;case 12322:return w[d>>2]=8,1;case 12323:return w[d>>2]=8,1;case 12324:return w[d>>2]=8,1;case 12325:return w[d>>2]=M.depth?
24:0,1;case 12326:return w[d>>2]=M.stencil?8:0,1;case 12327:return w[d>>2]=12344,1;case 12328:return w[d>>2]=62002,1;case 12329:return w[d>>2]=0,1;case 12330:return w[d>>2]=4096,1;case 12331:return w[d>>2]=16777216,1;case 12332:return w[d>>2]=4096,1;case 12333:return w[d>>2]=0,1;case 12334:return w[d>>2]=0,1;case 12335:return w[d>>2]=12344,1;case 12337:return w[d>>2]=M.antialias?4:0,1;case 12338:return w[d>>2]=M.antialias?1:0,1;case 12339:return w[d>>2]=4,1;case 12340:return w[d>>2]=12344,1;case 12341:case 12342:case 12343:return w[d>>
2]=-1,1;case 12345:case 12346:return w[d>>2]=0,1;case 12347:return w[d>>2]=0,1;case 12348:return w[d>>2]=1;case 12349:case 12350:return w[d>>2]=0,1;case 12351:return w[d>>2]=12430,1;case 12352:return w[d>>2]=4,1;case 12354:return w[d>>2]=0,1;default:return L=12292,0}},X:()=>{L=12288;return 62E3},wa:()=>L,Ia:(a,b,c)=>{if(62E3!=a)return L=12296,0;b&&(w[b>>2]=1);c&&(w[c>>2]=4);Cb=!0;L=12288;return 1},Ca:(a,b,c,d)=>{if(62E3!=a)return L=12296,0;if(0!=d&&62004!=d)return L=12294,0;if(0!=c&&62006!=c||0!=
b&&62006!=b)return L=12301,0;sb(d?Hb:null);Db=d;Fb=b;Eb=c;L=12288;return 1},va:(a,b)=>{if(62E3!=a)return L=12296,0;L=12288;if(Gb[b])return Gb[b];switch(b){case 12371:a=H("Emscripten");break;case 12372:a=H("1.4 Emscripten EGL");break;case 12373:a=H("");break;case 12429:a=H("OpenGL_ES");break;default:return L=12300,0}return Gb[b]=a},Da:()=>{if(Cb)if(h.pe)if(h.pe.isContextLost())L=12302;else return L=12288,1;else L=12290;else L=12289;return 0},Ea:(a,b)=>{if(62E3!=a)return L=12296,0;0==b?$a(0,0):$a(1,
b);L=12288;return 1},Ja:a=>{if(62E3!=a)return L=12296,0;Fb=Eb=Db=0;Cb=!1;L=12288;return 1},Ga:()=>{L=12288;return 1},Fa:()=>{L=12288;return 1},Oa:(a,b,c)=>{b=Zb(b,c);return Ga[a].apply(null,b)},b:(a,b,c)=>{b=Zb(b,c);return Ga[a].apply(null,b)},ga:()=>Date.now(),pa:()=>{if(!mc())return-1;gc(Kc);var a=Bc[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},ta:()=>{gc(Lc);if(document.exitPointerLock)document.exitPointerLock();
else return-1;return 0},q:()=>devicePixelRatio,h:(a,b,c)=>{a=V(a);if(!a)return-4;a=Jc(a);C[b>>3]=a.width;C[c>>3]=a.height;return 0},$:(a,b)=>{if(0>a||a>=oc.length)return-5;if(!oc[a])return-7;Mc(b,oc[a]);return 0},y:Xa,Ma:()=>oc.length,ua:(a,b)=>{w[a>>2]=screen.width;w[b>>2]=screen.height},Od:Nc,Nd:Oc,la:(a,b)=>{K.re.beginQueryEXT(a,P[b])},Md:(a,b,c)=>{K.bindAttribLocation(N[a],b,c?F(u,c):"")},Ld:Pc,Kd:(a,b)=>{K.bindFramebuffer(a,Nb[b])},Jd:(a,b)=>{K.bindRenderbuffer(a,Ob[b])},Id:Qc,Wd:a=>{K.bindVertexArray(Qb[a])},
Hd:function(a,b,c,d){K.blendColor(a,b,c,d)},Gd:function(a){K.blendEquation(a)},Fd:function(a,b){K.blendEquationSeparate(a,b)},Ed:function(a,b){K.blendFunc(a,b)},Dd:function(a,b,c,d){K.blendFuncSeparate(a,b,c,d)},Cd:Rc,Bd:(a,b,c,d)=>{K.bufferSubData(a,b,u.subarray(d,d+c))},Ad:function(a){return K.checkFramebufferStatus(a)},zd:Sc,yd:Tc,xd:function(a){K.clearDepth(a)},wd:function(a){K.clearStencil(a)},vd:(a,b,c,d)=>{K.colorMask(!!a,!!b,!!c,!!d)},ud:Uc,td:(a,b,c,d,e,f,g,m)=>{K.compressedTexImage2D(a,
b,c,d,e,f,m?u.subarray(m,m+g):null)},sd:(a,b,c,d,e,f,g,m,p)=>{K.compressedTexSubImage2D(a,b,c,d,e,f,g,p?u.subarray(p,p+m):null)},rd:function(a,b,c,d,e,f,g,m){K.copyTexImage2D(a,b,c,d,e,f,g,m)},qd:function(a,b,c,d,e,f,g,m){K.copyTexSubImage2D(a,b,c,d,e,f,g,m)},pd:Vc,od:Wc,nd:function(a){K.cullFace(a)},md:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=Mb[d];e&&(K.deleteBuffer(e),e.name=0,Mb[d]=null)}},ld:(a,b)=>{for(var c=0;c<a;++c){var d=w[b+4*c>>2],e=Nb[d];e&&(K.deleteFramebuffer(e),e.name=0,Nb[d]=
null)}},kd:Xc,na:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=P[d];e&&(K.re.deleteQueryEXT(e),P[d]=null)}},jd:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=Ob[d];e&&(K.deleteRenderbuffer(e),e.name=0,Ob[d]=null)}},id:a=>{if(a){var b=O[a];b?(K.deleteShader(b),O[a]=null):Q(1281)}},hd:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=Pb[d];e&&(K.deleteTexture(e),e.name=0,Pb[d]=null)}},Vd:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2];K.deleteVertexArray(Qb[d]);Qb[d]=null}},gd:function(a){K.depthFunc(a)},
fd:a=>{K.depthMask(!!a)},ed:function(a,b){K.depthRange(a,b)},dd:(a,b)=>{K.detachShader(N[a],O[b])},cd:function(a){K.disable(a)},bd:Yc,ad:(a,b,c)=>{K.drawArrays(a,b,c)},Rd:(a,b,c,d)=>{K.drawArraysInstanced(a,b,c,d)},Sd:(a,b)=>{for(var c=Zc[a],d=0;d<a;d++)c[d]=w[b+4*d>>2];K.drawBuffers(c)},$c,Qd:(a,b,c,d,e)=>{K.drawElementsInstanced(a,b,c,d,e)},_c:ad,Zc:bd,ka:a=>{K.re.endQueryEXT(a)},Yc:function(){K.finish()},Xc:function(){K.flush()},Wc:(a,b,c,d)=>{K.framebufferRenderbuffer(a,b,c,Ob[d])},Vc:(a,b,c,
d,e)=>{K.framebufferTexture2D(a,b,c,Pb[d],e)},Uc:function(a){K.frontFace(a)},Tc:dd,Rc:(a,b)=>{cd(a,b,"createFramebuffer",Nb)},oa:(a,b)=>{for(var c=0;c<a;c++){var d=K.re.createQueryEXT();if(!d){for(Q(1282);c<a;)w[b+4*c++>>2]=0;break}var e=Ub(P);d.name=e;P[e]=d;w[b+4*c>>2]=e}},Qc:(a,b)=>{cd(a,b,"createRenderbuffer",Ob)},Pc:ed,Ud:function(a,b){cd(a,b,"createVertexArray",Qb)},Sc:function(a){K.generateMipmap(a)},Oc:(a,b,c,d,e,f,g)=>{fd("getActiveAttrib",a,b,c,d,e,f,g)},Nc:(a,b,c,d,e,f,g)=>{fd("getActiveUniform",
a,b,c,d,e,f,g)},Mc:(a,b,c,d)=>{a=K.getAttachedShaders(N[a]);var e=a.length;e>b&&(e=b);w[c>>2]=e;for(b=0;b<e;++b)w[d+4*b>>2]=O.indexOf(a[b])},Lc:gd,Kc:(a,b)=>{hd(a,b,4)},Jc:(a,b,c)=>{c?w[c>>2]=K.getBufferParameter(a,b):Q(1281)},Ic:()=>{var a=K.getError()||Tb;Tb=0;return a},Hc:(a,b)=>{hd(a,b,2)},Gc:(a,b,c,d)=>{a=K.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;w[d>>2]=a},Fc:(a,b)=>{hd(a,b,0)},Dc:jd,Ec:kd,Yd:ld,ha:md,Xd:ld,Zd:md,ia:(a,
b,c)=>{c?w[c>>2]=K.re.getQueryEXT(a,b):Q(1281)},Cc:(a,b,c)=>{c?w[c>>2]=K.getRenderbufferParameter(a,b):Q(1281)},Ac:(a,b,c,d)=>{a=K.getShaderInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,u,d,b):0;c&&(w[c>>2]=b)},zc:(a,b,c,d)=>{a=K.getShaderPrecisionFormat(a,b);w[c>>2]=a.rangeMin;w[c+4>>2]=a.rangeMax;w[d>>2]=a.precision},yc:(a,b,c,d)=>{if(a=K.getShaderSource(O[a]))b=0<b&&d?E(a,u,d,b):0,c&&(w[c>>2]=b)},Bc:(a,b,c)=>{c?35716==b?(a=K.getShaderInfoLog(O[a]),null===a&&(a="(unknown error)"),w[c>>
2]=a?a.length+1:0):35720==b?(a=K.getShaderSource(O[a]),w[c>>2]=a?a.length+1:0):w[c>>2]=K.getShaderParameter(O[a],b):Q(1281)},xc:a=>{var b=Rb[a];if(!b){switch(a){case 7939:b=K.getSupportedExtensions()||[];b=b.concat(b.map(d=>"GL_"+d));b=H(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=K.getParameter(a))||Q(1280);b=b&&H(b);break;case 7938:b=H("OpenGL ES 2.0 ("+K.getParameter(7938)+")");break;case 35724:b=K.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);
null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=H(b);break;default:Q(1280)}Rb[a]=b}return b},wc:(a,b,c)=>{c?B[c>>2]=K.getTexParameter(a,b):Q(1281)},vc:(a,b,c)=>{c?w[c>>2]=K.getTexParameter(a,b):Q(1281)},sc:pd,uc:(a,b,c)=>{qd(a,b,c,2)},tc:(a,b,c)=>{qd(a,b,c,0)},pc:(a,b,c)=>{c?w[c>>2]=K.getVertexAttribOffset(a,b):Q(1281)},rc:(a,b,c)=>{rd(a,b,c,2)},qc:(a,b,c)=>{rd(a,b,c,5)},oc:function(a,b){K.hint(a,b)},nc:a=>(a=Mb[a])?K.isBuffer(a):0,mc:function(a){return K.isEnabled(a)},
lc:a=>(a=Nb[a])?K.isFramebuffer(a):0,kc:a=>(a=N[a])?K.isProgram(a):0,ma:a=>(a=P[a])?K.re.isQueryEXT(a):0,jc:a=>(a=Ob[a])?K.isRenderbuffer(a):0,ic:a=>(a=O[a])?K.isShader(a):0,hc:a=>(a=Pb[a])?K.isTexture(a):0,Td:a=>(a=Qb[a])?K.isVertexArray(a):0,gc:function(a){K.lineWidth(a)},fc:sd,ec:td,dc:function(a,b){K.polygonOffset(a,b)},ja:(a,b)=>{K.re.queryCounterEXT(P[a],b)},cc:(a,b,c,d,e,f,g)=>{(g=ud(f,e,c,d,g))?K.readPixels(a,b,c,d,e,f,g):Q(1280)},bc:()=>{},ac:function(a,b,c,d){K.renderbufferStorage(a,b,c,
d)},$b:(a,b)=>{K.sampleCoverage(a,!!b)},_b:function(a,b,c,d){K.scissor(a,b,c,d)},Zb:()=>{Q(1280)},Yb:vd,Wb:function(a,b,c){K.stencilFunc(a,b,c)},Vb:function(a,b,c,d){K.stencilFuncSeparate(a,b,c,d)},Ub:function(a){K.stencilMask(a)},Tb:function(a,b){K.stencilMaskSeparate(a,b)},Sb:function(a,b,c){K.stencilOp(a,b,c)},Rb:function(a,b,c,d){K.stencilOpSeparate(a,b,c,d)},Qb:wd,Pb:function(a,b,c){K.texParameterf(a,b,c)},Ob:(a,b,c)=>{K.texParameterf(a,b,B[c>>2])},Nb:xd,Mb:(a,b,c)=>{K.texParameteri(a,b,w[c>>
2])},Lb:(a,b,c,d,e,f,g,m,p)=>{var t=null;p&&(t=ud(m,g,e,f,p));K.texSubImage2D(a,b,c,d,e,f,g,m,t)},Kb:yd,Jb:(a,b,c)=>{if(288>=b)for(var d=X[b-1],e=0;e<b;++e)d[e]=B[c+4*e>>2];else d=B.subarray(c>>2,c+4*b>>2);K.uniform1fv(W(a),d)},Ib:zd,Hb:(a,b,c)=>{if(288>=b)for(var d=Ad[b-1],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+4*b>>2);K.uniform1iv(W(a),d)},Gb:(a,b,c)=>{K.uniform2f(W(a),b,c)},Fb:(a,b,c)=>{if(144>=b)for(var d=X[2*b-1],e=0;e<2*b;e+=2)d[e]=B[c+4*e>>2],d[e+1]=B[c+(4*e+4)>>2];else d=B.subarray(c>>
2,c+8*b>>2);K.uniform2fv(W(a),d)},Eb:(a,b,c)=>{K.uniform2i(W(a),b,c)},Db:(a,b,c)=>{if(144>=b)for(var d=Ad[2*b-1],e=0;e<2*b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2];else d=w.subarray(c>>2,c+8*b>>2);K.uniform2iv(W(a),d)},Cb:Bd,Bb:(a,b,c)=>{if(96>=b)for(var d=X[3*b-1],e=0;e<3*b;e+=3)d[e]=B[c+4*e>>2],d[e+1]=B[c+(4*e+4)>>2],d[e+2]=B[c+(4*e+8)>>2];else d=B.subarray(c>>2,c+12*b>>2);K.uniform3fv(W(a),d)},Ab:(a,b,c,d)=>{K.uniform3i(W(a),b,c,d)},zb:(a,b,c)=>{if(96>=b)for(var d=Ad[3*b-1],e=0;e<3*b;e+=3)d[e]=
w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2];else d=w.subarray(c>>2,c+12*b>>2);K.uniform3iv(W(a),d)},yb:(a,b,c,d,e)=>{K.uniform4f(W(a),b,c,d,e)},xb:(a,b,c)=>{if(72>=b){var d=X[4*b-1],e=B;c>>=2;for(var f=0;f<4*b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=B.subarray(c>>2,c+16*b>>2);K.uniform4fv(W(a),d)},wb:(a,b,c,d,e)=>{K.uniform4i(W(a),b,c,d,e)},vb:(a,b,c)=>{if(72>=b)for(var d=Ad[4*b-1],e=0;e<4*b;e+=4)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+
(4*e+8)>>2],d[e+3]=w[c+(4*e+12)>>2];else d=w.subarray(c>>2,c+16*b>>2);K.uniform4iv(W(a),d)},ub:(a,b,c,d)=>{if(72>=b)for(var e=X[4*b-1],f=0;f<4*b;f+=4)e[f]=B[d+4*f>>2],e[f+1]=B[d+(4*f+4)>>2],e[f+2]=B[d+(4*f+8)>>2],e[f+3]=B[d+(4*f+12)>>2];else e=B.subarray(d>>2,d+16*b>>2);K.uniformMatrix2fv(W(a),!!c,e)},tb:(a,b,c,d)=>{if(32>=b)for(var e=X[9*b-1],f=0;f<9*b;f+=9)e[f]=B[d+4*f>>2],e[f+1]=B[d+(4*f+4)>>2],e[f+2]=B[d+(4*f+8)>>2],e[f+3]=B[d+(4*f+12)>>2],e[f+4]=B[d+(4*f+16)>>2],e[f+5]=B[d+(4*f+20)>>2],e[f+6]=
B[d+(4*f+24)>>2],e[f+7]=B[d+(4*f+28)>>2],e[f+8]=B[d+(4*f+32)>>2];else e=B.subarray(d>>2,d+36*b>>2);K.uniformMatrix3fv(W(a),!!c,e)},sb:Cd,rb:Dd,qb:a=>{K.validateProgram(N[a])},pb:function(a,b){K.vertexAttrib1f(a,b)},ob:(a,b)=>{K.vertexAttrib1f(a,B[b>>2])},nb:function(a,b,c){K.vertexAttrib2f(a,b,c)},mb:(a,b)=>{K.vertexAttrib2f(a,B[b>>2],B[b+4>>2])},lb:function(a,b,c,d){K.vertexAttrib3f(a,b,c,d)},kb:(a,b)=>{K.vertexAttrib3f(a,B[b>>2],B[b+4>>2],B[b+8>>2])},jb:function(a,b,c,d,e){K.vertexAttrib4f(a,b,
c,d,e)},ib:(a,b)=>{K.vertexAttrib4f(a,B[b>>2],B[b+4>>2],B[b+8>>2],B[b+12>>2])},Pd:(a,b)=>{K.vertexAttribDivisor(a,b)},hb:Ed,gb:Fd,w:()=>0,fb:(a,b,c)=>u.copyWithin(a,b,b+c),qa:(a,b,c)=>Gd(a,{Le:w[c>>2],Je:w[c+4>>2],ff:w[c+8>>2],cf:b,Ae:w[c+12>>2],Qe:w[c+16>>2]}),W:(a,b)=>{a=V(a);return a?a.requestPointerLock?hc()?Lc(a):b?(fc(Lc,2,[a]),1):-2:-1:-4},Ya:()=>{q("OOM")},Ta:a=>{eval(a?F(u,a):"")},aa:()=>(oc=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads():
null)?0:-1,C:(a,b,c)=>"undefined"==typeof onbeforeunload?-1:1!==c?-5:Hd(a,b),O:(a,b,c,d)=>Id(a,b,c,d,12,"blur"),k:Fc,u:(a,b,c)=>{a=V(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},P:(a,b,c,d)=>Id(a,b,c,d,13,"focus"),E:(a,b,c,d)=>{if(!mc())return-1;a=V(a);if(!a)return-4;Jd(a,b,c,d,"webkitfullscreenchange");return Jd(a,b,c,d,"fullscreenchange")},_:(a,b,c)=>navigator.getGamepads||navigator.webkitGetGamepads?Kd(a,b,c,26,"gamepadconnected"):-1,Z:(a,b,c)=>navigator.getGamepads||
navigator.webkitGetGamepads?Kd(a,b,c,27,"gamepaddisconnected"):-1,H:(a,b,c,d)=>Ld(a,b,c,d,2,"keydown"),F:(a,b,c,d)=>Ld(a,b,c,d,1,"keypress"),G:(a,b,c,d)=>Ld(a,b,c,d,3,"keyup"),Pa:(a,b,c)=>{a=G(a);ib(a,b,c)},U:(a,b,c,d)=>Nd(a,b,c,d,5,"mousedown"),S:(a,b,c,d)=>Nd(a,b,c,d,33,"mouseenter"),R:(a,b,c,d)=>Nd(a,b,c,d,34,"mouseleave"),V:(a,b,c,d)=>Nd(a,b,c,d,8,"mousemove"),T:(a,b,c,d)=>Nd(a,b,c,d,6,"mouseup"),I:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.Be||
document.body.lf||document.body.kf))return-1;a=V(a);if(!a)return-4;Od(a,b,c,d,"mozpointerlockchange");Od(a,b,c,d,"webkitpointerlockchange");Od(a,b,c,d,"mspointerlockchange");return Od(a,b,c,d,"pointerlockchange")},x:(a,b,c,d)=>Pd(a,b,c,d),J:(a,b,c,d)=>Qd(a,b,c,d,25,"touchcancel"),M:(a,b,c,d)=>Qd(a,b,c,d,23,"touchend"),K:(a,b,c,d)=>Qd(a,b,c,d,24,"touchmove"),N:(a,b,c,d)=>Qd(a,b,c,d,22,"touchstart"),D:(a,b,c)=>Rd(a,b,c),Q:(a,b,c,d)=>(a=V(a))?"undefined"!=typeof a.onwheel?Sd(a,b,c,d):-1:-4,sa:a=>document.title=
a?F(u,a):"",v:()=>{throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},_a:(a,b)=>{var c=0;Vd().forEach((d,e)=>{var f=b+c;e=y[a+4*e>>2]=f;for(f=0;f<d.length;++f)r[e++>>0]=d.charCodeAt(f);r[e>>0]=0;c+=d.length+1});return 0},$a:(a,b)=>{var c=Vd();y[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);y[b>>2]=d;return 0},da:()=>52,ab:()=>52,Xa:function(){return 70},ea:(a,b,c,d)=>{for(var e=0,f=0;f<c;f++){var g=y[b>>2],m=y[b+4>>2];b+=8;for(var p=
0;p<m;p++){var t=u[g+p],v=Zd[a];0===t||10===t?((1===a?fa:l)(F(v,0)),v.length=0):v.push(t)}e+=m}y[d>>2]=e;return 0},bb:Nc,m:Oc,a:Pc,Y:Qc,c:Rc,Sa:Sc,Qa:Tc,n:Uc,B:Vc,p:Wc,_d:Xc,Ra:Yc,t:$c,ba:ad,f:bd,d:dd,Na:ed,l:gd,ra:jd,L:kd,e:pd,A:sd,Ua:td,o:vd,Aa:wd,r:xd,ca:yd,Va:zd,s:Bd,i:Cd,z:Dd,g:Ed,Xb:Fd,j:(a,b,c,d)=>{function e(n,x,z){for(n="number"==typeof n?n.toString():n||"";n.length<x;)n=z[0]+n;return n}function f(n,x){return e(n,x,"0")}function g(n,x){function z(Va){return 0>Va?-1:0<Va?1:0}var T;0===(T=
z(n.getFullYear()-x.getFullYear()))&&0===(T=z(n.getMonth()-x.getMonth()))&&(T=z(n.getDate()-x.getDate()));return T}function m(n){switch(n.getDay()){case 0:return new Date(n.getFullYear()-1,11,29);case 1:return n;case 2:return new Date(n.getFullYear(),0,3);case 3:return new Date(n.getFullYear(),0,2);case 4:return new Date(n.getFullYear(),0,1);case 5:return new Date(n.getFullYear()-1,11,31);case 6:return new Date(n.getFullYear()-1,11,30)}}function p(n){var x=n.ue;for(n=new Date((new Date(n.ve+1900,
0,1)).getTime());0<x;){var z=n.getMonth(),T=(Na(n.getFullYear())?$d:ae)[z];if(x>T-n.getDate())x-=T-n.getDate()+1,n.setDate(1),11>z?n.setMonth(z+1):(n.setMonth(0),n.setFullYear(n.getFullYear()+1));else{n.setDate(n.getDate()+x);break}}z=new Date(n.getFullYear()+1,0,4);x=m(new Date(n.getFullYear(),0,4));z=m(z);return 0>=g(x,n)?0>=g(z,n)?n.getFullYear()+1:n.getFullYear():n.getFullYear()-1}var t=y[d+40>>2];d={rf:w[d>>2],qf:w[d+4>>2],He:w[d+8>>2],Ne:w[d+12>>2],Ie:w[d+16>>2],ve:w[d+20>>2],qe:w[d+24>>2],
ue:w[d+28>>2],Df:w[d+32>>2],pf:w[d+36>>2],sf:t?t?F(u,t):"":""};c=c?F(u,c):"";t={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var v in t)c=c.replace(new RegExp(v,"g"),t[v]);
var A="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),ba="January February March April May June July August September October November December".split(" ");t={"%a":n=>A[n.qe].substring(0,3),"%A":n=>A[n.qe],"%b":n=>ba[n.Ie].substring(0,3),"%B":n=>ba[n.Ie],"%C":n=>f((n.ve+1900)/100|0,2),"%d":n=>f(n.Ne,2),"%e":n=>e(n.Ne,2," "),"%g":n=>p(n).toString().substring(2),"%G":n=>p(n),"%H":n=>f(n.He,2),"%I":n=>{n=n.He;0==n?n=12:12<n&&(n-=12);return f(n,2)},"%j":n=>{for(var x=0,z=0;z<=n.Ie-
1;x+=(Na(n.ve+1900)?$d:ae)[z++]);return f(n.Ne+x,3)},"%m":n=>f(n.Ie+1,2),"%M":n=>f(n.qf,2),"%n":()=>"\n","%p":n=>0<=n.He&&12>n.He?"AM":"PM","%S":n=>f(n.rf,2),"%t":()=>"\t","%u":n=>n.qe||7,"%U":n=>f(Math.floor((n.ue+7-n.qe)/7),2),"%V":n=>{var x=Math.floor((n.ue+7-(n.qe+6)%7)/7);2>=(n.qe+371-n.ue-2)%7&&x++;if(x)53==x&&(z=(n.qe+371-n.ue)%7,4==z||3==z&&Na(n.ve)||(x=1));else{x=52;var z=(n.qe+7-n.ue-1)%7;(4==z||5==z&&Na(n.ve%400-1))&&x++}return f(x,2)},"%w":n=>n.qe,"%W":n=>f(Math.floor((n.ue+7-(n.qe+6)%
7)/7),2),"%y":n=>(n.ve+1900).toString().substring(2),"%Y":n=>n.ve+1900,"%z":n=>{n=n.pf;var x=0<=n;n=Math.abs(n)/60;return(x?"+":"-")+String("0000"+(n/60*100+n%60)).slice(-4)},"%Z":n=>n.sf,"%%":()=>"%"};c=c.replace(/%%/g,"\x00\x00");for(v in t)c.includes(v)&&(c=c.replace(new RegExp(v,"g"),t[v](d)));c=c.replace(/\0\0/g,"%");v=be(c);if(v.length>b)return 0;r.set(v,a);return v.length-1}},Z=function(){function a(c){Z=c.exports;ia=Z.$d;c=ia.buffer;h.HEAP8=r=new Int8Array(c);h.HEAP16=la=new Int16Array(c);
h.HEAPU8=u=new Uint8Array(c);h.HEAPU16=ma=new Uint16Array(c);h.HEAP32=w=new Int32Array(c);h.HEAPU32=y=new Uint32Array(c);h.HEAPF32=B=new Float32Array(c);h.HEAPF64=C=new Float64Array(c);La=Z.de;oa.unshift(Z.ae);ta--;h.monitorRunDependencies&&h.monitorRunDependencies(ta);0==ta&&(null!==ua&&(clearInterval(ua),ua=null),va&&(c=va,va=null,c()));return Z}var b={a:ee};ta++;h.monitorRunDependencies&&h.monitorRunDependencies(ta);if(h.instantiateWasm)try{return h.instantiateWasm(b,a)}catch(c){return l(`Module.instantiateWasm callback failed with error: ${c}`),
!1}Ca(b,function(c){a(c.instance)});return{}}(),D=a=>(D=Z.be)(a),fe=h._main=(a,b)=>(fe=h._main=Z.ce)(a,b),$b=()=>($b=Z.ee)(),ac=a=>(ac=Z.fe)(a),Cc=a=>(Cc=Z.ge)(a);h.dynCall_jiji=(a,b,c,d,e)=>(h.dynCall_jiji=Z.he)(a,b,c,d,e);h.dynCall_ji=(a,b)=>(h.dynCall_ji=Z.ie)(a,b);var ge;va=function he(){ge||ie();ge||(va=he)};function je(a=[]){var b=fe;a.unshift(da);var c=a.length,d=Cc(4*(c+1)),e=d;a.forEach(g=>{y[e>>2]=Dc(g);e+=4});y[e>>2]=0;try{var f=b(c,d);jb(f)}catch(g){hb(g)}}
function ie(){var a=ca;function b(){if(!ge&&(ge=!0,h.calledRun=!0,!ja)){Ja(oa);Ja(pa);if(h.onRuntimeInitialized)h.onRuntimeInitialized();ke&&je(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();ra.unshift(c)}Ja(ra)}}if(!(0<ta)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)sa();Ja(na);0<ta||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);
b()},1)):b())}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var ke=!0;h.noInitialRun&&(ke=!1);ie();
