var g;g||(g=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},g),ba=[],ca="./this.program",da=(a,b)=>{throw b;},h="";"undefined"!=typeof document&&document.currentScript&&(h=document.currentScript.src);h=0!==h.indexOf("blob:")?h.substr(0,h.replace(/[?#].*/,"").lastIndexOf("/")+1):"";var ea=g.print||console.log.bind(console),m=g.printErr||console.warn.bind(console);Object.assign(g,aa);aa=null;g.arguments&&(ba=g.arguments);g.thisProgram&&(ca=g.thisProgram);
g.quit&&(da=g.quit);var fa;g.wasmBinary&&(fa=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!=typeof WebAssembly&&n("no native wasm support detected");var ha,q=!1,ia="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ja(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&ia)return ia.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|k:(e&7)<<18|f<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function t(a,b){return a?ja(y,a,b):""}
function z(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var k=a.charCodeAt(f);if(55296<=k&&57343>=k){var p=a.charCodeAt(++f);k=65536+((k&1023)<<10)|p&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e}
function ka(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}var A,y,la,B,C,D,ma,na,oa=[],pa=[],qa=[],ra=[],sa=[];function ta(){var a=g.preRun.shift();oa.unshift(a)}var E=0,ua=null,va=null;function n(a){if(g.onAbort)g.onAbort(a);a="Aborted("+a+")";m(a);q=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function wa(){return F.startsWith("data:application/octet-stream;base64,")}var F;F="index.wasm";
if(!wa()){var xa=F;F=g.locateFile?g.locateFile(xa,h):h+xa}function ya(){var a=F;try{if(a==F&&fa)return new Uint8Array(fa);throw"both async and sync fetching of the wasm failed";}catch(b){n(b)}}function za(){return fa||"function"!=typeof fetch?Promise.resolve().then(function(){return ya()}):fetch(F,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+F+"'";return a.arrayBuffer()}).catch(function(){return ya()})}
function Aa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}function Ba(a){for(;0<a.length;)a.shift()(g)}function Ca(a){return 0===a%4&&(0!==a%100||0===a%400)}var Da=[0,31,60,91,121,152,182,213,244,274,305,335],Ea=[0,31,59,90,120,151,181,212,243,273,304,334];function Fa(a){var b=ka(a)+1,c=G(b);c&&z(a,A,c,b);return c}var Ga=0;function Ha(){for(var a=H.length-1;0<=a;--a)Ia(a);H=[];Ja=[]}var Ja=[];
function Ka(){if(Ga&&La.Jd)for(var a=0;a<Ja.length;++a){var b=Ja[a];Ja.splice(a,1);--a;b.Wd.apply(null,b.Ld)}}var H=[];function Ia(a){var b=H[a];b.target.removeEventListener(b.Rc,b.xd,b.sd);H.splice(a,1)}function Ma(a){function b(d){++Ga;La=a;Ka();a.yd(d);Ka();--Ga}if(a.ud)a.xd=b,a.target.addEventListener(a.Rc,b,a.sd),H.push(a),Na||(ra.push(Ha),Na=!0);else for(var c=0;c<H.length;++c)H[c].target==a.target&&H[c].Rc==a.Rc&&Ia(c--)}var Na,La,Oa,Pa=[0,document,window];
function Qa(a){a=2<a?t(a):a;return Pa[a]||document.querySelector(a)}function Ra(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,k){b.drawElementsInstancedANGLE(c,d,e,f,k)})}
function Sa(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Ta(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}var Ua=1,Va=[],J=[],Wa=[],Xa=[],Ya=[],K=[],Za=[],$a=[],L=[],ab={},bb=4;
function M(a){cb||(cb=a)}function db(a){for(var b=Ua++,c=a.length;c<b;c++)a[c]=null;return b}function eb(a,b){a.fd||(a.fd=a.getContext,a.getContext=function(d,e){e=a.fd(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?fb(c,b):0}function fb(a,b){var c=db($a),d={Rd:c,attributes:b,version:b.Bd,ad:a};a.canvas&&(a.canvas.Id=d);$a[c]=d;("undefined"==typeof b.wd||b.wd)&&gb(d);return c}
function gb(a){a||(a=hb);if(!a.Ad){a.Ad=!0;var b=a.ad;Ra(b);Sa(b);Ta(b);b.Kc=b.getExtension("EXT_disjoint_timer_query");b.Ud=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var ib={},cb,hb,jb=[];function kb(a,b,c,d){for(var e=0;e<a;e++){var f=N[c](),k=f&&db(d);f?(f.name=k,d[k]=f):M(1282);B[b+4*e>>2]=k}}
function lb(a,b,c,d,e,f,k,p){b=J[b];if(a=N[a](b,c))d=p&&z(a.name,y,p,d),e&&(B[e>>2]=d),f&&(B[f>>2]=a.size),k&&(B[k>>2]=a.type)}function mb(a,b){C[a>>2]=b;C[a+4>>2]=(b-C[a>>2])/4294967296}
function nb(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&M(1280);return;case 36345:d=0;break;case 34466:var e=N.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=N.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":M(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:M(1280);return}else{if(e instanceof Float32Array||
e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:B[b+4*a>>2]=e[a];break;case 2:D[b+4*a>>2]=e[a];break;case 4:A[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){M(1280);m("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:M(1280);m("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:mb(b,
d);break;case 0:B[b>>2]=d;break;case 2:D[b>>2]=d;break;case 4:A[b>>0]=d?1:0}}else M(1281)}function ob(a){var b=ka(a)+1,c=G(b);z(a,y,c,b);return c}function pb(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function qb(a){var b=a.Pc,c=a.rd,d;if(!b)for(a.Pc=b={},a.qd={},d=0;d<N.getProgramParameter(a,35718);++d){var e=N.getActiveUniform(a,d);var f=e.name;e=e.size;var k=pb(f);k=0<k?f.slice(0,k):f;var p=a.ed;a.ed+=e;c[k]=[e,p];for(f=0;f<e;++f)b[p]=f,a.qd[p++]=k}}
function O(a){var b=N.vd;if(b){var c=b.Pc[a];"number"==typeof c&&(b.Pc[a]=c=N.getUniformLocation(b,b.qd[a]+(0<c?"["+c+"]":"")));return c}M(1282)}function rb(a,b,c,d){if(c)if(a=J[a],qb(a),a=N.getUniform(a,O(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:B[c>>2]=a;break;case 2:D[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:B[c+4*b>>2]=a[b];break;case 2:D[c+4*b>>2]=a[b]}else M(1281)}
function sb(a,b,c,d){if(c)if(a=N.getVertexAttrib(a,b),34975==b)B[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:B[c>>2]=a;break;case 2:D[c>>2]=a;break;case 5:B[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:B[c+4*b>>2]=a[b];break;case 2:D[c+4*b>>2]=a[b];break;case 5:B[c+4*b>>2]=Math.fround(a[b])}else M(1281)}
function tb(a,b,c,d,e){a-=5120;a=1==a?y:4==a?B:6==a?D:5==a||28922==a?C:la;var f=31-Math.clz32(a.BYTES_PER_ELEMENT),k=bb;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<f)+k-1&-k)>>f)}var Q=[],ub=[];function vb(a){a instanceof Aa||"unwind"==a||da(1,a)}function wb(a){if(!q)try{a()}catch(b){vb(b)}}function xb(a){setTimeout(function(){wb(a)},1E4)}function yb(a){zb||(zb={});zb[a]||(zb[a]=1,m(a))}
var zb,Ab=!1,R=null,Bb=0,Cb=null,Db=0,Eb=0,Fb=0,Gb=0,Hb=[],Ib={},Jb,Kb,Lb,Mb=!1,Nb=!1,Ob=[];
function Pb(){function a(){Nb=document.pointerLockElement===g.canvas||document.mozPointerLockElement===g.canvas||document.webkitPointerLockElement===g.canvas||document.msPointerLockElement===g.canvas}g.preloadPlugins||(g.preloadPlugins=[]);if(!Qb){Qb=!0;try{Rb=!0}catch(c){Rb=!1,m("warning: no blob constructor, cannot create blobs with mimetypes")}Sb="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:Rb?null:m("warning: no BlobBuilder");Tb="undefined"!=
typeof window?window.URL?window.URL:window.webkitURL:void 0;g.ld||"undefined"!=typeof Tb||(m("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),g.ld=!0);g.preloadPlugins.push({canHandle:function(c){return!g.ld&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var k=null;if(Rb)try{k=new Blob([c],{type:Ub(d)}),k.size!==c.length&&(k=new Blob([(new Uint8Array(c)).buffer],{type:Ub(d)}))}catch(u){yb("Blob constructor present but fails: "+
u+"; falling back to blob builder")}k||(k=new Sb,k.append((new Uint8Array(c)).buffer),k=k.getBlob());var p=Tb.createObjectURL(k),r=new Image;r.onload=()=>{r.complete||n("Image "+d+" could not be decoded");var u=document.createElement("canvas");u.width=r.width;u.height=r.height;u.getContext("2d").drawImage(r,0,0);Tb.revokeObjectURL(p);e&&e(c)};r.onerror=()=>{ea("Image "+p+" could not be decoded");f&&f()};r.src=p}});g.preloadPlugins.push({canHandle:function(c){return!g.Vd&&c.substr(-4)in{".ogg":1,".wav":1,
".mp3":1}},handle:function(c,d,e,f){function k(){r||(r=!0,e&&e(c))}function p(){r||(r=!0,new Audio,f&&f())}var r=!1;if(Rb){try{var u=new Blob([c],{type:Ub(d)})}catch(I){return p()}u=Tb.createObjectURL(u);var w=new Audio;w.addEventListener("canplaythrough",()=>k(w),!1);w.onerror=function(){if(!r){m("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var I="",P=0,l=0,v=0;v<c.length;v++)for(P=P<<8|c[v],l+=8;6<=l;){var x=P>>l-6&63;l-=6;I+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[x]}2==
l?(I+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(P&3)<<4],I+="=="):4==l&&(I+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(P&15)<<2],I+="=");w.src="data:audio/x-"+d.substr(-3)+";base64,"+I;k(w)}};w.src=u;xb(function(){k(w)})}else return p()}});var b=g.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||
document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),g.elementPointerLock&&b.addEventListener("click",c=>{!Nb&&g.canvas.requestPointerLock&&(g.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Vb(a,b,c,d){if(b&&g.Oc&&a==g.canvas)return g.Oc;var e;if(b){var f={antialias:!1,alpha:!1,Bd:1};if(d)for(var k in d)f[k]=d[k];if("undefined"!=typeof ib&&(e=eb(a,f)))var p=$a[e].ad}else p=a.getContext("2d");if(!p)return null;c&&(b||"undefined"==typeof N||n("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),g.Oc=p,b&&(hb=$a[e],g.Oc=N=hb&&hb.ad),g.Yd=b,Ob.forEach(function(r){r()}),Pb());return p}var Wb=!1,Xb=void 0,Yb=void 0;
function Zb(a,b){function c(){Mb=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=$b,Xb&&d.requestPointerLock(),Mb=!0,Yb?("undefined"!=typeof SDL&&(B[SDL.screen>>2]=C[SDL.screen>>2]|8388608),ac(g.canvas),bc()):ac(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),Yb?("undefined"!=typeof SDL&&(B[SDL.screen>>2]=C[SDL.screen>>2]&
-8388609),ac(g.canvas),bc()):ac(d));if(g.onFullScreen)g.onFullScreen(Mb);if(g.onFullscreen)g.onFullscreen(Mb)}Xb=a;Yb=b;"undefined"==typeof Xb&&(Xb=!0);"undefined"==typeof Yb&&(Yb=!1);var d=g.canvas;Wb||(Wb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}
function $b(){if(!Mb)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var cc=0;function dc(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===cc)cc=b+1E3/60;else for(;b+2>=cc;)cc+=1E3/60;setTimeout(a,Math.max(cc-b,0))}}
function Ub(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var ec=0,fc=0,gc=0,hc=0;
function ic(a){if(Nb)"mousemove"!=a.type&&"mozMovementX"in a?gc=hc=0:(gc=a.movementX||a.mozMovementX||a.webkitMovementX||0,hc=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(ec=SDL.Sd+gc,fc=SDL.Td+hc):(ec+=gc,fc+=hc);else{var b=g.canvas.getBoundingClientRect(),c=g.canvas.width,d=g.canvas.height,e="undefined"!=typeof window.scrollX?window.scrollX:window.pageXOffset,f="undefined"!=typeof window.scrollY?window.scrollY:window.pageYOffset;"touchstart"!==a.type&&"touchend"!==
a.type&&"touchmove"!==a.type&&(e=a.pageX-(e+b.left),a=a.pageY-(f+b.top),e*=c/b.width,a*=d/b.height,gc=e-ec,hc=a-fc,ec=e,fc=a)}}var jc=[];function bc(){var a=g.canvas;jc.forEach(function(b){b(a.width,a.height)})}function kc(a,b,c){ac(g.canvas,a,b);c||bc()}
function ac(a,b,c){b&&c?(a.Hd=b,a.zd=c):(b=a.Hd,c=a.zd);var d=b,e=c;g.forcedAspectRatio&&0<g.forcedAspectRatio&&(d/e<g.forcedAspectRatio?d=Math.round(e*g.forcedAspectRatio):e=Math.round(d/g.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}Yb?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var Qb,Rb,Sb,Tb;
function lc(a,b){Eb=a;Fb=b;if(Cb)if(Ab||(Ab=!0),0==a)R=function(){var d=Math.max(0,Kb+b-mc())|0;setTimeout(Lb,d)};else if(1==a)R=function(){dc(Lb)};else if(2==a){if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);postMessage("setimmediate","*")}}R=function(){setImmediate(Lb)}}}var mc;mc=()=>performance.now();
function nc(a,b,c,d,e){!Cb||n("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");Cb=a;Db=d;var f=Bb;Ab=!1;Lb=function(){if(!q)if(0<Hb.length){var k=Date.now(),p=Hb.shift();p.Qd(p.Kd);if(Jb){var r=Jb,u=0==r%1?r-1:Math.floor(r);Jb=p.Od?u:(8*r+(u+.5))/9}ea('main loop blocker "'+p.name+'" took '+(Date.now()-k)+" ms");g.setStatus&&(k=g.statusMessage||"Please wait...",
p=Jb,r=Ib.Pd,p?p<r?g.setStatus(k+" ("+(r-p)+"/"+r+")"):g.setStatus(k):g.setStatus(""));f<Bb||setTimeout(Lb,0)}else f<Bb||(Gb=Gb+1|0,1==Eb&&1<Fb&&0!=Gb%Fb?R():(0==Eb&&(Kb=mc()),q||g.preMainLoop&&!1===g.preMainLoop()||(wb(a),g.postMainLoop&&g.postMainLoop()),f<Bb||("object"==typeof SDL&&SDL.audio&&SDL.audio.Cd&&SDL.audio.Cd(),R())))};e||(b&&0<b?lc(0,1E3/b):lc(1,1),R());if(c)throw"unwind";}var oc=[];function S(a){var b=oc[a];b||(a>=oc.length&&(oc.length=a+1),oc[a]=b=na.get(a));return b}
function pc(a,b,c,d){Oa||(Oa=G(36));a=Qa(a);Ma({target:a,Rc:"resize",ud:d,yd:function(e=event){if(e.target==a){var f=document.body;if(f){var k=Oa;B[k>>2]=e.detail;B[k+4>>2]=f.clientWidth;B[k+8>>2]=f.clientHeight;B[k+12>>2]=innerWidth;B[k+16>>2]=innerHeight;B[k+20>>2]=outerWidth;B[k+24>>2]=outerHeight;B[k+28>>2]=pageXOffset;B[k+32>>2]=pageYOffset;S(d)(10,k,b)&&e.preventDefault()}}},sd:c})}function qc(a){if(!noExitRuntime){if(g.onExit)g.onExit(a);q=!0}da(a,new Aa(a))}var rc=[null,[],[]];
function sc(a,b,c,d){this.id=a;this.y=this.x=0;this.cd=!1;this.pd=this.od=0;this.width=b;this.height=c;this.nd=b;this.md=c;this.title=d;this.attributes=T;this.buttons=0;this.keys=[];this.bd=[];this.gd=this.Sc=this.jd=this.Xc=this.Qc=this.hd=this.Wc=this.kd=this.td=this.$c=this.title=null}function U(a){return 0>=a||!V?null:V[a-1]}
var W=null,V=null,tc=null,T=null,uc={131073:0,131074:0,131075:1,131076:1,131077:1,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0};
function vc(a){switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;
case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 96;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;
case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;
case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;
case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 93:return 348;default:return-1}}function xc(){var a=W,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);a.keys[343]&&(b|=8);return b}function yc(a){W&&W.gd&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||S(W.gd)(W.id,a))}function zc(a,b){if(W){var c=vc(a);if(-1!=c){var d=b&&W.keys[c];W.keys[c]=b;W.bd[a]=b;W.Sc&&(d&&(b=2),S(W.Sc)(W.id,c,a,b,xc()))}}}
function Ac(){Bc()}function Cc(){Bc()}function Dc(a){zc(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()}function Ec(a){zc(a.keyCode,0)}function Fc(){if(W)for(var a=0;a<W.bd.length;++a)W.bd[a]&&zc(a,0)}function Gc(a){W&&(ic(a),a.target==g.canvas&&W.hd&&S(W.hd)(W.id,ec,fc))}function Hc(a){W&&a.target==g.canvas&&W.Qc&&S(W.Qc)(W.id,1)}function Ic(a){W&&a.target==g.canvas&&W.Qc&&S(W.Qc)(W.id,0)}
function Jc(a,b){if(W&&(ic(a),a.target==g.canvas)){var c=a.button;0<c&&(c=1==c?2:1);if(1==b){W.buttons|=1<<c;try{a.target.setCapture()}catch(d){}}else W.buttons&=~(1<<c);W.Wc&&S(W.Wc)(W.id,c,b,xc())}}function Kc(a){W&&Jc(a,1)}function Lc(a){W&&Jc(a,0)}
function Mc(a){switch(a.type){case "DOMMouseScroll":var b=a.detail/3;break;case "mousewheel":b=a.wheelDelta/120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=100;break;case 1:b/=3;break;case 2:b*=80;break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}b=-b;b=0==b?0:0<b?Math.max(b,1):Math.min(b,-1);if(W&&W.Xc&&a.target==g.canvas){var c=b;b="mousewheel"==a.type?a.wheelDeltaX:a.deltaX;S(W.Xc)(W.id,b,c);a.preventDefault()}}
var Y={},Nc=[],Oc=null;
function Bc(){if(Gb!==Oc||!Gb){Nc=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads:[];Oc=Gb;for(var a=0;a<Nc.length;++a){var b=Nc[a];if(b){Y[a]||(ea("glfw joystick connected:",a),Y[a]={id:Fa(b.id),Nd:b.buttons.length,Md:b.axes.length,buttons:G(b.buttons.length),axes:G(4*b.axes.length)});for(var c=Y[a],d=0;d<b.buttons.length;++d)A[c.buttons+d>>0]=b.buttons[d].pressed;for(d=0;d<b.axes.length;++d)D[c.axes+4*d>>2]=b.axes[d]}else Y[a]&&(ea("glfw joystick disconnected",
a),Pc(Y[a].id),Pc(Y[a].buttons),Pc(Y[a].axes),delete Y[a])}}}function Qc(a){if(W&&W.jd&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length)return a.preventDefault(),!1}function Rc(a){if(W&&W.jd)return a.preventDefault(),!1}var Sc=[31,29,31,30,31,30,31,31,30,31,30,31],Tc=[31,28,31,30,31,30,31,31,30,31,30,31];function Uc(a){var b=Array(ka(a)+1);z(a,b,0,b.length);return b}for(var N,Z=0;32>Z;++Z)jb.push(Array(Z));var Vc=new Float32Array(288);for(Z=0;288>Z;++Z)Q[Z]=Vc.subarray(0,Z+1);
var Wc=new Int32Array(288);for(Z=0;288>Z;++Z)ub[Z]=Wc.subarray(0,Z+1);g.requestFullscreen=function(a,b){Zb(a,b)};g.requestAnimationFrame=function(a){dc(a)};g.setCanvasSize=function(a,b,c){kc(a,b,c)};g.pauseMainLoop=function(){R=null;Bb++};g.resumeMainLoop=function(){Bb++;var a=Eb,b=Fb,c=Cb;Cb=null;nc(c,0,!1,Db,!0);lc(a,b);R()};g.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};
g.createContext=function(a,b,c,d){return Vb(a,b,c,d)};
var Xc={Na:function(a,b){a=new Date(1E3*(C[a>>2]+4294967296*B[a+4>>2]));B[b>>2]=a.getSeconds();B[b+4>>2]=a.getMinutes();B[b+8>>2]=a.getHours();B[b+12>>2]=a.getDate();B[b+16>>2]=a.getMonth();B[b+20>>2]=a.getFullYear()-1900;B[b+24>>2]=a.getDay();B[b+28>>2]=(Ca(a.getFullYear())?Da:Ea)[a.getMonth()]+a.getDate()-1|0;B[b+36>>2]=-(60*a.getTimezoneOffset());var c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset(),d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();B[b+32>>2]=(c!=d&&a.getTimezoneOffset()==
Math.min(d,c))|0},Oa:function(a,b,c){function d(r){return(r=r.toTimeString().match(/\(([A-Za-z ]+)\)$/))?r[1]:"GMT"}var e=(new Date).getFullYear(),f=new Date(e,0,1),k=new Date(e,6,1);e=f.getTimezoneOffset();var p=k.getTimezoneOffset();C[a>>2]=60*Math.max(e,p);B[b>>2]=Number(e!=p);a=d(f);b=d(k);a=Fa(a);b=Fa(b);p<e?(C[c>>2]=a,C[c+4>>2]=b):(C[c>>2]=b,C[c+4>>2]=a)},Ma:function(){return Date.now()},M:function(a,b,c){a=Qa(a);if(!a)return-4;a=0>Pa.indexOf(a)?a.getBoundingClientRect():{left:0,top:0};ma[b>>
3]=a.width;ma[c>>3]=a.height;return 0},na:function(a){N.activeTexture(a)},ma:function(a,b){N.attachShader(J[a],K[b])},Ea:function(a,b){N.Kc.beginQueryEXT(a,L[b])},la:function(a,b,c){N.bindAttribLocation(J[a],b,t(c))},ka:function(a,b){N.bindBuffer(a,Va[b])},ja:function(a,b){N.bindFramebuffer(a,Wa[b])},ia:function(a,b){N.bindRenderbuffer(a,Xa[b])},ha:function(a,b){N.bindTexture(a,Ya[b])},wa:function(a){N.bindVertexArray(Za[a])},fa:function(a,b,c,d){N.blendColor(a,b,c,d)},ea:function(a){N.blendEquation(a)},
da:function(a,b){N.blendEquationSeparate(a,b)},ca:function(a,b){N.blendFunc(a,b)},ba:function(a,b,c,d){N.blendFuncSeparate(a,b,c,d)},aa:function(a,b,c,d){N.bufferData(a,c?y.subarray(c,c+b):b,d)},$:function(a,b,c,d){N.bufferSubData(a,b,y.subarray(d,d+c))},_:function(a){return N.checkFramebufferStatus(a)},Z:function(a){N.clear(a)},Y:function(a,b,c,d){N.clearColor(a,b,c,d)},W:function(a){N.clearDepth(a)},V:function(a){N.clearStencil(a)},U:function(a,b,c,d){N.colorMask(!!a,!!b,!!c,!!d)},T:function(a){N.compileShader(K[a])},
S:function(a,b,c,d,e,f,k,p){N.compressedTexImage2D(a,b,c,d,e,f,p?y.subarray(p,p+k):null)},R:function(a,b,c,d,e,f,k,p,r){N.compressedTexSubImage2D(a,b,c,d,e,f,k,r?y.subarray(r,r+p):null)},Q:function(a,b,c,d,e,f,k,p){N.copyTexImage2D(a,b,c,d,e,f,k,p)},P:function(a,b,c,d,e,f,k,p){N.copyTexSubImage2D(a,b,c,d,e,f,k,p)},O:function(){var a=db(J),b=N.createProgram();b.name=a;b.Vc=b.Tc=b.Uc=0;b.ed=1;J[a]=b;return a},N:function(a){var b=db(K);K[b]=N.createShader(a);return b},L:function(a){N.cullFace(a)},K:function(a,
b){for(var c=0;c<a;c++){var d=B[b+4*c>>2],e=Va[d];e&&(N.deleteBuffer(e),e.name=0,Va[d]=null)}},J:function(a,b){for(var c=0;c<a;++c){var d=B[b+4*c>>2],e=Wa[d];e&&(N.deleteFramebuffer(e),e.name=0,Wa[d]=null)}},I:function(a){if(a){var b=J[a];b?(N.deleteProgram(b),b.name=0,J[a]=null):M(1281)}},Ga:function(a,b){for(var c=0;c<a;c++){var d=B[b+4*c>>2],e=L[d];e&&(N.Kc.deleteQueryEXT(e),L[d]=null)}},H:function(a,b){for(var c=0;c<a;c++){var d=B[b+4*c>>2],e=Xa[d];e&&(N.deleteRenderbuffer(e),e.name=0,Xa[d]=null)}},
G:function(a){if(a){var b=K[a];b?(N.deleteShader(b),K[a]=null):M(1281)}},F:function(a,b){for(var c=0;c<a;c++){var d=B[b+4*c>>2],e=Ya[d];e&&(N.deleteTexture(e),e.name=0,Ya[d]=null)}},va:function(a,b){for(var c=0;c<a;c++){var d=B[b+4*c>>2];N.deleteVertexArray(Za[d]);Za[d]=null}},E:function(a){N.depthFunc(a)},D:function(a){N.depthMask(!!a)},C:function(a,b){N.depthRange(a,b)},B:function(a,b){N.detachShader(J[a],K[b])},A:function(a){N.disable(a)},z:function(a){N.disableVertexAttribArray(a)},y:function(a,
b,c){N.drawArrays(a,b,c)},qa:function(a,b,c,d){N.drawArraysInstanced(a,b,c,d)},sa:function(a,b){for(var c=jb[a],d=0;d<a;d++)c[d]=B[b+4*d>>2];N.drawBuffers(c)},x:function(a,b,c,d){N.drawElements(a,b,c,d)},pa:function(a,b,c,d,e){N.drawElementsInstanced(a,b,c,d,e)},w:function(a){N.enable(a)},v:function(a){N.enableVertexAttribArray(a)},Da:function(a){N.Kc.endQueryEXT(a)},u:function(){N.finish()},t:function(){N.flush()},s:function(a,b,c,d){N.framebufferRenderbuffer(a,b,c,Xa[d])},q:function(a,b,c,d,e){N.framebufferTexture2D(a,
b,c,Ya[d],e)},p:function(a){N.frontFace(a)},o:function(a,b){kb(a,b,"createBuffer",Va)},m:function(a,b){kb(a,b,"createFramebuffer",Wa)},Ha:function(a,b){for(var c=0;c<a;c++){var d=N.Kc.createQueryEXT();if(!d){for(M(1282);c<a;)B[b+4*c++>>2]=0;break}var e=db(L);d.name=e;L[e]=d;B[b+4*c>>2]=e}},l:function(a,b){kb(a,b,"createRenderbuffer",Xa)},k:function(a,b){kb(a,b,"createTexture",Ya)},ua:function(a,b){kb(a,b,"createVertexArray",Za)},n:function(a){N.generateMipmap(a)},j:function(a,b,c,d,e,f,k){lb("getActiveAttrib",
a,b,c,d,e,f,k)},i:function(a,b,c,d,e,f,k){lb("getActiveUniform",a,b,c,d,e,f,k)},h:function(a,b,c,d){a=N.getAttachedShaders(J[a]);var e=a.length;e>b&&(e=b);B[c>>2]=e;for(b=0;b<e;++b)B[d+4*b>>2]=K.indexOf(a[b])},Ac:function(a,b){return N.getAttribLocation(J[a],t(b))},zc:function(a,b){nb(a,b,4)},yc:function(a,b,c){c?B[c>>2]=N.getBufferParameter(a,b):M(1281)},xc:function(){var a=N.getError()||cb;cb=0;return a},wc:function(a,b){nb(a,b,2)},vc:function(a,b,c,d){a=N.getFramebufferAttachmentParameter(a,b,
c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;B[d>>2]=a},uc:function(a,b){nb(a,b,0)},sc:function(a,b,c,d){a=N.getProgramInfoLog(J[a]);null===a&&(a="(unknown error)");b=0<b&&d?z(a,y,d,b):0;c&&(B[c>>2]=b)},tc:function(a,b,c){if(c)if(a>=Ua)M(1281);else if(a=J[a],35716==b)a=N.getProgramInfoLog(a),null===a&&(a="(unknown error)"),B[c>>2]=a.length+1;else if(35719==b){if(!a.Vc)for(b=0;b<N.getProgramParameter(a,35718);++b)a.Vc=Math.max(a.Vc,N.getActiveUniform(a,b).name.length+
1);B[c>>2]=a.Vc}else if(35722==b){if(!a.Tc)for(b=0;b<N.getProgramParameter(a,35721);++b)a.Tc=Math.max(a.Tc,N.getActiveAttrib(a,b).name.length+1);B[c>>2]=a.Tc}else if(35381==b){if(!a.Uc)for(b=0;b<N.getProgramParameter(a,35382);++b)a.Uc=Math.max(a.Uc,N.getActiveUniformBlockName(a,b).length+1);B[c>>2]=a.Uc}else B[c>>2]=N.getProgramParameter(a,b);else M(1281)},ya:function(a,b,c){if(c){a=N.Kc.getQueryObjectEXT(L[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;mb(c,d)}else M(1281)},Aa:function(a,b,c){if(c){a=
N.Kc.getQueryObjectEXT(L[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;B[c>>2]=d}else M(1281)},xa:function(a,b,c){if(c){a=N.Kc.getQueryObjectEXT(L[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;mb(c,d)}else M(1281)},za:function(a,b,c){if(c){a=N.Kc.getQueryObjectEXT(L[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;B[c>>2]=d}else M(1281)},Ba:function(a,b,c){c?B[c>>2]=N.Kc.getQueryEXT(a,b):M(1281)},rc:function(a,b,c){c?B[c>>2]=N.getRenderbufferParameter(a,b):M(1281)},oc:function(a,b,c,d){a=N.getShaderInfoLog(K[a]);
null===a&&(a="(unknown error)");b=0<b&&d?z(a,y,d,b):0;c&&(B[c>>2]=b)},nc:function(a,b,c,d){a=N.getShaderPrecisionFormat(a,b);B[c>>2]=a.rangeMin;B[c+4>>2]=a.rangeMax;B[d>>2]=a.precision},mc:function(a,b,c,d){if(a=N.getShaderSource(K[a]))b=0<b&&d?z(a,y,d,b):0,c&&(B[c>>2]=b)},pc:function(a,b,c){c?35716==b?(a=N.getShaderInfoLog(K[a]),null===a&&(a="(unknown error)"),B[c>>2]=a?a.length+1:0):35720==b?(a=N.getShaderSource(K[a]),B[c>>2]=a?a.length+1:0):B[c>>2]=N.getShaderParameter(K[a],b):M(1281)},lc:function(a){var b=
ab[a];if(!b){switch(a){case 7939:b=N.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=ob(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=N.getParameter(a))||M(1280);b=b&&ob(b);break;case 7938:b=ob("OpenGL ES 2.0 ("+N.getParameter(7938)+")");break;case 35724:b=N.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=ob(b);break;default:M(1280)}ab[a]=
b}return b},kc:function(a,b,c){c?D[c>>2]=N.getTexParameter(a,b):M(1281)},jc:function(a,b,c){c?B[c>>2]=N.getTexParameter(a,b):M(1281)},gc:function(a,b){b=t(b);if(a=J[a]){qb(a);var c=a.Pc,d=0,e=b,f=pb(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.rd[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||N.getUniformLocation(a,b)))return d}else M(1281);return-1},ic:function(a,b,c){rb(a,b,c,2)},hc:function(a,b,c){rb(a,b,c,0)},cc:function(a,b,c){c?B[c>>2]=N.getVertexAttribOffset(a,b):M(1281)},ec:function(a,
b,c){sb(a,b,c,2)},dc:function(a,b,c){sb(a,b,c,5)},bc:function(a,b){N.hint(a,b)},ac:function(a){return(a=Va[a])?N.isBuffer(a):0},$b:function(a){return N.isEnabled(a)},_b:function(a){return(a=Wa[a])?N.isFramebuffer(a):0},Zb:function(a){return(a=J[a])?N.isProgram(a):0},Fa:function(a){return(a=L[a])?N.Kc.isQueryEXT(a):0},Yb:function(a){return(a=Xa[a])?N.isRenderbuffer(a):0},Xb:function(a){return(a=K[a])?N.isShader(a):0},Vb:function(a){return(a=Ya[a])?N.isTexture(a):0},ta:function(a){return(a=Za[a])?N.isVertexArray(a):
0},Ub:function(a){N.lineWidth(a)},Tb:function(a){a=J[a];N.linkProgram(a);a.Pc=0;a.rd={}},Sb:function(a,b){3317==a&&(bb=b);N.pixelStorei(a,b)},Rb:function(a,b){N.polygonOffset(a,b)},Ca:function(a,b){N.Kc.queryCounterEXT(L[a],b)},Qb:function(a,b,c,d,e,f,k){(k=tb(f,e,c,d,k))?N.readPixels(a,b,c,d,e,f,k):M(1280)},Pb:function(){},Ob:function(a,b,c,d){N.renderbufferStorage(a,b,c,d)},Nb:function(a,b){N.sampleCoverage(a,!!b)},Mb:function(a,b,c,d){N.scissor(a,b,c,d)},Kb:function(){M(1280)},Jb:function(a,b,
c,d){for(var e="",f=0;f<b;++f){var k=d?B[d+4*f>>2]:-1;e+=t(B[c+4*f>>2],0>k?void 0:k)}N.shaderSource(K[a],e)},Ib:function(a,b,c){N.stencilFunc(a,b,c)},Hb:function(a,b,c,d){N.stencilFuncSeparate(a,b,c,d)},Gb:function(a){N.stencilMask(a)},Fb:function(a,b){N.stencilMaskSeparate(a,b)},Eb:function(a,b,c){N.stencilOp(a,b,c)},Db:function(a,b,c,d){N.stencilOpSeparate(a,b,c,d)},Cb:function(a,b,c,d,e,f,k,p,r){N.texImage2D(a,b,c,d,e,f,k,p,r?tb(p,k,d,e,r):null)},Bb:function(a,b,c){N.texParameterf(a,b,c)},zb:function(a,
b,c){N.texParameterf(a,b,D[c>>2])},yb:function(a,b,c){N.texParameteri(a,b,c)},xb:function(a,b,c){N.texParameteri(a,b,B[c>>2])},wb:function(a,b,c,d,e,f,k,p,r){var u=null;r&&(u=tb(p,k,e,f,r));N.texSubImage2D(a,b,c,d,e,f,k,p,u)},vb:function(a,b){N.uniform1f(O(a),b)},ub:function(a,b,c){if(288>=b)for(var d=Q[b-1],e=0;e<b;++e)d[e]=D[c+4*e>>2];else d=D.subarray(c>>2,c+4*b>>2);N.uniform1fv(O(a),d)},tb:function(a,b){N.uniform1i(O(a),b)},sb:function(a,b,c){if(288>=b)for(var d=ub[b-1],e=0;e<b;++e)d[e]=B[c+4*
e>>2];else d=B.subarray(c>>2,c+4*b>>2);N.uniform1iv(O(a),d)},rb:function(a,b,c){N.uniform2f(O(a),b,c)},qb:function(a,b,c){if(144>=b)for(var d=Q[2*b-1],e=0;e<2*b;e+=2)d[e]=D[c+4*e>>2],d[e+1]=D[c+(4*e+4)>>2];else d=D.subarray(c>>2,c+8*b>>2);N.uniform2fv(O(a),d)},ob:function(a,b,c){N.uniform2i(O(a),b,c)},nb:function(a,b,c){if(144>=b)for(var d=ub[2*b-1],e=0;e<2*b;e+=2)d[e]=B[c+4*e>>2],d[e+1]=B[c+(4*e+4)>>2];else d=B.subarray(c>>2,c+8*b>>2);N.uniform2iv(O(a),d)},mb:function(a,b,c,d){N.uniform3f(O(a),b,
c,d)},lb:function(a,b,c){if(96>=b)for(var d=Q[3*b-1],e=0;e<3*b;e+=3)d[e]=D[c+4*e>>2],d[e+1]=D[c+(4*e+4)>>2],d[e+2]=D[c+(4*e+8)>>2];else d=D.subarray(c>>2,c+12*b>>2);N.uniform3fv(O(a),d)},kb:function(a,b,c,d){N.uniform3i(O(a),b,c,d)},jb:function(a,b,c){if(96>=b)for(var d=ub[3*b-1],e=0;e<3*b;e+=3)d[e]=B[c+4*e>>2],d[e+1]=B[c+(4*e+4)>>2],d[e+2]=B[c+(4*e+8)>>2];else d=B.subarray(c>>2,c+12*b>>2);N.uniform3iv(O(a),d)},ib:function(a,b,c,d,e){N.uniform4f(O(a),b,c,d,e)},hb:function(a,b,c){if(72>=b){var d=Q[4*
b-1],e=D;c>>=2;for(var f=0;f<4*b;f+=4){var k=c+f;d[f]=e[k];d[f+1]=e[k+1];d[f+2]=e[k+2];d[f+3]=e[k+3]}}else d=D.subarray(c>>2,c+16*b>>2);N.uniform4fv(O(a),d)},gb:function(a,b,c,d,e){N.uniform4i(O(a),b,c,d,e)},fb:function(a,b,c){if(72>=b)for(var d=ub[4*b-1],e=0;e<4*b;e+=4)d[e]=B[c+4*e>>2],d[e+1]=B[c+(4*e+4)>>2],d[e+2]=B[c+(4*e+8)>>2],d[e+3]=B[c+(4*e+12)>>2];else d=B.subarray(c>>2,c+16*b>>2);N.uniform4iv(O(a),d)},db:function(a,b,c,d){if(72>=b)for(var e=Q[4*b-1],f=0;f<4*b;f+=4)e[f]=D[d+4*f>>2],e[f+1]=
D[d+(4*f+4)>>2],e[f+2]=D[d+(4*f+8)>>2],e[f+3]=D[d+(4*f+12)>>2];else e=D.subarray(d>>2,d+16*b>>2);N.uniformMatrix2fv(O(a),!!c,e)},cb:function(a,b,c,d){if(32>=b)for(var e=Q[9*b-1],f=0;f<9*b;f+=9)e[f]=D[d+4*f>>2],e[f+1]=D[d+(4*f+4)>>2],e[f+2]=D[d+(4*f+8)>>2],e[f+3]=D[d+(4*f+12)>>2],e[f+4]=D[d+(4*f+16)>>2],e[f+5]=D[d+(4*f+20)>>2],e[f+6]=D[d+(4*f+24)>>2],e[f+7]=D[d+(4*f+28)>>2],e[f+8]=D[d+(4*f+32)>>2];else e=D.subarray(d>>2,d+36*b>>2);N.uniformMatrix3fv(O(a),!!c,e)},bb:function(a,b,c,d){if(18>=b){var e=
Q[16*b-1],f=D;d>>=2;for(var k=0;k<16*b;k+=16){var p=d+k;e[k]=f[p];e[k+1]=f[p+1];e[k+2]=f[p+2];e[k+3]=f[p+3];e[k+4]=f[p+4];e[k+5]=f[p+5];e[k+6]=f[p+6];e[k+7]=f[p+7];e[k+8]=f[p+8];e[k+9]=f[p+9];e[k+10]=f[p+10];e[k+11]=f[p+11];e[k+12]=f[p+12];e[k+13]=f[p+13];e[k+14]=f[p+14];e[k+15]=f[p+15]}}else e=D.subarray(d>>2,d+64*b>>2);N.uniformMatrix4fv(O(a),!!c,e)},ab:function(a){a=J[a];N.useProgram(a);N.vd=a},$a:function(a){N.validateProgram(J[a])},_a:function(a,b){N.vertexAttrib1f(a,b)},Za:function(a,b){N.vertexAttrib1f(a,
D[b>>2])},Ya:function(a,b,c){N.vertexAttrib2f(a,b,c)},Xa:function(a,b){N.vertexAttrib2f(a,D[b>>2],D[b+4>>2])},Wa:function(a,b,c,d){N.vertexAttrib3f(a,b,c,d)},Ua:function(a,b){N.vertexAttrib3f(a,D[b>>2],D[b+4>>2],D[b+8>>2])},Ta:function(a,b,c,d,e){N.vertexAttrib4f(a,b,c,d,e)},Sa:function(a,b){N.vertexAttrib4f(a,D[b>>2],D[b+4>>2],D[b+8>>2],D[b+12>>2])},oa:function(a,b){N.vertexAttribDivisor(a,b)},Ra:function(a,b,c,d,e,f){N.vertexAttribPointer(a,b,c,!!d,e,f)},Qa:function(a,b,c,d){N.viewport(a,b,c,d)},
Pa:function(a,b,c){y.copyWithin(a,b,b+c)},Ka:function(){n("OOM")},ga:function(a,b,c){a=Qa(a);if(!a)return-4;a.width=b;a.height=c;return 0},Ja:function(a,b,c){a=S(a);nc(a,b,c)},La:function(a,b,c,d){pc(a,b,c,d);return 0},b:qc,g:function(a,b,c,d){for(var e=0,f=0;f<c;f++){var k=C[b>>2],p=C[b+4>>2];b+=8;for(var r=0;r<p;r++){var u=y[k+r],w=rc[a];0===u||10===u?((1===a?ea:m)(ja(w,0)),w.length=0):w.push(u)}e+=p}C[d>>2]=e;return 0},r:function(a,b,c,d){var e;for(e=0;e<V.length&&null!==V[e];e++);if(0<e)throw"glfwCreateWindow only supports one window at time currently";
var f=e+1;if(0>=a||0>=b)f=0;else{d?Zb():kc(a,b);for(e=0;e<V.length&&null==V[e];e++);d=0<T[139265];e==V.length&&(d?g.Oc=Vb(g.canvas,!0,!0,{antialias:1<T[135181],depth:0<T[135173],stencil:0<T[135174],alpha:0<T[135172]}):Pb());!g.Oc&&d?f=0:(a=new sc(f,a,b,c),f-1==V.length?V.push(a):V[f-1]=a,W=a,f=a.id)}return f},Ia:function(a){a:{if(a=U(a)){a.td&&S(a.td)(a.id);V[a.id-1]=null;W.id==a.id&&(W=null);for(a=0;a<V.length;a++)if(null!==V[a]){a=void 0;break a}g.Oc=void 0}a=void 0}return a},d:function(a,b,c){ma[b>>
3]=ec;ma[c>>3]=fc},Bc:function(){return 1},f:function(){return mc()/1E3-tc},qc:function(){return 0},X:function(){if(V)return 1;tc=mc()/1E3;T=uc;V=[];W=null;window.addEventListener("gamepadconnected",Ac,!0);window.addEventListener("gamepaddisconnected",Cc,!0);window.addEventListener("keydown",Dc,!0);window.addEventListener("keypress",yc,!0);window.addEventListener("keyup",Ec,!0);window.addEventListener("blur",Fc,!0);g.canvas.addEventListener("touchmove",Gc,!0);g.canvas.addEventListener("touchstart",
Kc,!0);g.canvas.addEventListener("touchcancel",Lc,!0);g.canvas.addEventListener("touchend",Lc,!0);g.canvas.addEventListener("mousemove",Gc,!0);g.canvas.addEventListener("mousedown",Kc,!0);g.canvas.addEventListener("mouseup",Lc,!0);g.canvas.addEventListener("wheel",Mc,!0);g.canvas.addEventListener("mousewheel",Mc,!0);g.canvas.addEventListener("mouseenter",Hc,!0);g.canvas.addEventListener("mouseleave",Ic,!0);g.canvas.addEventListener("drop",Qc,!0);g.canvas.addEventListener("dragover",Rc,!0);jc.push((a,
b)=>{if(W){var c=!0;document.fullscreen||document.fullScreen||document.mozFullScreen||document.webkitIsFullScreen?(W.od=W.x,W.pd=W.y,W.nd=W.width,W.md=W.height,W.x=W.y=0,W.width=screen.width,W.height=screen.height,W.cd=!0):1==W.cd?(W.x=W.od,W.y=W.pd,W.width=W.nd,W.height=W.md,W.cd=!1):W.width!=a||W.height!=b?(W.width=a,W.height=b):c=!1;c&&(kc(W.width,W.height,!0),W&&W.$c&&S(W.$c)(W.id,W.width,W.height),W&&W.kd&&S(W.kd)(W.id,W.width,W.height))}});return 1},eb:function(){},Lb:function(a,b){if(a=U(a)){var c=
a.Sc;a.Sc=b;b=c}else b=null;return b},Ab:function(a,b){if(a=U(a)){var c=a.Wc;a.Wc=b;b=c}else b=null;return b},pb:function(a,b){if(a=U(a)){var c=a.Xc;a.Xc=b;b=c}else b=null;return b},fc:function(a,b,c){if(a=U(a))a.x=b,a.y=c},Wb:function(a,b){if(a=U(a)){var c=a.$c;a.$c=b;b=c}else b=null;return b},Cc:function(a,b){if(a=U(a))a.title=t(b),W.id==a.id&&(document.title=a.title)},ra:function(){},Va:function(a){a=Math.abs(a);0==a?lc(0,0):lc(1,a)},e:function(){window.removeEventListener("gamepadconnected",Ac,
!0);window.removeEventListener("gamepaddisconnected",Cc,!0);window.removeEventListener("keydown",Dc,!0);window.removeEventListener("keypress",yc,!0);window.removeEventListener("keyup",Ec,!0);window.removeEventListener("blur",Fc,!0);g.canvas.removeEventListener("touchmove",Gc,!0);g.canvas.removeEventListener("touchstart",Kc,!0);g.canvas.removeEventListener("touchcancel",Lc,!0);g.canvas.removeEventListener("touchend",Lc,!0);g.canvas.removeEventListener("mousemove",Gc,!0);g.canvas.removeEventListener("mousedown",
Kc,!0);g.canvas.removeEventListener("mouseup",Lc,!0);g.canvas.removeEventListener("wheel",Mc,!0);g.canvas.removeEventListener("mousewheel",Mc,!0);g.canvas.removeEventListener("mouseenter",Hc,!0);g.canvas.removeEventListener("mouseleave",Ic,!0);g.canvas.removeEventListener("drop",Qc,!0);g.canvas.removeEventListener("dragover",Rc,!0);g.canvas.width=g.canvas.height=1;W=V=null},a:function(a,b){T[a]=b},c:function(a,b,c,d){function e(l,v,x){for(l="number"==typeof l?l.toString():l||"";l.length<v;)l=x[0]+
l;return l}function f(l,v){return e(l,v,"0")}function k(l,v){function x(wc){return 0>wc?-1:0<wc?1:0}var X;0===(X=x(l.getFullYear()-v.getFullYear()))&&0===(X=x(l.getMonth()-v.getMonth()))&&(X=x(l.getDate()-v.getDate()));return X}function p(l){switch(l.getDay()){case 0:return new Date(l.getFullYear()-1,11,29);case 1:return l;case 2:return new Date(l.getFullYear(),0,3);case 3:return new Date(l.getFullYear(),0,2);case 4:return new Date(l.getFullYear(),0,1);case 5:return new Date(l.getFullYear()-1,11,
31);case 6:return new Date(l.getFullYear()-1,11,30)}}function r(l){var v=l.Mc;for(l=new Date((new Date(l.Nc+1900,0,1)).getTime());0<v;){var x=l.getMonth(),X=(Ca(l.getFullYear())?Sc:Tc)[x];if(v>X-l.getDate())v-=X-l.getDate()+1,l.setDate(1),11>x?l.setMonth(x+1):(l.setMonth(0),l.setFullYear(l.getFullYear()+1));else{l.setDate(l.getDate()+v);break}}x=new Date(l.getFullYear()+1,0,4);v=p(new Date(l.getFullYear(),0,4));x=p(x);return 0>=k(v,l)?0>=k(x,l)?l.getFullYear()+1:l.getFullYear():l.getFullYear()-1}
var u=B[d+40>>2];d={Fd:B[d>>2],Ed:B[d+4>>2],Yc:B[d+8>>2],dd:B[d+12>>2],Zc:B[d+16>>2],Nc:B[d+20>>2],Lc:B[d+24>>2],Mc:B[d+28>>2],Xd:B[d+32>>2],Dd:B[d+36>>2],Gd:u?t(u):""};c=t(c);u={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U",
"%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var w in u)c=c.replace(new RegExp(w,"g"),u[w]);var I="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),P="January February March April May June July August September October November December".split(" ");u={"%a":function(l){return I[l.Lc].substring(0,3)},"%A":function(l){return I[l.Lc]},"%b":function(l){return P[l.Zc].substring(0,3)},"%B":function(l){return P[l.Zc]},"%C":function(l){return f((l.Nc+1900)/100|0,2)},"%d":function(l){return f(l.dd,
2)},"%e":function(l){return e(l.dd,2," ")},"%g":function(l){return r(l).toString().substring(2)},"%G":function(l){return r(l)},"%H":function(l){return f(l.Yc,2)},"%I":function(l){l=l.Yc;0==l?l=12:12<l&&(l-=12);return f(l,2)},"%j":function(l){for(var v=0,x=0;x<=l.Zc-1;v+=(Ca(l.Nc+1900)?Sc:Tc)[x++]);return f(l.dd+v,3)},"%m":function(l){return f(l.Zc+1,2)},"%M":function(l){return f(l.Ed,2)},"%n":function(){return"\n"},"%p":function(l){return 0<=l.Yc&&12>l.Yc?"AM":"PM"},"%S":function(l){return f(l.Fd,
2)},"%t":function(){return"\t"},"%u":function(l){return l.Lc||7},"%U":function(l){return f(Math.floor((l.Mc+7-l.Lc)/7),2)},"%V":function(l){var v=Math.floor((l.Mc+7-(l.Lc+6)%7)/7);2>=(l.Lc+371-l.Mc-2)%7&&v++;if(v)53==v&&(x=(l.Lc+371-l.Mc)%7,4==x||3==x&&Ca(l.Nc)||(v=1));else{v=52;var x=(l.Lc+7-l.Mc-1)%7;(4==x||5==x&&Ca(l.Nc%400-1))&&v++}return f(v,2)},"%w":function(l){return l.Lc},"%W":function(l){return f(Math.floor((l.Mc+7-(l.Lc+6)%7)/7),2)},"%y":function(l){return(l.Nc+1900).toString().substring(2)},
"%Y":function(l){return l.Nc+1900},"%z":function(l){l=l.Dd;var v=0<=l;l=Math.abs(l)/60;return(v?"+":"-")+String("0000"+(l/60*100+l%60)).slice(-4)},"%Z":function(l){return l.Gd},"%%":function(){return"%"}};c=c.replace(/%%/g,"\x00\x00");for(w in u)c.includes(w)&&(c=c.replace(new RegExp(w,"g"),u[w](d)));c=c.replace(/\0\0/g,"%");w=Uc(c);if(w.length>b)return 0;A.set(w,a);return w.length-1}};
(function(){function a(e){g.asm=e.exports;ha=g.asm.Dc;e=ha.buffer;g.HEAP8=A=new Int8Array(e);g.HEAP16=new Int16Array(e);g.HEAP32=B=new Int32Array(e);g.HEAPU8=y=new Uint8Array(e);g.HEAPU16=la=new Uint16Array(e);g.HEAPU32=C=new Uint32Array(e);g.HEAPF32=D=new Float32Array(e);g.HEAPF64=ma=new Float64Array(e);na=g.asm.Ic;pa.unshift(g.asm.Ec);E--;g.monitorRunDependencies&&g.monitorRunDependencies(E);0==E&&(null!==ua&&(clearInterval(ua),ua=null),va&&(e=va,va=null,e()))}function b(e){a(e.instance)}function c(e){return za().then(function(f){return WebAssembly.instantiate(f,
d)}).then(function(f){return f}).then(e,function(f){m("failed to asynchronously prepare wasm: "+f);n(f)})}var d={a:Xc};E++;g.monitorRunDependencies&&g.monitorRunDependencies(E);if(g.instantiateWasm)try{return g.instantiateWasm(d,a)}catch(e){return m("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return fa||"function"!=typeof WebAssembly.instantiateStreaming||wa()||"function"!=typeof fetch?c(b):fetch(F,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,
d).then(b,function(f){m("wasm streaming compile failed: "+f);m("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();function G(){return(G=g.asm.Fc).apply(null,arguments)}function Pc(){return(Pc=g.asm.Gc).apply(null,arguments)}var Yc=g._main=function(){return(Yc=g._main=g.asm.Hc).apply(null,arguments)};function Zc(){return(Zc=g.asm.Jc).apply(null,arguments)}var $c;va=function ad(){$c||bd();$c||(va=ad)};
function cd(a=[]){var b=Yc;a.unshift(ca);var c=a.length,d=Zc(4*(c+1)),e=d>>2;a.forEach(k=>{var p=B,r=e++,u=ka(k)+1,w=Zc(u);z(k,A,w,u);p[r]=w});B[e]=0;try{var f=b(c,d);qc(f,!0)}catch(k){vb(k)}}
function bd(){var a=ba;function b(){if(!$c&&($c=!0,g.calledRun=!0,!q)){Ba(pa);Ba(qa);if(g.onRuntimeInitialized)g.onRuntimeInitialized();dd&&cd(a);if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();sa.unshift(c)}Ba(sa)}}if(!(0<E)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)ta();Ba(oa);0<E||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},
1)):b())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var dd=!0;g.noInitialRun&&(dd=!1);bd();
