var g;g||(g=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},g),ba=[],ca="./this.program",da=(a,b)=>{throw b;},h="";"undefined"!=typeof document&&document.currentScript&&(h=document.currentScript.src);h=0!==h.indexOf("blob:")?h.substr(0,h.replace(/[?#].*/,"").lastIndexOf("/")+1):"";var ea=g.print||console.log.bind(console),m=g.printErr||console.error.bind(console);Object.assign(g,aa);aa=null;g.arguments&&(ba=g.arguments);g.thisProgram&&(ca=g.thisProgram);
g.quit&&(da=g.quit);var fa;g.wasmBinary&&(fa=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!=typeof WebAssembly&&ha("no native wasm support detected");var ia,n=!1,ja,ka,q,la,t,w,x,ma,na=[],oa=[],pa=[],qa=[],ra=[];function sa(){var a=g.preRun.shift();na.unshift(a)}var z=0,ta=null,ua=null;function ha(a){if(g.onAbort)g.onAbort(a);a="Aborted("+a+")";m(a);n=!0;ja=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}
function va(a){return a.startsWith("data:application/octet-stream;base64,")}var A;A="index.wasm";if(!va(A)){var wa=A;A=g.locateFile?g.locateFile(wa,h):h+wa}function xa(a){if(a==A&&fa)return new Uint8Array(fa);throw"both async and sync fetching of the wasm failed";}function ya(a){return fa||"function"!=typeof fetch?Promise.resolve().then(()=>xa(a)):fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>xa(a))}
function za(a,b,c){return ya(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{m(`failed to asynchronously prepare wasm: ${d}`);ha(d)})}function Aa(a,b){var c=A;fa||"function"!=typeof WebAssembly.instantiateStreaming||va(c)||"function"!=typeof fetch?za(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){m(`wasm streaming compile failed: ${e}`);m("falling back to ArrayBuffer instantiation");return za(c,a,b)}))}
function Ba(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Ca=a=>{for(;0<a.length;)a.shift()(g)},Da=a=>0===a%4&&(0!==a%100||0===a%400),Ea=[0,31,60,91,121,152,182,213,244,274,305,335],Fa=[0,31,59,90,120,151,181,212,243,273,304,334],Ga=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},B=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var k=a.charCodeAt(f);if(55296<=k&&57343>=k){var p=a.charCodeAt(++f);k=65536+((k&1023)<<10)|p&1023}if(127>=k){if(c>=d)break;
b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e},D=a=>{var b=Ga(a)+1,c=Ha(b);c&&B(a,q,c,b);return c},Ia=0;function Ja(){for(var a=E.length-1;0<=a;--a)Ka(a);E=[];La=[]}var La=[];
function Ma(){if(navigator.userActivation?navigator.userActivation.isActive:Ia&&Na.Id)for(var a=0;a<La.length;++a){var b=La[a];La.splice(a,1);--a;b.Td.apply(null,b.Kd)}}var E=[];function Ka(a){var b=E[a];b.target.removeEventListener(b.Qc,b.wd,b.qd);E.splice(a,1)}
function Oa(a){function b(d){++Ia;Na=a;Ma();a.xd(d);Ma();--Ia}if(!a.target)return-4;if(a.td)a.wd=b,a.target.addEventListener(a.Qc,b,a.qd),E.push(a),Pa||(qa.push(Ja),Pa=!0);else for(var c=0;c<E.length;++c)E[c].target==a.target&&E[c].Qc==a.Qc&&Ka(c--);return 0}
var Pa,Na,Qa,Ra="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,F=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ra)return Ra.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|k:(e&7)<<18|f<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
Sa=[0,document,window],Ta=a=>{a=2<a?a?F(q,a):"":a;return Sa[a]||document.querySelector(a)},Ua=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,k)=>b.drawElementsInstancedANGLE(c,d,e,f,k))},Va=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Wa=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Xa=1,Ya=[],G=[],Za=[],H=[],I=[],J=[],$a=[],ab=[],K=[],bb={},cb=4;function L(a){db||(db=a)}
var eb=a=>{for(var b=Xa++,c=a.length;c<b;c++)a[c]=null;return b},gb=(a,b)=>{a.dd||(a.dd=a.getContext,a.getContext=function(d,e){e=a.dd(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?fb(c,b):0},fb=(a,b)=>{var c=eb(ab),d={handle:c,attributes:b,version:b.Ad,Yc:a};a.canvas&&(a.canvas.Hd=d);ab[c]=d;("undefined"==typeof b.vd||b.vd)&&hb(d);return c},hb=a=>{a||(a=ib);if(!a.zd){a.zd=!0;var b=a.Yc;Ua(b);Va(b);Wa(b);b.Kc=b.getExtension("EXT_disjoint_timer_query");
b.Sd=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},jb={},db,ib,kb=[],lb=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=M[c](),k=f&&eb(d);f?(f.name=k,d[k]=f):L(1282);t[b+4*e>>2]=k}},mb=(a,b,c,d,e,f,k,p)=>{b=G[b];if(a=M[a](b,c))d=p&&B(a.name,q,p,d),e&&(t[e>>2]=d),f&&(t[f>>2]=a.size),k&&(t[k>>2]=a.type)},nb=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&L(1280);return;
case 36345:d=0;break;case 34466:var e=M.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=M.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":L(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:L(1280);return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:t[b+
4*a>>2]=e[a];break;case 2:x[b+4*a>>2]=e[a];break;case 4:ka[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){L(1280);m("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:L(1280);m("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:c=d;w[b>>2]=c;w[b+4>>2]=(c-w[b>>2])/4294967296;break;case 0:t[b>>2]=d;break;case 2:x[b>>2]=d;break;case 4:ka[b>>
0]=d?1:0}}else L(1281)},ob=(a,b,c)=>{if(c){a=M.Kc.getQueryObjectEXT(K[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;w[c>>2]=d;w[c+4>>2]=(d-w[c>>2])/4294967296}else L(1281)},pb=(a,b,c)=>{if(c){a=M.Kc.getQueryObjectEXT(K[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;t[c>>2]=d}else L(1281)},qb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),rb=a=>{var b=a.Oc,c=a.pd,d;if(!b)for(a.Oc=b={},a.od={},d=0;d<M.getProgramParameter(a,35718);++d){var e=M.getActiveUniform(a,d);var f=e.name;e=e.size;var k=qb(f);k=0<k?f.slice(0,
k):f;var p=a.cd;a.cd+=e;c[k]=[e,p];for(f=0;f<e;++f)b[p]=f,a.od[p++]=k}},N=a=>{var b=M.ud;if(b){var c=b.Oc[a];"number"==typeof c&&(b.Oc[a]=c=M.getUniformLocation(b,b.od[a]+(0<c?"["+c+"]":"")));return c}L(1282)},sb=(a,b,c,d)=>{if(c)if(a=G[a],rb(a),a=M.getUniform(a,N(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:t[c>>2]=a;break;case 2:x[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:t[c+4*b>>2]=a[b];break;case 2:x[c+4*b>>2]=a[b]}else L(1281)},tb=(a,b,c,d)=>{if(c)if(a=M.getVertexAttrib(a,
b),34975==b)t[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:t[c>>2]=a;break;case 2:x[c>>2]=a;break;case 5:t[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:t[c+4*b>>2]=a[b];break;case 2:x[c+4*b>>2]=a[b];break;case 5:t[c+4*b>>2]=Math.fround(a[b])}else L(1281)},ub=(a,b,c,d,e)=>{a-=5120;a=1==a?q:4==a?t:6==a?x:5==a||28922==a?w:la;var f=31-Math.clz32(a.BYTES_PER_ELEMENT),k=cb;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<
f)+k-1&-k)>>f)},O=[],vb=[],wb=a=>{a instanceof Ba||"unwind"==a||da(1,a)},xb=a=>{ja=a;if(!noExitRuntime){if(g.onExit)g.onExit(a);n=!0}da(a,new Ba(a))},yb=a=>{ja=a;xb(a)},zb=!1,P=null,Q=0,Ab=null,Bb=0,Cb=0,Db=0,R=0,Eb=[],Fb={},Gb,Hb,Ib,Jb=!1,Kb=!1,Lb=[];
function Mb(){function a(){Kb=document.pointerLockElement===g.canvas||document.mozPointerLockElement===g.canvas||document.webkitPointerLockElement===g.canvas||document.msPointerLockElement===g.canvas}if(!Nb){Nb=!0;var b=g.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),
b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),g.elementPointerLock&&b.addEventListener("click",c=>{!Kb&&g.canvas.requestPointerLock&&(g.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Ob(a,b,c,d){if(b&&g.Nc&&a==g.canvas)return g.Nc;var e;if(b){var f={antialias:!1,alpha:!1,Ad:1};if(d)for(var k in d)f[k]=d[k];if("undefined"!=typeof jb&&(e=gb(a,f)))var p=ab[e].Yc}else p=a.getContext("2d");if(!p)return null;c&&(b||"undefined"==typeof M||ha("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),g.Nc=p,b&&(ib=ab[e],g.Nc=M=ib&&ib.Yc),g.Vd=b,Lb.forEach(r=>r()),Mb());return p}var Pb=!1,Qb=void 0,Rb=void 0;
function Sb(a,b){function c(){Jb=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=Tb,Qb&&d.requestPointerLock(),Jb=!0,Rb?("undefined"!=typeof SDL&&(t[SDL.screen>>2]=w[SDL.screen>>2]|8388608),Ub(g.canvas),Vb()):Ub(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),Rb?("undefined"!=typeof SDL&&(t[SDL.screen>>2]=w[SDL.screen>>2]&
-8388609),Ub(g.canvas),Vb()):Ub(d));if(g.onFullScreen)g.onFullScreen(Jb);if(g.onFullscreen)g.onFullscreen(Jb)}Qb=a;Rb=b;"undefined"==typeof Qb&&(Qb=!0);"undefined"==typeof Rb&&(Rb=!1);var d=g.canvas;Pb||(Pb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}
function Tb(){if(!Jb)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var Wb=0;function Xb(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Wb)Wb=b+1E3/60;else for(;b+2>=Wb;)Wb+=1E3/60;setTimeout(a,Math.max(Wb-b,0))}}var Yb=0,Zb=0,$b=0,ac=0;
function bc(a){if(Kb)"mousemove"!=a.type&&"mozMovementX"in a?$b=ac=0:($b=a.movementX||a.mozMovementX||a.webkitMovementX||0,ac=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(Yb=SDL.Qd+$b,Zb=SDL.Rd+ac):(Yb+=$b,Zb+=ac);else{var b=g.canvas.getBoundingClientRect(),c=g.canvas.width,d=g.canvas.height,e="undefined"!=typeof window.scrollX?window.scrollX:window.pageXOffset,f="undefined"!=typeof window.scrollY?window.scrollY:window.pageYOffset;"touchstart"!==a.type&&"touchend"!==
a.type&&"touchmove"!==a.type&&(e=a.pageX-(e+b.left),a=a.pageY-(f+b.top),e*=c/b.width,a*=d/b.height,$b=e-Yb,ac=a-Zb,Yb=e,Zb=a)}}var cc=[];function Vb(){var a=g.canvas;cc.forEach(b=>b(a.width,a.height))}function dc(a,b,c){Ub(g.canvas,a,b);c||Vb()}
function Ub(a,b,c){b&&c?(a.Gd=b,a.yd=c):(b=a.Gd,c=a.yd);var d=b,e=c;g.forcedAspectRatio&&0<g.forcedAspectRatio&&(d/e<g.forcedAspectRatio?d=Math.round(e*g.forcedAspectRatio):e=Math.round(d/g.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}Rb?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var Nb,fc=(a,b)=>{Cb=a;Db=b;if(Ab)if(zb||(zb=!0),0==a)P=function(){var d=Math.max(0,Hb+b-ec())|0;setTimeout(Ib,d)};else if(1==a)P=function(){Xb(Ib)};else if(2==a){if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);postMessage("setimmediate","*")}}P=function(){setImmediate(Ib)}}},ec;ec=()=>performance.now();
var gc=(a,b,c,d,e)=>{!Ab||ha("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");Ab=a;Bb=d;var f=Q;zb=!1;Ib=function(){if(!n)if(0<Eb.length){var k=Eb.shift();k.Pd(k.Jd);if(Gb){var p=Gb,r=0==p%1?p-1:Math.floor(p);Gb=k.Nd?r:(8*p+(r+.5))/9}g.setStatus&&(k=g.statusMessage||"Please wait...",p=Gb,r=Fb.Od,p?p<r?g.setStatus(k+" ("+(r-p)+"/"+r+")"):g.setStatus(k):g.setStatus(""));
f<Q||setTimeout(Ib,0)}else if(!(f<Q))if(R=R+1|0,1==Cb&&1<Db&&0!=R%Db)P();else{0==Cb&&(Hb=ec());if(!(n||g.preMainLoop&&!1===g.preMainLoop())){if(!n)try{if(a(),!noExitRuntime)try{ja=k=ja,xb(k)}catch(v){wb(v)}}catch(v){wb(v)}g.postMainLoop&&g.postMainLoop()}f<Q||("object"==typeof SDL&&SDL.audio&&SDL.audio.Bd&&SDL.audio.Bd(),P())}};e||(b&&0<b?fc(0,1E3/b):fc(1,1),P());if(c)throw"unwind";},hc=[],ic,S=a=>{var b=hc[a];b||(a>=hc.length&&(hc.length=a+1),hc[a]=b=ic.get(a));return b},jc=(a,b,c,d)=>{Qa||(Qa=Ha(36));
a=Ta(a);return Oa({target:a,Qc:"resize",td:d,xd:(e=event)=>{if(e.target==a){var f=document.body;if(f){var k=Qa;t[k>>2]=e.detail;t[k+4>>2]=f.clientWidth;t[k+8>>2]=f.clientHeight;t[k+12>>2]=innerWidth;t[k+16>>2]=innerHeight;t[k+20>>2]=outerWidth;t[k+24>>2]=outerHeight;t[k+28>>2]=pageXOffset;t[k+32>>2]=pageYOffset;S(d)(10,k,b)&&e.preventDefault()}}},qd:c})},kc=[null,[],[]];
function lc(a,b,c,d){this.id=a;this.y=this.x=0;this.ad=!1;this.nd=this.md=0;this.width=b;this.height=c;this.ld=b;this.kd=c;this.title=d;this.attributes=U;this.buttons=0;this.keys=[];this.$c=[];this.ed=this.Rc=this.fd=this.jd=this.Pc=this.Zc=this.hd=this.sd=this.gd=this.rd=this.Xc=this.title=null}
var V=null,mc=null,W=null,nc=null,oc=null,U=null,pc={131073:0,131074:0,131075:1,131076:1,131077:1,131082:0,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0,139276:0},qc=a=>{switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;
case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;
case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 96;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;
case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;
case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 93:return 348;default:return-1}},rc=()=>{var a=
V,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);a.keys[343]&&(b|=8);return b},vc=a=>{V&&V.ed&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||S(V.ed)(V.id,a))},wc=(a,b)=>{if(V){var c=qc(a);if(-1!=c){var d=b&&V.keys[c];V.keys[c]=b;V.$c[a]=b;V.Rc&&(d&&(b=2),S(V.Rc)(V.id,c,a,b,rc()))}}},yc=()=>{xc()},zc=()=>{xc()},Ac=a=>{wc(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()},Bc=a=>{wc(a.keyCode,0)},Cc=()=>{if(V)for(var a=0;a<V.$c.length;++a)V.$c[a]&&wc(a,0)},Dc=
a=>{V&&(bc(a),a.target==g.canvas&&V.Zc&&V.Zc&&S(V.Zc)(V.id,Yb,Zb))},Ec=a=>{V&&a.target==g.canvas&&V.Pc&&S(V.Pc)(V.id,1)},Fc=a=>{V&&a.target==g.canvas&&V.Pc&&S(V.Pc)(V.id,0)},Gc=(a,b)=>{if(V&&(bc(a),a.target==g.canvas)){var c=a.button;0<c&&(c=1==c?2:1);if(1==b){V.buttons|=1<<c;try{a.target.setCapture()}catch(d){}}else V.buttons&=~(1<<c);V.hd&&S(V.hd)(V.id,c,b,rc())}},Hc=a=>{V&&Gc(a,1)},Ic=a=>{V&&Gc(a,0)},Jc=a=>{switch(a.type){case "DOMMouseScroll":var b=a.detail/3;break;case "mousewheel":b=a.wheelDelta/
120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=100;break;case 1:b/=3;break;case 2:b*=80;break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}b=-b;b=0==b?0:0<b?Math.max(b,1):Math.min(b,-1);if(V&&V.jd&&a.target==g.canvas){var c=b;b="mousewheel"==a.type?a.wheelDeltaX:a.deltaX;S(V.jd)(V.id,b,c);a.preventDefault()}},X={},Kc=[],Lc=null,xc=()=>{if(R!==Lc||!R){Kc=navigator.getGamepads?navigator.getGamepads():
navigator.webkitGetGamepads?navigator.webkitGetGamepads:[];Lc=R;for(var a=0;a<Kc.length;++a){var b=Kc[a];if(b){X[a]||(ea("glfw joystick connected:",a),X[a]={id:D(b.id),Md:b.buttons.length,Ld:b.axes.length,buttons:Ha(b.buttons.length),axes:Ha(4*b.axes.length)});for(var c=X[a],d=0;d<b.buttons.length;++d)ka[c.buttons+d>>0]=b.buttons[d].pressed;for(d=0;d<b.axes.length;++d)x[c.axes+4*d>>2]=b.axes[d]}else X[a]&&(ea("glfw joystick disconnected",a),Mc(X[a].id),Mc(X[a].buttons),Mc(X[a].axes),delete X[a])}}},
Nc=a=>{if(V&&V.fd&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length)return a.preventDefault(),!1},Oc=a=>{if(V&&V.fd)return a.preventDefault(),!1},Pc=[31,29,31,30,31,30,31,31,30,31,30,31],Qc=[31,28,31,30,31,30,31,31,30,31,30,31];function Rc(a){var b=Array(Ga(a)+1);B(a,b,0,b.length);return b}for(var M,Y=0;32>Y;++Y)kb.push(Array(Y));var Sc=new Float32Array(288);for(Y=0;288>Y;++Y)O[Y]=Sc.subarray(0,Y+1);var Tc=new Int32Array(288);for(Y=0;288>Y;++Y)vb[Y]=Tc.subarray(0,Y+1);
g.requestFullscreen=(a,b)=>Sb(a,b);g.requestAnimationFrame=a=>Xb(a);g.setCanvasSize=(a,b,c)=>dc(a,b,c);g.pauseMainLoop=()=>{P=null;Q++};g.resumeMainLoop=()=>{Q++;var a=Cb,b=Db,c=Ab;Ab=null;gc(c,0,!1,Bb,!0);fc(a,b);P()};g.getUserMedia=()=>{window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};g.createContext=(a,b,c,d)=>Ob(a,b,c,d);
var Uc={La:function(a,b,c){a=new Date(1E3*(b+2097152>>>0<4194305-!!a?(a>>>0)+4294967296*b:NaN));t[c>>2]=a.getSeconds();t[c+4>>2]=a.getMinutes();t[c+8>>2]=a.getHours();t[c+12>>2]=a.getDate();t[c+16>>2]=a.getMonth();t[c+20>>2]=a.getFullYear()-1900;t[c+24>>2]=a.getDay();t[c+28>>2]=(Da(a.getFullYear())?Ea:Fa)[a.getMonth()]+a.getDate()-1|0;t[c+36>>2]=-(60*a.getTimezoneOffset());b=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();t[c+32>>2]=(b!=
d&&a.getTimezoneOffset()==Math.min(d,b))|0},Na:(a,b,c)=>{function d(r){return(r=r.toTimeString().match(/\(([A-Za-z ]+)\)$/))?r[1]:"GMT"}var e=(new Date).getFullYear(),f=new Date(e,0,1),k=new Date(e,6,1);e=f.getTimezoneOffset();var p=k.getTimezoneOffset();w[a>>2]=60*Math.max(e,p);t[b>>2]=Number(e!=p);a=d(f);b=d(k);a=D(a);b=D(b);p<e?(w[c>>2]=a,w[c+4>>2]=b):(w[c>>2]=b,w[c+4>>2]=a)},Oa:()=>Date.now(),A:(a,b,c)=>{a=Ta(a);if(!a)return-4;a=0>Sa.indexOf(a)?a.getBoundingClientRect():{left:0,top:0};ma[b>>3]=
a.width;ma[c>>3]=a.height;return 0},na:function(a){M.activeTexture(a)},ma:(a,b)=>{M.attachShader(G[a],J[b])},Ea:(a,b)=>{M.Kc.beginQueryEXT(a,K[b])},la:(a,b,c)=>{M.bindAttribLocation(G[a],b,c?F(q,c):"")},ka:(a,b)=>{M.bindBuffer(a,Ya[b])},ja:(a,b)=>{M.bindFramebuffer(a,Za[b])},ia:(a,b)=>{M.bindRenderbuffer(a,H[b])},ha:(a,b)=>{M.bindTexture(a,I[b])},wa:a=>{M.bindVertexArray($a[a])},ga:function(a,b,c,d){M.blendColor(a,b,c,d)},ea:function(a){M.blendEquation(a)},da:function(a,b){M.blendEquationSeparate(a,
b)},ca:function(a,b){M.blendFunc(a,b)},ba:function(a,b,c,d){M.blendFuncSeparate(a,b,c,d)},aa:(a,b,c,d)=>{M.bufferData(a,c?q.subarray(c,c+b):b,d)},$:(a,b,c,d)=>{M.bufferSubData(a,b,q.subarray(d,d+c))},_:function(a){return M.checkFramebufferStatus(a)},Z:function(a){M.clear(a)},Y:function(a,b,c,d){M.clearColor(a,b,c,d)},X:function(a){M.clearDepth(a)},V:function(a){M.clearStencil(a)},U:(a,b,c,d)=>{M.colorMask(!!a,!!b,!!c,!!d)},T:a=>{M.compileShader(J[a])},S:(a,b,c,d,e,f,k,p)=>{M.compressedTexImage2D(a,
b,c,d,e,f,p?q.subarray(p,p+k):null)},R:(a,b,c,d,e,f,k,p,r)=>{M.compressedTexSubImage2D(a,b,c,d,e,f,k,r?q.subarray(r,r+p):null)},Q:function(a,b,c,d,e,f,k,p){M.copyTexImage2D(a,b,c,d,e,f,k,p)},P:function(a,b,c,d,e,f,k,p){M.copyTexSubImage2D(a,b,c,d,e,f,k,p)},O:()=>{var a=eb(G),b=M.createProgram();b.name=a;b.Uc=b.Sc=b.Tc=0;b.cd=1;G[a]=b;return a},N:a=>{var b=eb(J);J[b]=M.createShader(a);return b},M:function(a){M.cullFace(a)},K:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=Ya[d];e&&(M.deleteBuffer(e),
e.name=0,Ya[d]=null)}},J:(a,b)=>{for(var c=0;c<a;++c){var d=t[b+4*c>>2],e=Za[d];e&&(M.deleteFramebuffer(e),e.name=0,Za[d]=null)}},I:a=>{if(a){var b=G[a];b?(M.deleteProgram(b),b.name=0,G[a]=null):L(1281)}},Ga:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=K[d];e&&(M.Kc.deleteQueryEXT(e),K[d]=null)}},H:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=H[d];e&&(M.deleteRenderbuffer(e),e.name=0,H[d]=null)}},G:a=>{if(a){var b=J[a];b?(M.deleteShader(b),J[a]=null):L(1281)}},F:(a,b)=>{for(var c=0;c<a;c++){var d=
t[b+4*c>>2],e=I[d];e&&(M.deleteTexture(e),e.name=0,I[d]=null)}},va:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2];M.deleteVertexArray($a[d]);$a[d]=null}},E:function(a){M.depthFunc(a)},D:a=>{M.depthMask(!!a)},C:function(a,b){M.depthRange(a,b)},B:(a,b)=>{M.detachShader(G[a],J[b])},z:function(a){M.disable(a)},y:a=>{M.disableVertexAttribArray(a)},x:(a,b,c)=>{M.drawArrays(a,b,c)},ra:(a,b,c,d)=>{M.drawArraysInstanced(a,b,c,d)},sa:(a,b)=>{for(var c=kb[a],d=0;d<a;d++)c[d]=t[b+4*d>>2];M.drawBuffers(c)},w:(a,
b,c,d)=>{M.drawElements(a,b,c,d)},pa:(a,b,c,d,e)=>{M.drawElementsInstanced(a,b,c,d,e)},v:function(a){M.enable(a)},u:a=>{M.enableVertexAttribArray(a)},Da:a=>{M.Kc.endQueryEXT(a)},t:function(){M.finish()},s:function(){M.flush()},r:(a,b,c,d)=>{M.framebufferRenderbuffer(a,b,c,H[d])},q:(a,b,c,d,e)=>{M.framebufferTexture2D(a,b,c,I[d],e)},p:function(a){M.frontFace(a)},o:(a,b)=>{lb(a,b,"createBuffer",Ya)},m:(a,b)=>{lb(a,b,"createFramebuffer",Za)},Ha:(a,b)=>{for(var c=0;c<a;c++){var d=M.Kc.createQueryEXT();
if(!d){for(L(1282);c<a;)t[b+4*c++>>2]=0;break}var e=eb(K);d.name=e;K[e]=d;t[b+4*c>>2]=e}},l:(a,b)=>{lb(a,b,"createRenderbuffer",H)},k:(a,b)=>{lb(a,b,"createTexture",I)},ua:function(a,b){lb(a,b,"createVertexArray",$a)},n:function(a){M.generateMipmap(a)},j:(a,b,c,d,e,f,k)=>{mb("getActiveAttrib",a,b,c,d,e,f,k)},i:(a,b,c,d,e,f,k)=>{mb("getActiveUniform",a,b,c,d,e,f,k)},h:(a,b,c,d)=>{a=M.getAttachedShaders(G[a]);var e=a.length;e>b&&(e=b);t[c>>2]=e;for(b=0;b<e;++b)t[d+4*b>>2]=J.indexOf(a[b])},g:(a,b)=>
M.getAttribLocation(G[a],b?F(q,b):""),zc:(a,b)=>{nb(a,b,4)},yc:(a,b,c)=>{c?t[c>>2]=M.getBufferParameter(a,b):L(1281)},xc:()=>{var a=M.getError()||db;db=0;return a},wc:(a,b)=>{nb(a,b,2)},vc:(a,b,c,d)=>{a=M.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;t[d>>2]=a},uc:(a,b)=>{nb(a,b,0)},sc:(a,b,c,d)=>{a=M.getProgramInfoLog(G[a]);null===a&&(a="(unknown error)");b=0<b&&d?B(a,q,d,b):0;c&&(t[c>>2]=b)},tc:(a,b,c)=>{if(c)if(a>=Xa)L(1281);else if(a=
G[a],35716==b)a=M.getProgramInfoLog(a),null===a&&(a="(unknown error)"),t[c>>2]=a.length+1;else if(35719==b){if(!a.Uc)for(b=0;b<M.getProgramParameter(a,35718);++b)a.Uc=Math.max(a.Uc,M.getActiveUniform(a,b).name.length+1);t[c>>2]=a.Uc}else if(35722==b){if(!a.Sc)for(b=0;b<M.getProgramParameter(a,35721);++b)a.Sc=Math.max(a.Sc,M.getActiveAttrib(a,b).name.length+1);t[c>>2]=a.Sc}else if(35381==b){if(!a.Tc)for(b=0;b<M.getProgramParameter(a,35382);++b)a.Tc=Math.max(a.Tc,M.getActiveUniformBlockName(a,b).length+
1);t[c>>2]=a.Tc}else t[c>>2]=M.getProgramParameter(a,b);else L(1281)},ya:ob,Aa:pb,xa:ob,za:pb,Ba:(a,b,c)=>{c?t[c>>2]=M.Kc.getQueryEXT(a,b):L(1281)},rc:(a,b,c)=>{c?t[c>>2]=M.getRenderbufferParameter(a,b):L(1281)},oc:(a,b,c,d)=>{a=M.getShaderInfoLog(J[a]);null===a&&(a="(unknown error)");b=0<b&&d?B(a,q,d,b):0;c&&(t[c>>2]=b)},nc:(a,b,c,d)=>{a=M.getShaderPrecisionFormat(a,b);t[c>>2]=a.rangeMin;t[c+4>>2]=a.rangeMax;t[d>>2]=a.precision},mc:(a,b,c,d)=>{if(a=M.getShaderSource(J[a]))b=0<b&&d?B(a,q,d,b):0,c&&
(t[c>>2]=b)},qc:(a,b,c)=>{c?35716==b?(a=M.getShaderInfoLog(J[a]),null===a&&(a="(unknown error)"),t[c>>2]=a?a.length+1:0):35720==b?(a=M.getShaderSource(J[a]),t[c>>2]=a?a.length+1:0):t[c>>2]=M.getShaderParameter(J[a],b):L(1281)},lc:a=>{var b=bb[a];if(!b){switch(a){case 7939:b=M.getSupportedExtensions()||[];b=b.concat(b.map(d=>"GL_"+d));b=D(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=M.getParameter(a))||L(1280);b=b&&D(b);break;case 7938:b=D("OpenGL ES 2.0 ("+M.getParameter(7938)+
")");break;case 35724:b=M.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=D(b);break;default:L(1280)}bb[a]=b}return b},kc:(a,b,c)=>{c?x[c>>2]=M.getTexParameter(a,b):L(1281)},jc:(a,b,c)=>{c?t[c>>2]=M.getTexParameter(a,b):L(1281)},gc:(a,b)=>{b=b?F(q,b):"";if(a=G[a]){rb(a);var c=a.Oc,d=0,e=b,f=qb(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.pd[e])&&d<e[0]&&(d+=e[1],c[d]=
c[d]||M.getUniformLocation(a,b)))return d}else L(1281);return-1},ic:(a,b,c)=>{sb(a,b,c,2)},hc:(a,b,c)=>{sb(a,b,c,0)},cc:(a,b,c)=>{c?t[c>>2]=M.getVertexAttribOffset(a,b):L(1281)},fc:(a,b,c)=>{tb(a,b,c,2)},dc:(a,b,c)=>{tb(a,b,c,5)},bc:function(a,b){M.hint(a,b)},ac:a=>(a=Ya[a])?M.isBuffer(a):0,$b:function(a){return M.isEnabled(a)},_b:a=>(a=Za[a])?M.isFramebuffer(a):0,Zb:a=>(a=G[a])?M.isProgram(a):0,Fa:a=>(a=K[a])?M.Kc.isQueryEXT(a):0,Yb:a=>(a=H[a])?M.isRenderbuffer(a):0,Xb:a=>(a=J[a])?M.isShader(a):
0,Wb:a=>(a=I[a])?M.isTexture(a):0,ta:a=>(a=$a[a])?M.isVertexArray(a):0,Ub:function(a){M.lineWidth(a)},Tb:a=>{a=G[a];M.linkProgram(a);a.Oc=0;a.pd={}},Sb:(a,b)=>{3317==a&&(cb=b);M.pixelStorei(a,b)},Rb:function(a,b){M.polygonOffset(a,b)},Ca:(a,b)=>{M.Kc.queryCounterEXT(K[a],b)},Qb:(a,b,c,d,e,f,k)=>{(k=ub(f,e,c,d,k))?M.readPixels(a,b,c,d,e,f,k):L(1280)},Pb:()=>{},Ob:function(a,b,c,d){M.renderbufferStorage(a,b,c,d)},Nb:(a,b)=>{M.sampleCoverage(a,!!b)},Mb:function(a,b,c,d){M.scissor(a,b,c,d)},Lb:()=>{L(1280)},
Jb:(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var k=d?t[d+4*f>>2]:-1,p=t[c+4*f>>2];k=p?F(q,p,0>k?void 0:k):"";e+=k}M.shaderSource(J[a],e)},Ib:function(a,b,c){M.stencilFunc(a,b,c)},Hb:function(a,b,c,d){M.stencilFuncSeparate(a,b,c,d)},Gb:function(a){M.stencilMask(a)},Fb:function(a,b){M.stencilMaskSeparate(a,b)},Eb:function(a,b,c){M.stencilOp(a,b,c)},Db:function(a,b,c,d){M.stencilOpSeparate(a,b,c,d)},Cb:(a,b,c,d,e,f,k,p,r)=>{M.texImage2D(a,b,c,d,e,f,k,p,r?ub(p,k,d,e,r):null)},Bb:function(a,b,c){M.texParameterf(a,
b,c)},Ab:(a,b,c)=>{M.texParameterf(a,b,x[c>>2])},yb:function(a,b,c){M.texParameteri(a,b,c)},xb:(a,b,c)=>{M.texParameteri(a,b,t[c>>2])},wb:(a,b,c,d,e,f,k,p,r)=>{var v=null;r&&(v=ub(p,k,e,f,r));M.texSubImage2D(a,b,c,d,e,f,k,p,v)},vb:(a,b)=>{M.uniform1f(N(a),b)},ub:(a,b,c)=>{if(288>=b)for(var d=O[b-1],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);M.uniform1fv(N(a),d)},tb:(a,b)=>{M.uniform1i(N(a),b)},sb:(a,b,c)=>{if(288>=b)for(var d=vb[b-1],e=0;e<b;++e)d[e]=t[c+4*e>>2];else d=t.subarray(c>>
2,c+4*b>>2);M.uniform1iv(N(a),d)},rb:(a,b,c)=>{M.uniform2f(N(a),b,c)},qb:(a,b,c)=>{if(144>=b)for(var d=O[2*b-1],e=0;e<2*b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2];else d=x.subarray(c>>2,c+8*b>>2);M.uniform2fv(N(a),d)},pb:(a,b,c)=>{M.uniform2i(N(a),b,c)},nb:(a,b,c)=>{if(144>=b)for(var d=vb[2*b-1],e=0;e<2*b;e+=2)d[e]=t[c+4*e>>2],d[e+1]=t[c+(4*e+4)>>2];else d=t.subarray(c>>2,c+8*b>>2);M.uniform2iv(N(a),d)},mb:(a,b,c,d)=>{M.uniform3f(N(a),b,c,d)},lb:(a,b,c)=>{if(96>=b)for(var d=O[3*b-1],e=0;e<3*b;e+=
3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2];else d=x.subarray(c>>2,c+12*b>>2);M.uniform3fv(N(a),d)},kb:(a,b,c,d)=>{M.uniform3i(N(a),b,c,d)},jb:(a,b,c)=>{if(96>=b)for(var d=vb[3*b-1],e=0;e<3*b;e+=3)d[e]=t[c+4*e>>2],d[e+1]=t[c+(4*e+4)>>2],d[e+2]=t[c+(4*e+8)>>2];else d=t.subarray(c>>2,c+12*b>>2);M.uniform3iv(N(a),d)},ib:(a,b,c,d,e)=>{M.uniform4f(N(a),b,c,d,e)},hb:(a,b,c)=>{if(72>=b){var d=O[4*b-1],e=x;c>>=2;for(var f=0;f<4*b;f+=4){var k=c+f;d[f]=e[k];d[f+1]=e[k+1];d[f+2]=e[k+2];
d[f+3]=e[k+3]}}else d=x.subarray(c>>2,c+16*b>>2);M.uniform4fv(N(a),d)},gb:(a,b,c,d,e)=>{M.uniform4i(N(a),b,c,d,e)},fb:(a,b,c)=>{if(72>=b)for(var d=vb[4*b-1],e=0;e<4*b;e+=4)d[e]=t[c+4*e>>2],d[e+1]=t[c+(4*e+4)>>2],d[e+2]=t[c+(4*e+8)>>2],d[e+3]=t[c+(4*e+12)>>2];else d=t.subarray(c>>2,c+16*b>>2);M.uniform4iv(N(a),d)},eb:(a,b,c,d)=>{if(72>=b)for(var e=O[4*b-1],f=0;f<4*b;f+=4)e[f]=x[d+4*f>>2],e[f+1]=x[d+(4*f+4)>>2],e[f+2]=x[d+(4*f+8)>>2],e[f+3]=x[d+(4*f+12)>>2];else e=x.subarray(d>>2,d+16*b>>2);M.uniformMatrix2fv(N(a),
!!c,e)},cb:(a,b,c,d)=>{if(32>=b)for(var e=O[9*b-1],f=0;f<9*b;f+=9)e[f]=x[d+4*f>>2],e[f+1]=x[d+(4*f+4)>>2],e[f+2]=x[d+(4*f+8)>>2],e[f+3]=x[d+(4*f+12)>>2],e[f+4]=x[d+(4*f+16)>>2],e[f+5]=x[d+(4*f+20)>>2],e[f+6]=x[d+(4*f+24)>>2],e[f+7]=x[d+(4*f+28)>>2],e[f+8]=x[d+(4*f+32)>>2];else e=x.subarray(d>>2,d+36*b>>2);M.uniformMatrix3fv(N(a),!!c,e)},bb:(a,b,c,d)=>{if(18>=b){var e=O[16*b-1],f=x;d>>=2;for(var k=0;k<16*b;k+=16){var p=d+k;e[k]=f[p];e[k+1]=f[p+1];e[k+2]=f[p+2];e[k+3]=f[p+3];e[k+4]=f[p+4];e[k+5]=f[p+
5];e[k+6]=f[p+6];e[k+7]=f[p+7];e[k+8]=f[p+8];e[k+9]=f[p+9];e[k+10]=f[p+10];e[k+11]=f[p+11];e[k+12]=f[p+12];e[k+13]=f[p+13];e[k+14]=f[p+14];e[k+15]=f[p+15]}}else e=x.subarray(d>>2,d+64*b>>2);M.uniformMatrix4fv(N(a),!!c,e)},ab:a=>{a=G[a];M.useProgram(a);M.ud=a},$a:a=>{M.validateProgram(G[a])},_a:function(a,b){M.vertexAttrib1f(a,b)},Za:(a,b)=>{M.vertexAttrib1f(a,x[b>>2])},Ya:function(a,b,c){M.vertexAttrib2f(a,b,c)},Xa:(a,b)=>{M.vertexAttrib2f(a,x[b>>2],x[b+4>>2])},Wa:function(a,b,c,d){M.vertexAttrib3f(a,
b,c,d)},Va:(a,b)=>{M.vertexAttrib3f(a,x[b>>2],x[b+4>>2],x[b+8>>2])},Ta:function(a,b,c,d,e){M.vertexAttrib4f(a,b,c,d,e)},Sa:(a,b)=>{M.vertexAttrib4f(a,x[b>>2],x[b+4>>2],x[b+8>>2],x[b+12>>2])},oa:(a,b)=>{M.vertexAttribDivisor(a,b)},Ra:(a,b,c,d,e,f)=>{M.vertexAttribPointer(a,b,c,!!d,e,f)},Qa:function(a,b,c,d){M.viewport(a,b,c,d)},Pa:(a,b,c)=>q.copyWithin(a,b,b+c),Ma:()=>{ha("OOM")},fa:(a,b,c)=>{a=Ta(a);if(!a)return-4;a.width=b;a.height=c;return 0},Ka:(a,b,c)=>{a=S(a);gc(a,b,c)},Ua:(a,b,c,d)=>jc(a,b,
c,d),c:yb,f:(a,b,c,d)=>{for(var e=0,f=0;f<c;f++){var k=w[b>>2],p=w[b+4>>2];b+=8;for(var r=0;r<p;r++){var v=q[k+r],C=kc[a];0===v||10===v?((1===a?ea:m)(F(C,0)),C.length=0):C.push(v)}e+=p}w[d>>2]=e;return 0},Ac:(a,b,c,d)=>{var e;for(e=0;e<W.length&&null!==W[e];e++);if(0<e)throw"glfwCreateWindow only supports one window at time currently";var f=e+1;if(0>=a||0>=b)f=0;else{d?Sb():dc(a,b);for(e=0;e<W.length&&null==W[e];e++);d=0<U[139265];e==W.length&&(d?g.Nc=Ob(g.canvas,!0,!0,{antialias:1<U[135181],depth:0<
U[135173],stencil:0<U[135174],alpha:0<U[135172]}):Mb());!g.Nc&&d?f=0:(a=new lc(f,a,b,c),f-1==W.length?W.push(a):W[f-1]=a,V=a,f=a.id)}return f},Ia:a=>{a:{if(a=0>=a||!W?null:W[a-1]){a.rd&&S(a.rd)(a.id);W[a.id-1]=null;V.id==a.id&&(V=null);for(a=0;a<W.length;a++)if(null!==W[a]){a=void 0;break a}g.Nc=void 0}a=void 0}return a},pc:()=>1,d:()=>ec()/1E3-oc,W:()=>{nc||(nc=D("3.2.1 JS WebGL Emscripten"));return nc},ec:()=>0,L:()=>{if(W)return 1;oc=ec()/1E3;U=pc;W=[];V=null;mc=devicePixelRatio;window.addEventListener("gamepadconnected",
yc,!0);window.addEventListener("gamepaddisconnected",zc,!0);window.addEventListener("keydown",Ac,!0);window.addEventListener("keypress",vc,!0);window.addEventListener("keyup",Bc,!0);window.addEventListener("blur",Cc,!0);(function b(){window.matchMedia("(resolution: "+window.devicePixelRatio+"dppx)").addEventListener("change",b,{once:!0});mc=devicePixelRatio;V&&V.sd&&S(V.sd)(V.id,mc,mc)})();g.canvas.addEventListener("touchmove",Dc,!0);g.canvas.addEventListener("touchstart",Hc,!0);g.canvas.addEventListener("touchcancel",
Ic,!0);g.canvas.addEventListener("touchend",Ic,!0);g.canvas.addEventListener("mousemove",Dc,!0);g.canvas.addEventListener("mousedown",Hc,!0);g.canvas.addEventListener("mouseup",Ic,!0);g.canvas.addEventListener("wheel",Jc,!0);g.canvas.addEventListener("mousewheel",Jc,!0);g.canvas.addEventListener("mouseenter",Ec,!0);g.canvas.addEventListener("mouseleave",Fc,!0);g.canvas.addEventListener("drop",Nc,!0);g.canvas.addEventListener("dragover",Oc,!0);cc.push((b,c)=>{if(V){var d=!0;document.fullscreen||document.fullScreen||
document.mozFullScreen||document.webkitIsFullScreen?(V.md=V.x,V.nd=V.y,V.ld=V.width,V.kd=V.height,V.x=V.y=0,V.width=screen.width,V.height=screen.height,V.ad=!0):1==V.ad?(V.x=V.md,V.y=V.nd,V.width=V.ld,V.height=V.kd,V.ad=!1):V.width!=b||V.height!=c?(V.width=b,V.height=c):d=!1;d&&(dc(V.width,V.height,!0),V&&V.Xc&&S(V.Xc)(V.id,V.width,V.height),V&&V.gd&&S(V.gd)(V.id,V.width,V.height))}});return 1},zb:()=>{},Ja:()=>{},Kb:(a,b)=>{if(a=0>=a||!W?null:W[a-1]){var c=a.Rc;a.Rc=b;b=c}else b=null;return b},db:()=>
{},Vb:(a,b)=>{if(a=0>=a||!W?null:W[a-1]){var c=a.Xc;a.Xc=b;b=c}else b=null;return b},a:(a,b)=>{if(a=0>=a||!W?null:W[a-1])a.title=b,V.id==a.id&&(document.title=b?F(q,b):"")},qa:()=>{},ob:a=>{a=Math.abs(a);0==a?fc(0,0):fc(1,a)},e:()=>{window.removeEventListener("gamepadconnected",yc,!0);window.removeEventListener("gamepaddisconnected",zc,!0);window.removeEventListener("keydown",Ac,!0);window.removeEventListener("keypress",vc,!0);window.removeEventListener("keyup",Bc,!0);window.removeEventListener("blur",
Cc,!0);g.canvas.removeEventListener("touchmove",Dc,!0);g.canvas.removeEventListener("touchstart",Hc,!0);g.canvas.removeEventListener("touchcancel",Ic,!0);g.canvas.removeEventListener("touchend",Ic,!0);g.canvas.removeEventListener("mousemove",Dc,!0);g.canvas.removeEventListener("mousedown",Hc,!0);g.canvas.removeEventListener("mouseup",Ic,!0);g.canvas.removeEventListener("wheel",Jc,!0);g.canvas.removeEventListener("mousewheel",Jc,!0);g.canvas.removeEventListener("mouseenter",Ec,!0);g.canvas.removeEventListener("mouseleave",
Fc,!0);g.canvas.removeEventListener("drop",Nc,!0);g.canvas.removeEventListener("dragover",Oc,!0);g.canvas.width=g.canvas.height=1;V=W=null},b:(a,b)=>{U[a]=b},Bc:(a,b,c,d)=>{function e(l,u,y){for(l="number"==typeof l?l.toString():l||"";l.length<u;)l=y[0]+l;return l}function f(l,u){return e(l,u,"0")}function k(l,u){function y(sc){return 0>sc?-1:0<sc?1:0}var T;0===(T=y(l.getFullYear()-u.getFullYear()))&&0===(T=y(l.getMonth()-u.getMonth()))&&(T=y(l.getDate()-u.getDate()));return T}function p(l){switch(l.getDay()){case 0:return new Date(l.getFullYear()-
1,11,29);case 1:return l;case 2:return new Date(l.getFullYear(),0,3);case 3:return new Date(l.getFullYear(),0,2);case 4:return new Date(l.getFullYear(),0,1);case 5:return new Date(l.getFullYear()-1,11,31);case 6:return new Date(l.getFullYear()-1,11,30)}}function r(l){var u=l.Lc;for(l=new Date((new Date(l.Mc+1900,0,1)).getTime());0<u;){var y=l.getMonth(),T=(Da(l.getFullYear())?Pc:Qc)[y];if(u>T-l.getDate())u-=T-l.getDate()+1,l.setDate(1),11>y?l.setMonth(y+1):(l.setMonth(0),l.setFullYear(l.getFullYear()+
1));else{l.setDate(l.getDate()+u);break}}y=new Date(l.getFullYear()+1,0,4);u=p(new Date(l.getFullYear(),0,4));y=p(y);return 0>=k(u,l)?0>=k(y,l)?l.getFullYear()+1:l.getFullYear():l.getFullYear()-1}var v=w[d+40>>2];d={Ed:t[d>>2],Dd:t[d+4>>2],Vc:t[d+8>>2],bd:t[d+12>>2],Wc:t[d+16>>2],Mc:t[d+20>>2],Jc:t[d+24>>2],Lc:t[d+28>>2],Ud:t[d+32>>2],Cd:t[d+36>>2],Fd:v?v?F(q,v):"":""};c=c?F(q,c):"";v={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S",
"%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var C in v)c=c.replace(new RegExp(C,"g"),v[C]);var tc="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),uc="January February March April May June July August September October November December".split(" ");v={"%a":l=>tc[l.Jc].substring(0,
3),"%A":l=>tc[l.Jc],"%b":l=>uc[l.Wc].substring(0,3),"%B":l=>uc[l.Wc],"%C":l=>f((l.Mc+1900)/100|0,2),"%d":l=>f(l.bd,2),"%e":l=>e(l.bd,2," "),"%g":l=>r(l).toString().substring(2),"%G":l=>r(l),"%H":l=>f(l.Vc,2),"%I":l=>{l=l.Vc;0==l?l=12:12<l&&(l-=12);return f(l,2)},"%j":l=>{for(var u=0,y=0;y<=l.Wc-1;u+=(Da(l.Mc+1900)?Pc:Qc)[y++]);return f(l.bd+u,3)},"%m":l=>f(l.Wc+1,2),"%M":l=>f(l.Dd,2),"%n":()=>"\n","%p":l=>0<=l.Vc&&12>l.Vc?"AM":"PM","%S":l=>f(l.Ed,2),"%t":()=>"\t","%u":l=>l.Jc||7,"%U":l=>f(Math.floor((l.Lc+
7-l.Jc)/7),2),"%V":l=>{var u=Math.floor((l.Lc+7-(l.Jc+6)%7)/7);2>=(l.Jc+371-l.Lc-2)%7&&u++;if(u)53==u&&(y=(l.Jc+371-l.Lc)%7,4==y||3==y&&Da(l.Mc)||(u=1));else{u=52;var y=(l.Jc+7-l.Lc-1)%7;(4==y||5==y&&Da(l.Mc%400-1))&&u++}return f(u,2)},"%w":l=>l.Jc,"%W":l=>f(Math.floor((l.Lc+7-(l.Jc+6)%7)/7),2),"%y":l=>(l.Mc+1900).toString().substring(2),"%Y":l=>l.Mc+1900,"%z":l=>{l=l.Cd;var u=0<=l;l=Math.abs(l)/60;return(u?"+":"-")+String("0000"+(l/60*100+l%60)).slice(-4)},"%Z":l=>l.Fd,"%%":()=>"%"};c=c.replace(/%%/g,
"\x00\x00");for(C in v)c.includes(C)&&(c=c.replace(new RegExp(C,"g"),v[C](d)));c=c.replace(/\0\0/g,"%");C=Rc(c);if(C.length>b)return 0;ka.set(C,a);return C.length-1}},Z=function(){function a(c){Z=c.exports;ia=Z.Cc;c=ia.buffer;g.HEAP8=ka=new Int8Array(c);g.HEAP16=new Int16Array(c);g.HEAPU8=q=new Uint8Array(c);g.HEAPU16=la=new Uint16Array(c);g.HEAP32=t=new Int32Array(c);g.HEAPU32=w=new Uint32Array(c);g.HEAPF32=x=new Float32Array(c);g.HEAPF64=ma=new Float64Array(c);ic=Z.Hc;oa.unshift(Z.Dc);z--;g.monitorRunDependencies&&
g.monitorRunDependencies(z);0==z&&(null!==ta&&(clearInterval(ta),ta=null),ua&&(c=ua,ua=null,c()));return Z}var b={a:Uc};z++;g.monitorRunDependencies&&g.monitorRunDependencies(z);if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(c){return m(`Module.instantiateWasm callback failed with error: ${c}`),!1}Aa(b,function(c){a(c.instance)});return{}}(),Ha=a=>(Ha=Z.Ec)(a),Mc=a=>(Mc=Z.Fc)(a),Vc=g._main=(a,b)=>(Vc=g._main=Z.Gc)(a,b),Wc=a=>(Wc=Z.Ic)(a),Xc;ua=function Yc(){Xc||Zc();Xc||(ua=Yc)};
function $c(a=[]){var b=Vc;a.unshift(ca);var c=a.length,d=Wc(4*(c+1)),e=d;a.forEach(k=>{var p=w,r=e>>2,v=Ga(k)+1,C=Wc(v);B(k,q,C,v);p[r]=C;e+=4});w[e>>2]=0;try{var f=b(c,d);yb(f,!0)}catch(k){wb(k)}}
function Zc(){var a=ba;function b(){if(!Xc&&(Xc=!0,g.calledRun=!0,!n)){Ca(oa);Ca(pa);if(g.onRuntimeInitialized)g.onRuntimeInitialized();ad&&$c(a);if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();ra.unshift(c)}Ca(ra)}}if(!(0<z)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)sa();Ca(na);0<z||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},
1)):b())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var ad=!0;g.noInitialRun&&(ad=!1);Zc();
