var h;h||(h=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},h),ba=[],ca="./this.program",da=(a,b)=>{throw b;},k="",ea;"undefined"!=typeof document&&document.currentScript&&(k=document.currentScript.src);k=0!==k.indexOf("blob:")?k.substr(0,k.replace(/[?#].*/,"").lastIndexOf("/")+1):"";ea=a=>{document.title=a};var fa=h.print||console.log.bind(console),l=h.printErr||console.warn.bind(console);Object.assign(h,aa);aa=null;h.arguments&&(ba=h.arguments);
h.thisProgram&&(ca=h.thisProgram);h.quit&&(da=h.quit);var ha;h.wasmBinary&&(ha=h.wasmBinary);var noExitRuntime=h.noExitRuntime||!0;"object"!=typeof WebAssembly&&r("no native wasm support detected");var ia,ja=!1,ka="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function la(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&ka)return ka.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function t(a,b){return a?la(v,a,b):""}
function ma(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var m=a.charCodeAt(++f);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e}function y(a,b,c){return ma(a,v,b,c)}
function na(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}var A,v,oa,pa,B,C,D,E,qa,ra=[],sa=[],ta=[],ua=[],va=[];function wa(){var a=h.preRun.shift();ra.unshift(a)}var xa=0,ya=null,za=null;function r(a){if(h.onAbort)h.onAbort(a);a="Aborted("+a+")";l(a);ja=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function Aa(){return F.startsWith("data:application/octet-stream;base64,")}var F;
F="index.wasm";if(!Aa()){var Ba=F;F=h.locateFile?h.locateFile(Ba,k):k+Ba}function Ca(){var a=F;try{if(a==F&&ha)return new Uint8Array(ha);throw"both async and sync fetching of the wasm failed";}catch(b){r(b)}}function Da(){return ha||"function"!=typeof fetch?Promise.resolve().then(function(){return Ca()}):fetch(F,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+F+"'";return a.arrayBuffer()}).catch(function(){return Ca()})}
var Ea,Fa,Ja={149744:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,149891:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,150125:a=>{"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.de||("undefined"!==typeof AudioContext?b.de=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.de=new webkitAudioContext),
b.de&&Ga(b.de));return void 0===b.de?-1:0},150618:()=>h.SDL2.de.sampleRate,150686:(a,b,c,d)=>{function e(){}function f(m){void 0!==g.capture.we&&(clearTimeout(g.capture.we),g.capture.we=void 0);g.capture.ze=g.de.createMediaStreamSource(m);g.capture.fe=g.de.createScriptProcessor(b,a,1);g.capture.fe.onaudioprocess=function(p){void 0!==g&&void 0!==g.capture&&(p.outputBuffer.getChannelData(0).fill(0),g.capture.Ge=p.inputBuffer,Ha(c,[d]))};g.capture.ze.connect(g.capture.fe);g.capture.fe.connect(g.de.destination);
g.capture.stream=m}var g=h.SDL2;g.capture.Ae=g.de.createBuffer(a,b,g.de.sampleRate);g.capture.Ae.getChannelData(0).fill(0);g.capture.we=setTimeout(function(){g.capture.Ge=g.capture.Ae;Ha(c,[d])},b/g.de.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},152338:(a,b,c,d)=>{var e=h.SDL2;e.audio.fe=
e.de.createScriptProcessor(b,0,a);e.audio.fe.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(e.audio.Me=f.outputBuffer,Ha(c,[d]))};e.audio.fe.connect(e.de.destination)},152748:(a,b)=>{for(var c=h.SDL2,d=c.capture.Ge.numberOfChannels,e=0;e<d;++e){var f=c.capture.Ge.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var g=0;g<b;++g)Ia(a+4*g,f[g]);else for(g=0;g<b;++g)Ia(a+4*(g*d+e),
f[g])}},153353:(a,b)=>{for(var c=h.SDL2,d=c.audio.Me.numberOfChannels,e=0;e<d;++e){var f=c.audio.Me.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=D[a+(g*d+e<<2)>>2]}},153833:a=>{var b=h.SDL2;if(a){void 0!==b.capture.we&&clearTimeout(b.capture.we);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);
b.capture.stream=void 0}void 0!==b.capture.fe&&(b.capture.fe.onaudioprocess=function(){},b.capture.fe.disconnect(),b.capture.fe=void 0);void 0!==b.capture.ze&&(b.capture.ze.disconnect(),b.capture.ze=void 0);void 0!==b.capture.Ae&&(b.capture.Ae=void 0);b.capture=void 0}else void 0!=b.audio.fe&&(b.audio.fe.disconnect(),b.audio.fe=void 0),b.audio=void 0;void 0!==b.de&&void 0===b.audio&&void 0===b.capture&&(b.de.close(),b.de=void 0)},155005:(a,b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;d.Ue!==h.canvas&&
(d.ke=h.createContext(h.canvas,!1,!0),d.Ue=h.canvas);if(d.w!==a||d.df!==b||d.ff!==d.ke)d.image=d.ke.createImageData(a,b),d.w=a,d.df=b,d.ff=d.ke;a=d.image.data;b=c>>2;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=B[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.We!==a&&(d.Ve=new Int32Array(a.buffer),d.Xe=new Uint8Array(a.buffer),d.We=a),a=d.Ve,c=a.length,a.set(B.subarray(b,b+c)),a=d.Xe,b=3,e=b+4*c,0==c%8)for(;b<
e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.ke.putImageData(d.image,0,0)},156474:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e>>=2;var m=0,p;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(p=b.length;m<p;){var q=B[e];b[m]=q&255;b[m+1]=q>>8&255;b[m+2]=q>>16&
255;b[m+3]=q>>24&255;e++;m+=4}else b=new Int32Array(b.buffer),p=b.length,b.set(B.subarray(e,e+p));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=G(c.length+1);y(c,d,c.length+1);return d},157463:a=>{h.canvas&&(h.canvas.style.cursor=t(a))},157546:()=>{h.canvas&&(h.canvas.style.cursor="none")},157615:()=>window.innerWidth,157645:()=>window.innerHeight};
function Ka(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}function La(a,b,c){a.addEventListener(b,c,{once:!0})}function Ga(a){var b;b||(b=[document,document.getElementById("canvas")]);["keydown","mousedown","touchstart"].forEach(function(c){b.forEach(function(d){d&&La(d,c,()=>{"suspended"===a.state&&a.resume()})})})}function Ma(a){for(;0<a.length;)a.shift()(h)}var Na=[];
function H(a){var b=Na[a];b||(a>=Na.length&&(Na.length=a+1),Na[a]=b=qa.get(a));return b}function Ha(a,b){if("vi".includes("j")){var c=h.dynCall_vi;b&&b.length?c.apply(null,[a].concat(b)):c.call(null,a)}else H(a).apply(null,b)}
function Ia(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":A[a>>0]=b;break;case "i8":A[a>>0]=b;break;case "i16":oa[a>>1]=b;break;case "i32":B[a>>2]=b;break;case "i64":Fa=[b>>>0,(Ea=b,1<=+Math.abs(Ea)?0<Ea?(Math.min(+Math.floor(Ea/4294967296),4294967295)|0)>>>0:~~+Math.ceil((Ea-+(~~Ea>>>0))/4294967296)>>>0:0)];B[a>>2]=Fa[0];B[a+4>>2]=Fa[1];break;case "float":D[a>>2]=b;break;case "double":E[a>>3]=b;break;case "*":C[a>>2]=b;break;default:r("invalid type for setValue: "+c)}}
function Oa(a){return 0===a%4&&(0!==a%100||0===a%400)}var Pa=[0,31,60,91,121,152,182,213,244,274,305,335],Qa=[0,31,59,90,120,151,181,212,243,273,304,334];function Ra(a){var b=na(a)+1,c=G(b);c&&ma(a,A,c,b);return c}
function Sa(a,b){Ta=a;Ua=b;if(Va)if(Wa||(Wa=!0),0==a)I=function(){var d=Math.max(0,Xa+b-Ya())|0;setTimeout(Za,d)};else if(1==a)I=function(){$a(Za)};else if(2==a){if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);postMessage("setimmediate","*")}}I=function(){setImmediate(Za)}}}var Ya;Ya=()=>performance.now();
function bb(a,b,c,d,e){!Va||r("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");Va=a;cb=d;var f=db;Wa=!1;Za=function(){if(!ja)if(0<eb.length){var g=Date.now(),m=eb.shift();m.vf(m.rf);if(fb){var p=fb,q=0==p%1?p-1:Math.floor(p);fb=m.tf?q:(8*p+(q+.5))/9}fa('main loop blocker "'+m.name+'" took '+(Date.now()-g)+" ms");h.setStatus&&(g=h.statusMessage||"Please wait...",
m=fb,p=gb.uf,m?m<p?h.setStatus(g+" ("+(p-m)+"/"+p+")"):h.setStatus(g):h.setStatus(""));f<db||setTimeout(Za,0)}else f<db||(hb=hb+1|0,1==Ta&&1<Ua&&0!=hb%Ua?I():(0==Ta&&(Xa=Ya()),ja||h.preMainLoop&&!1===h.preMainLoop()||(ib(a),h.postMainLoop&&h.postMainLoop()),f<db||("object"==typeof SDL&&SDL.audio&&SDL.audio.hf&&SDL.audio.hf(),I())))};e||(b&&0<b?Sa(0,1E3/b):Sa(1,1),I());if(c)throw"unwind";}function jb(a){a instanceof Ka||"unwind"==a||da(1,a)}function ib(a){if(!ja)try{a()}catch(b){jb(b)}}
function kb(a){setTimeout(function(){ib(a)},1E4)}function lb(a){mb||(mb={});mb[a]||(mb[a]=1,l(a))}var mb,Wa=!1,I=null,db=0,Va=null,cb=0,Ta=0,Ua=0,hb=0,eb=[],gb={},Xa,Za,fb,nb=!1,ob=!1,pb=[];
function qb(){function a(){ob=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}h.preloadPlugins||(h.preloadPlugins=[]);if(!rb){rb=!0;try{sb=!0}catch(c){sb=!1,l("warning: no blob constructor, cannot create blobs with mimetypes")}tb="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:sb?null:l("warning: no BlobBuilder");ub="undefined"!=
typeof window?window.URL?window.URL:window.webkitURL:void 0;h.Qe||"undefined"!=typeof ub||(l("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),h.Qe=!0);h.preloadPlugins.push({canHandle:function(c){return!h.Qe&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var g=null;if(sb)try{g=new Blob([c],{type:vb(d)}),g.size!==c.length&&(g=new Blob([(new Uint8Array(c)).buffer],{type:vb(d)}))}catch(q){lb("Blob constructor present but fails: "+
q+"; falling back to blob builder")}g||(g=new tb,g.append((new Uint8Array(c)).buffer),g=g.getBlob());var m=ub.createObjectURL(g),p=new Image;p.onload=()=>{p.complete||r("Image "+d+" could not be decoded");var q=document.createElement("canvas");q.width=p.width;q.height=p.height;q.getContext("2d").drawImage(p,0,0);ub.revokeObjectURL(m);e&&e(c)};p.onerror=()=>{fa("Image "+m+" could not be decoded");f&&f()};p.src=m}});h.preloadPlugins.push({canHandle:function(c){return!h.Af&&c.substr(-4)in{".ogg":1,".wav":1,
".mp3":1}},handle:function(c,d,e,f){function g(){p||(p=!0,e&&e(c))}function m(){p||(p=!0,new Audio,f&&f())}var p=!1;if(sb){try{var q=new Blob([c],{type:vb(d)})}catch(x){return m()}q=ub.createObjectURL(q);var u=new Audio;u.addEventListener("canplaythrough",()=>g(u),!1);u.onerror=function(){if(!p){l("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var x="",L=0,n=0,w=0;w<c.length;w++)for(L=L<<8|c[w],n+=8;6<=n;){var z=L>>n-6&63;n-=6;x+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[z]}2==
n?(x+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(L&3)<<4],x+="=="):4==n&&(x+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(L&15)<<2],x+="=");u.src="data:audio/x-"+d.substr(-3)+";base64,"+x;g(u)}};u.src=q;kb(function(){g(u)})}else return m()}});var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||
document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",c=>{!ob&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function wb(a,b,c,d){if(b&&h.ke&&a==h.canvas)return h.ke;var e;if(b){var f={antialias:!1,alpha:!1,Pe:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!=typeof xb&&(e=yb(a,f)))var m=J[e].pe}else m=a.getContext("2d");if(!m)return null;c&&(b||"undefined"==typeof K||r("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),h.ke=m,b&&zb(e),h.pf=b,pb.forEach(function(p){p()}),qb());return m}var Ab=!1,Bb=void 0,Cb=void 0;
function Db(a,b){function c(){nb=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=Eb,Bb&&d.requestPointerLock(),nb=!0,Cb?("undefined"!=typeof SDL&&(B[SDL.screen>>2]=C[SDL.screen>>2]|8388608),Fb(h.canvas),Gb()):Fb(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),Cb?("undefined"!=typeof SDL&&(B[SDL.screen>>2]=C[SDL.screen>>2]&
-8388609),Fb(h.canvas),Gb()):Fb(d));if(h.onFullScreen)h.onFullScreen(nb);if(h.onFullscreen)h.onFullscreen(nb)}Bb=a;Cb=b;"undefined"==typeof Bb&&(Bb=!0);"undefined"==typeof Cb&&(Cb=!1);var d=h.canvas;Ab||(Ab=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}
function Eb(){if(!nb)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var Hb=0;function $a(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Hb)Hb=b+1E3/60;else for(;b+2>=Hb;)Hb+=1E3/60;setTimeout(a,Math.max(Hb-b,0))}}
function vb(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Ib=[];function Gb(){var a=h.canvas;Ib.forEach(function(b){b(a.width,a.height)})}
function Fb(a,b,c){b&&c?(a.qf=b,a.ef=c):(b=a.qf,c=a.ef);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}Cb?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var rb,sb,tb,ub,M=12288,Jb=!1,Kb=0,Lb=0,Mb=0,N={alpha:!1,depth:!1,stencil:!1,antialias:!1},Nb={},Ob;function Pb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,g){b.drawElementsInstancedANGLE(c,d,e,f,g)})}
function Qb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Rb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}var Sb=1,Tb=[],O=[],Ub=[],Vb=[],Wb=[],P=[],Xb=[],J=[],Q=[],Yb={},Zb=4;
function R(a){$b||($b=a)}function ac(a){for(var b=Sb++,c=a.length;c<b;c++)a[c]=null;return b}function bc(a,b,c){for(var d="",e=0;e<a;++e){var f=c?B[c+4*e>>2]:-1;d+=t(B[b+4*e>>2],0>f?void 0:f)}return d}function yb(a,b){a.ye||(a.ye=a.getContext,a.getContext=function(d,e){e=a.ye(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?cc(c,b):0}
function cc(a,b){var c=ac(J),d={wf:c,attributes:b,version:b.Pe,pe:a};a.canvas&&(a.canvas.ve=d);J[c]=d;("undefined"==typeof b.$e||b.$e)&&dc(d);return c}function zb(a){ec=J[a];h.ke=K=ec&&ec.pe}function dc(a){a||(a=ec);if(!a.gf){a.gf=!0;var b=a.pe;Pb(b);Qb(b);Rb(b);b.ie=b.getExtension("EXT_disjoint_timer_query");b.zf=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var xb={},$b,ec,fc=[];
function gc(a,b){fc.length=0;var c;for(b>>=2;c=v[a++];)b+=105!=c&b,fc.push(105==c?B[b]:E[b++>>1]),++b;return fc}function hc(a){var b=ic();a=a();jc(b);return a}var kc=0;function lc(){for(var a=S.length-1;0<=a;--a)mc(a);S=[];T=[]}var T=[];function nc(a,b,c){function d(g,m){if(g.length!=m.length)return!1;for(var p in g)if(g[p]!=m[p])return!1;return!0}for(var e in T){var f=T[e];if(f.Ie==a&&d(f.Ke,c))return}T.push({Ie:a,Se:b,Ke:c});T.sort(function(g,m){return g.Se<m.Se})}
function oc(a){for(var b=0;b<T.length;++b)T[b].Ie==a&&(T.splice(b,1),--b)}function pc(){if(kc&&qc.re)for(var a=0;a<T.length;++a){var b=T[a];T.splice(a,1);--a;b.Ie.apply(null,b.Ke)}}var S=[];function mc(a){var b=S[a];b.target.removeEventListener(b.ee,b.af,b.ge);S.splice(a,1)}
function U(a){function b(d){++kc;qc=a;pc();a.je(d);pc();--kc}if(a.he)a.af=b,a.target.addEventListener(a.ee,b,a.ge),S.push(a),rc||(ua.push(lc),rc=!0);else for(var c=0;c<S.length;++c)S[c].target==a.target&&S[c].ee==a.ee&&mc(c--)}function sc(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}function tc(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}var uc={},rc,qc,vc,wc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc={},Ic=[0,document,window];
function W(a){a=2<a?t(a):a;return Ic[a]||document.querySelector(a)}function Jc(a){return hc(function(){var b=Kc(8),c=b+4,d=Kc(a.id.length+1);y(a.id,d,a.id.length+1);if(d=W(d))B[b>>2]=d.width,B[c>>2]=d.height;return[B[b>>2],B[c>>2]]})}function Lc(a,b,c){a=W(a);if(!a)return-4;a.width=b;a.height=c;return 0}function Mc(a,b,c){a.sf?hc(function(){var d=Kc(a.id.length+1);y(a.id,d,a.id.length+1);Lc(d,b,c)}):(a.width=b,a.height=c)}
function Nc(a){function b(){document.fullscreenElement||document.webkitFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),Mc(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=m,p||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=p,a.style.paddingLeft=q,a.style.paddingRight=u,a.style.paddingTop=x,a.style.paddingBottom=L,a.style.marginLeft=n,a.style.marginRight=w,a.style.marginTop=
z,a.style.marginBottom=V,document.body.style.margin=ab,document.documentElement.style.overflow=wd,document.body.scroll=xd,a.style.qe=yd,a.ve&&a.ve.pe.viewport(0,0,d,e),Hc.xe&&H(Hc.xe)(37,0,Hc.Le))}var c=Jc(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,m=a.style.backgroundColor,p=document.body.style.backgroundColor,q=a.style.paddingLeft,u=a.style.paddingRight,x=a.style.paddingTop,L=a.style.paddingBottom,n=a.style.marginLeft,w=a.style.marginRight,z=a.style.marginTop,V=a.style.marginBottom,ab=document.body.style.margin,
wd=document.documentElement.style.overflow,xd=document.body.scroll,yd=a.style.qe;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)}function Oc(a,b,c){a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"}function Pc(a){return 0>Ic.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function Qc(a,b){if(0!=b.He||0!=b.Fe){Nc(a);var c=b.jf?innerWidth:screen.width,d=b.jf?innerHeight:screen.height,e=Pc(a),f=e.width;e=e.height;var g=Jc(a),m=g[0];g=g[1];3==b.He?(Oc(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.He&&(c*g<m*d?(f=g*c/m,Oc(a,(d-f)/2,0),d=f):(f=m*d/g,Oc(a,0,(c-f)/2),c=f));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.cf&&(a.style.qe="optimizeSpeed",
a.style.qe="-moz-crisp-edges",a.style.qe="-o-crisp-edges",a.style.qe="-webkit-optimize-contrast",a.style.qe="optimize-contrast",a.style.qe="crisp-edges",a.style.qe="pixelated");f=2==b.Fe?devicePixelRatio:1;0!=b.Fe&&(c=c*f|0,d=d*f|0,Mc(a,c,d),a.ve&&a.ve.pe.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return tc()?-3:-1;Hc=b;b.xe&&H(b.xe)(37,0,b.Le);return 0}
function Rc(a){if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0}
function Sc(a,b){E[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)E[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)E[a+8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)B[a+4*c+1040>>2]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];B[a+1296>>2]=b.connected;B[a+1300>>2]=b.index;B[a+8>>2]=b.axes.length;B[a+12>>2]=b.buttons.length;y(b.id,a+1304,64);y(b.mapping,a+1368,64)}var Tc=[];
function Uc(a,b,c,d){for(var e=0;e<a;e++){var f=K[c](),g=f&&ac(d);f?(f.name=g,d[g]=f):R(1282);B[b+4*e>>2]=g}}function Vc(a,b,c,d,e,f,g,m){b=O[b];if(a=K[a](b,c))d=m&&y(a.name,m,d),e&&(B[e>>2]=d),f&&(B[f>>2]=a.size),g&&(B[g>>2]=a.type)}function Wc(a,b){C[a>>2]=b;C[a+4>>2]=(b-C[a>>2])/4294967296}
function Xc(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&R(1280);return;case 36345:d=0;break;case 34466:var e=K.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=K.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":R(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:R(1280);return}else{if(e instanceof Float32Array||
e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:B[b+4*a>>2]=e[a];break;case 2:D[b+4*a>>2]=e[a];break;case 4:A[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){R(1280);l("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:R(1280);l("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:Wc(b,
d);break;case 0:B[b>>2]=d;break;case 2:D[b>>2]=d;break;case 4:A[b>>0]=d?1:0}}else R(1281)}function Yc(a){var b=na(a)+1,c=G(b);y(a,c,b);return c}function Zc(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function $c(a){var b=a.ue,c=a.Ee,d;if(!b)for(a.ue=b={},a.Te={},d=0;d<K.getProgramParameter(a,35718);++d){var e=K.getActiveUniform(a,d);var f=e.name;e=e.size;var g=Zc(f);g=0<g?f.slice(0,g):f;var m=a.De;a.De+=e;c[g]=[e,m];for(f=0;f<e;++f)b[m]=f,a.Te[m++]=g}}
function X(a){var b=K.Ne;if(b){var c=b.ue[a];"number"==typeof c&&(b.ue[a]=c=K.getUniformLocation(b,b.Te[a]+(0<c?"["+c+"]":"")));return c}R(1282)}function ad(a,b,c,d){if(c)if(a=O[a],$c(a),a=K.getUniform(a,X(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:B[c>>2]=a;break;case 2:D[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:B[c+4*b>>2]=a[b];break;case 2:D[c+4*b>>2]=a[b]}else R(1281)}
function bd(a,b,c,d){if(c)if(a=K.getVertexAttrib(a,b),34975==b)B[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:B[c>>2]=a;break;case 2:D[c>>2]=a;break;case 5:B[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:B[c+4*b>>2]=a[b];break;case 2:D[c+4*b>>2]=a[b];break;case 5:B[c+4*b>>2]=Math.fround(a[b])}else R(1281)}
function cd(a,b,c,d,e){a-=5120;a=1==a?v:4==a?B:6==a?D:5==a||28922==a?C:pa;var f=31-Math.clz32(a.BYTES_PER_ELEMENT),g=Zb;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<f)+g-1&-g)>>f)}var Y=[],dd=[];function ed(a,b){if(!tc())return-1;a=W(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?kc&&qc.re?Qc(a,b):b.Ye?(nc(Qc,1,[a,b]),1):-2:-3:-4}
function fd(a,b){var c={target:W(2),ee:"beforeunload",he:b,je:function(d=event){var e=H(b)(28,0,a);e&&(e=t(e));if(e)return d.preventDefault(),d.returnValue=e},ge:!0};U(c)}function gd(a,b,c,d,e,f){wc||(wc=G(256));a={target:W(a),ee:f,he:d,je:function(g=event){var m=g.target.id?g.target.id:"",p=wc;y(sc(g.target),p+0,128);y(m,p+128,128);H(d)(e,p,b)&&g.preventDefault()},ge:c};U(a)}
function hd(a,b,c,d,e){yc||(yc=G(280));U({target:a,ee:e,he:d,je:function(f=event){var g=yc,m=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,p=!!m;B[g>>2]=p;B[g+4>>2]=tc();var q=p?m:xc,u=q&&q.id?q.id:"";y(sc(q),g+8,128);y(u,g+136,128);B[g+264>>2]=q?q.clientWidth:0;B[g+268>>2]=q?q.clientHeight:0;B[g+272>>2]=screen.width;B[g+276>>2]=screen.height;p&&(xc=m);H(d)(19,g,b)&&f.preventDefault()},ge:c})}
function jd(a,b,c,d,e){zc||(zc=G(1432));b={target:W(2),re:!0,ee:e,he:c,je:function(f=event){var g=zc;Sc(g,f.gamepad);H(c)(d,g,a)&&f.preventDefault()},ge:b};U(b)}
function kd(a,b,c,d,e,f){Ac||(Ac=G(176));a={target:W(a),re:!0,ee:f,he:d,je:function(g){var m=Ac;E[m>>3]=g.timeStamp;var p=m>>2;B[p+2]=g.location;B[p+3]=g.ctrlKey;B[p+4]=g.shiftKey;B[p+5]=g.altKey;B[p+6]=g.metaKey;B[p+7]=g.repeat;B[p+8]=g.charCode;B[p+9]=g.keyCode;B[p+10]=g.which;y(g.key||"",m+44,32);y(g.code||"",m+76,32);y(g.char||"",m+108,32);y(g.locale||"",m+140,32);H(d)(e,m,b)&&g.preventDefault()},ge:c};U(a)}
function ld(a,b,c){E[a>>3]=b.timeStamp;a>>=2;B[a+2]=b.screenX;B[a+3]=b.screenY;B[a+4]=b.clientX;B[a+5]=b.clientY;B[a+6]=b.ctrlKey;B[a+7]=b.shiftKey;B[a+8]=b.altKey;B[a+9]=b.metaKey;oa[2*a+20]=b.button;oa[2*a+21]=b.buttons;B[a+11]=b.movementX;B[a+12]=b.movementY;c=Pc(c);B[a+13]=b.clientX-c.left;B[a+14]=b.clientY-c.top}
function md(a,b,c,d,e,f){Bc||(Bc=G(72));a=W(a);U({target:a,re:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,ee:f,he:d,je:function(g=event){ld(Bc,g,a);H(d)(e,Bc,b)&&g.preventDefault()},ge:c})}function nd(a,b,c,d,e){Cc||(Cc=G(260));U({target:a,ee:e,he:d,je:function(f=event){var g=Cc,m=document.pointerLockElement||document.ye||document.bf||document.Ze;B[g>>2]=!!m;var p=m&&m.id?m.id:"";y(sc(m),g+4,128);y(p,g+132,128);H(d)(20,g,b)&&f.preventDefault()},ge:c})}
function od(a,b,c,d){Dc||(Dc=G(36));a=W(a);U({target:a,ee:"resize",he:d,je:function(e=event){if(e.target==a){var f=document.body;if(f){var g=Dc;B[g>>2]=e.detail;B[g+4>>2]=f.clientWidth;B[g+8>>2]=f.clientHeight;B[g+12>>2]=innerWidth;B[g+16>>2]=innerHeight;B[g+20>>2]=outerWidth;B[g+24>>2]=outerHeight;B[g+28>>2]=pageXOffset;B[g+32>>2]=pageYOffset;H(d)(10,g,b)&&e.preventDefault()}}},ge:c})}
function pd(a,b,c,d,e,f){Ec||(Ec=G(1696));a=W(a);U({target:a,re:"touchstart"==f||"touchend"==f,ee:f,he:d,je:function(g){for(var m,p={},q=g.touches,u=0;u<q.length;++u)m=q[u],m.Oe=m.Re=0,p[m.identifier]=m;for(u=0;u<g.changedTouches.length;++u)m=g.changedTouches[u],m.Oe=1,p[m.identifier]=m;for(u=0;u<g.targetTouches.length;++u)p[g.targetTouches[u].identifier].Re=1;q=Ec;E[q>>3]=g.timeStamp;var x=q>>2;B[x+3]=g.ctrlKey;B[x+4]=g.shiftKey;B[x+5]=g.altKey;B[x+6]=g.metaKey;x+=7;var L=Pc(a),n=0;for(u in p)if(m=
p[u],B[x]=m.identifier,B[x+1]=m.screenX,B[x+2]=m.screenY,B[x+3]=m.clientX,B[x+4]=m.clientY,B[x+5]=m.pageX,B[x+6]=m.pageY,B[x+7]=m.Oe,B[x+8]=m.Re,B[x+9]=m.clientX-L.left,B[x+10]=m.clientY-L.top,x+=13,31<++n)break;B[q+8>>2]=n;H(d)(e,q,b)&&g.preventDefault()},ge:c})}
function qd(a,b,c){var d=Ic[1];Fc||(Fc=G(8));U({target:d,ee:"visibilitychange",he:c,je:function(e=event){var f=Fc,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);B[f>>2]=document.hidden;B[f+4>>2]=g;H(c)(21,f,a)&&e.preventDefault()},ge:b})}
function rd(a,b,c,d){Gc||(Gc=G(104));U({target:a,re:!0,ee:"wheel",he:d,je:function(e=event){var f=Gc;ld(f,e,a);E[f+72>>3]=e.deltaX;E[f+80>>3]=e.deltaY;E[f+88>>3]=e.deltaZ;B[f+96>>2]=e.deltaMode;H(d)(9,f,b)&&e.preventDefault()},ge:c})}var sd={};
function td(){if(!ud){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in sd)void 0===sd[b]?delete a[b]:a[b]=sd[b];var c=[];for(b in a)c.push(b+"="+a[b]);ud=c}return ud}var ud,vd=[null,[],[]],zd=[31,29,31,30,31,30,31,31,30,31,30,31],Ad=[31,28,31,30,31,30,31,31,30,31,30,31];
function Bd(a){var b=Array(na(a)+1);ma(a,b,0,b.length);return b}function Cd(a){if(!noExitRuntime){if(h.onExit)h.onExit(a);ja=!0}da(a,new Ka(a))}h.requestFullscreen=function(a,b){Db(a,b)};h.requestAnimationFrame=function(a){$a(a)};h.setCanvasSize=function(a,b,c){Fb(h.canvas,a,b);c||Gb()};h.pauseMainLoop=function(){I=null;db++};h.resumeMainLoop=function(){db++;var a=Ta,b=Ua,c=Va;Va=null;bb(c,0,!1,cb,!0);Sa(a,b);I()};
h.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};h.createContext=function(a,b,c,d){return wb(a,b,c,d)};for(var K,Z=0;32>Z;++Z)Tc.push(Array(Z));var Dd=new Float32Array(288);for(Z=0;288>Z;++Z)Y[Z]=Dd.subarray(0,Z+1);var Ed=new Int32Array(288);for(Z=0;288>Z;++Z)dd[Z]=Ed.subarray(0,Z+1);
var Fd={_:function(){return 0},Za:function(){return 0},_a:function(){},$a:function(){return!0},bb:function(a,b){a=new Date(1E3*(C[a>>2]+4294967296*B[a+4>>2]));B[b>>2]=a.getSeconds();B[b+4>>2]=a.getMinutes();B[b+8>>2]=a.getHours();B[b+12>>2]=a.getDate();B[b+16>>2]=a.getMonth();B[b+20>>2]=a.getFullYear()-1900;B[b+24>>2]=a.getDay();B[b+28>>2]=(Oa(a.getFullYear())?Pa:Qa)[a.getMonth()]+a.getDate()-1|0;B[b+36>>2]=-(60*a.getTimezoneOffset());var c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset(),d=(new Date(a.getFullYear(),
0,1)).getTimezoneOffset();B[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},cb:function(a,b,c){function d(p){return(p=p.toTimeString().match(/\(([A-Za-z ]+)\)$/))?p[1]:"GMT"}var e=(new Date).getFullYear(),f=new Date(e,0,1),g=new Date(e,6,1);e=f.getTimezoneOffset();var m=g.getTimezoneOffset();C[a>>2]=60*Math.max(e,m);B[b>>2]=Number(e!=m);a=d(f);b=d(g);a=Ra(a);b=Ra(b);m<e?(C[c>>2]=a,C[c+4>>2]=b):(C[c>>2]=b,C[c+4>>2]=a)},Ha:function(a){if(12448==a)return M=12288,1;M=12300;return 0},Ka:function(a,
b,c,d,e){if(62E3!=a)M=12296,c=0;else{if(b)for(;;){a=B[b>>2];if(12321==a)N.alpha=0<B[b+4>>2];else if(12325==a)N.depth=0<B[b+4>>2];else if(12326==a)N.stencil=0<B[b+4>>2];else if(12337==a)a=B[b+4>>2],N.antialias=0<a;else if(12338==a)a=B[b+4>>2],N.antialias=1==a;else if(12544==a)N.xf=12547!=B[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(B[e>>2]=1),c&&0<d&&(B[c>>2]=62002),M=12288,c=1):(M=12300,c=0)}return c},xa:function(a,b,c,d){if(62E3!=a)return M=12296,0;for(a=1;;){b=B[d>>2];if(12440==b)a=B[d+4>>
2];else if(12344==b)break;else return M=12292,0;d+=8}if(2!=a)return M=12293,0;N.Pe=a-1;N.yf=0;Ob=yb(h.canvas,N);if(0!=Ob)return M=12288,zb(Ob),h.pf=!0,pb.forEach(function(e){e()}),zb(null),62004;M=12297;return 0},za:function(a,b){if(62E3!=a)return M=12296,0;if(62002!=b)return M=12293,0;M=12288;return 62006},ya:function(a,b){if(62E3!=a)return M=12296,0;if(62004!=b)return M=12294,0;a=Ob;ec===J[a]&&(ec=null);if("object"==typeof uc)for(var c=J[a].pe.canvas,d=0;d<S.length;++d)S[d].target!=c||mc(d--);J[a]&&
J[a].pe.canvas&&(J[a].pe.canvas.ve=void 0);J[a]=null;M=12288;Kb==b&&(Kb=0);return 1},Aa:function(a,b){if(62E3!=a)return M=12296,0;if(62006!=b)return M=12301,1;Lb==b&&(Lb=0);Mb==b&&(Mb=0);M=12288;return 1},La:function(a,b,c,d){if(62E3!=a)return M=12296,0;if(62002!=b)return M=12293,0;if(!d)return M=12300,0;M=12288;switch(c){case 12320:return B[d>>2]=N.alpha?32:24,1;case 12321:return B[d>>2]=N.alpha?8:0,1;case 12322:return B[d>>2]=8,1;case 12323:return B[d>>2]=8,1;case 12324:return B[d>>2]=8,1;case 12325:return B[d>>
2]=N.depth?24:0,1;case 12326:return B[d>>2]=N.stencil?8:0,1;case 12327:return B[d>>2]=12344,1;case 12328:return B[d>>2]=62002,1;case 12329:return B[d>>2]=0,1;case 12330:return B[d>>2]=4096,1;case 12331:return B[d>>2]=16777216,1;case 12332:return B[d>>2]=4096,1;case 12333:return B[d>>2]=0,1;case 12334:return B[d>>2]=0,1;case 12335:return B[d>>2]=12344,1;case 12337:return B[d>>2]=N.antialias?4:0,1;case 12338:return B[d>>2]=N.antialias?1:0,1;case 12339:return B[d>>2]=4,1;case 12340:return B[d>>2]=12344,
1;case 12341:case 12342:case 12343:return B[d>>2]=-1,1;case 12345:case 12346:return B[d>>2]=0,1;case 12347:return B[d>>2]=0,1;case 12348:return B[d>>2]=1;case 12349:case 12350:return B[d>>2]=0,1;case 12351:return B[d>>2]=12430,1;case 12352:return B[d>>2]=4,1;case 12354:return B[d>>2]=0,1;default:return M=12292,0}},S:function(){M=12288;return 62E3},wa:function(){return M},Ia:function(a,b,c){if(62E3!=a)return M=12296,0;b&&(B[b>>2]=1);c&&(B[c>>2]=4);Jb=!0;M=12288;return 1},Ba:function(a,b,c,d){if(62E3!=
a)return M=12296,0;if(0!=d&&62004!=d)return M=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return M=12301,0;zb(d?Ob:null);Kb=d;Mb=b;Lb=c;M=12288;return 1},va:function(a,b){if(62E3!=a)return M=12296,0;M=12288;if(Nb[b])return Nb[b];switch(b){case 12371:a=Ra("Emscripten");break;case 12372:a=Ra("1.4 Emscripten EGL");break;case 12373:a=Ra("");break;case 12429:a=Ra("OpenGL_ES");break;default:return M=12300,0}return Nb[b]=a},Ca:function(){if(Jb)if(h.ke)if(h.ke.isContextLost())M=12302;else return M=12288,1;
else M=12290;else M=12289;return 0},Da:function(a,b){if(62E3!=a)return M=12296,0;0==b?Sa(0,0):Sa(1,b);M=12288;return 1},Ja:function(a){if(62E3!=a)return M=12296,0;Mb=Lb=Kb=0;Jb=!1;M=12288;return 1},Ga:function(){M=12288;return 1},Fa:function(){M=12288;return 1},Oa:function(a,b,c){b=gc(b,c);return Ja[a].apply(null,b)},f:function(a,b,c){b=gc(b,c);return Ja[a].apply(null,b)},$:function(){return Date.now()},qa:function(){if(!tc())return-1;oc(Qc);var a=Ic[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();
else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},ta:function(){oc(Rc);if(document.exitPointerLock)document.exitPointerLock();else return-1;return 0},l:function(){return devicePixelRatio},h:function(a,b,c){a=W(a);if(!a)return-4;a=Pc(a);E[b>>3]=a.width;E[c>>3]=a.height;return 0},V:function(a,b){if(0>a||a>=vc.length)return-5;if(!vc[a])return-7;Sc(b,vc[a]);return 0},s:Ya,Na:function(){return vc.length},ua:function(a,b){B[a>>2]=screen.width;B[b>>
2]=screen.height},Pd:function(a){K.activeTexture(a)},Od:function(a,b){K.attachShader(O[a],P[b])},ma:function(a,b){K.ie.beginQueryEXT(a,Q[b])},Nd:function(a,b,c){K.bindAttribLocation(O[a],b,t(c))},Md:function(a,b){K.bindBuffer(a,Tb[b])},Ld:function(a,b){K.bindFramebuffer(a,Ub[b])},Jd:function(a,b){K.bindRenderbuffer(a,Vb[b])},Id:function(a,b){K.bindTexture(a,Wb[b])},da:function(a){K.bindVertexArray(Xb[a])},Hd:function(a,b,c,d){K.blendColor(a,b,c,d)},Gd:function(a){K.blendEquation(a)},Fd:function(a,
b){K.blendEquationSeparate(a,b)},Ed:function(a,b){K.blendFunc(a,b)},Dd:function(a,b,c,d){K.blendFuncSeparate(a,b,c,d)},Cd:function(a,b,c,d){K.bufferData(a,c?v.subarray(c,c+b):b,d)},Bd:function(a,b,c,d){K.bufferSubData(a,b,v.subarray(d,d+c))},Ad:function(a){return K.checkFramebufferStatus(a)},zd:function(a){K.clear(a)},yd:function(a,b,c,d){K.clearColor(a,b,c,d)},xd:function(a){K.clearDepth(a)},wd:function(a){K.clearStencil(a)},vd:function(a,b,c,d){K.colorMask(!!a,!!b,!!c,!!d)},ud:function(a){K.compileShader(P[a])},
td:function(a,b,c,d,e,f,g,m){K.compressedTexImage2D(a,b,c,d,e,f,m?v.subarray(m,m+g):null)},sd:function(a,b,c,d,e,f,g,m,p){K.compressedTexSubImage2D(a,b,c,d,e,f,g,p?v.subarray(p,p+m):null)},rd:function(a,b,c,d,e,f,g,m){K.copyTexImage2D(a,b,c,d,e,f,g,m)},qd:function(a,b,c,d,e,f,g,m){K.copyTexSubImage2D(a,b,c,d,e,f,g,m)},pd:function(){var a=ac(O),b=K.createProgram();b.name=a;b.oe=b.me=b.ne=0;b.De=1;O[a]=b;return a},od:function(a){var b=ac(P);P[b]=K.createShader(a);return b},nd:function(a){K.cullFace(a)},
md:function(a,b){for(var c=0;c<a;c++){var d=B[b+4*c>>2],e=Tb[d];e&&(K.deleteBuffer(e),e.name=0,Tb[d]=null)}},ld:function(a,b){for(var c=0;c<a;++c){var d=B[b+4*c>>2],e=Ub[d];e&&(K.deleteFramebuffer(e),e.name=0,Ub[d]=null)}},kd:function(a){if(a){var b=O[a];b?(K.deleteProgram(b),b.name=0,O[a]=null):R(1281)}},oa:function(a,b){for(var c=0;c<a;c++){var d=B[b+4*c>>2],e=Q[d];e&&(K.ie.deleteQueryEXT(e),Q[d]=null)}},jd:function(a,b){for(var c=0;c<a;c++){var d=B[b+4*c>>2],e=Vb[d];e&&(K.deleteRenderbuffer(e),
e.name=0,Vb[d]=null)}},id:function(a){if(a){var b=P[a];b?(K.deleteShader(b),P[a]=null):R(1281)}},hd:function(a,b){for(var c=0;c<a;c++){var d=B[b+4*c>>2],e=Wb[d];e&&(K.deleteTexture(e),e.name=0,Wb[d]=null)}},ca:function(a,b){for(var c=0;c<a;c++){var d=B[b+4*c>>2];K.deleteVertexArray(Xb[d]);Xb[d]=null}},gd:function(a){K.depthFunc(a)},ed:function(a){K.depthMask(!!a)},dd:function(a,b){K.depthRange(a,b)},cd:function(a,b){K.detachShader(O[a],P[b])},bd:function(a){K.disable(a)},ad:function(a){K.disableVertexAttribArray(a)},
$c:function(a,b,c){K.drawArrays(a,b,c)},Sd:function(a,b,c,d){K.drawArraysInstanced(a,b,c,d)},Td:function(a,b){for(var c=Tc[a],d=0;d<a;d++)c[d]=B[b+4*d>>2];K.drawBuffers(c)},_c:function(a,b,c,d){K.drawElements(a,b,c,d)},Rd:function(a,b,c,d,e){K.drawElementsInstanced(a,b,c,d,e)},Zc:function(a){K.enable(a)},Yc:function(a){K.enableVertexAttribArray(a)},ka:function(a){K.ie.endQueryEXT(a)},Xc:function(){K.finish()},Wc:function(){K.flush()},Vc:function(a,b,c,d){K.framebufferRenderbuffer(a,b,c,Vb[d])},Uc:function(a,
b,c,d,e){K.framebufferTexture2D(a,b,c,Wb[d],e)},Tc:function(a){K.frontFace(a)},Sc:function(a,b){Uc(a,b,"createBuffer",Tb)},Qc:function(a,b){Uc(a,b,"createFramebuffer",Ub)},pa:function(a,b){for(var c=0;c<a;c++){var d=K.ie.createQueryEXT();if(!d){for(R(1282);c<a;)B[b+4*c++>>2]=0;break}var e=ac(Q);d.name=e;Q[e]=d;B[b+4*c>>2]=e}},Pc:function(a,b){Uc(a,b,"createRenderbuffer",Vb)},Oc:function(a,b){Uc(a,b,"createTexture",Wb)},ba:function(a,b){Uc(a,b,"createVertexArray",Xb)},Rc:function(a){K.generateMipmap(a)},
Nc:function(a,b,c,d,e,f,g){Vc("getActiveAttrib",a,b,c,d,e,f,g)},Mc:function(a,b,c,d,e,f,g){Vc("getActiveUniform",a,b,c,d,e,f,g)},Lc:function(a,b,c,d){a=K.getAttachedShaders(O[a]);var e=a.length;e>b&&(e=b);B[c>>2]=e;for(b=0;b<e;++b)B[d+4*b>>2]=P.indexOf(a[b])},Kc:function(a,b){return K.getAttribLocation(O[a],t(b))},Jc:function(a,b){Xc(a,b,4)},Ic:function(a,b,c){c?B[c>>2]=K.getBufferParameter(a,b):R(1281)},Hc:function(){var a=K.getError()||$b;$b=0;return a},Gc:function(a,b){Xc(a,b,2)},Fc:function(a,
b,c,d){a=K.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;B[d>>2]=a},Ec:function(a,b){Xc(a,b,0)},Cc:function(a,b,c,d){a=K.getProgramInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?y(a,d,b):0;c&&(B[c>>2]=b)},Dc:function(a,b,c){if(c)if(a>=Sb)R(1281);else if(a=O[a],35716==b)a=K.getProgramInfoLog(a),null===a&&(a="(unknown error)"),B[c>>2]=a.length+1;else if(35719==b){if(!a.oe)for(b=0;b<K.getProgramParameter(a,35718);++b)a.oe=Math.max(a.oe,
K.getActiveUniform(a,b).name.length+1);B[c>>2]=a.oe}else if(35722==b){if(!a.me)for(b=0;b<K.getProgramParameter(a,35721);++b)a.me=Math.max(a.me,K.getActiveAttrib(a,b).name.length+1);B[c>>2]=a.me}else if(35381==b){if(!a.ne)for(b=0;b<K.getProgramParameter(a,35382);++b)a.ne=Math.max(a.ne,K.getActiveUniformBlockName(a,b).length+1);B[c>>2]=a.ne}else B[c>>2]=K.getProgramParameter(a,b);else R(1281)},fa:function(a,b,c){if(c){a=K.ie.getQueryObjectEXT(Q[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;Wc(c,d)}else R(1281)},
ha:function(a,b,c){if(c){a=K.ie.getQueryObjectEXT(Q[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;B[c>>2]=d}else R(1281)},ea:function(a,b,c){if(c){a=K.ie.getQueryObjectEXT(Q[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;Wc(c,d)}else R(1281)},ga:function(a,b,c){if(c){a=K.ie.getQueryObjectEXT(Q[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;B[c>>2]=d}else R(1281)},ia:function(a,b,c){c?B[c>>2]=K.ie.getQueryEXT(a,b):R(1281)},Bc:function(a,b,c){c?B[c>>2]=K.getRenderbufferParameter(a,b):R(1281)},zc:function(a,
b,c,d){a=K.getShaderInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?y(a,d,b):0;c&&(B[c>>2]=b)},yc:function(a,b,c,d){a=K.getShaderPrecisionFormat(a,b);B[c>>2]=a.rangeMin;B[c+4>>2]=a.rangeMax;B[d>>2]=a.precision},xc:function(a,b,c,d){if(a=K.getShaderSource(P[a]))b=0<b&&d?y(a,d,b):0,c&&(B[c>>2]=b)},Ac:function(a,b,c){c?35716==b?(a=K.getShaderInfoLog(P[a]),null===a&&(a="(unknown error)"),B[c>>2]=a?a.length+1:0):35720==b?(a=K.getShaderSource(P[a]),B[c>>2]=a?a.length+1:0):B[c>>2]=K.getShaderParameter(P[a],
b):R(1281)},wc:function(a){var b=Yb[a];if(!b){switch(a){case 7939:b=K.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Yc(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=K.getParameter(a))||R(1280);b=b&&Yc(b);break;case 7938:b=Yc("OpenGL ES 2.0 ("+K.getParameter(7938)+")");break;case 35724:b=K.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=
Yc(b);break;default:R(1280)}Yb[a]=b}return b},vc:function(a,b,c){c?D[c>>2]=K.getTexParameter(a,b):R(1281)},uc:function(a,b,c){c?B[c>>2]=K.getTexParameter(a,b):R(1281)},rc:function(a,b){b=t(b);if(a=O[a]){$c(a);var c=a.ue,d=0,e=b,f=Zc(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.Ee[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||K.getUniformLocation(a,b)))return d}else R(1281);return-1},tc:function(a,b,c){ad(a,b,c,2)},sc:function(a,b,c){ad(a,b,c,0)},oc:function(a,b,c){c?B[c>>2]=K.getVertexAttribOffset(a,
b):R(1281)},qc:function(a,b,c){bd(a,b,c,2)},pc:function(a,b,c){bd(a,b,c,5)},nc:function(a,b){K.hint(a,b)},mc:function(a){return(a=Tb[a])?K.isBuffer(a):0},lc:function(a){return K.isEnabled(a)},kc:function(a){return(a=Ub[a])?K.isFramebuffer(a):0},jc:function(a){return(a=O[a])?K.isProgram(a):0},na:function(a){return(a=Q[a])?K.ie.isQueryEXT(a):0},ic:function(a){return(a=Vb[a])?K.isRenderbuffer(a):0},hc:function(a){return(a=P[a])?K.isShader(a):0},gc:function(a){return(a=Wb[a])?K.isTexture(a):0},Ud:function(a){return(a=
Xb[a])?K.isVertexArray(a):0},fc:function(a){K.lineWidth(a)},ec:function(a){a=O[a];K.linkProgram(a);a.ue=0;a.Ee={}},dc:function(a,b){3317==a&&(Zb=b);K.pixelStorei(a,b)},cc:function(a,b){K.polygonOffset(a,b)},ja:function(a,b){K.ie.queryCounterEXT(Q[a],b)},bc:function(a,b,c,d,e,f,g){(g=cd(f,e,c,d,g))?K.readPixels(a,b,c,d,e,f,g):R(1280)},ac:function(){},$b:function(a,b,c,d){K.renderbufferStorage(a,b,c,d)},_b:function(a,b){K.sampleCoverage(a,!!b)},Zb:function(a,b,c,d){K.scissor(a,b,c,d)},Yb:function(){R(1280)},
Xb:function(a,b,c,d){b=bc(b,c,d);K.shaderSource(P[a],b)},Wb:function(a,b,c){K.stencilFunc(a,b,c)},Vb:function(a,b,c,d){K.stencilFuncSeparate(a,b,c,d)},Ub:function(a){K.stencilMask(a)},Tb:function(a,b){K.stencilMaskSeparate(a,b)},Sb:function(a,b,c){K.stencilOp(a,b,c)},Rb:function(a,b,c,d){K.stencilOpSeparate(a,b,c,d)},Qb:function(a,b,c,d,e,f,g,m,p){K.texImage2D(a,b,c,d,e,f,g,m,p?cd(m,g,d,e,p):null)},Pb:function(a,b,c){K.texParameterf(a,b,c)},Ob:function(a,b,c){K.texParameterf(a,b,D[c>>2])},Nb:function(a,
b,c){K.texParameteri(a,b,c)},Mb:function(a,b,c){K.texParameteri(a,b,B[c>>2])},Lb:function(a,b,c,d,e,f,g,m,p){var q=null;p&&(q=cd(m,g,e,f,p));K.texSubImage2D(a,b,c,d,e,f,g,m,q)},Kb:function(a,b){K.uniform1f(X(a),b)},Jb:function(a,b,c){if(288>=b)for(var d=Y[b-1],e=0;e<b;++e)d[e]=D[c+4*e>>2];else d=D.subarray(c>>2,c+4*b>>2);K.uniform1fv(X(a),d)},Ib:function(a,b){K.uniform1i(X(a),b)},Hb:function(a,b,c){if(288>=b)for(var d=dd[b-1],e=0;e<b;++e)d[e]=B[c+4*e>>2];else d=B.subarray(c>>2,c+4*b>>2);K.uniform1iv(X(a),
d)},Fb:function(a,b,c){K.uniform2f(X(a),b,c)},Eb:function(a,b,c){if(144>=b)for(var d=Y[2*b-1],e=0;e<2*b;e+=2)d[e]=D[c+4*e>>2],d[e+1]=D[c+(4*e+4)>>2];else d=D.subarray(c>>2,c+8*b>>2);K.uniform2fv(X(a),d)},Db:function(a,b,c){K.uniform2i(X(a),b,c)},Cb:function(a,b,c){if(144>=b)for(var d=dd[2*b-1],e=0;e<2*b;e+=2)d[e]=B[c+4*e>>2],d[e+1]=B[c+(4*e+4)>>2];else d=B.subarray(c>>2,c+8*b>>2);K.uniform2iv(X(a),d)},Bb:function(a,b,c,d){K.uniform3f(X(a),b,c,d)},Ab:function(a,b,c){if(96>=b)for(var d=Y[3*b-1],e=0;e<
3*b;e+=3)d[e]=D[c+4*e>>2],d[e+1]=D[c+(4*e+4)>>2],d[e+2]=D[c+(4*e+8)>>2];else d=D.subarray(c>>2,c+12*b>>2);K.uniform3fv(X(a),d)},zb:function(a,b,c,d){K.uniform3i(X(a),b,c,d)},yb:function(a,b,c){if(96>=b)for(var d=dd[3*b-1],e=0;e<3*b;e+=3)d[e]=B[c+4*e>>2],d[e+1]=B[c+(4*e+4)>>2],d[e+2]=B[c+(4*e+8)>>2];else d=B.subarray(c>>2,c+12*b>>2);K.uniform3iv(X(a),d)},xb:function(a,b,c,d,e){K.uniform4f(X(a),b,c,d,e)},wb:function(a,b,c){if(72>=b){var d=Y[4*b-1],e=D;c>>=2;for(var f=0;f<4*b;f+=4){var g=c+f;d[f]=e[g];
d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=D.subarray(c>>2,c+16*b>>2);K.uniform4fv(X(a),d)},ub:function(a,b,c,d,e){K.uniform4i(X(a),b,c,d,e)},tb:function(a,b,c){if(72>=b)for(var d=dd[4*b-1],e=0;e<4*b;e+=4)d[e]=B[c+4*e>>2],d[e+1]=B[c+(4*e+4)>>2],d[e+2]=B[c+(4*e+8)>>2],d[e+3]=B[c+(4*e+12)>>2];else d=B.subarray(c>>2,c+16*b>>2);K.uniform4iv(X(a),d)},sb:function(a,b,c,d){if(72>=b)for(var e=Y[4*b-1],f=0;f<4*b;f+=4)e[f]=D[d+4*f>>2],e[f+1]=D[d+(4*f+4)>>2],e[f+2]=D[d+(4*f+8)>>2],e[f+3]=D[d+(4*f+12)>>
2];else e=D.subarray(d>>2,d+16*b>>2);K.uniformMatrix2fv(X(a),!!c,e)},rb:function(a,b,c,d){if(32>=b)for(var e=Y[9*b-1],f=0;f<9*b;f+=9)e[f]=D[d+4*f>>2],e[f+1]=D[d+(4*f+4)>>2],e[f+2]=D[d+(4*f+8)>>2],e[f+3]=D[d+(4*f+12)>>2],e[f+4]=D[d+(4*f+16)>>2],e[f+5]=D[d+(4*f+20)>>2],e[f+6]=D[d+(4*f+24)>>2],e[f+7]=D[d+(4*f+28)>>2],e[f+8]=D[d+(4*f+32)>>2];else e=D.subarray(d>>2,d+36*b>>2);K.uniformMatrix3fv(X(a),!!c,e)},qb:function(a,b,c,d){if(18>=b){var e=Y[16*b-1],f=D;d>>=2;for(var g=0;g<16*b;g+=16){var m=d+g;e[g]=
f[m];e[g+1]=f[m+1];e[g+2]=f[m+2];e[g+3]=f[m+3];e[g+4]=f[m+4];e[g+5]=f[m+5];e[g+6]=f[m+6];e[g+7]=f[m+7];e[g+8]=f[m+8];e[g+9]=f[m+9];e[g+10]=f[m+10];e[g+11]=f[m+11];e[g+12]=f[m+12];e[g+13]=f[m+13];e[g+14]=f[m+14];e[g+15]=f[m+15]}}else e=D.subarray(d>>2,d+64*b>>2);K.uniformMatrix4fv(X(a),!!c,e)},pb:function(a){a=O[a];K.useProgram(a);K.Ne=a},ob:function(a){K.validateProgram(O[a])},nb:function(a,b){K.vertexAttrib1f(a,b)},mb:function(a,b){K.vertexAttrib1f(a,D[b>>2])},lb:function(a,b,c){K.vertexAttrib2f(a,
b,c)},kb:function(a,b){K.vertexAttrib2f(a,D[b>>2],D[b+4>>2])},jb:function(a,b,c,d){K.vertexAttrib3f(a,b,c,d)},ib:function(a,b){K.vertexAttrib3f(a,D[b>>2],D[b+4>>2],D[b+8>>2])},hb:function(a,b,c,d,e){K.vertexAttrib4f(a,b,c,d,e)},gb:function(a,b){K.vertexAttrib4f(a,D[b>>2],D[b+4>>2],D[b+8>>2],D[b+12>>2])},Qd:function(a,b){K.vertexAttribDivisor(a,b)},fb:function(a,b,c,d,e,f){K.vertexAttribPointer(a,b,c,!!d,e,f)},eb:function(a,b,c,d){K.viewport(a,b,c,d)},q:function(){return 0},db:function(a,b,c){v.copyWithin(a,
b,b+c)},ra:function(a,b,c){return ed(a,{He:B[c>>2],Fe:B[c+4>>2],cf:B[c+8>>2],Ye:b,xe:B[c+12>>2],Le:B[c+16>>2]})},Q:function(a,b){a=W(a);return a?a.requestPointerLock?kc&&qc.re?Rc(a):b?(nc(Rc,2,[a]),1):-2:-1:-4},Ua:function(){r("OOM")},ab:function(a){eval(t(a))},W:function(){return(vc=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads():null)?0:-1},v:function(a,b,c){if("undefined"==typeof onbeforeunload)return-1;if(1!==c)return-5;fd(a,b);return 0},
H:function(a,b,c,d){gd(a,b,c,d,12,"blur");return 0},k:Lc,o:function(a,b,c){a=W(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},I:function(a,b,c,d){gd(a,b,c,d,13,"focus");return 0},x:function(a,b,c,d){if(!tc())return-1;a=W(a);if(!a)return-4;hd(a,b,c,d,"fullscreenchange");hd(a,b,c,d,"webkitfullscreenchange");return 0},U:function(a,b,c){if(!navigator.getGamepads&&!navigator.webkitGetGamepads)return-1;jd(a,b,c,26,"gamepadconnected");return 0},T:function(a,b,c){if(!navigator.getGamepads&&
!navigator.webkitGetGamepads)return-1;jd(a,b,c,27,"gamepaddisconnected");return 0},B:function(a,b,c,d){kd(a,b,c,d,2,"keydown");return 0},z:function(a,b,c,d){kd(a,b,c,d,1,"keypress");return 0},A:function(a,b,c,d){kd(a,b,c,d,3,"keyup");return 0},Pa:function(a,b,c){a=H(a);bb(a,b,c)},O:function(a,b,c,d){md(a,b,c,d,5,"mousedown");return 0},M:function(a,b,c,d){md(a,b,c,d,33,"mouseenter");return 0},L:function(a,b,c,d){md(a,b,c,d,34,"mouseleave");return 0},P:function(a,b,c,d){md(a,b,c,d,8,"mousemove");return 0},
N:function(a,b,c,d){md(a,b,c,d,6,"mouseup");return 0},C:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.ye||document.body.bf||document.body.Ze))return-1;a=W(a);if(!a)return-4;nd(a,b,c,d,"pointerlockchange");nd(a,b,c,d,"mozpointerlockchange");nd(a,b,c,d,"webkitpointerlockchange");nd(a,b,c,d,"mspointerlockchange");return 0},r:function(a,b,c,d){od(a,b,c,d);return 0},D:function(a,b,c,d){pd(a,b,c,d,25,"touchcancel");return 0},F:function(a,b,c,d){pd(a,b,
c,d,23,"touchend");return 0},E:function(a,b,c,d){pd(a,b,c,d,24,"touchmove");return 0},G:function(a,b,c,d){pd(a,b,c,d,22,"touchstart");return 0},w:function(a,b,c){qd(a,b,c);return 0},K:function(a,b,c,d){a=W(a);return"undefined"!=typeof a.onwheel?(rd(a,b,c,d),0):-1},sa:function(a){ea(t(a))},p:function(){throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},Va:function(a,b){var c=0;td().forEach(function(d,e){var f=b+c;e=C[a+4*e>>2]=f;for(f=
0;f<d.length;++f)A[e++>>0]=d.charCodeAt(f);A[e>>0]=0;c+=d.length+1});return 0},Xa:function(a,b){var c=td();C[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});C[b>>2]=d;return 0},Y:function(){return 52},Ya:function(){return 52},Ta:function(){return 70},Z:function(a,b,c,d){for(var e=0,f=0;f<c;f++){var g=C[b>>2],m=C[b+4>>2];b+=8;for(var p=0;p<m;p++){var q=v[g+p],u=vd[a];0===q||10===q?((1===a?fa:l)(la(u,0)),u.length=0):u.push(q)}e+=m}C[d>>2]=e;return 0},aa:function(a,b){K.attachShader(O[a],
P[b])},a:function(a,b){K.bindBuffer(a,Tb[b])},Sa:function(a,b){K.blendFunc(a,b)},b:function(a,b,c,d){K.bufferData(a,c?v.subarray(c,c+b):b,d)},Wa:function(a){K.clear(a)},Ra:function(a,b,c,d){K.clearColor(a,b,c,d)},y:function(a){K.compileShader(P[a])},la:function(){var a=ac(O),b=K.createProgram();b.name=a;b.oe=b.me=b.ne=0;b.De=1;O[a]=b;return a},R:function(a){var b=ac(P);P[b]=K.createShader(a);return b},Ea:function(a){if(a){var b=O[a];b?(K.deleteProgram(b),b.name=0,O[a]=null):R(1281)}},Gb:function(a){K.disable(a)},
i:function(a,b,c,d){K.drawElements(a,b,c,d)},t:function(a){K.enable(a)},d:function(a){K.enableVertexAttribArray(a)},c:function(a,b){Uc(a,b,"createBuffer",Tb)},u:function(a,b){return K.getAttribLocation(O[a],t(b))},Ma:function(a,b,c,d){a=K.getProgramInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?y(a,d,b):0;c&&(B[c>>2]=b)},X:function(a,b,c){if(c)if(a>=Sb)R(1281);else if(a=O[a],35716==b)a=K.getProgramInfoLog(a),null===a&&(a="(unknown error)"),B[c>>2]=a.length+1;else if(35719==b){if(!a.oe)for(b=
0;b<K.getProgramParameter(a,35718);++b)a.oe=Math.max(a.oe,K.getActiveUniform(a,b).name.length+1);B[c>>2]=a.oe}else if(35722==b){if(!a.me)for(b=0;b<K.getProgramParameter(a,35721);++b)a.me=Math.max(a.me,K.getActiveAttrib(a,b).name.length+1);B[c>>2]=a.me}else if(35381==b){if(!a.ne)for(b=0;b<K.getProgramParameter(a,35382);++b)a.ne=Math.max(a.ne,K.getActiveUniformBlockName(a,b).length+1);B[c>>2]=a.ne}else B[c>>2]=K.getProgramParameter(a,b);else R(1281)},n:function(a,b){b=t(b);if(a=O[a]){$c(a);var c=a.ue,
d=0,e=b,f=Zc(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.Ee[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||K.getUniformLocation(a,b)))return d}else R(1281);return-1},Kd:function(a){a=O[a];K.linkProgram(a);a.ue=0;a.Ee={}},J:function(a,b,c,d){b=bc(b,c,d);K.shaderSource(P[a],b)},j:function(a,b){K.uniform1f(X(a),b)},Qa:function(a,b,c,d){K.uniform3f(X(a),b,c,d)},g:function(a,b,c,d){if(18>=b){var e=Y[16*b-1],f=D;d>>=2;for(var g=0;g<16*b;g+=16){var m=d+g;e[g]=f[m];e[g+1]=f[m+1];e[g+2]=f[m+2];e[g+3]=
f[m+3];e[g+4]=f[m+4];e[g+5]=f[m+5];e[g+6]=f[m+6];e[g+7]=f[m+7];e[g+8]=f[m+8];e[g+9]=f[m+9];e[g+10]=f[m+10];e[g+11]=f[m+11];e[g+12]=f[m+12];e[g+13]=f[m+13];e[g+14]=f[m+14];e[g+15]=f[m+15]}}else e=D.subarray(d>>2,d+64*b>>2);K.uniformMatrix4fv(X(a),!!c,e)},fd:function(a){a=O[a];K.useProgram(a);K.Ne=a},e:function(a,b,c,d,e,f){K.vertexAttribPointer(a,b,c,!!d,e,f)},vb:function(a,b,c,d){K.viewport(a,b,c,d)},m:function(a,b,c,d){function e(n,w,z){for(n="number"==typeof n?n.toString():n||"";n.length<w;)n=z[0]+
n;return n}function f(n,w){return e(n,w,"0")}function g(n,w){function z(ab){return 0>ab?-1:0<ab?1:0}var V;0===(V=z(n.getFullYear()-w.getFullYear()))&&0===(V=z(n.getMonth()-w.getMonth()))&&(V=z(n.getDate()-w.getDate()));return V}function m(n){switch(n.getDay()){case 0:return new Date(n.getFullYear()-1,11,29);case 1:return n;case 2:return new Date(n.getFullYear(),0,3);case 3:return new Date(n.getFullYear(),0,2);case 4:return new Date(n.getFullYear(),0,1);case 5:return new Date(n.getFullYear()-1,11,
31);case 6:return new Date(n.getFullYear()-1,11,30)}}function p(n){var w=n.se;for(n=new Date((new Date(n.te+1900,0,1)).getTime());0<w;){var z=n.getMonth(),V=(Oa(n.getFullYear())?zd:Ad)[z];if(w>V-n.getDate())w-=V-n.getDate()+1,n.setDate(1),11>z?n.setMonth(z+1):(n.setMonth(0),n.setFullYear(n.getFullYear()+1));else{n.setDate(n.getDate()+w);break}}z=new Date(n.getFullYear()+1,0,4);w=m(new Date(n.getFullYear(),0,4));z=m(z);return 0>=g(w,n)?0>=g(z,n)?n.getFullYear()+1:n.getFullYear():n.getFullYear()-1}
var q=B[d+40>>2];d={mf:B[d>>2],lf:B[d+4>>2],Be:B[d+8>>2],Je:B[d+12>>2],Ce:B[d+16>>2],te:B[d+20>>2],le:B[d+24>>2],se:B[d+28>>2],Bf:B[d+32>>2],kf:B[d+36>>2],nf:q?t(q):""};c=t(c);q={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U",
"%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var u in q)c=c.replace(new RegExp(u,"g"),q[u]);var x="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),L="January February March April May June July August September October November December".split(" ");q={"%a":function(n){return x[n.le].substring(0,3)},"%A":function(n){return x[n.le]},"%b":function(n){return L[n.Ce].substring(0,3)},"%B":function(n){return L[n.Ce]},"%C":function(n){return f((n.te+1900)/100|0,2)},"%d":function(n){return f(n.Je,
2)},"%e":function(n){return e(n.Je,2," ")},"%g":function(n){return p(n).toString().substring(2)},"%G":function(n){return p(n)},"%H":function(n){return f(n.Be,2)},"%I":function(n){n=n.Be;0==n?n=12:12<n&&(n-=12);return f(n,2)},"%j":function(n){for(var w=0,z=0;z<=n.Ce-1;w+=(Oa(n.te+1900)?zd:Ad)[z++]);return f(n.Je+w,3)},"%m":function(n){return f(n.Ce+1,2)},"%M":function(n){return f(n.lf,2)},"%n":function(){return"\n"},"%p":function(n){return 0<=n.Be&&12>n.Be?"AM":"PM"},"%S":function(n){return f(n.mf,
2)},"%t":function(){return"\t"},"%u":function(n){return n.le||7},"%U":function(n){return f(Math.floor((n.se+7-n.le)/7),2)},"%V":function(n){var w=Math.floor((n.se+7-(n.le+6)%7)/7);2>=(n.le+371-n.se-2)%7&&w++;if(w)53==w&&(z=(n.le+371-n.se)%7,4==z||3==z&&Oa(n.te)||(w=1));else{w=52;var z=(n.le+7-n.se-1)%7;(4==z||5==z&&Oa(n.te%400-1))&&w++}return f(w,2)},"%w":function(n){return n.le},"%W":function(n){return f(Math.floor((n.se+7-(n.le+6)%7)/7),2)},"%y":function(n){return(n.te+1900).toString().substring(2)},
"%Y":function(n){return n.te+1900},"%z":function(n){n=n.kf;var w=0<=n;n=Math.abs(n)/60;return(w?"+":"-")+String("0000"+(n/60*100+n%60)).slice(-4)},"%Z":function(n){return n.nf},"%%":function(){return"%"}};c=c.replace(/%%/g,"\x00\x00");for(u in q)c.includes(u)&&(c=c.replace(new RegExp(u,"g"),q[u](d)));c=c.replace(/\0\0/g,"%");u=Bd(c);if(u.length>b)return 0;A.set(u,a);return u.length-1}};
(function(){function a(e){h.asm=e.exports;ia=h.asm.Vd;e=ia.buffer;h.HEAP8=A=new Int8Array(e);h.HEAP16=oa=new Int16Array(e);h.HEAP32=B=new Int32Array(e);h.HEAPU8=v=new Uint8Array(e);h.HEAPU16=pa=new Uint16Array(e);h.HEAPU32=C=new Uint32Array(e);h.HEAPF32=D=new Float32Array(e);h.HEAPF64=E=new Float64Array(e);qa=h.asm.Zd;sa.unshift(h.asm.Wd);xa--;h.monitorRunDependencies&&h.monitorRunDependencies(xa);0==xa&&(null!==ya&&(clearInterval(ya),ya=null),za&&(e=za,za=null,e()))}function b(e){a(e.instance)}function c(e){return Da().then(function(f){return WebAssembly.instantiate(f,
d)}).then(function(f){return f}).then(e,function(f){l("failed to asynchronously prepare wasm: "+f);r(f)})}var d={a:Fd};xa++;h.monitorRunDependencies&&h.monitorRunDependencies(xa);if(h.instantiateWasm)try{return h.instantiateWasm(d,a)}catch(e){return l("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return ha||"function"!=typeof WebAssembly.instantiateStreaming||Aa()||"function"!=typeof fetch?c(b):fetch(F,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,
d).then(b,function(f){l("wasm streaming compile failed: "+f);l("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();function G(){return(G=h.asm.Xd).apply(null,arguments)}var Gd=h._main=function(){return(Gd=h._main=h.asm.Yd).apply(null,arguments)};function ic(){return(ic=h.asm._d).apply(null,arguments)}function jc(){return(jc=h.asm.$d).apply(null,arguments)}function Kc(){return(Kc=h.asm.ae).apply(null,arguments)}
h.dynCall_jiji=function(){return(h.dynCall_jiji=h.asm.be).apply(null,arguments)};h.dynCall_ji=function(){return(h.dynCall_ji=h.asm.ce).apply(null,arguments)};var Hd;za=function Id(){Hd||Jd();Hd||(za=Id)};function Kd(a=[]){var b=Gd;a.unshift(ca);var c=a.length,d=Kc(4*(c+1)),e=d>>2;a.forEach(g=>{var m=B,p=e++,q=na(g)+1,u=Kc(q);ma(g,A,u,q);m[p]=u});B[e]=0;try{var f=b(c,d);Cd(f)}catch(g){jb(g)}}
function Jd(){var a=ba;function b(){if(!Hd&&(Hd=!0,h.calledRun=!0,!ja)){Ma(sa);Ma(ta);if(h.onRuntimeInitialized)h.onRuntimeInitialized();Ld&&Kd(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();va.unshift(c)}Ma(va)}}if(!(0<xa)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)wa();Ma(ra);0<xa||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);
b()},1)):b())}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var Ld=!0;h.noInitialRun&&(Ld=!1);Jd();
